### ISSUE TITLE
`start-minimized` breaks my statusbar

### ISSUE THREAD

**Issue by jonasbadstuebner** [tobi-wan-kenobi/bumblebee-status#1011]
#### Description
Affected module: At least `nic`.
Version used: latest git

<description>

#### How to reproduce

Set something like
```
[core]
modules = nic
[module-parameters]
nic.start-minimized = True
```
and you should get an error like
`IndexError: list index out of range` at `blocks.extend(self.separator_block(module, module.widgets()[0]))`

I tried to fix it, but when I added a check for it, my statusbar has a triangle that I cannot click or anything.

**TL;DR:** I tried to fix it, but couldn't easily.

![grafik](https://github.com/tobi-wan-kenobi/bumblebee-status/assets/18399895/aaa85de3-8a14-4947-b740-81d929c8e41e)

It's not very important for me, I just thought it would work.

**Comment by tobi-wan-kenobi** [comment]
Which version of bumblebee-status are you using? 

With current git, I cannot reproduce this behaviour:

```
$ cat ~/.config/bumblebee-status.conf 
[core]
modules = nic
[module-parameters]
nic.start-minimized = True
bumblebee-status on  main via 🐍 v3.12.1 
$ ./bumblebee-status            
{"version": 1, "click_events": true}
[
[{"full_text": " lan enp1s0f1 down ", "color": "#aabbcc", "name": "nic", "instance": "nic::0", "_raw": "enp1s0f1 down", "_suffix": " ", "_prefix": " lan ", "align": null}],
[{"full_text": " lan enp1s0f1 down ", "color": "#aabbcc", "name": "nic", "instance": "nic::0", "_raw": "enp1s0f1 down", "_suffix": " ", "_prefix": " lan ", "align": null}],
```

**Comment by DrBu7cher** [comment]
Could you try
```
[core]
modules = eth:nic,wifi:nic
[module-parameters]
eth.include = eth0
eth.start-minimized = True

wifi.include = wlan0
wifi.start-minimized = True
```
please?

**Comment by DrBu7cher** [comment]
My config is more compley, I tried to give a minimal example and you are right, the one I provided first does work.

**Comment by tobi-wan-kenobi** [comment]
Closing, because I was unable to reproduce (and frankly, forgot about this ticket and it has timed out).

If this issue persists, I apologize, and please reopen the ticket & I will look at it asap.

**Comment by jonasbadstuebner** [comment]
Did you test it with the latest config I provided?
The issue is with renaming the nic and trying to set the setting for the name, rather than the nic-module, I think.

**Comment by tobi-wan-kenobi** [comment]
Hey! Sorry, that one is on me, I totally overlooked that.

Might be a very easy problem: In the config you provided, the module name and the alias are reversed - it's always `<module>:<alias>`, not the other way round.

Can you please give that a try? And sorry again for taking so long to spot this!

**Comment by tobi-wan-kenobi** [comment]
I also checked your config on my machine with module <> alias switched, and it seems to work fine.

**Comment by jonasbadstuebner** [comment]
Ah, you are right, I think that one is on me. Thank you for having a look, can be closed. :+1:
