### ISSUE TITLE
Rapidly jumping of bumblebee-status and i3-statusbar

### ISSUE THREAD

**Issue by franzmondlichtmann** [tobi-wan-kenobi/bumblebee-status#1016]
#### Description
Every ~30 miliseconds the elements of the bar jump half a centimeter to the right, but only the modules.
The virtual display indicator stays on the same place and also the applets (like steam and fcitx5) stay on the same place.
It only happens sometimes, I have not quite found the trigger.
It happens with bumblebee-status and also i3-status bar.
I don't think its a graphical glitch in the sense, that it has anything to do with the gpu.
Maybe it's the way the bar gets drawn or updated?
With gap on the right:
![image](https://github.com/tobi-wan-kenobi/bumblebee-status/assets/105480088/db08a487-7ac6-4360-9ed4-ed3951e0e677)
Without gap on the right:
![image](https://github.com/tobi-wan-kenobi/bumblebee-status/assets/105480088/f15590af-d0b6-4229-9da3-09b73a60212a)
Now image the gap being drawn and vanishing rapidly afterwards.

**Comment by franzmondlichtmann** [comment]
The culprit seems to be the message box from dolphin:
<What do you want to do with this file: "Execute" "Cancel">
![image](https://github.com/tobi-wan-kenobi/bumblebee-status/assets/105480088/179ec8ba-60f4-42ff-a8bd-9a86d225345b)

**Comment by franzmondlichtmann** [comment]
Maybe it tries to spawn some applet to the right, when this dolphin-message-box appears? But fails, and is stuck in an infinite loop at this point?!

**Comment by tobi-wan-kenobi** [comment]
OK, so I am pretty sure this is a problem with the applet, *not* the status bar. The right-hand part (the "tray") that contains the applet icons is *not* part of the i3 status bar.

Simething changes the size of the bar - maybe that is the fcitx applet or (as you indicate) some other app such as dolphin that pops up and creats an empty entry in the tray.

**Comment by franzmondlichtmann** [comment]
Good. I think the only way would be to test it by disabling the applet icons one by one and test it this way.
If anything bumblebee related shows up I will reopen the issue.
