### ISSUE TITLE
Pulseaudio module is failing on system startup

### ISSUE THREAD

**Issue by Kwbmm** [tobi-wan-kenobi/bumblebee-status#108]
So, after fixing #103 , I get "pacmd stat exited with status code 1". This happens at boot and **until** I run an application that requires sound capabilities (e.g Spotify). Running `pacmd stat` on the terminal returns (translated):

    No PulseAudio daemon running or not running as session daemon

Not sure if it's a fault on my end or if using `pacmd stat` to fix #103 is not a good solution.

**EDIT:** Just to be clear, running spotify and then reloading i3 config solves the issue, but it's suboptimal..

**Comment by tobi-wan-kenobi** [comment]
Confirmed, same here after rebooting my system. Will investigate. Thanks for the bug report!

**Comment by dschense** [comment]
I think this problem is still present.
each boot i get the message - pulseaudio --start exited 1.
I have to restart i3-msg to get the bar back.

**Comment by tobi-wan-kenobi** [comment]
Weird... When you look at your process list, is the pulseaudio daemon running? For now, I will just ignore this error, just so that the bar comes up.

**Comment by Kwbmm** [comment]
I'm too still experiencing some crashes. However, it looks like they're random and I'm not able to reproduce the bug.
I hope to be able to get a better insight of what is going on.

**Comment by tobi-wan-kenobi** [comment]
@Kwbmm Could you please add the error message that you are receiving during a crash?

Mostly, it seems that error occur if the pulseaudio daemon is not running, so one way to trigger it *might* be to kill the pulseaudio daemon and then reload the i3 bar. Having said that, for me, the lastest version works fine, so I'd really appreciate any additional insights that you discover on why this issue keeps appearing.

Thanks a lot!

**Comment by Kwbmm** [comment]
I'm pretty sure the error message is different now, but unfortunately not being able to reproduce the bug keeps from posting here the exact message i'm receiving.

Will report back as soon as I get this error message

**Comment by ibrokemypie** [comment]
Something perhaps relevant, if you kill pulseaudio while bumblebee is running, bumblebee completely locks up due to pactl being unable to find the server, even when it has come back up. The rest of the bar is removed. Restarting the bar fixes it.
```
killall pulseaudio
pulseaudio --kill
```

**Comment by tobi-wan-kenobi** [comment]
Ah... damn.

I don't want to check for (and restart) pulseaudio once a second in the bar. Seems like I need to come up with a different solution for the localization problem than using `pacmd`.

**Comment by tobi-wan-kenobi** [comment]
OK, so I've now added code that tries to restart the pulseaudio daemon if an error occurs. 

If this causes problems, there's a parameter called "pulseaudio.autostart" that can be used to disable this behaviour. In such cases, "n/a" is displayed in the module if the pulseaudio daemon could not be contacted.

It would be great if you could let me know if this changes/improves the situation for you!

**Comment by mschoenwaelder** [comment]
I had the same issue as dschense described in his post (pulseaudio --start exited 1). Your latest changes fixed the problem on my machine. Thank you!

**Comment by ibrokemypie** [comment]
I personally don't think the statusbar should be responsible for pulseaudio, tthere are some situations where you may want pulseaudio not to be running, and pulseaudio is called whenever a client needs it. It would be more useful simply to show the status of pulseaudio, eg its volume, or that it is down, rather than trying to bring it up.

**Comment by tobi-wan-kenobi** [comment]
@ibrokemypie : I agree, that's a sensible position to take :) If you set `pulseaudio.autorun` to `false`, that's the behaviour of the status bar (unless I've bugged it....).

I've modeled the behaviour a bit after the tool `pavucontrol`, which also launches the pulseaudio daemon if it's not running, as far as I can tell.

**Comment by ibrokemypie** [comment]
May I request that to be the default behaviour? Iff for no other reason than to reduce clutter in the calling command, since in the majority of usecases it at the minimum would be increasing overhead, and could potentially cause major problems at the other end.

**Comment by tobi-wan-kenobi** [comment]
Good points, adjusted the default behaviour!

**Comment by codingo** [comment]
I didn't experience the original issue but performed testing with the latest branch based on what I saw reflected in the comments and believe this to be fixed.
