### ISSUE TITLE
bumblebee.modules has no attribute '__file__'

### ISSUE THREAD

**Issue by subpanda101** [tobi-wan-kenobi/bumblebee-status#109]

**Comment by tobi-wan-kenobi** [comment]
Hi,

I have never encountered that particular error message before. Could you please tell me when you get this error? I.e. your i3 configuration and bumblebee-status commandline would be very helpful in figuring out what is going wrong.

Thanks a lot!

**Comment by subpanda101** [comment]
I got this error for seemingly no reason, I have made sure if I have all the correct packages which I do. My i3 config is on my own github page (it is up to date) and at the command line I get `cannot stat '/home/brandon/.i3/config': No such file or directory
screens: DVI-I-1` My i3 config is in ~/.config/i3/config, could this be the issue?

**Comment by subpanda101** [comment]
All I had to do was pull a new version of the bar, apologies for that.

**Comment by tobi-wan-kenobi** [comment]
No problem, glad to read that the issue is resolved!
