### ISSUE TITLE
Weather module failing?

### ISSUE THREAD

**Issue by Kwbmm** [tobi-wan-kenobi/bumblebee-status#110]
I'm guessing weather module is failing sometime. I'm getting an exception on my status bar saying:

    exception occurred: No JSON object could be decoded

I think this is the weather module failing as it should be the only one handling JSON files. Unfortunately I did not have `-d` flag turned on when the error occurred so I can't tell for sure.

**Comment by ibrokemypie** [comment]
It could also be the github module, do you have that enabled?

**Comment by tobi-wan-kenobi** [comment]
@ibrokemypie is right, weather and github are the two modules decoding JSON data right now.

I'll protect those two against missing data (ie. URL was not reachable), but I will also investigate logging the module that caused the execption.

Thanks for the report!

**Comment by Kwbmm** [comment]
I do not have the github module running, so the weather module must be the culprit.

I'm pretty sure wrapping the json.loads statements inside a try/catch clause is enough to fix the issue.

**Comment by tobi-wan-kenobi** [comment]
done :)
