### ISSUE TITLE
Allow module icons to be changed with the theme by changing configuration setup

### ISSUE THREAD

**Issue by codingo** [tobi-wan-kenobi/bumblebee-status#114]
I've been developing some modules (pr incoming soon) and I struggled to quickly identify where icons for modules were being driven. I found the current layout a bit unintuitive and initially I expected the config for modules to be within the module itself, or the theme file.

I think it would make more sense to merge the icons object (currently in ./themes/icons) into the theme files themselves so that users on the current branch could change the icons for their modules as they change their theme.

Thoughts?

**Comment by tobi-wan-kenobi** [comment]
Hi,

looking forward to the PR a lot :-)

Originally, the icons were part of the theme, but I found myself mostly copy/pasting from existing themes, so I thought the notion of an "iconset" would make sense. If you feel this is intuitive, maybe I was wrong ;-)

I haven't tried it, but right top off my head, I *think* that you should be able to simply not use the iconset feature and configure the icons directly in the theme. Essentially, the iconset is just a JSON file that is merged into the theme (to fill in any elements that don't have a value in the theme), if I remember correctly.

**Comment by codingo** [comment]
That makes sense. Since I'm in here anyway I'll test and reopen the issue again only if it doesn't work.

And plugin is now working on a local branch - just figuring out how I can pass flags to it (a filepath) and then I'll put in pr for the branch. 2-3 days away for the first one!

**Comment by tobi-wan-kenobi** [comment]
Looking forward to the PR! :)
