### ISSUE TITLE
Bumblebee status claims laptop is charging when it isn't. Battery module isn't working.

### ISSUE THREAD

**Issue by subpanda101** [tobi-wan-kenobi/bumblebee-status#117]

**Comment by tobi-wan-kenobi** [comment]
Hi,

hm, for me, the module seems to work. Could you please provide the following information to narrow down the issue:

* Output of `ls /sys/class/power_supply/`
* Output of `cat /sys/class/power_supply/BAT0/capacity`
* Output of `cat /sys/class/power_supply/BAT0/status`

If you don't have a `BAT0` directory, but a different one, could you please try spawning `bumblebee-status` with the parameter `-p battery.device=<whatever directory name you do have>`?

Thanks!

**Comment by subpanda101** [comment]
ls /sys/class/power_supply returns two directories, ACAD and BAT1.
I dont think I have a BAT0 directory but other applications like the cinnamon desktop can pick up on my battery.

**Comment by ibrokemypie** [comment]
@subpanda101 did you try `bumblebee-status -p battery.device=BAT1`?

**Comment by subpanda101** [comment]
That seemed to have worked! Thanks :)

**Comment by tobi-wan-kenobi** [comment]
Thanks @ibrokemypie for the help!

I'm going to have a stab at reworking the battery module for autodetection of the battery device. I hope I won't break the module too badly for anyone :-)
