### ISSUE TITLE
battery icon is shown twice

### ISSUE THREAD

**Issue by alrayyes** [tobi-wan-kenobi/bumblebee-status#136]
The battery is shown twice on my Thinkpad:

![example](https://user-images.githubusercontent.com/511318/27985561-322c7b0a-63ed-11e7-8ba0-699f520e33ba.png)

Bumblee command in 3config is:

```shell
	bumblebee-status -m mpd pasink pasource brightness battery bluetooth nic pacman load sensors datetime caffeine -p datetime.format="%Y-%m-%d %H:%M:%S" nic.states=^down nic.exclude=br,lo,docker0 disk.path=/home disk.open="termite -e ranger" disk.showUsed=false disk.showSize=false -t solarized-powerline
```

As far as I know I only have one battery.

**Comment by tobi-wan-kenobi** [comment]
When you enter `ls /sys/class/power_supply/`, what's the output?

If you see two `BAT` directories, that would explain the behaviour - but would also indicate that your system "thinks" there are two batteries. If so, the easiest solution is to provide `-p battery.devie=BAT0` (or whichever device you want to display).

Just out of curiosity: Are the two icons behaving identical? I.e. when you unplug, do both go to "discharging" mode and do the percentages always correlate?

Hope this helps!

**Comment by alrayyes** [comment]
That indeed fixed it, thanks!
