### ISSUE TITLE
[module/pulseaudio] volume not updating

### ISSUE THREAD

**Issue by Towelythetowel** [tobi-wan-kenobi/bumblebee-status#144]
Hi,
When i'm using the pulseaudio module, the displayed volume is always showing 30%.
I have only one sink available so I really don't know what is going wrong.
I have confirmed pulseaudio is installed on my system and pavucontrol is working fine.
Am I doing something wrong ?

**Comment by tobi-wan-kenobi** [comment]
Can you please post the relevant section of your i3 configuration? Are you using `pasink` or `pasource`?

Output on your system of the following commands would also be helpful:

* pacmd list-sinks
* pacmd list-sources
* pacmd stat

I have to admit that the pulseaudio command unfortunately is one of the more flaky ones, as it does a lot of command output parsing, sorry that you are having issues!

**Comment by Towelythetowel** [comment]
Thanks for the help! I don't know what part of my i3 configuration is relevant ( the part where I call bumblebee-status ? )

Otherwise, by running the command you stated above, I figured where the problem is coming from,  the module show me the volume of my default input device (instead of the output device).
I played with my mic volume and it is now sitting at 51%.
Can this be fixed somehow ? Otherwise I will use the Amixer module that display correct volume but do not show if the speaker are muted.


[list-sinks.txt](https://github.com/tobi-wan-kenobi/bumblebee-status/files/1157008/list-sinks.txt)
[list-sources.txt](https://github.com/tobi-wan-kenobi/bumblebee-status/files/1157010/list-sources.txt)
[stat.txt](https://github.com/tobi-wan-kenobi/bumblebee-status/files/1157009/stat.txt)

**Comment by tobi-wan-kenobi** [comment]
Ah, yeah, that's less intuitive than it should be :-P

You're probably using `pulseaudio` directly, right? This defaults to showing the source (i.e. microphone).

Can you please try to use the module `pasink` instead? It's just an alias for `pulseaudio`, but displays the volume of the sink, instead of the source.

**Comment by Towelythetowel** [comment]
It is working with pasink! I thought it was exactly the same as using pulseaudio.
Thanks for the help!
