### ISSUE TITLE
Limiting network adapters under module

### ISSUE THREAD

**Issue by garrettjj** [tobi-wan-kenobi/bumblebee-status#155]
So this is probably less of an issue than it is a question about configuration. I have two vmnet* adapters that always show in the status bar. I'm wondering if there's a way to hide those so it doesn't need to have the vmnet adapters showing?

**Comment by tobi-wan-kenobi** [comment]
Actually, there is :-)

The module "nic" has a parameter "exclude" (defaulting to "lo,virbr,docker,vboxnet,veth") that can be used to provide a list of prefixes. Each interface with a matching prefix will not be displayed.

For your case, please try to call `bumblebee-status` like this:

`bumblebee-status -m nic -p nic.exclude=lo,virbr,docker,vboxnet,veth,vmnet`

**Comment by garrettjj** [comment]
:O Thank you so much!

-- 
Garrett Jansen
