### ISSUE TITLE
[module/cmus] Hide cmus widget when it's not in use

### ISSUE THREAD

**Issue by guillegran** [tobi-wan-kenobi/bumblebee-status#157]
Hello, I wanted to know if there is a way to open the cmus widget on the bar just when cmus is working, just as the spotify one does.

**Comment by tobi-wan-kenobi** [comment]
Hi,

wasn't possible until now - plus, the cmus module was broken, and I didn't notice it.

Now it should work again and should be hidden when not active.

Thanks!

**Comment by guillegran** [comment]
It's working for me! Thank you very much again!
