### ISSUE TITLE
[module/datetime] Day names not working in Spanish

### ISSUE THREAD

**Issue by guillegran** [tobi-wan-kenobi/bumblebee-status#158]
Hello, I'm using the datetime module in the following way:
`time date -p date.format="%a, %d %b %Y"`
and on Wednesdays and Saturdays the whole bar crashes and I get the following error:
`exception ocurred: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range (128) in bumblebee.modules.datetime`.
I think it appears because Wednesday and Saturday in Spanish are "miércoles" and "sábado" and are abbreviated as "mié." and "sáb." and the accent makes the bar crash.
¿Is there any way to fix it?

**Comment by tobi-wan-kenobi** [comment]
Hi,

sorry you're having issue. I've committed a small change, could you please let me know whether this fixes the issue?

Thanks!

**Comment by guillegran** [comment]
It is working now! Thank you very much! :-)
