### ISSUE TITLE
Powerline theme not displaying properly

### ISSUE THREAD

**Issue by reflynn** [tobi-wan-kenobi/bumblebee-status#161]
There's a gap between the left angle symbol and the left side of each module in the Powerline themes. This occurs regardless of the powerline-compatible font used.
Here's a screenshot:
![bumblebee-powerline-bug](https://user-images.githubusercontent.com/31167573/29490646-5618a81a-84f7-11e7-99ac-92ca256f8192.jpg)

**Comment by tobi-wan-kenobi** [comment]
Hi,

is this maybe the same issue as #82 ?

If not: Can you please post the i3 configuration part for the status bar? Also, I've read on some forums that on some distributions, people had to use negative values for `separator-block-width` in the theme file `powerline.json`, maybe that resolves your issue?

**Comment by ibrokemypie** [comment]
ooh same here

**Comment by tobi-wan-kenobi** [comment]
@ibrokemypie If I use your config, I don't get any separators at all (greek sum symbol instead). What fixed it for me in that case was changing the order of the fonts (+ writing `DejaVu` instead of `DevaVu` ;-) ):

```
	font pango:DejaVu Sans Book 10
	font pango:FontAwesome 10
	font pango:Fira Mono for Powerline 10
```

For me personally, this works best:
```
font pango:Inconsolata 11
```

(yeah, **not** `Inconsolata for Powerline`, don't know why, it just looks nicer).

**Comment by ibrokemypie** [comment]
Odd, after making the changes it actually got even worse, even if I just used inconsolata.. thanks for picking up DevaVu though :D

**Comment by tobi-wan-kenobi** [comment]
How "worse"? With **only** "Fira Mono for Powerline", you should have at least a working bar. Can you maybe check that the font in question is available and has exactly the name you provided? (maybe using `gnome-font-viewer` or st. like that?)

I've noticed that different distributions tend to name the fonts a bit differently, which can cause issues.

**Comment by reflynn** [comment]
I changed "DejaVu Sans Mono 11" to "DejaVu Sans Mono for Powerline 11." There's still a sliver of a gap, but it's a lot better than it was. Interestingly, some fonts work better than others. Droid Sans Mono for Powerline and Inconsolata for Powerline have no gap, while Fira Mono for Powerline has a huge gap. Screenshots below.

DejaVu Sans Mono for Powerline:
![dejavusansmono](https://user-images.githubusercontent.com/31167573/29497311-bb32b594-859a-11e7-9f1d-1f3761f57e54.jpg)

Droid Sans Mono for Powerline:
![droidsansmono](https://user-images.githubusercontent.com/31167573/29497316-beeaca46-859a-11e7-9d16-baed57a93b9b.jpg)

Inconsolata for Powerline:
![inconsolata](https://user-images.githubusercontent.com/31167573/29497317-c30b4a92-859a-11e7-8da3-a374a0e2b0e4.jpg)

Fira Mono for Powerline:
![firamono](https://user-images.githubusercontent.com/31167573/29497319-c5fc2d5c-859a-11e7-982c-a982301e2f2d.jpg)
