### ISSUE TITLE
Powerline theme colour problem

### ISSUE THREAD

**Issue by ratanawanno** [tobi-wan-kenobi/bumblebee-status#173]
Hi,

I have tried to enable the -t powerline in my config file, everything including powerline font seems to works fine except the background color of the module texts don't show as shown in the readme file and the theme example.

I have attach what I get from my configuration below.

![menu_001](https://user-images.githubusercontent.com/31958263/30429491-a1c4d25e-994f-11e7-9ba9-630e0071424e.png)

**Comment by tobi-wan-kenobi** [comment]
hhmm.... what's your i3 version? I *seem* to remember that older i3 versions might have issues.

Also, can you please post the output of `bumblebee-status -m cpu memory -t solarized`?

Do other themes work?

Thanks!

**Comment by ratanawanno** [comment]
Hi,

Thank you from the prompt in responding. My i3 version 4.11 maybe that is the cause of it.

I am sending you the result from the command
./bumblebee-status/bumblebee-status -m cpu memory -t solarized

![menu_002](https://user-images.githubusercontent.com/31958263/30452626-49437574-998e-11e7-9aab-a2a96aed15d7.png)

**Comment by tobi-wan-kenobi** [comment]
According to the changelog, 4.11 *should* have background support already. I will try to compile 4.11 and see what I get.

Also: Sorry, I was explaining this badly: Can you please post the output of the command when you run it in the terminal? I'd like to see whether the background colors are present in the JSON.

Finally: Can you please tell me the distribution and version you are using? Maybe I can set up a VM to try to reproduce the issue.

Thanks for your patience!

**Comment by ratanawanno** [comment]
Hi,

I did try to run command again, I coppy the result in the attach file.
I use xubuntu 16.04.3 LTS 32 bit.

thank you,


tobi-wan-kenobi writes:

> According to the changelog, 4.11 *should* have background support already. I will try to compile 4.11 and see what I get.
>
> Also: Sorry, I was explaining this badly: Can you please post the output of the command when you run it in the terminal? I'd like to see whether the background colors are present in the JSON.
>
> Finally: Can you please tell me the distribution and version you are using? Maybe I can set up a VM to try to reproduce the issue.
>
> Thanks for your patience!


--

**Comment by ratanawanno** [comment]
It seems that the attachment didn't go with my reply, sending it again.
[bumblebee-status_test.txt](https://github.com/tobi-wan-kenobi/bumblebee-status/files/1308160/bumblebee-status_test.txt)

**Comment by tobi-wan-kenobi** [comment]
@ratanawanno : I checked again, unfortunately, I was wrong in my earlier assessment.

Background colors for individual elements was introduced in v4.12 of i3wm:

"

**Comment by ratanawanno** [comment]
I did upgrade my i3 to the newest version and the colour is here.
![menu_003](https://user-images.githubusercontent.com/31958263/30511966-e63df374-9adb-11e7-8fcf-59553df58d41.png)

Thank you very much,

**Comment by tobi-wan-kenobi** [comment]
Perfect, glad to hear it! Will also update the documentation to indicate the i3wm version requirement.
