### ISSUE TITLE
Cmus module - crash with japanese characters

### ISSUE THREAD

**Issue by ariSunz** [tobi-wan-kenobi/bumblebee-status#176]
Don't really know where to begin, but I never had issues with i3status and i3blocks when trying to display weird characters. Did I miss any requirements? Sorry if I'm missing something really obvious.

[Debug log here.](https://gist.github.com/ariSunz/54d359823d873cb776257c3f42c76f21)

**Comment by tobi-wan-kenobi** [comment]
Hi,

that's classic "me not able to handle unicode correctly in python", sorry about that. I could have *sworn* I had that fixed for the `cmus` module. Will investigate and try to find a general solution to this super-annoying issue.

Thanks for raising the issue & sorry for the inconvenience!

**Comment by tobi-wan-kenobi** [comment]
Could you please let me know whether  dfb1e39 fixes the issue for you?

**Comment by ariSunz** [comment]
Like a charm! 
![screenshot_2017-09-16_10-30-10](https://user-images.githubusercontent.com/29211266/30512617-1137f50a-9aca-11e7-9fb0-d8739be41afb.png)

That was really fast, thank you!

**Comment by tobi-wan-kenobi** [comment]
Glad to hear it worked :+1: 

BTW: Nice color scheme :-)

**Comment by tobi-wan-kenobi** [comment]
Sorry to bring this up again, but the change caused #180 (basically inoperability with Python3).

Hope that the new change still fixes your issue!

**Comment by ariSunz** [comment]
Just updated, can confirm the latest commit still works, thank you!

**Comment by tobi-wan-kenobi** [comment]
Glad to hear it, thanks for checking!
