### ISSUE TITLE
set_defaultencoding_globally('utf-8') crashes bumblebee-status

### ISSUE THREAD

**Issue by Sweenu** [tobi-wan-kenobi/bumblebee-status#180]
I'm using bumblebee-status on arch with a python3.6 installation.
At first I was getting a non-zero exit code when launching i3 and what solved this was commenting out the 90th line: set_defaultencoding_globally('utf-8')

Could I make a pull request with this line removed or is it still relevant ? (the tests passes with it removed)

**Comment by tobi-wan-kenobi** [comment]
Yeah, I found out today that there's a bug with UTF-8 support in Python3.

Frankly: I *hate* it :-P

I'll try to find a way that supports both Python 2 and Python 3.
