### ISSUE TITLE
Memory Usage reported is much higher than true memory usage

### ISSUE THREAD

**Issue by spookykidmm** [tobi-wan-kenobi/bumblebee-status#181]
I don't believe this is your fault, but rather whatever you use to collect memory information(psutil, I believe).
The values reported by py3status(around 620MiB at time of posting this) and free -m(around 609Mib) are  fairly similar whereas bumblebee-status reports around 908.01MiB used. I attached a picture below which contains a completely clean desktop(I mean, clean plus conkies xD)
![y1g4](https://user-images.githubusercontent.com/10724754/30621383-cc822456-9d78-11e7-92ce-580f900b1c84.jpg)

**Comment by tobi-wan-kenobi** [comment]
Thanks for the hint! Please let me know if the following commit fixes the issue for you. Nice side effect: Get rid of `psutil` dependency for the `memory` module.

**Comment by spookykidmm** [comment]
this worked perfectly! I'm now reporting at 248MiB for Memory used, which is just about right!
