### ISSUE TITLE
pywal support?

### ISSUE THREAD

**Issue by ariSunz** [tobi-wan-kenobi/bumblebee-status#185]
Seeing how themes are loaded as JSON files, would it be possible to load the colors generated by [pywal](https://github.com/dylanaraps/pywal) (maybe with help of the [JSON also generated by pywal itself](https://github.com/dylanaraps/pywal/wiki/Customization#json-file)?) and use them for special themes?

For example, `wal-gruvbox` and `wal-powerline` would contain such colors imported from the files generated by pywal.

**Comment by tobi-wan-kenobi** [comment]
Good idea, I saw `pywal` for the first time in your (excellent) theme on reddit. I will investigate that & see what I can come up with. Thanks!

**Comment by tobi-wan-kenobi** [comment]
Hi,

looks like this was easier than anticipated. Since it's still somewhat experimental, I've pushed it only to a separate branch called `pywal-support`. Please feel free to try it out and give me feedback, I'd appreciate it a lot.

Essentially, what I have done is:

- In a theme, you can now specify an array of `colors`, similar to how the `icons` are specified already. If you do that, `bumblebee-status` loads color definitions from that file (currently only the wal colors are supported) and you can use the color names throughout the theme. For example:

```
{
        "icons": [ "awesome-fonts" ],
        "colors": [ "wal" ],
        "defaults": {
                "separator-block-width": 0,
                "critical": {
                        "fg": "cursor",
                        "bg": "color5"
                },
                "warning": {
                        "fg": "cursor",
                        "bg": "color6"
                },
                "default_separators": false
        },
        "cycle": [
                {
                        "fg": "foreground",
                        "bg": "background"
                },
                {
                        "fg": "background",
                        "bg": "foreground"
                }
        ],
        "dnf": {
                "good": {
                        "fg": "background",
                        "bg": "color3"
                }
        },
        "battery": {
                "charged": {
                        "fg": "background",
                        "bg": "color3"
                },
                "AC": {
                        "fg": "background",
                        "bg": "color3"
                }
        }
}
```

**Comment by ariSunz** [comment]
I've been toying with different values and modules and so far it seems pretty solid!

![screenshot_2017-10-08_14-59-14](https://user-images.githubusercontent.com/29211266/31319440-e7519aee-ac39-11e7-8b3e-9d8da3379e06.png)
![screenshot_2017-10-08_14-57-00](https://user-images.githubusercontent.com/29211266/31319441-e75f9978-ac39-11e7-8850-abfd12edcf3f.png)
(cpu intentionally stressed)

This is much easier now. I'll report back if anything breaks. Thanks a lot! 😄

**Comment by tobi-wan-kenobi** [comment]
Glad to hear it! Thank *you* for the suggestion, I like this feature :)

**Comment by ltgouvea** [comment]
Just tested it and works like a charm. Thanks a lot :heart:
