### ISSUE TITLE
Currency module

### ISSUE THREAD

**Issue by AntouanK** [tobi-wan-kenobi/bumblebee-status#190]
@tobi-wan-kenobi Regarding the currency module.
So far, I used the "fixer.io" endpoint. The good thing is that it can give you many pairs in one call, but unfortunately it only updates once a day.

I wanted to change it to use the internal FT endpoint.
_example for GBP/USD_
`https://markets.ft.com/data/currencies/ajax/conversion?amount=100&baseCurrency=GBP&comparison=USD`
But, apart from changing the way to access the value from the JSON response ( that's simple, just change the keys ) the difference is that here we need one call per pair.
But, this one updates every few minutes, so it's much more useful.

My python knowledge is non existent, so can you give it a try to change it?
Somehow can we recognise the arguments, and add 1 call for each argument in the "loop"?

I guess the separator will become optional as well, depending on whether you have more than 1 arguments.

**Comment by fredj** [comment]
I can give a try to change it

**Comment by tobi-wan-kenobi** [comment]
How about something like a format string for the URL (e.g. https://markets.ft.com/data/currencies/ajax/conversion?amount={amount}&baseCurrency={source}&comparison={destination})?

About how to correctly parse the destination, I'm a bit unsure, frankly....

**Comment by AntouanK** [comment]
as a note: I'd say keep the amount fixed at 100. To look like the request the webpage does. The amount doesn't matter anyway, you want the exchange rate.
