### ISSUE TITLE
Clicking on the date/time module should bring up a calendar

### ISSUE THREAD

**Issue by mahmoudhossam** [tobi-wan-kenobi/bumblebee-status#195]
I often find myself needing to check my calendar, it'd be really great if the datetime module would allow that.

[Gsimplecal](https://github.com/dmedvinsky/gsimplecal) has the calendar functionality, we could integrate it so the calendar would appear near the date, like what currently happens in GNOME if you click the date.

**Comment by tobi-wan-kenobi** [comment]
Hi,

this should already be possible by mapping mouse events, for example:

`./bumblebee-status -m date -p date.format="%a, %b %d %Y" date.left-click=gsimplecal`

Does that match your needs?

**Comment by mahmoudhossam** [comment]
@tobi-wan-kenobi It does! Thank you!

I didn't see this option in the readme so I assumed there was no way of mapping mouse click events, maybe we should update the readme so people would know they exist?

**Comment by tobi-wan-kenobi** [comment]
Yes, this information is only available in the wiki. It's a bit of a trade-off between keeping the readme shortish and putting enough info there.

I agree, that the mouse mappings belong in the readme :-)

Thanks!

**Comment by mahmoudhossam** [comment]
@tobi-wan-kenobi If you want to keep things brief, then the readme should only contain a quickstart and the rest of the info should be in the wiki.
