### ISSUE TITLE
status_command process exited unexectedly (exit 1)

### ISSUE THREAD

**Issue by GrayedFox** [tobi-wan-kenobi/bumblebee-status#196]
I'm not sure if this is the exact cause of the problem but on Debian (fresh install) when I do `which python` the path to python 2.7 is output.

The supported python version lists 3.5 as well (I have 3.5.3, which is also bundled with Debian). In my opinion, the latest version of Python should be the preference - but this might be a bit tricky to do in a build script (which is guaranteed to work cross platform). Not quite sure what to suggest here.

Bumblebee seems to be using Python 2.7 on Debian 9 despite Python 3.3 also being present. The current make file also seems to confirm this (when listing dependencies). I installed netifaces and psutil using pip3, but the debug output is looking in the 2.7 lib:

```
Traceback (most recent call last):
  File "./bumblebee-status", line 73, in <module>
    main()
  File "./bumblebee-status", line 45, in main
    inp=inp,
  File "/opt/git/bumblebee-status/bumblebee/engine.py", line 117, in __init__
    self._aliases = self._read_aliases()
  File "/opt/git/bumblebee-status/bumblebee/engine.py", line 194, in _read_aliases
    mod = importlib.import_module("bumblebee.modules.{}".format(module["name"]))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/git/bumblebee-status/bumblebee/modules/getcrypto.py", line 16, in <module>
    import requests
ImportError: No module named requests
```

I would also add that the readme states that we shouldn't need python modules (like requests) if not using a Bumblebee Module that requires it (I am not using getcrypto in my i3 config!).

Looks like an awesome tool, I will keep digging around and see if I can get my status bar working (will likely just end up installing the dependencies for python if I can't figure our how to make bumblebee use my python 3!).

Thanks!

**Comment by GrayedFox** [comment]
I can confirm that after installing pip and then adding each dependency to python 2.7 I now have a fully awesome status bar!

workaround for Debian 9 users:
1. install pip by doing `apt-get install python-pip`
2. install any python dependencies needed for any module you are using: `pip install netifaces psutil`
3. install any other dependencies you need from the apt repository (i.e. `apt-get install nvidia-smi`)

It's sometimes not clear whether a dependency listed on the modules page comes from python or is a Debian package. Trial and error prevails here.

**Comment by tobi-wan-kenobi** [comment]
Hi,

thanks for the report and for digging around to find a solution! :-)

What bumblebee-status does is invoking #!/usr/bin/env python, so whatever your system default python is, it will be used (i.e. if you enter python --version in a shell, you'll probably see python2.7, unless I bugged that up somehow.

At the time of writing, I thought that to be more robust than trying to "intelligently" detect the highest installed python version.

Reg. pip vs. apt: I don't know about Debian, but other Distros allow you to install packages such as netifaces for python 2.x by installing the package python-netifaces, and for python3.x by installing python3-netifaces, so maybe that would be an alternative solution.

Thanks for using bumblebee-status! :-)

**Comment by GrayedFox** [comment]
Hmm - so should I close this? I know there are some people which symlink `python` to `python3` but I think that's a pretty crazy workaround to this oft encountered problem.

I installed packages using pip3, which did indeed installed python3 netifaces. The problem was that despite having python 3 and the listed dependencies, bumblebee used my 2.7 python. 

Is there a way to somehow configure bumblee to use python3, if multiple python versions are present? Or is this maybe a task for [pyenv](https://github.com/pyenv/pyenv)?

**Comment by GrayedFox** [comment]
Seems like Debian wants its users to handle python versions (and system defaults) by doing [this](https://linuxconfig.org/how-to-change-default-python-version-on-debian-9-stretch-linux).

It's a mess, really. `pip2 --version` prints: 
pip 9.0.1 from /home/grayedfox/.local/lib/python3.5/site-packages (python 3.5)

`python2 --version` prints:
Python 2.7.13

Anyhow, any confusion here is most likely due to the OS, and how it symlinks python. After updating my system to default to python3, I can confirm bumblebee correctly searches the python 3 library for dependencies (and thus uses python 3).

```
Traceback (most recent call last):
  File "./bumblebee-status", line 73, in <module>
    main()
  File "./bumblebee-status", line 45, in main
    inp=inp,
  File "/opt/git/bumblebee-status/bumblebee/engine.py", line 117, in __init__
    self._aliases = self._read_aliases()
  File "/opt/git/bumblebee-status/bumblebee/engine.py", line 194, in _read_aliases
    mod = importlib.import_module("bumblebee.modules.{}".format(module["name"]))
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/git/bumblebee-status/bumblebee/modules/traffic.py", line 12, in <module>
    import netifaces
ImportError: No module named 'netifaces'
```

**Comment by tobi-wan-kenobi** [comment]
Yeah, `update-alternatives` seems to be pretty wide-spread, also Fedora is doing it like this, AFAIK.

Anyhow, thanks for digging into this to that level of detail (+ glad that it works now for you)!
