### ISSUE TITLE
[themes] Use fontawesome library to reference fonts by name

### ISSUE THREAD

**Issue by tobi-wan-kenobi** [tobi-wan-kenobi/bumblebee-status#20]
In the theme, allow referencing fonts/icons by their name using https://pypi.python.org/pypi/fontawesome/.

(submitted by @paxy97 )

**Comment by codingo** [comment]
I'm happy to do this one. 


I've been writing a couple of modules (pr coming soon) and I personally struggled to immediately identify where the icons for modules were stored. To me it would make sense to either have this within the module or within the theme file.

I think it would make the most sense for theme files to have their own object for module icons so they could be changed with your theme. Essentially logically merging the theme file for the fonts from ./themes/icons into an object within the theme file itself. What do you think?

If this is appended to the existing *.json and the existing ./themes/fonts folder and files it retained it should allow for backwards compatibility with theme files but those on the latest release would have more control over their icon choices.
