### ISSUE TITLE
time and datetime fontawesome icon

### ISSUE THREAD

**Issue by fredj** [tobi-wan-kenobi/bumblebee-status#201]
The icon for the time and datetime seems to be wrong:
https://github.com/tobi-wan-kenobi/bumblebee-status/blob/3455ad3da42e551f1af7c029eeb8efcc31a6ebb7/themes/icons/awesome-fonts.json#L7
and:
https://github.com/tobi-wan-kenobi/bumblebee-status/blob/3455ad3da42e551f1af7c029eeb8efcc31a6ebb7/themes/icons/awesome-fonts.json#L8

Shouldn't it be a clock icon?

**Comment by fredj** [comment]
I think it's an issue with the font install on my side

**Comment by tobi-wan-kenobi** [comment]
Hi,

I've just checked: both `time` and `datetime` have a clock icon (in master, at least). I'm a bit confused, as your samples also show a clock each time - what do you see?

**Comment by fredj** [comment]
I see something like a `~` character:
![fa_clock](https://user-images.githubusercontent.com/100959/32165469-322aadc8-bd63-11e7-98a6-9394565a27a8.png)

But the icon at fontawesome.io is correctly displayed: http://fontawesome.io/icon/clock-o/ (in Chrome and firefox)

**Comment by tobi-wan-kenobi** [comment]
I get that problem sometimes with certain terminals (i.e. `gnome-terminal` displays the fonts fine, but `xterm`doesn't), I think that may be related to (missing) unicode support and/or font selection.
