### ISSUE TITLE
Allow themes/icons/modules from outside the tree

### ISSUE THREAD

**Issue by dawikur** [tobi-wan-kenobi/bumblebee-status#203]
It would be great to be able to create **theme**/**icon set** which would live outside the **repo**.
My use case is: I have cloned ```bumblebee-status```  on the disk and I want to have theme/icons in my **dotfiles**, not necessary upload them here.

I guess it would be fine to look for them in ```~/.config/bublebee-status/themes/icons```, ```~/.config/bublebee-status/bumbleebee/modules```.

**Comment by tobi-wan-kenobi** [comment]
I like the idea and will look into implementing it as soon as possible :-)

Thanks!

**Comment by tobi-wan-kenobi** [comment]
Added a first draft implementation in a separate branch (`theme-directories`), for two reasons:
* I don't have enough time to test the changes sufficiently this week
* Adding a user-configurable directory is difficult

**Comment by dawikur** [comment]
Great. I've check it briefly just switching to branch and drag-drop files in proper places. Works nicely :ok_hand:

**Comment by tobi-wan-kenobi** [comment]
Great, thanks!

I will do some additional tests and fix your PPS (good catch!), probably during the next weekend.

**Comment by tobi-wan-kenobi** [comment]
Hi,

sorry for the long time without update!

I've now updated the branch `theme-directories` to match the latest master and incorporated your changes. I'll wait a few more days to see whether any errors occur, and will merge it back to master afterwards.

Thanks!
