### ISSUE TITLE
Many instance of module with different parameters.

### ISSUE THREAD

**Issue by zymone** [tobi-wan-kenobi/bumblebee-status#211]
I encountered yet another problem with "disk" module. I would like to see information about two different partitions in my status bar. The current version of disk module is capable to display information about single partition at once.
There are basically two possibilities to solve this problem. First, improvement of the disk module to handle multiple partitions. Second, include disk module twice in modules list, but there is the problem that there is only one configurable variable for two instances of disk module.

I would say that second option is smoother in this case and maybe better in general view, but there is a need for changes in core files. 
So the question is it sensible to introduce changes in core of the bumblebee so that it enables features as multiple instances of one module with different parameters?

**Comment by cacyss0807** [comment]
This is an interesting idea as simpler modules as the `shortcut` (94f8f2e42614e21a31983a946fda120a5d040353) one could benefit from that. The current approach follows your first option thought.

**Comment by tobi-wan-kenobi** [comment]
If I understand your question correctly, this is already possible using "aliases":

```
$ bumblebee-status -m disk:root disk:boot -p root.path=/ boot.path=/boot
```

Does that fit your requirements? If so, I'd say it is more a matter of clearly documenting this feature :-)

**Comment by zymone** [comment]
@tobi-wan-kenobi That is exactly the feature I was talking about. Thanks!
