### ISSUE TITLE
Fixed PKGBUILD

### ISSUE THREAD

**Issue by spookykidmm** [tobi-wan-kenobi/bumblebee-status#214]
Hey, I just wanted to let you know that I believe I fixed the PKGBUILD used for the arch package. Will confirm when I actually have a package update:
https://app.box.com/s/gnp7uira9m29yc3gqc1ghp10w9and9no

**Comment by tobi-wan-kenobi** [comment]
Nice, that looks much better than the PKGBUILD i currently have 📦 👍 

I successfully built the package and was able to install it on my system (I've switched to Arch some days ago), so looks good for me.

Will wait for your final confirmation and do an update then. Thanks a lot!

**Comment by tobi-wan-kenobi** [comment]
After some more testing, I went ahead and committed your changes:

https://aur.archlinux.org/cgit/aur.git/commit/?h=bumblebee-status&id=fa0956361feb2d1fc709e6902998b904f2172203

Many thanks for your contribution!
