### ISSUE TITLE
symbols.json created with no content, and crashes powerline themes.

### ISSUE THREAD

**Issue by gorzell** [tobi-wan-kenobi/bumblebee-status#216]
After re-installing my laptop bumble-bee was throwing errors related to the `{calendar}` place holder when loading themes.  Looking at the code it appears to be related to the recently added dependency of a symbols file, downloaded as yaml and converted to json. https://github.com/tobi-wan-kenobi/bumblebee-status/commit/bac3d6bc578b8e490057b6808ba4317b23996012

There is a delay on first start(which would perhaps imply that the download is happening), but the file in the end is always empty.  I get the same result if I delete and re-create the file.

```
bumblebee-status -m nic battery pulseaudio date time -p date.format="%d.%m.%Y" time.format="%H:%M" -t solarized-powerline
Traceback (most recent call last):
  File "/usr/local/bin/bumblebee-status", line 74, in <module>
    main()
  File "/usr/local/bin/bumblebee-status", line 37, in main
    theme = bumblebee.theme.Theme(config.theme())
  File "/opt/bumblebee-status/bumblebee/theme.py", line 54, in __init__
    self._init(data)
  File "/opt/bumblebee-status/bumblebee/theme.py", line 85, in _init
    self._merge(data, self._load_icons(iconset))
  File "/opt/bumblebee-status/bumblebee/theme.py", line 172, in _load_icons
    return self._replace_symbols(result)
  File "/opt/bumblebee-status/bumblebee/theme.py", line 178, in _replace_symbols
    rep = rep.replace(token, self._symbols[token])
KeyError: '${calendar}'
```

**Comment by tobi-wan-kenobi** [comment]
Hi,

thanks a lot for the bug report. I will try to reproduce it, in the meantime, I have disabled the automatic download and reverted the pre-packaged themes. Wasn't a good idea to automagically download those symbols, anyhow :)

Sorry for the issue!

**Comment by gorzell** [comment]
Ya, it also added the yaml dependency.  It might be something that is better suited to being bundled when you get the packaging mentioned in #129 working.

Thanks for the quick fix.
