### ISSUE TITLE
Window freeze / crash in certain cases

### ISSUE THREAD

**Issue by adibis** [tobi-wan-kenobi/bumblebee-status#218]
Hi, 

Here's what I am seeing.

1. I have the disk module in the status bar.
2. My action is to open a file manager on click (tried with both Thunar and Nautilus).
3. When I open a file manager by clicking on the disk module, then open a video (tried with both mplayer and vlc) and go full screen, it freezes and blanks out.
4. If I open the file manager by using dmenu/rofi then this issue is not observed.

My bar setup is: 
`
status_command bumblebee-status -m brightness pasink pasource battery cpu disk nic datetime -p datetime.format="%a %d %b %Y %H:%M" nic.exclude=eth0,lo disk.open=nautilus disk.path=/home disk.format="home: {percent:05.02f}" -t gruvbox-powerline
`

**Comment by tobi-wan-kenobi** [comment]
Hi,

unfortunately, I was unable to reproduce this bug, for me, it works (thunar + VLC in Arch Linux). Also, I don't see any explanation for how this could happen, as once the file manager is spawned, it doesn't have *any* further connection to the status bar.

Please let me ask a few questions:
* Which codecs is the video using?
* Is the video player in a tile, or is the layout tabbed (or does the layout not make any difference?)
* Are you explicitly providing the file manager as parameter to bumblebee, or are you using xdg-open?

In the meantime, I will try a few more things to try to reproduce the issue.

Sorry for the problems!

**Comment by adibis** [comment]
Hi, 

Thanks for replying. This is a brilliant tool - for the first time I find i3 usable in an hour vs trying to spend a day getting it to show basic information. Kudos on a job well done.

As for the issue, I updated the whole system once - rebooted for new kernel and now the crash is gone. I cannot reproduce it either. Closing the ticket.

Thanks,
Aditya
