### ISSUE TITLE
Exception occurring with battery module

### ISSUE THREAD

**Issue by ltgouvea** [tobi-wan-kenobi/bumblebee-status#221]
Bumblebee status works just fine for a while after rebooting or reloading i3 (I'm using i3-gaps), but a few moments later (let's say half an hour approx.) this shows up:
![image](https://user-images.githubusercontent.com/12522078/34802758-76179be6-f656-11e7-8af1-6f2c5c278acd.png)

This is what I have as a status command right now
`        status_command ~/.i3/bumblebee-status/bumblebee-status -m mpd cpu sensors memory battery brightness  pasource date-time -p brightness.wheel-up='light -A 5' brightness.wheel-down='light -U 5' date-time.format='%d/%m | %H:%M' memory.format='{used}' -t wal-powerline
`

**Comment by tobi-wan-kenobi** [comment]
Oh, that is weird... :)

Could you please have a look at `/sys/class/power_supply/` and tell me what you see there both when `bumblebee-status` works and when it is broken.

What I will do in any case are nicer error messages and a recovery logic.

**Comment by ltgouvea** [comment]
[power_supply_bumblebee_broken.txt](https://github.com/tobi-wan-kenobi/bumblebee-status/files/1626378/power_supply_bumblebee_broken.txt)
[power_supply_bumblebee_working.txt](https://github.com/tobi-wan-kenobi/bumblebee-status/files/1626379/power_supply_bumblebee_working.txt)
[bumblebee-status-debug.log](https://github.com/tobi-wan-kenobi/bumblebee-status/files/1626367/bumblebee-status-debug.log)

Update: Now i3 is throwing `status_command process exited unexpectedly` at the bar. When i run it in the terminal no errors occur

**Comment by ltgouvea** [comment]
Removing the *.pyc files in bumblebee/modules/ got the bar running again :D thx! Now let us see if it breaks again and if it happens I'll let u know ASAP

**Comment by tobi-wan-kenobi** [comment]
seems to be fixed :)
