### ISSUE TITLE
crypto module throwing

### ISSUE THREAD

**Issue by AntouanK** [tobi-wan-kenobi/bumblebee-status#222]
Kraken is down, so their API is down as well

![screenshot_2018-01-11_08-53-18](https://user-images.githubusercontent.com/4569111/34816472-f019e290-f6ac-11e7-8e3b-82f3e5628707.png)

I'll close the issue once they go online again.
If the API doesn't come back, I'll see if we can find another one.

**Comment by tobi-wan-kenobi** [comment]
Thanks for the information!

Together with #221, I'll have a look at having nicer / recoverable error messages.

**Comment by AntouanK** [comment]
Seems like they finally resolved it.
https://status.kraken.com/incidents/nswthr1lyx72
( it was a big mess apparently )

Crypto module works fine now.
@tobi-wan-kenobi close the issue if you want.

**Comment by tobi-wan-kenobi** [comment]
Thanks for the info! Wow, that sounds like one mean update :)
