### ISSUE TITLE
spacer could be set to a custom color *feature request*

### ISSUE THREAD

**Issue by freed00m** [tobi-wan-kenobi/bumblebee-status#223]
Hi,

I like to have powerline themes and I dislike that the tray area wont start with the arrow symbol.

What I do now, is setting i3 bar color to be the same as the last module in my tray and it's getting annoying that I have different number of modules and one i3config.

If spacer could be custom colorized I would just put single spacer with color from i3 config and would end up with same tray area blending perfectly.

Just a simple parameter for spacer?

**Comment by tobi-wan-kenobi** [comment]
Nice idea!

What I'm going to implement is an option to override theme settings via parameters, so that you could do, for example:

`bumblebee-status -m spacer -p spacer.theme.bg=#ff0000` to get a spacer with a red background.

Does that fit your requirement?

**Comment by freed00m** [comment]
Yes that would be great. :)

**Comment by tobi-wan-kenobi** [comment]
There you go :)

Feedback would be much appreciated!

**Comment by freed00m** [comment]
Excelent, that suits my needs.

Note that modules that changes bg themselves on click events "pasink" wont be changing bg color any longer and will be forever overwritten. I don't mind and I am happy with this solution.

**Comment by tobi-wan-kenobi** [comment]
Oh, right you are. For stateful widgets, that's tricky. Will evolve the concept a bit, if someone needs it :)

Thanks a lot for the feedback and the improvement suggestion!
