### ISSUE TITLE
Broken links on "How to write a theme"

### ISSUE THREAD

**Issue by adibis** [tobi-wan-kenobi/bumblebee-status#224]
The links at the bottom of the page are broken:
https://github.com/tobi-wan-kenobi/bumblebee-status/wiki/How-to-write-a-theme

 solarized-powerline.json points to: https://github.com/tobi-wan-kenobi/i3bumblebee/blob/master/bumblebee/themes/solarized-powerline.json
Needs to point to: https://github.com/tobi-wan-kenobi/bumblebee-status/blob/master/themes/solarized-powerline.json

default.json points to: https://github.com/tobi-wan-kenobi/i3bumblebee/blob/master/bumblebee/themes/default.json
Needs to pint to: https://github.com/tobi-wan-kenobi/bumblebee-status/blob/master/themes/default.json

**Comment by tobi-wan-kenobi** [comment]
fixed, thanks a lot for spotting this!
