### ISSUE TITLE
Solarized Powerline theme not rendering correctly

### ISSUE THREAD

**Issue by 2secslater** [tobi-wan-kenobi/bumblebee-status#228]
I have all the Powerline fonts installed and this is the result:
![screenshot_2018-02-10_21-07-54](https://user-images.githubusercontent.com/30773181/36066708-89e94a9e-0ea6-11e8-954a-a15f4ca8bf7a.png)
This is what is in my i3 config:
``bar{
        font pango:FontAwesome 10
        status_command ~/Documents/bumblebee-status/bumblebee-status/bumblebee-status -m nic disk:home cpu memory date time -p interval=1 time.format="%H:%M:%S" date.format="%a, %b %d %Y" home.path=/home -t solarized-powerline
        position bottom
}``

Why is mine not rendering like it does in the official screenshots for this github repository?

**Comment by tobi-wan-kenobi** [comment]
Just to be on the safe side: Did you close the ticket intentionally (i.e. found a solution for the issue)?

**Comment by 2secslater** [comment]
Yes I closed it intentionally as I did find a solution.

All I had to do was add one line to the bar block in the i3 config above the status command.
`font pango:Inconsolata 8.8`

After adding that line, it started rendering correctly.
