### ISSUE TITLE
Inaccurate Memory Percentage

### ISSUE THREAD

**Issue by 2secslater** [tobi-wan-kenobi/bumblebee-status#229]
As you can see in the screenshot below, the percentage is not correct.
![screenshot_2018-02-11_20-04-56](https://user-images.githubusercontent.com/30773181/36077780-da5bb366-0f66-11e8-81f9-9429ff4c23b8.png)

The correct percentage for that would be 61.76%, not 77.84%.

**Comment by tobi-wan-kenobi** [comment]
That is ... slightly embarassing :P Thanks for the notification, will fix this right away

**Comment by 2secslater** [comment]
Thanks! Works just fine now!
