### ISSUE TITLE
can't run ./bumblebee-status

### ISSUE THREAD

**Issue by pirey** [tobi-wan-kenobi/bumblebee-status#232]
Hi, I'm new to this,

I have problem when running ./bumblebee-status, it says

```
Traceback (most recent call last):
  File "./bumblebee-status", line 6, in <module>
    import bumblebee.theme
  File "/home/yeri/bumblebee-status/bumblebee/theme.py", line 9, in <module>
    import yaml
ImportError: No module named yaml
```

What am I missing?

**Comment by tobi-wan-kenobi** [comment]
Hi,

this means you are missing the `yaml` Python module. You can install that either via your package manager (depends on the distribution you run) or via pip.

See  here, for example: https://stackoverflow.com/questions/14261614/how-do-i-install-the-yaml-package-for-python

Generally, some of bumblebee-status's modules require additional modules and/or commandline utilities, this is documented here: https://github.com/tobi-wan-kenobi/bumblebee-status/wiki/Available-Modules

The `yaml` dependency comes from the core, this is - unfortunately - not documented anywhere yet.

Hope this helps!
