### ISSUE TITLE
'FileNotFoundError' is not iterable

### ISSUE THREAD

**Issue by yuceltoluyag** [tobi-wan-kenobi/bumblebee-status#237]
Hi ./bumblebee-status -l modules  run this command and error

`    amixer:
      get volume level

    battery:
      Displays battery status, remaining percentage and charging information.

      Parameters:
          * battery.device     : Comma-separated list of battery devices to read
            information from (defaults to auto for auto-detection)
          * battery.warning    : Warning threshold in % of remaining charge
            (defaults to 20)
          * battery.critical   : Critical threshold in % of remaining charge
            (defaults to 10)
          * battery.showdevice : If set to "true", add the device name to the
            widget (defaults to False)

    bluetooth:
      Displays bluetooth status (Bluez). Left mouse click launches manager app,
      right click toggles bluetooth. Needs dbus-send to toggle bluetooth state.

      Parameters:
          * bluetooth.device : the device to read state from (default is hci0)
          * bluetooth.manager : application to launch on click (blueman-manager)

    brightness:
      Displays the brightness of a display

      Parameters:
          * brightness.step: The amount of increase/decrease on scroll in %
            (defaults to 2)
          * brightness.device_path: The device path (defaults to
            /sys/class/backlight/intel_backlight)

    caffeine:
      Enable/disable automatic screen locking.

      Requires the following executables:
          * xset
          * notify-send

    cmus:
      Displays information about the current song in cmus.

      Requires the following executable:
          * cmus-remote

      Parameters:
          * cmus.format: Format string for the song information. Tag values can
            be put in curly brackets (i.e. {artist})

    cpu:
      Displays CPU utilization across all CPUs.

      Parameters:
          * cpu.warning : Warning threshold in % of CPU usage (defaults to 70%)
          * cpu.critical: Critical threshold in % of CPU usage (defaults to 80%)
          * cpu.format  : Format string (defaults to "{:.01f}%)")

    currency:
      Displays currency exchange rates. Currently, displays currency between GBP
            and USD/EUR only.

      Requires the following python packages:
          * requests

      Parameters:
          * currency.interval: Interval in minutes between updates, default is
            1.
          * currency.source: Source currency (defaults to "GBP")
          * currency.destination: Comma-separated list of destination currencies
            (defaults to "USD,EUR")
          * currency.sourceformat: String format for source formatting; Defaults
            to "{}: {}" and has two variables,
                                   the base symbol and the rate list
          * currency.destinationdelimiter: Delimiter used for separating
            individual rates (defaults to "|")

      Note: source and destination names right now must correspond to the names
            used by the API of https://markets.ft.com

    datetime:
      Displays the current date and time.

      Parameters:
          * datetime.format: strftime()-compatible formatting string
          * date.format    : alias for datetime.format
          * time.format    : alias for datetime.format
          * datetime.locale: locale to use rather than the system default
          * date.locale    : alias for datetime.locale
          * time.locale    : alias for datetime.locale

    disk:
      Shows free diskspace, total diskspace and the percentage of free disk
            space.

      Parameters:
          * disk.warning: Warning threshold in % of disk space (defaults to 80%)
          * disk.critical: Critical threshold in % of disk space (defaults ot
            90%)
          * disk.path: Path to calculate disk usage from (defaults to /)
          * disk.open: Which application / file manager to launch (default xdg-
            open)
          * disk.format: Format string, tags {path}, {used}, {left}, {size} and
            {percent} (defaults to "{path} {used}/{size} ({percent:05.02f}%)")
          * (deprecated) disk.showUsed: Show used space (defaults to yes)
          * (deprecated) disk.showSize: Show total size (defaults to yes)
          * (deprecated) disk.showPercent: Show usage percentage (defaults to
            yes)

    dnf:
      Displays DNF package update information
            (<security>/<bugfixes>/<enhancements>/<other>)

      Requires the following executable:
          * dnf

      Parameters:
          * dnf.interval: Time in seconds between two consecutive update checks
            (defaults to 30 minutes)

    error:
      Draws an error widget.

    getcrypto:
      Displays the price of a cryptocurrency.

      Requires the following python packages:
          * requests

      Parameters:
          * getcrypto.interval: Interval in seconds for updating the price,
            default is 120, less than that will probably get your IP banned.
          * getcrypto.getbtc: 0 for not getting price of BTC, 1 for getting it
            (default).
          * getcrypto.geteth: 0 for not getting price of ETH, 1 for getting it
            (default).
          * getcrypto.getltc: 0 for not getting price of LTC, 1 for getting it
            (default).
          * getcrypto.getcur: Set the currency to display the price in, usd is
            the default.

    github:
      Displays the unread GitHub notifications for a GitHub user

      Requires the following library:
          * requests

      Parameters:
          * github.token: GitHub user access token, the token needs to have the
            'notifications' scope.
          * github.interval: Interval in minutes

    gpmdp:
      Displays information about the current song in Google Play music player.

      Requires the following executable:
          * gpmdp-remote

    hipchat:
      Displays the unread messages count for an HipChat user

      Requires the following library:
          * requests

      Parameters:
          * hipchat.token: HipChat user access token, the token needs to have
            the 'View Messages' scope.
          * hipchat.interval: Refresh interval in minutes (defaults to 5)

    kernel:
      Shows Linux kernel version information
    layout-xkb:
      Displays the current keyboard layout using libX11

      Requires the following library:
          * libX11.so.6

      Parameters:
          * layout-xkb.showname: Boolean that indicate whether the full name
            should be displayed. Defaults to false (only the symbol will be
            displayed)

    layout:
      Displays and changes the current keyboard layout

      Requires the following executable:
          * setxkbmap

    load:
      Displays system load.

      Parameters:
          * load.warning : Warning threshold for the one-minute load average
            (defaults to 70% of the number of CPUs)
          * load.critical: Critical threshold for the one-minute load average
            (defaults to 80% of the number of CPUs)

    memory:
      Displays available RAM, total amount of RAM and percentage available.

      Parameters:
          * memory.warning : Warning threshold in % of memory used (defaults to
            80%)
          * memory.critical: Critical threshold in % of memory used (defaults to
            90%)
          * memory.format: Format string (defaults to "{used}/{total}
            ({percent:05.02f}%)")
          * memory.usedonly: Only show the amount of RAM in use (defaults to
            False). Same as memory.format="{used}"

    mocp:
      Displays information about the current song in mocp.

      Requires the following executable:
          * mocp

      Parameters:
          * mocp.format: Format string for the song information. Tag values can
            be put in curly brackets (i.e. {artist})

    mpd:
      Displays information about the current song in mpd.

      Requires the following executable:
          * mpc

      Parameters:
          * mpd.format: Format string for the song information. Tag values can
            be put in curly brackets (i.e. {artist})
          * mpd.host: MPD host to connect to. (mpc behaviour by default)

    nic:
      Displays the name, IP address(es) and status of each available network
            interface.

      Parameters:
          * nic.exclude: Comma-separated list of interface prefixes to exclude
            (defaults to "lo,virbr,docker,vboxnet,veth")
          * nic.states: Comma-separated list of states to show (prefix with "^"
            to invert - i.e. ^down -> show all devices that are not in state
            down)

    nvidiagpu:
      Displays GPU name, temperature and memory usage.

      Requires nvidia-smi

    pacman:
      Displays update information per repository for pacman."

      Requires the following executables:
          * fakeroot
          * pacman

    ping:
      Periodically checks the RTT of a configurable host using ICMP echos

      Requires the following executable:
          * ping

      Parameters:
          * ping.interval: Time in seconds between two RTT checks (defaults to
            60)
          * ping.address : IP address to check
          * ping.timeout : Timeout for waiting for a reply (defaults to 5.0)
          * ping.probes  : Number of probes to send (defaults to 5)
          * ping.warning : Threshold for warning state, in seconds (defaults to
            1.0)
          * ping.critical: Threshold for critical state, in seconds (defaults to
            2.0)

    publicip:
      Displays public IP address

      Requires the following python packages:
          * requests

      Parameters:
          * publicip.region: us-central (default), us-east, us-west, uk, de, pl,
            nl
          * publicip.service: web address that returns plaintext ip address (ex.
            "http://l2.io/ip")

    pulseaudio:
      Displays volume and mute status and controls for PulseAudio devices. Use
            wheel up and down to change volume, left click mutes, right click
            opens pavucontrol.

      Aliases: pasink (use this to control output instead of input), pasource

      Parameters:
          * pulseaudio.autostart: If set to "true" (default is "false"),
            automatically starts the pulseaudio daemon if it is not running

      Requires the following executable:
          * pulseaudio
          * pactl
          * pavucontrol
          * pacmd

    redshift:
      Displays the current color temperature of redshift

      Requires the following executable:
          * redshift

    rotation:
      Shows a widget for each connected screen and allows the user to loop
            through different orientations.

      Requires the following executable:
          * xrandr

    sensors:
      Displays sensor temperature

      Parameters:
          * sensors.path: path to temperature file (default
            /sys/class/thermal/thermal_zone0/temp).
          * sensors.match: (fallback) Line to match against output of 'sensors
            -u' (default: temp1_input)
          * sensors.match_number: (fallback) which of the matches you want
            (default -1: last match).
      ￼

    shortcut:
      Shows a widget per user-defined shortcut and allows to define the
            behaviour
      when clicking on it.

      For more than one shortcut, the commands and labels are strings separated
            by
      a demiliter (; semicolon by default).

      For example in order to create two shortcuts labeled A and B with commands
      cmdA and cmdB you could do:

       ./bumblebee-status -m shortcut -p shortcut.cmd="ls;ps"
            shortcut.label="A;B"

      Parameters:
          * shortcut.cmds  : List of commands to execute
          * shortcut.labels: List of widgets' labels (text)
          * shortcut.delim : Commands and labels delimiter (; semicolon by
            default)

    spacer:
      Draws a widget with configurable text content.

      Parameters:
          * spacer.text: Widget contents (defaults to empty string)

    spotify:
      Displays the current song being played

      Requires the following library:
          * python-dbus

      Parameters:
          * spotify.format: Format string (defaults to "{artist} - {title}")
                            Available values are: {album}, {title}, {artist},
            {trackNumber}

    stock:
      Display a stock quote from yahoo finance.

      Requires the following python packages:
          * requests

      Parameters:
          * stock.symbols : Comma-separated list of symbols to fetch
          * stock.change : Should we fetch change in stock value (defaults to
            True)
          * stock.currencies : List of symbols to go with the values (default $)

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/taskw/warrior.py", line 554, in get_version
    stdout=subprocess.PIPE
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'task': 'task'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bumblebee-status", line 74, in <module>
    main()
  File "./bumblebee-status", line 21, in main
    config = bumblebee.config.Config(sys.argv[1:])
  File "/home/friday13/bumblebee-status/bumblebee/config.py", line 71, in __init__
    self._args = parser.parse_args(args if args else [])
  File "/usr/lib/python3.6/argparse.py", line 1730, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.6/argparse.py", line 1968, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.6/argparse.py", line 1908, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.6/argparse.py", line 1836, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/friday13/bumblebee-status/bumblebee/config.py", line 28, in __call__
    self.print_modules()
  File "/home/friday13/bumblebee-status/bumblebee/config.py", line 38, in print_modules
    mod = importlib.import_module("bumblebee.modules.{}".format(m["name"]))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/friday13/bumblebee-status/bumblebee/modules/taskwarrior.py", line 14, in <module>
    from taskw import TaskWarrior
  File "/usr/lib/python3.6/site-packages/taskw/__init__.py", line 1, in <module>
    from taskw.warrior import (
  File "/usr/lib/python3.6/site-packages/taskw/warrior.py", line 916, in <module>
    if TaskWarriorShellout.can_use():
  File "/usr/lib/python3.6/site-packages/taskw/warrior.py", line 543, in can_use
    return cls.get_version() > LooseVersion('2')
  File "/usr/lib/python3.6/site-packages/taskw/warrior.py", line 557, in get_version
    if 'No such file or directory' in e:
TypeError: argument of type 'FileNotFoundError' is not iterable
`

**Comment by tobi-wan-kenobi** [comment]
Thanks for the report, hope this fixes your issue!
