### ISSUE TITLE
Incompatability with Font Awesome 5 Free

### ISSUE THREAD

**Issue by IVXCVI** [tobi-wan-kenobi/bumblebee-status#239]
Hello,

After getting B-S to work under latest Debian Stretch, I found the unicode icon for the CPU module was not rendering correctly (unicode F0E4) with the gruvbox-powerline theme. 

After some digging, it appears to me that the icon's name has changed from fa-tachometer in FA4 to fa-tachometer-alt in FA5. The unicode hex value for the changed(?) icon is F3FD. Please see the link below:

[https://fontawesome.com/icons/tachometer-alt?style=solid](https://fontawesome.com/icons/tachometer-alt?style=solid)

I was able to work around this by holding `Ctrl`+`Shift`+`U` & typing `F3FD` into LibreOffice Writer and copying the resulting glyph to bumblebee-status/themes/icons/awesome-fonts.json; copying over the glyph under "cpu".

Is this a reproducible bug? I can submit a pull request for this issue but the fix was also very simple. Let me know what you prefer.

Cheers!

**Comment by tobi-wan-kenobi** [comment]
Interesting, and confusing. I would have expected backwards compatibility with Font Awesome (i.e. add new glyphs, but don't delete existing ones).

Thanks a lot for the PR! I have to admit, though, I'm a bit reluctant to merge it, as this would probably break any installation using Font Awesome 4, right?

Maybe we can find an icon that works in both? I don't know, maybe an hourglass? I browsed through the icons, but didn't find anything satisfying so far....

What do you think?

**Comment by IVXCVI** [comment]
I'm not sure either. I'm also confused by the change. The information behind the reason doesn't seem immediately apparent.

I do agree the PR will break compatibility with FA v4, which I did not consider (& also do not want, either). I will look over alternatives & reply when I see something that might work (or find why tachometer was changed).

Cheers!

On March 31, 2018 1:10:03 AM CDT, tobi-wan-kenobi <notifications@github.com> wrote:
>Interesting, and confusing. I would have expected backwards
>compatibility with Font Awesome (i.e. add new glyphs, but don't delete
>existing ones).
>
>Thanks a lot for the PR! I have to admit, though, I'm a bit reluctant
>to merge it, as this would probably break any installation using Font
>Awesome 4, right?
>
>Maybe we can find an icon that works in both? I don't know, maybe an
>hourglass? I browsed through the icons, but didn't find anything
>satisfying so far....
>
>What do you think?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tobi-wan-kenobi/bumblebee-status/issues/239#issuecomment-377669444

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tobi-wan-kenobi** [comment]
How about this: https://fontawesome.com/icons/rocket?style=solid ?

**Comment by IVXCVI** [comment]
Hey mate, sorry--I've been troubleshooting kernel panics.

Looks like the FontAwesome team has "re-written" FontAwesome from the ground up. I still haven't read why--but as you can see--they've put `tachometer` behind a paywall in v5:

https://fontawesome.com/icons?d=gallery&q=tachometer

Rocket ship might work in a pinch, but I'm not sure it's a great fit. I don't know about you, but I'm not a fan of what the FontAwesome team is doing. I would consider just stating that v5 is not supported due to incompatibilities in the README.

I'll try and spend a little more time looking for alternatives tomorrow morning.

 Cheers!

**Comment by tobi-wan-kenobi** [comment]
Hi,

I agree, I don't like breaking backwards compatibility by asking a fee for something that was free previously. Particularly, since the kickstarter page (https://www.kickstarter.com/projects/232193852/font-awesome-5) actually mentions that backwards compat. with FA4 is a goal.

Anyhow, I like your suggestions, so that's what I will do for now.

Thanks a lot for the time and consideration!
