### ISSUE TITLE
unreadable characters

### ISSUE THREAD

**Issue by IlhamSetiawan** [tobi-wan-kenobi/bumblebee-status#242]
![2018-04-07-052037_1366x768_scrot](https://user-images.githubusercontent.com/37190439/38446685-9c8fd4bc-3a23-11e8-9542-d7684df6a0c0.png)
how to fix this?
I've installed all the required fonts,
but still there are unreadable characters

**Comment by tobi-wan-kenobi** [comment]
Hi,

can you please post the status bar config section from your i3 config?

Thanks!

**Comment by tobi-wan-kenobi** [comment]
On second glance, that weirdly looks like an issue that whitespaces are not correctly displayed, U+0020 is an ordinary "space" character.

If you can post the font configuration for the status bar, I can dig into the issue.

**Comment by IlhamSetiawan** [comment]
![2018-04-12-230703_1366x768_scrot](https://user-images.githubusercontent.com/37190439/38689741-94f5f68c-3ea6-11e8-875a-51d44de8b705.png)
solved sir
