### ISSUE TITLE
ImportError: No module named yaml on blank Fedora 27

### ISSUE THREAD

**Issue by AndreiArion** [tobi-wan-kenobi/bumblebee-status#244]
[aar@localhost bumblebee-status]$ ./bumblebee-status
Traceback (most recent call last):
  File "./bumblebee-status", line 6, in <module>
    import bumblebee.theme
  File "/home/aar/ssd/tools/bumblebee-status/bumblebee/theme.py", line 9, in <module>
    import yaml
ImportError: No module named yaml

**Comment by AndreiArion** [comment]
The readme should have a line with the dependencies needed, for example 
pip install pyyaml ?

**Comment by fredj** [comment]
`yaml` is imported in `theme.py` but it's not used. It can be removed.
