### ISSUE TITLE
RAM for all working processes

### ISSUE THREAD

**Issue by mikigure** [tobi-wan-kenobi/bumblebee-status#253]
Affected module: memory

Description:
Doesn't show the correct amount of memory currently in use:

Hi Tobi,
I wanted to report that yesterday I ran into the issue that my computer completely froze up, because I had not properly calculated how much memory I had given out to my vms and your memory module showed 8% used. I was well aware of this deficiency, but it would be nice if you could adjust the readings.

Thank you.

PS > the attached file is an example of the code that I wrote in order to folder ALL memory usage of the system.

[ShowMemory.txt](https://github.com/tobi-wan-kenobi/bumblebee-status/files/1963210/ShowMemory.txt)

**Comment by tobi-wan-kenobi** [comment]
Hope this patch fixes the issue for you!

I'm not sure why you only see 8% memory used. When I start my VMs, the amount of available RAM quickly depletes, also in the widget.

If you could provide me some sample output from `/proc/meminfo`, I'll gladly investigate further.

**Comment by mikigure** [comment]
YES!! Your patch did the trick.

Thank you for such a quick response.
Miki
