### ISSUE TITLE
Layout module doesn't show the actual layout being used correctly

### ISSUE THREAD

**Issue by oboroqoru** [tobi-wan-kenobi/bumblebee-status#260]
Hello, it looks like there is some bug with switching layouts in bumblebee. I'm not sure how it's actually supposed to work, but I when press alt+shift (which is the binding I use to switch layouts) to switch say, from us to ru (russian), the current layout displayed in the status bar doesn't seem to change accordingly for some reason.
For example at a given moment the output of the setxkbmap command with the -query option may look like this:
>$ setxkbmap -query
>rules:      evdev
>model:      pc105
>layout:     us,ru
>variant:    ,
>options:    grp:alt_shift_toggle

Bumblebee shows that the current layout is us.

Now I press alt+shift and get the following output from setxkbmap issued with -query:
>$ setxkbmap -query
>rules:      evdev
>model:      pc105
>layout:     us,ru
>variant:    ,
>options:    grp:alt_shift_toggle

Now I can type messages in russian, but bumblebee says the current layout is *still* us. 
Then I try to change the layout manually by clicking on the corresponding spot in the status bar, and it now bumblebee shows 'ru'. Yet this time, although bumblebee says I'm using the ru layout, ACTUALLY the symbols I'm typing are english, that is bumblebee is once again mistaken. And now when I issue setxkbmap -query, the output is:
>$ setxkbmap -query
>rules:      evdev
>model:      pc105
>layout:     ru,us
>variant:    ,
>options:    grp:alt_shift_toggle

Is this intended behaviour or a bug indeed?

**Comment by tobi-wan-kenobi** [comment]
Hi,

you are right, this is a bug. When I wrote that module, I wasn't aware that `setxkbmap -query` doesn't necessarily reflect the *actual* layout.

Can you please give the module `layout-xkb` a try instead? It should be a drop-in replacement for `layout` and provide the same functionality. It requires the python module xkbgroup, though.

**Comment by oboroqoru** [comment]
The layout-xkb module works fine indeed. The issue is now resolved. Thank you!
