### ISSUE TITLE
Fedora 28

### ISSUE THREAD

**Issue by loonymike** [tobi-wan-kenobi/bumblebee-status#261]
I see no other way to let you know but I got it working on Fedora 28. Also on the NIC module, would it be possible for the wired interface to behave like the VPN tunnel. That is, it does not present its self until there is an actual IP address. It saves bar space since I use a laptop I am on wireless 100% of the time. Thanks.
Never mind I just turned it off in the bios. Very nice work BTW.

**Comment by tobi-wan-kenobi** [comment]
Hi,

that's great to know, thanks!

Reg. your issue with `nic`: This should be achievable with the parameter `nic.states`. If you want to show only interfaces that are configured and have an IP address, you could do it like this:

`bumblebee-status -m nic -p nic.states=^down`

This would show all interfaces that are *not* in state "down".

Hope this helps!

**Comment by loonymike** [comment]
#
