### ISSUE TITLE
powerline indicator gap

### ISSUE THREAD

**Issue by loonymike** [tobi-wan-kenobi/bumblebee-status#266]
![screenshot from 2018-05-31 10-15-18](https://user-images.githubusercontent.com/30101473/40797092-d7c69184-64bb-11e8-8ef5-dbe7b24e1b51.png)
How can I get rid of that gap? 
Thanks Mike
#### Summary

Affected module: <module name>

Description:
<description>

##### Specs
*Paste the output of `./script/diagnostics.sh [interface]`*

**Comment by tobi-wan-kenobi** [comment]
Hi,

that looks as if the font you are not using is not an AwesomeFont one. Can you please paste the config section of your i3bar from your i3 config? Especially the part where you set the font.

Thanks in advance!

**Comment by loonymike** [comment]
bar {
        status_command  ~/.config/i3/bumblebee-status/bumblebee-status -m cpu load sensors nic amixer battery date time -p interval=3 time.format="%H:%M" date.format="%a, %b %d" home.path=/home -t gruvbox-light
        #font pango:System San Francisco Display 11
        font pango:DejaVu Sans Mono for Powerline 10
        position bottom
        
        colors {
           background #222222
           statusline #eeeeee
           separator #666666
           #                  border  backgr. text
           focused_workspace  #4c7899 #285577 #ffffff
           active_workspace   #333333 #5f676a #ffffff
           inactive_workspace #333333 #222222 #888888
           urgent_workspace   #2f343a #900000 #ffffff
        }
}

**Comment by loonymike** [comment]
It was the font. Thanks for pointing that out.
