### ISSUE TITLE
[modules] Fixed-length modules

### ISSUE THREAD

**Issue by tobi-wan-kenobi** [tobi-wan-kenobi/bumblebee-status#27]
The length of some modules (e.g. cmus) fluctuates quite a lot depending on the content. It would be nice to have the option to restrict the length by padding/truncating the contents.

**Comment by meain** [comment]
or scrolling text for something like cmus maybe?

**Comment by tobi-wan-kenobi** [comment]
That's a good idea, I'll look into it. Having something like a maximum configured length (per widget?) and a interval-based one-character scrolling should be do-able, I think.

**Comment by meain** [comment]
We can set the max-width per component and give flags for scrollable components inside a widget ( as one might contain buttons and stuff )
