### ISSUE TITLE
Battery module

### ISSUE THREAD

**Issue by loonymike** [tobi-wan-kenobi/bumblebee-status#273]
### Feature Request
battery module time to empty

#### Summary
I could swear this used to tell me the time remaining on my battery. If not is this something you can add to the module?
Thanks, Mike

**Comment by tobi-wan-kenobi** [comment]
Hi,

yeah, the module should display the remaining time, given two prerequisites:
1. It doesn't show remaining if you are on AC
2. You need to have the python module "power" installed. A lot of distros don't have that packaged and you need to install it via PIP. Could this be the issue?

Thanks,

Tobi

**Comment by loonymike** [comment]
Yep. That was it. Thanks!
