### ISSUE TITLE
Wrong temperature

### ISSUE THREAD

**Issue by eknoes** [tobi-wan-kenobi/bumblebee-status#275]
#### Summary
Affected module: sensors

Description:
The wrong temperature is shown. I work outside at a temperature >30°C, but the sensors module constantly reports 20°C in my laptop. The module relies on the output of `/sys/class/thermal/thermal_zone0/temp` which can be the right one, but according to [unix.stackexchange](https://unix.stackexchange.com/questions/304845/discrepancy-between-number-of-cores-and-thermal-zones-in-sys-class-thermal) can also be the wrong one.

I will fix it in the next days and do a PR, but am unsure if it is better to 
* iterate through all thermal zones on initialization to find the right type as described on SE
* reverse the order of determining temperature + fallback, so the sensors command will be used if available, otherwise `/sys/.../temp` is read

Maybe a combination of both.

**Comment by tobi-wan-kenobi** [comment]
Fixed in PR #276
