### ISSUE TITLE
Mouse and keyboard lag

### ISSUE THREAD

**Issue by r3v1** [tobi-wan-kenobi/bumblebee-status#280]
#### Summary
Affected module: xrandr

#### Description:
When loading xrandr module, lag appear at mouse and keyboard every time bumblebee-status refreshes (every ~1 second).

#### What is the current behavior and what is the expected behavior?
Keyboard and mouse lag.

#### How to reproduce
4.17.14-arch1-1-ARCH

Bumblebee-status installed by:
`aurman -S bumblebee-status-git`

Also tried with: 
`aurman -S bumblebee-status`

Open a terminal and type:
`bumblebee-status -m xrandr`

#### Expected behavior
The expected behavior was to xrandr won't generate that annoying lag. Maybe caused by xrandr command output delay?

**Comment by tobi-wan-kenobi** [comment]
Thank you for the bug report, sorry you are having issues.

Unfortunately, I cannot reproduce that on my end (4.17.9-1-ARCH, but I'm using the xrandr module since its inception). Could you maybe post the full output of `time xrandr -q`? For me, the command takes 0.028s overall. If, for some reason, the invocation takes significantly longer on your system, that might explain the issue, as this is something I haven't accounted for.

**Comment by r3v1** [comment]
Yes, here it is `time xrandr -q` output:

> [david@arch-david]: ~>$ time xrandr -q
Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 16384 x 16384
DVI-I-0 disconnected (normal left inverted right x axis y axis)
DVI-I-1 disconnected (normal left inverted right x axis y axis)
HDMI-0 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 477mm x 268mm
   1920x1080     60.00*+  59.94    50.00    60.05    60.00    50.04  
   1680x1050     59.95  
   1600x900      60.00  
   1440x900      59.89  
   1400x1050     59.98  
   1280x1024     60.02  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1152x864      60.00  
   1024x768      60.00  
   800x600       60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       59.94    59.93  
DP-0 disconnected (normal left inverted right x axis y axis)
DVI-D-0 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-1-0 disconnected (normal left inverted right x axis y axis)
VGA-1-0 connected (normal left inverted right x axis y axis)
   1280x800      60.16 +
   1280x768      59.87  
   1280x720      60.00  
   1024x768      75.03    70.07    60.00  
   800x600       72.19    75.00    60.32    56.25  
   640x480       75.00    72.81    59.94  
   720x400       70.08  
DVI-1-0 disconnected (normal left inverted right x axis y axis)
  1280x720 (0x49) 74.250MHz +HSync +VSync
        h: width  1280 start 1390 end 1430 total 1650 skew    0 clock  45.00KHz
        v: height  720 start  725 end  730 total  750           clock  60.00Hz
  1024x768 (0x4c) 65.000MHz -HSync -VSync
        h: width  1024 start 1048 end 1184 total 1344 skew    0 clock  48.36KHz
        v: height  768 start  771 end  777 total  806           clock  60.00Hz
  800x600 (0x4f) 40.000MHz +HSync +VSync
        h: width   800 start  840 end  968 total 1056 skew    0 clock  37.88KHz
        v: height  600 start  601 end  605 total  628           clock  60.32Hz
  640x480 (0x53) 25.175MHz -HSync -VSync
        h: width   640 start  656 end  752 total  800 skew    0 clock  31.47KHz
        v: height  480 start  490 end  492 total  525           clock  59.94Hz

> real    0m0,196s
> user    0m0,000s
> sys     0m0,004s

**Comment by tobi-wan-kenobi** [comment]
Hm, that looks good. From the code, I don't see where else a lag could come from.

Can you please post your full bumblebee-status invocation line? Maybe there's a different module playing into that....

**Comment by r3v1** [comment]
Full invocation line: `bumblebee-status -m nic sensors cpu disk:root memory spotify datetime -p nic.exclude="enp1s0,lo" root.format="{percent:05.02f}%" memory.format="{percent:05.02f}%" time.format="%H:%M CW %V" date.format="%A, %d %b %Y" -t solarized-powerline`

However, just `bumblebee-status -m xrandr` gives the same problem

**Comment by tobi-wan-kenobi** [comment]
Ah, that's interesting to know, thanks for the update!
In that case, I'll stop digging through my code :P
