### ISSUE TITLE
Symbol/Emoji fonts are no rendering properly 

### ISSUE THREAD

**Issue by GreyDireWolf** [tobi-wan-kenobi/bumblebee-status#281]
![2018-08-18-160632_1920x21_scrot](https://user-images.githubusercontent.com/13380243/44298498-d6de7c80-a301-11e8-81d4-8e64b0b7120e.png)
On fresh arch linux install I'm having trouble with rendering emoji fonts properly. I have installed noto-emoji fonts still there is a problem in rendering.

**Comment by tobi-wan-kenobi** [comment]
Hi,

can you please post the relevant section (the `bar { }` part) of your i3 configuration? Usually, emoji errors come from there.

Thanks!

**Comment by GreyDireWolf** [comment]
`bar {
colors {
	focused_workspace #008080 #008080 #ffffff
	inactive_workspace #000000 #000000 #005050
	active_workspace #000000 #000000 #008080
	urgent_workspace #8B0000 #8B0000 #000000
	}
	font pango:Hack 9
	status_command bumblebee-status -m pasink battery nic disk datetime -p disk.path=/home datetime.format="%a,%b%d,%Y at %I:%M %p" nic.exclude="enp2s0" -t solarized-powerline
	position top
	}`

**Comment by tobi-wan-kenobi** [comment]
OK, so the problem seems to be that you are using the "Hack" font for the bar, so installing the noto-emoji package won't help (you'll need to select the noto fonts for that).

**Comment by GreyDireWolf** [comment]
Well Ok this was dumb mistake. I just realized i was using glyphs from awesome-terminal-fonts which i did not install. Installing `awesome-terminal-fonts` worked for me. Thanks for your help!

**Comment by davix3f** [comment]
Debian Stretch 9.5 user here.
I partially fixed this issue installing `fonts-font-awesome`. After installing this package, some symbols were rendered. After installing `powerline`, every symbol is now rendered correctly.

Both `powerline` and `fonts-font-awesome` are included in the standard Debian repo
