### ISSUE TITLE
Add more possibilities for theme

### ISSUE THREAD

**Issue by whzup** [tobi-wan-kenobi/bumblebee-status#295]
### Feature Request

It would be very nice to have some more possibilities for theming. For example, a frame would be nice.
#### Summary

I have briefly looked into the code but I'm not quite sure how this would be implemented or how hard it would be. If you could give me a short explanation of the existing code I'd even be down to work on this 😄

**Comment by tobi-wan-kenobi** [comment]
Hi,

I know what you mean, styling options are somewhat limited. I did some investigation, but I believe  this is a restriction from the way the i3 bar works. In a nutshell, `bumblebee-status` generates output "events" conforming to the following protocol: https://i3wm.org/docs/i3bar-protocol.html

`bumblebee-status` supports *all* of the supported parameters (foreground, background, etc.) Some things, like separators, were added "outside" the protocol to allow for powerline-style bars.

In case you want to take a look, all of the relevant code is located in `bumblebee/output.py` in the `I3BarOutput` class. 

Cheers!

**Comment by whzup** [comment]
I see. :thinking: So one would have to change `i3` itself or add some characters to the end or beginning of the widget to add more styling options, right?
But how about something to change the cycling? I guess at the moment it paints the widgets from left to right. It'd be nice to specify it from right to left. For example with a "cycle reversed" option.

**Comment by tobi-wan-kenobi** [comment]
You are right, this would require changes to i3 directly.

Reversing the widgets, however, should be relatively straight-forward. That's in the `I3BarOutput` class, too. Either by caching the output lines and reversing them before printing, or by reversing the widget arrays, I'd have to have a look which one is easier. 

The latter seems cleaner, at first glance.

If that is functionality that is useful for you, feel free to create a feature request, and I will look into implementing it, as soon as I have some spare time :)

Thanks!

**Comment by tobi-wan-kenobi** [comment]
Hi @whzup ,

looked into it, and actually, drawing the widgets right-to-left is pretty straight-forward, so I went ahead and implemented it. Does that fit what you imagined?

Please feel free to open a ticket for any further ideas you might have. 

Cheers!

**Comment by whzup** [comment]
Hello @tobi-wan-kenobi,

Yes it looks good! Thanks a lot for your work! :smile:
