### ISSUE TITLE
Rework your README

### ISSUE THREAD

**Issue by Chilzi** [tobi-wan-kenobi/bumblebee-status#301]
|    Q        |   A
|------------ | -----
| Version     | x

#### Support Question

Could you please go over your README and remove all equality signs in `status_command =`?
After following your example code just got a
'status_command not found or is missing a library dependency (exit 127)' 
errormessage after which I started a small witchhunt.
Took me hours to realize the equality sign is just wrong (maybe i3 changed it's syntax? I'm new to linux).

**Comment by tobi-wan-kenobi** [comment]
Damn, that's one nasty documentation bug, thanks for finding it!

Will fix as soon as I'm in front of a laptop again, so probably tomorrow or so.

Thanks!

⁣Sent from TypeApp ​
