### ISSUE TITLE
status_command not found or missing a library

### ISSUE THREAD

**Issue by IlhamSetiawan** [tobi-wan-kenobi/bumblebee-status#303]
hello sir I want to report that the bumblebee status in linux arch does not work, as if there are problems with the dependency.

I also included my config : https://pastebin.com/gkEx7KjU

![2018-10-19-022037_1366x768_scrot](https://user-images.githubusercontent.com/37190439/47178526-b18fde00-d345-11e8-8aa7-1abda0d58f3f.png)

**Comment by tobi-wan-kenobi** [comment]
Hi,

I *think* that the Arch package doesn't automatically pull in optional dependencies. Can you please try to run your statusbar command in a terminal and let me know the output?

Probably one of the python modules (python-psutil, maybe?) are missing.

Cheers!

**Comment by jombo1** [comment]
I have it running on my Arch Linux.  You can check out my config here:
https://github.com/jombo1/dotfiles/blob/master/i3/config

Check if all your modules have the required python modules and commandline executables from here:
https://github.com/tobi-wan-kenobi/bumblebee-status/wiki/Available-Modules

**Comment by tobi-wan-kenobi** [comment]
Closing due to timeout. If the issue persists, please reopen.

**Comment by djdanielsson** [comment]
I am having this issue as well. It doesn't error when I just run the command by itself so I believe I have a ll the dependencies. I am on Fedora 30 and I cloned the repo and pip installed the dependencies.

**Comment by tobi-wan-kenobi** [comment]
*Sometimes* this seems to be related to Python 2 vs. Python 3 (i.e. on the console, bumblebee-status uses one, in i3 the other).

Can you please try to enable the debug log (`-d`) in i3 and post the contents of `~/bumblebee-status-debug.log`?

Many thanks!

**Comment by djdanielsson** [comment]
I figured it out, I didn't double check the path I was using which was causing the error.
