### ISSUE TITLE
Support for Nerdfonts

### ISSUE THREAD

**Issue by jombo1** [tobi-wan-kenobi/bumblebee-status#304]
I've been trying to get some powerline-extra-symbols from the Nerdfont package as separators. The icons don't show up when I set `"seperator": "\ue0b6"` in icons/awesome-fonts.json or themes/powerline.json. I've tried it on supporting fonts like Inconsolata Nerdfont Mono Medium but it still doesn't show. How do I make this nerd-font compatible?

**Comment by tobi-wan-kenobi** [comment]
Hi,

hm, that *should* work. Can you show me how you are setting the status bar font in the i3 configuration?

One small thing: I see you have a typo in your example ("separator" vs. "seperator"), might that be the reason?

**Comment by jombo1** [comment]
I double checked that it's spelled correctly.

Here's i3config:
```
bar {
    position top
    font pango:Inconsolata Nerd Font Mono Medium 8
    status_command ~/.config/bumblebee-status/bumblebee-status -m disk memory cpu uptime nic layout pasink battery date time -p time.format="%H:%M CW %V" date.format="%a, %b %d %Y" -t iceberg-powerline
    tray_output none
    colors {
        separator $cn
        focused_workspace   $rd $bk $rd
        active_workspace    $bg $bk $fg
        inactive_workspace  $bg $bk $fg
        urgent_workspace    $bk $rd $bk
    }

```
Likewise here's an edit of iceberg-powerline.json
```
{
    "icons": [ "awesome-fonts"],
    "defaults": {
        "separator-block-width": 0,
        "default-separators": false,
        "separator": "\ue0b6",
        "warning": {
            "fg": "#0f1117",
            "bg": "#e2a478"
        },
        "critical": {
            "fg": "#0f1117",
            "bg": "#e27878"
        }
    },
    "cycle": [
        { "fg": "#696d80", "bg": "#34394e" },
        { "fg": "#17171b", "bg": "#5a5f72" },
        { "fg": "#17171b", "bg": "#818596" },
        { "fg": "#161821", "bg": "#c6c8d1" },
        { "fg": "#17171b", "bg": "#818596" },
        { "fg": "#17171b", "bg": "#5a5f72" }
    ],
    "dnf": {
        "good": {
            "fg": "#b4be82",
            "bg": "#161821"
        }
    },
    "pacman": {
        "good": {
            "fg": "b4be82",
            "bg": "#161821"
        }
    },
    "battery": {
        "charged": {
            "fg": "#0f1117",
            "bg": "#b4be82"
        },
        "charging": {
            "fg": "#0f1117",
            "bg": "#84a0c6"
        }
    }
}
```
What shows: 
![bumblebeehelp](https://user-images.githubusercontent.com/43164062/47234254-14a36400-d38a-11e8-8464-46b37a1df041.png)

**Comment by tobi-wan-kenobi** [comment]
Just gave it a try in Arch, worked for me (damn, the Nerd fonts are one big download!)

I know it's a stupid question, but is it possible that the Inconsolata Nerd font is missing? From what I can see, there's multiple ways to install those fonts, and some contain patches for all fonts, others don't. Did that possibly slip?

**Comment by jombo1** [comment]
Derp, I rebooted my system and tried again and they work now. Probably should have been the first thing I tried. I'm not sure why it worked since I was able to use Nerd Fonts fine with vim-airline and tmux status bar. Thank you for taking the time to look at this for me anyway. 

And thank you for creating this nice status bar.

**Comment by tobi-wan-kenobi** [comment]
Glad the issue is resolved, and thanks for using bumblebee-status!
