### ISSUE TITLE
Broken status bar (laps over)

### ISSUE THREAD

**Issue by npsoni88** [tobi-wan-kenobi/bumblebee-status#305]
I am new to i3wm and its installed on linux Mint, here's the OS.
nishant@b0x:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 19 Tara
Release:	19
Codename:	tara

I installed bumblebee-status and here's what the output looks like. Any clues as to why would this happen?
![bumblebee-error](https://user-images.githubusercontent.com/38212081/47233443-641c7b00-d3f0-11e8-9311-7df89c25df2f.png)

Here's my status command:
status_command /home/nishant/.config/bumblebee-status/bumblebee-status -m cpu memory battery -p time.format="%H:%M" -t solarized-dark-awesome

**Comment by tobi-wan-kenobi** [comment]
Hi,

can you please try the following:

1. Install the package "font-inconsolata"
2. Change the bar configuration so that it looks like this:
`
bar {
        font pango:Inconsolata 12
        status_command /home/nishant/.config/bumblebee-status/bumblebee-status -m cpu memory battery -p time.format="%H:%M" -t solarized-dark-awesome
}
`

**Comment by tobi-wan-kenobi** [comment]
Closing due to timeout. If the issue persists, please reopen.
