### ISSUE TITLE
traffic module shows incorrect values if interval is not 1s

### ISSUE THREAD

**Issue by ilmagico** [tobi-wan-kenobi/bumblebee-status#306]
#### Summary
Affected module: traffic

Description:
The reported upload/download speed is incorrect if the update interval is not 1 second.

#### What is the current behaviour and what is the expected behaviour?

It seems the algorithm to compute the "speed" is just the current total minus the previous total. This works as long as the time interval between now and the previous value is exactly one second, but it needn't be.

The correct behaviour would be to divide the value by the time interval.

#### How to reproduce
```
$ bumblebee-status -m traffic -p interval=3
```
then use `wget` or something to download a file, watch the speed `wget` reports, and compare with the one reported by the traffic module (about three times as much for interval=3).

#### Expected behavior
The speed should match reality.

**Comment by ilmagico** [comment]
Thanks! That was quick ;)
Just one question though: wouldn't it be better to keep the time as float instead of casting it to an integer? This way fractional intervals would work correctly too. For example, the documentation at https://github.com/tobi-wan-kenobi/bumblebee-status/wiki#usage has an example with `interval=2.5`.

**Comment by tobi-wan-kenobi** [comment]
Good point. That is my C background, with inherit distrust wrt. float coming through :P

**Comment by tobi-wan-kenobi** [comment]
Thanks for the bug report, I try to fix stuff that's really broken (as in this case) as quickly as I can.
