### ISSUE TITLE
Temperature reading from the wrong sensor

### ISSUE THREAD

**Issue by cdarken** [tobi-wan-kenobi/bumblebee-status#308]
#### Summary
Affected module: sensors

Description:
My output for `sensors -u`:

```
$ sensors -u    
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:
  temp1_input: 46.000
  temp1_max: 100.000
  temp1_crit: 100.000
  temp1_crit_alarm: 0.000
Core 0:
  temp2_input: 46.000
  temp2_max: 100.000
  temp2_crit: 100.000
  temp2_crit_alarm: 0.000
Core 1:
  temp3_input: 45.000
  temp3_max: 100.000
  temp3_crit: 100.000
  temp3_crit_alarm: 0.000

acpitz-virtual-0
Adapter: Virtual device
temp1:
  temp1_input: 44.000
  temp1_crit: 103.000

iwlwifi-virtual-0
Adapter: Virtual device
temp1:
  temp1_input: 44.000

pch_skylake-virtual-0
Adapter: Virtual device
temp1:
  temp1_input: 40.500
```

#### What is the current behaviour and what is the expected behaviour?
Instead of the Package id 0 temp1_input I see the temperature reported by the Virtual device adapter.
I managed to fix this by changing the sensors call like this: `sensors -u coretemp-isa-0000` but I don't know if this is a viable solution for everyone. Maybe modifying the regex to look for 'Package id 0' would be more portable.

**Comment by cdarken** [comment]
Awesome, it works. Sorry for the noise, I didn't read carefully the available parameters.

**Comment by cdarken** [comment]
Coming back to this, the `sensors -u` output changed, the order is different, I don't know why:
```
$ sensors -u 
iwlwifi-virtual-0
Adapter: Virtual device
temp1:
  temp1_input: 46.000

acpitz-virtual-0
Adapter: Virtual device
temp1:
  temp1_input: 66.000
  temp1_crit: 103.000

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:
  temp1_input: 66.000
  temp1_max: 100.000
  temp1_crit: 100.000
  temp1_crit_alarm: 0.000
Core 0:
  temp2_input: 66.000
  temp2_max: 100.000
  temp2_crit: 100.000
  temp2_crit_alarm: 0.000
Core 1:
  temp3_input: 66.000
  temp3_max: 100.000
  temp3_crit: 100.000
  temp3_crit_alarm: 0.000

pch_skylake-virtual-0
Adapter: Virtual device
temp1:
  temp1_input: 53.000
```
So I guess that adding the option to specify a different adapter would be a good idea.

**Comment by cdarken** [comment]
In my specific case `sensors -j` isn't an option, the -j option does not exist. I'm on Ubuntu 16.04, `sensors -v` output is `sensors version 3.4.0 with libsensors version 3.4.0`

**Comment by tobi-wan-kenobi** [comment]
Hm, damn.

Would using pysensors be an option? Alternatively, I think having an adapter match, as you suggested, probably is the best solution.

**Comment by tobi-wan-kenobi** [comment]
Hope this fixes your issue. *Instead* of putting "match_number", you can now use "match_pattern" to define a pattern that has to match *before" the "match". The next match is then used for the sensors value.

**Comment by cdarken** [comment]
So I should put these lines in the config file?
```
sensors.match_number=0
sensors.match_pattern=coretemp-isa-0000
```
And I should have the same result as using `sensors -u coretemp-isa-0000` with just the match_number option ?

**Comment by cdarken** [comment]
Something's wrong with the regular expression, that's where the "no such..." text is coming from: "IndexError: no such group"

**Comment by tobi-wan-kenobi** [comment]
My bad, there was a bug in the module, which should now be fixed.

Actually, right now, the *only* thing you have to provide is the "match_pattern" (if you want to read "temp1_input"):

`/bumblebee-status -m sensors -p sensors.match_pattern="Core 1"`

This gets you the value of the next "temp1_input" that follows "Core 1".
