### ISSUE TITLE
Sway support

### ISSUE THREAD

**Issue by JonnyMako** [tobi-wan-kenobi/bumblebee-status#312]
### Feature Request
It almost works with Sway.
https://github.com/swaywm/sway

The separator icons and colors don't quite matchup.

#### Summary
I am attaching a screenshot of how bumblebee-status bar looks with solarized-powerline theme with the default example from the wiki:
```
bar {
	status_command <path>/bumblebee-status -m cpu memory battery time pasink pasource -p time.format="%H:%M" -t solarized-powerline
}
```
![bbstatus](https://user-images.githubusercontent.com/6559121/47779313-d0d42700-dcc6-11e8-8954-7ebddd410395.png)

**Comment by tobi-wan-kenobi** [comment]
Hi,

this looks like a font issue, can you check whether any of the suggestions in 
#228 or #233 help? Sometimes, it's just the right font package or font configuration missing.

Alternatively, setting `separator-block-width` in the theme to a negative value could also help.

Please let me know whether that fixes the issue, if not, I'll gladly dig deeper :)

**Comment by JonnyMako** [comment]
Yes, it was a font issue. There was a global font set for my config. Sorry for the confusion.
