### ISSUE TITLE
Arbitrary path to theme

### ISSUE THREAD

**Issue by ZuluEchoRomeoOscar** [tobi-wan-kenobi/bumblebee-status#319]
### Feature Request
Working on a new theme - a version of one of the supplied themes - when the latest update arrived. Without thinking it through, I applied the update - only to find that my theme was swallowed up!

#### Summary
Would it be possible to assign a /path/to/my/own/theme.json?

**Comment by tobi-wan-kenobi** [comment]
Oh, that is a nice idea, on it!

**Comment by tobi-wan-kenobi** [comment]
Hopefully this change fulfills your request.

Please note that the change also enables you to load the iconsets (the `icon` parameter in the theme file) via filenames now.

Thanks for the excellent suggestion!
