### ISSUE TITLE
xrandr clobbers my i3 config file.

### ISSUE THREAD

**Issue by jeffeb3** [tobi-wan-kenobi/bumblebee-status#322]
#### Summary
Affected module: xrandr

Description:
When I toggle my monitors with xrandr, it copies ~/.config/i3/config.template (which it made earlier) to the ~/.config/i3/config. I haven't seen anywhere that this is documented, and it seems like a real problem. I was looking through a lot of i3 settings, and getting my config just right, and then I disable a monitor and there goes that work...

The code that does it is in load-i3-bars.sh:
https://github.com/tobi-wan-kenobi/bumblebee-status/blob/master/bin/load-i3-bars.sh

#### What is the current behaviour and what is the expected behaviour?
It deletes my i3 configuration, silently.

#### How to reproduce
Put something in the config that's not in the config.template. toggle a monitor, watch the setting disappear.

#### Expected behavior
Don't delete my config file without telling me.

**Comment by jeffeb3** [comment]
From the load-i3-bars.sh script, it looks like it's expecting someone to have some common functionality in config.template, then add screen specific things with screen.<screen> or screen.<screen>.<otherscreens>. If you had screen specific configurations, then it would make sense to have a base config file, and screen additions.

Maybe the solution is to reorder the concatenations so it only does the config->config.template and config.template->config if there are any config.screen files present?

**Comment by tobi-wan-kenobi** [comment]
Ouch, yeah. That's a pretty bad bug. I originally implemented that to suit my purposes and promptly forgot about the implications when putting the tool on github for general usage.

Thinking about it, I believe the safest bet is to *only* do this if the user explicitly allows it via configuration (i.e. if you set `xrandr.overwrite_i3config` to `true`, the behavior would be fine).

Thanks for raising it and sorry for trashing your config :(

**Comment by tobi-wan-kenobi** [comment]
For what it is worth, the corresponding documentation is here: https://github.com/tobi-wan-kenobi/bumblebee-status/wiki/xrandr
