### ISSUE TITLE
Dual Monitors  questions

### ISSUE THREAD

**Issue by Dobbie03** [tobi-wan-kenobi/bumblebee-status#323]
I have dual monitors and I would like to have a status bar across both screens.  One with workspaces/modules the other with workspaces/tray.  At the moment both screens show the same modules.

Is this possible?

**Comment by tobi-wan-kenobi** [comment]
Yes, that works using the i3 config:

```
bar {
  output <first output name taken from xrandr>
  tray_output none
  status_command <bumblebee-status invocation>
}
bar {
  output <second output name taken from xrandr>
  tray_output <second output name taken from xrandr>
  status_command <bumblebee-status invocation>
}
```

**Comment by Dobbie03** [comment]
Most excellent, thank you for the reply.
