### ISSUE TITLE
module shortcut not responsive

### ISSUE THREAD

**Issue by mnpqraven** [tobi-wan-kenobi/bumblebee-status#324]
#### Summary
Affected module: shortcut

Description:
Hello, i came across this bug when trying to install bumblebee in i3, the parameters in the docs for the modules, i entered the example `./bumblebee-status -m shortcut -p shortcut.cmds="ls;ps" shortcut.label    s="A;B"` and saw the changes(bar is now `A<B`) to the bar but i couldn't click on it and also nothing happened. Is there anything that i could've missed ?

**Comment by mnpqraven** [comment]
so that's what i have misunderstood, i thought it would open a new terminal window for me. But if that is the case, is there anyway to replicate that ?(opening a CLI with a string of command)
also thank you very much for the help

**Comment by tobi-wan-kenobi** [comment]
Yes, that should be possible. Most terminal emulators (gnome-terminal, xterm, etc.) allow you to pass the command to execute as a parameter, so you could have a command like this: "xterm /bin/bash -c 'top'", for example (untested, but I think the syntax should be something like that)

⁣Sent from TypeApp ​
