### ISSUE TITLE
An all battery option.

### ISSUE THREAD

**Issue by martindoublem** [tobi-wan-kenobi/bumblebee-status#327]
### Feature Request
Instead of having several batteries showing when you have more than one, an idea could be to have an option all for showing a combined result of all of them.

I am currently trying to make one (with my limited skills).  I am a little struggling with the whole widget engine but here is the idea I had from the original engine by making a quick script in python.

```  
class Batteries:
    def __init__(self):
        self._batteries = []
        self._batteries.append("/sys/class/power_supply/BAT0")
        self._batteries.append("/sys/class/power_supply/BAT1")

    def widget(self, name):
        for widget in self._widgets:
            if widget.name == name:
                return widget

    def find_capacity(self):
        new_widgets = []
        for path in self._batteries:
            widget = path
            new_widgets.append(widget)
            print(self.capacity(widget))
        print(self.capacity_all(new_widgets))

    def capacity(self, widget):
        try:
            with open("{}/energy_full".format(widget)) as f:
                energy_full = int(f.read())
            with open("{}/energy_now".format(widget)) as o:
                energy_now = int(o.read())
                capacity = int( energy_now / energy_full  * 100)
        except IOError:
            return "n/a"
        capacity = capacity if capacity < 100 else 100
        output =  "{}%".format(capacity)
        return output

    def capacity_all(self, widgets):
        energy_now = 0
        energy_full = 0
        for widget in widgets:
            try:
                with open("{}/energy_full".format(widget)) as f:
                    energy_full += int(f.read())
                with open("{}/energy_now".format(widget)) as o:
                    energy_now += int(o.read())
            except IOError:
                return "n/a"

        capacity = int( energy_now / energy_full  * 100)
        capacity = capacity if capacity < 100 else 100
        output =  "{}%".format(capacity)
        return output




battery = Batteries()

print(battery._batteries)

print(battery.find_capacity())


```

#### Summary
Battery combined widget or all option for all the batteries presents instead of them individually.

**Comment by tobi-wan-kenobi** [comment]
Good idea, thanks! I'd just need somebody to test that, once it is implemented. I only have a single battery :(

**Comment by martindoublem** [comment]
I can test it for you. I am currently trying to build one myself. but I am struggling a bit with widgets as I said.

**Comment by tobi-wan-kenobi** [comment]
Sounds great, thanks! If you have any specific questions regarding widgets, please feel free to reach out.

I think making it a *separate* module is probably better than trying to integrate it into the existing module and over-complicating it, what do you think?

**Comment by martindoublem** [comment]
Got it to work: I am missing the icons for the battery and the charging or discharging as per the normal battery module. Not sure if that was due to me or upstream of widget or something.

I also have an issue indicating that is on AC, I managed to fix that by commenting the lines out (but probably not the right way to go about that.

as of now my battery_all module is the following:

```

# pylint: disable=C0111,R0903

"""Displays battery status, remaining percentage and charging information.

Parameters:
    * battery.device     : Comma-separated list of battery devices to read information from (defaults to auto for auto-detection)
    * battery.warning    : Warning threshold in % of remaining charge (defaults to 20)
    * battery.critical   : Critical threshold in % of remaining charge (defaults to 10)
    * battery.showdevice : If set to "true", add the device name to the widget (defaults to False)
"""

import os
import glob

import bumblebee.input
import bumblebee.output
import bumblebee.engine
import bumblebee.util

try:
    import power
except ImportError:
    pass

class Module(bumblebee.engine.Module):
    def __init__(self, engine, config):
        widgets = []
        super(Module, self).__init__(engine, config, widgets)
        self._batteries = []
        self._batteries.append("/sys/class/power_supply/BAT0")
        self._batteries.append("/sys/class/power_supply/BAT1")
        self.update(widgets)
        engine.input.register_callback(self, button=bumblebee.input.LEFT_MOUSE,
            cmd="gnome-power-statistics")

    def update(self, widgets):
        widget_all = []
        widget_all_name = "All"
        widget_all = self.widget(widget_all_name)
        if not widget_all:
                widget_all = bumblebee.output.Widget(full_text=self.capacity_all, name="All")
        self.capacity_all(widget_all)
        while len(widgets) > 0: del widgets[0]
        widgets.append(widget_all)
        self._widgets = widgets

    def remaining(self):
        estimate = 0.0
        try:
            estimate = power.PowerManagement().get_time_remaining_estimate()
            # do not show remaining if on AC
            if estimate == power.common.TIME_REMAINING_UNLIMITED:
                return None
            if estimate == power.common.TIME_REMAINING_UNKNOWN:
                return ""
        except Exception:
            return ""
        return bumblebee.util.durationfmt(estimate*60, shorten=True, suffix=True) # estimate is in minutes

    def capacity_all(self, widget):
        widget.set("capacity", -1)
        widget.set("ac", False)
        # if not os.path.exists(widget.name):
        #     widget.set("capacity", 100)
        #     widget.set("ac", True)
        #     return "ac"
        capacity = 100
        energy_now = 0
        energy_full = 0
        for path in self._batteries:
            try:
                with open("{}/energy_full".format(path)) as f:
                    energy_full += int(f.read())
                with open("{}/energy_now".format(path)) as o:
                    energy_now += int(o.read())
            except IOError:
                return "n/a"

        capacity = int( energy_now / energy_full  * 100)
        capacity = capacity if capacity < 100 else 100
        widget.set("capacity", capacity)
        output =  "{}%".format(capacity)
        widget.set("theme.minwidth", "100%")
        
        if bumblebee.util.asbool(self.parameter("showremaining", True))\
                and self.getCharge(widget) == "Discharging":
            output = "{} {}".format(output, self.remaining())

        if bumblebee.util.asbool(self.parameter("showdevice", False)):
            output = "{} ({})".format(output, os.path.basename(widget.name))



        return output

       
    def state(self, widget):
        state = []
        capacity = widget.get("capacity")

        if capacity < 0:
            return ["critical", "unknown"]

        if capacity < int(self.parameter("critical", 10)):
            state.append("critical")
        elif capacity < int(self.parameter("warning", 20)):
            state.append("warning")

        if widget.get("ac"):
            state.append("AC")
        else:
            charge = self.getCharge(widget)
            if charge == "Discharging":
                state.append("discharging-{}".format(min([10, 25, 50, 80, 100], key=lambda i: abs(i-capacity))))
            elif charge == "Unknown":
                state.append("unknown-{}".format(min([10, 25, 50, 80, 100], key=lambda i: abs(i-capacity))))
            else:
                if capacity > 95:
                    state.append("charged")
                else:
                    state.append("charging")

        return state

    def getCharge(self, widget):
        charge = ""
        charge_list = []
        for x in range(len(self._batteries)):
            try:
                with open("{}/status".format(self._batteries[x])) as f:
                    charge_list.append(f.read().strip())
            except IOError:
                    pass
        for x in range(len(charge_list)):
            if charge_list[x] == "Discharging":
                charge = charge_list[x]
                break
        return charge

```

**Comment by tobi-wan-kenobi** [comment]
Hi,

thanks! That is a good starting point. 

A few small things:
* Wrong text alignment usually comes from strange special characters - can you please post a screenshot?
* I think it would be nice if the module was able to handle more than 2 batteries (basically by just iterating over all of them)
* We can simplify the module, I think if we change the widget handling so that it always only creates a single widget (if you want to have per-battery widgets, too, you can just use the existing battery module).
* Last but not least: If you want to get your source code into the repository (and I very much encourage you to), could you please open a Pull Request with your changes? You just have to fork my repository, do your change (in a separate branch, preferably), and then create a PR from the github web interface. That way, it is easy for me to review the changes and merge them into the main repository.

Thanks a lot for your contribution!

**Comment by tobi-wan-kenobi** [comment]
Having read your code again:
* Please disregard my 2nd point, that's already happening. There are a few minor thing how we could clean up the code, but we can do that once your changes are in.
* I see why AC cannot work anymore. Maybe the best thing would be to change that code so that in `capacity_all`, the AC code is triggered if *none* of the battery files are available?
* The icons are most likely gone because your module has a different name now. You need to go into the icon definition (themes/icons/...) and copy the "battery" section to a new section that is called like your module.

**Comment by martindoublem** [comment]
Ok, no problem my handling of github and git is quite poor so let me get up to speed and then I will pull my changes

**Comment by tobi-wan-kenobi** [comment]
No worries, please let me know if you need something specific.

If you prefer, I can also add the new module manually this time.

⁣Sent from TypeApp ​

**Comment by martindoublem** [comment]
As you can see the 69% is off by a little, I am yet to try to add the icons

and nice work on sensors2. might make a sensors3 (for myself) to make it just one temp.
 
![2018-11-17-16 40 42-screenshot](https://user-images.githubusercontent.com/42241431/48662825-d9c74580-ea87-11e8-8b48-67f2ebfbc6f1.png)

**Comment by martindoublem** [comment]
Ok let me test this and get back to you. I have them on Arch myself under sys/class/power_input/BAT*

An issue exist still on time remaining:
The time remaining is calculated only for one battery. It could be possible to use the energy_now / power_now to calculate this.

**Comment by tobi-wan-kenobi** [comment]
Ah, interesting... maybe depends on the driver, or some package?

Yeah, I was also wondering about how to calculate time remaining. Should that be just the sum of both? Depends on whether both are discharging at the same time, or one after the other, no?

I am looking forward to see what you will come up with :-)

⁣Sent from TypeApp ​

**Comment by martindoublem** [comment]
Yes it is dependent on the power library of python. I was trying to look into how it calculate the remaining time but it look rather complex. I decided to combine it with a manual calculation as it is useful to find the cases of unlimited or unknown.

The results can be found in: #329

**Comment by tobi-wan-kenobi** [comment]
Since the module has now been merged to the master branch, I'll just close this issue.

Thanks for the additional module!

**Comment by jonasreitemeyer** [comment]
Had the same issue and it took some time to get the solution here. 
My suggestion: Putting a hint into the readme would be great.

Also big thanks to @martindoublem for the module and of course @tobi-wan-kenobi for this awesome status line
