### ISSUE TITLE
Unecpected behaviour on left clicking one particular instance of 'disk'

### ISSUE THREAD

**Issue by ZuluEchoRomeoOscar** [tobi-wan-kenobi/bumblebee-status#330]
#### Summary
Affected module: disk

Description:
I have three instances of the disk module on one of my two i3bars:
`bumblebee-status -m disk:home disk:root disk:angel -p root.path=/ home.path=/home/zero/ angel.path=/mnt/Angel/`
`/mnt/Angel/` is my external backup disk by the way.
All three display correctly, and on `home` and `root` left clicking brings up my file browser (`pcmanfm`) correctly. However, left clicking on `angel` launches `QDirStat` - which is actually quite useful, but not expected behaviour!

**Comment by ZuluEchoRomeoOscar** [comment]
Further info: uninstalling `qdirstat` corrects this behaviour.

**Comment by tobi-wan-kenobi** [comment]
Oh, I am *really* curious to get to the bottom of this. What a weird behaviour. I'll try to reproduce it. Would you be willing to install debug versions to further narrow down the issue, if necessary?

**Comment by tobi-wan-kenobi** [comment]
Looking at the code, I am using xdg-open to open the resource. Possibly *something* makes xdg-open think that /mnt/Angel/ needs to be opened with qdirstat.

Can you try to execute "xdg-open /mnt/Angel/" in a terminal and see whether that does the same?

**Comment by ZuluEchoRomeoOscar** [comment]
Yep - for some reason that opens Angel in qdirstst.
I'm not at all with the mechanics of xdg, so I'm not sure how to debug this - but it clearly isn't the fault of bumblebee...

**Comment by ZuluEchoRomeoOscar** [comment]
Could it be some sort of default for disks mounted in /mnt - they are presumed to be external devices maybe?

**Comment by ZuluEchoRomeoOscar** [comment]
`xdg-mime query filetype /mnt/Angel/` returns `inode/mount-point` - as opposed to` inode/directory` which is what is normally expected. I have a further two drives mounted on `/mnt` which also return `inode/mount-point` so it's not something unique to Angel.
I am currently doing some reading on xdg via the always reliable (but somewhat terse) Arch wiki...

**Comment by ZuluEchoRomeoOscar** [comment]
https://github.com/shundhammer/qdirstat/issues/21#issuecomment-230163936

**Comment by ZuluEchoRomeoOscar** [comment]
SOLVED: In pcmanfm I selected 'Devices' from the left panel, which lists all the attached disks and the File System. Right clicking on the disk labelled Angel brings up a 'properties' dialogue, from which the default handler can be chosen.
Thanks for you help and this interesting digression!

**Comment by tobi-wan-kenobi** [comment]
Ah, that's good to know! Thanks for sharing and the really uniquely interesting bug report :)

**Comment by ZuluEchoRomeoOscar** [comment]
I have just discovered that the disk module has `disk.open` parameter - which defaults to `xdg-open` - which would have solved it in the first place. For all cases!
