### ISSUE TITLE
Wiki is incorrect

### ISSUE THREAD

**Issue by tonijarjour** [tobi-wan-kenobi/bumblebee-status#331]
The wiki says this:

`bar {
	status_command = <path to bumblebee-status/bumblebee-status> -m <list of modules> -p <parameters> -t <theme>
}`

when it should say this:

`bar {
	status_command <path to bumblebee-status/bumblebee-status> -m <list of modules> -p <parameters> -t <theme>
}`

**Comment by tobi-wan-kenobi** [comment]
Good catch! Should be fixed now, thanks for pointing this out!
