### ISSUE TITLE
Can't hit play on cmus module when the status output is empty

### ISSUE THREAD

**Issue by TheEdgeOfRage** [tobi-wan-kenobi/bumblebee-status#334]
#### Summary
Affected module: cmus

Description:
When I initially start cmus the output in bumblebee is just `- /`. The problem is that clicking on the empty part after it doesn't register as a click on the module, only when clicking on the text or icon. I could fix it easily by padding the output with spaces if there is no song currently playing, though it might be a better idea to fix it in the engine itself.

#### How to reproduce
When cmus hasn't loaded a song yet, the bumblebee module looks like this:
https://i.imgur.com/6HY8kwD.png
Clicking on the empty part does nothing, only when either clicking the stop icon or `- /`.

#### Expected behavior
The click should register on the whole widget, not just where there's text.

**Comment by tobi-wan-kenobi** [comment]
Hey, welcome back and thanks for the report :-)

That's a funny bug, to be sure. From what I can see so far, this looks to be something within i3 itself. I am using the "min_width" field in the i3bar protocol to extend the length, and I am not even getting a click event in that section.

I will investigate whether I can replace the min_width with a custom implementation that does some kind of whitespace padding, but that might be difficult.

Cheers!

**Comment by tobi-wan-kenobi** [comment]
Hm, that was easier than anticipated, though the implementation is slightly ugly (conversion of "width" to string and vice versa).

Please let me know if it works for you!

**Comment by TheEdgeOfRage** [comment]
Works and looks the same. Thanks :)
