### ISSUE TITLE
Click events not firing

### ISSUE THREAD

**Issue by DLongoni** [tobi-wan-kenobi/bumblebee-status#336]
Hello,

I am using i3gaps, and i3wm 4.16, and a freshly cloned version of bumblebee status. Click events are not triggering commands, for instance clicking pasink is not triggering pavucontrol. Even adding pasink.left-click="pavucontrol" won't help. I have tried running bumblebee status with -d flag, but I didn't notice any useful info. Do you have any hint on why this is happening or on how to debug it?

Thanks

**Comment by tobi-wan-kenobi** [comment]
Hi,

that is strange, as I have i3wm 4.16, too, with i3gaps (Arch Linux), and click events work for me.

I have committed a few additions to the logging right now, which should give us detailed information about the incoming events.

If you could update bumblebee-status, run it in debug mode and attach the log, that would be a great help for tracking down this issue.

Thanks and sorry for the issues!

**Comment by DLongoni** [comment]
Great, thanks a lot for the feedback. I will do it as soon as possible, which will probably be in some 10 hours from now. I'll keep you posted.

**Comment by DLongoni** [comment]
Cloned the repo, and click is working. How typical! Consider that I last cloned the repo 2 days ago. 
As for the logging, I enabled only pasink and memory modules. Left clicked on the memory module, and the output of "pacmd stat' and 'pacmd list-sinks' is added to the log every second:

`[2018-12-05 00:05:18,357] INFO     executing command 'pacmd list-sinks'
[2018-12-05 00:05:18,367] INFO     command returned '2 sink(s) available.
    index: 0
...
`
`[2018-12-05 00:05:18,348] INFO     executing command 'pacmd stat'
[2018-12-05 00:05:18,357] INFO     command returned 'Memory blocks currently allocated: 1, size: 63,9 KiB.`

And the same at 00:05:19, 00:05:20, and so on. I don't think this is the intended behavior. I mean, those command are run by the pulseaudio module and that's fine, only I don't know if they should be logged.
On the other hand, if i click on the "memory" block, the execution is logged only once:
`[2018-12-05 00:07:40,520] INFO     executing command 'gnome-system-monitor'`

Anyway, thank you very much for the support.

**Comment by tobi-wan-kenobi** [comment]
Heh, yeah, another Heisenbug ;)

If you have the buggy bumblebee-status still cloned somewhere, I'd be interested in a "diff -Naupr" between those two directories. I fixed a click event issue recently (#318 / 3e39f443efdaa02), but it was ~2w ago, so it shouldn't be present in a 2-day old checkout.

Regarding your other question: In debug mode, all executions are logged, including those the modules do to figure out what to display. For me, the output looks OK.

Thanks for the report, if we can't reproduce the issue at all, I'd say to just close the ticket as a one-off :)

Cheers,

tobi-wan

**Comment by DLongoni** [comment]
Yeah sorry man but I din't think about it and I just replaced the old version I had. All good then, agreed in closing this. Thanks a lot for the suppport!
Cheers
