### ISSUE TITLE
Cant use themes using -t <theme>

### ISSUE THREAD

**Issue by jsharp1207** [tobi-wan-kenobi/bumblebee-status#338]
|    Q        |   A
|------------ | -----
| Version     | not sure how to check. git cloned it today.

#### Support Question
./bumblebee-status -m datetime -p time.format="%H:%M" date.format="%a, %b %d %Y" -t iceberg.json 
returns...

File ".bumblebee-status", line 80, in <module>
      main()
File "/home/jack/bumblebee-status/bumblebee/theme.py", line 53, in __init__
      raise bumblebee.error.ThemeLoadError("no such theme")
bumblebee.error.ThemeLoadError: no such theme

All my themes are in ~/bumblebee-status/themes

**Comment by tobi-wan-kenobi** [comment]
Hi,

yeah, that's something that could be better documented.

Normally, you just have to specify the theme *name* (in your case, "iceberg"), e.g. `bumblebee-status -t iceberg`, without the trailing ".json". Alternatively, you can specify the full path to the theme file, e.g. `bumblebee-status -t themes/iceberg.json`.

Hope that helps!
