### ISSUE TITLE
Power module based on upower

### ISSUE THREAD

**Issue by tobi-wan-kenobi** [tobi-wan-kenobi/bumblebee-status#347]
### Feature Request
The current power module doesn't work reliably on some laptops (charging state is "unknown" quite often).

Using `upower` to query the power daemon, if available, could improve this.

**Comment by martindoublem** [comment]
I could take a look into this if you want.

**Comment by tobi-wan-kenobi** [comment]
@martindoublem that would be awesome! Realistically, I won't have time to look into it for the next couple of weeks, at least, and I think it would be a really nice addition.

If you need anything wrt. to the framework, please let me know.

**Comment by martindoublem** [comment]
Do you know which OS uses upower by default, because the one I used dont. Making it complicated for me to do so.

**Comment by tobi-wan-kenobi** [comment]
I am using Arch and it's present there.

Cheers!

⁣Sent from TypeApp ​

**Comment by martindoublem** [comment]
OK so I started it, now you can finish it. ;) I only did it for the display device but much more could be done.

**Comment by tobi-wan-kenobi** [comment]
Thanks a lot for the contribution, I really appreciate it!
