### ISSUE TITLE
Scrolling over the bar causes it to speed up

### ISSUE THREAD

**Issue by Morganamilo** [tobi-wan-kenobi/bumblebee-status#353]
### Bug Report

The bar appears to update on a timer. It also appears to update whenever the user interacts with the bar. On laptops, scrolling using the trackpad counts as many many interactions per second. This causes all the modules to kind of speed up.

The cpu and ram usage flickers between a bunch of values quickly. The battery animation speeds up 100 fold. It all just looks weird and distracting whenever I want to change the volume.

#### How to reproduce
Scroll quickly over the bar, preferably on a trackpad with momentum enabled.

#### Expected behavior
The current module should update, the rest should remain as normal.

**Comment by tobi-wan-kenobi** [comment]
That's a good point. TBH, I haven't fixed that so far, because I suspect it requires relatively big changes in the code.

I will start working on it, but just to give fair warning: It might take some time until you see results, and then they might be buggy... :)

**Comment by tobi-wan-kenobi** [comment]
I've added a few debug messages. If you don't mind, it would be great if you could run your bar in debug mode (`-d`) and paste the contents of `~/bumblebee-status-debug.log` after the problem has occurred.

Also, for reproducing, if you could share how you're calling bumblebee-status, that would be very helpful.

Thanks and sorry for the inconvenience!

**Comment by tobi-wan-kenobi** [comment]
Just for reference: I've now pushed the changes to master, as they seem to work for me. That way, if they cause issues, at least somebody else might notice and say so :)

Please let me know if you can collect the log. In the meantime, I'll keep this bug updated in case I manage to trigger the issue again.

**Comment by tobi-wan-kenobi** [comment]
Sorry to hear that!

A couple of question:
- Which distribution are you using?
- On the commandline, is the command "pactl" available?
- Also, if you could enable debug logging ("-d -f <path to log file>") and provide the log file, that would be a big help.

Thanks in advance and sorry for the issues!

**Comment by tobi-wan-kenobi** [comment]
Closed due to timeout
