### ISSUE TITLE
unicode rendering issue with font awesome 5.7

### ISSUE THREAD

**Issue by JonnyMako** [tobi-wan-kenobi/bumblebee-status#356]
Earlier today I upgraded ttf-font-awesome (5.6.3-1 -> 5.7.0-1) and this is causing issues with some icons not being rendered properly. See disk, calendar and weather icons in the screenshot.

![status](https://user-images.githubusercontent.com/6559121/51956269-acdec980-240c-11e9-97f8-7423c0f3e8c8.png)

**Comment by tobi-wan-kenobi** [comment]
That is weird. This looks a bit as if - sometimes - the space character isn't rendered correctly.

Can you please let me know how the font config for your i3bar looks like?

Also, according to #281, it's the awesome console fonts, not the TTF fonts that are considered for the bar, seemingly (at least, if you are on Arch)

Also, Awesome 5 doesn't work completely (#239).

**Comment by JonnyMako** [comment]
This is the bar invocation in config.

```
bar {
        font pango:Inconsolata for Powerline 10
        status_command /usr/bin/bumblebee-status -m cpu load sensors traffic disk memory battery date time weather -p time.format="%H:%M:%S" weather.unit="Imperial" -t gruvbox-powerline
}
```

**Comment by tobi-wan-kenobi** [comment]
Well, that should definitely work. Can you please try to see what happens if you switch to plain "Inconsolata"? Typically, these problems occur if fonts don't specify certain glyphs...

**Comment by JonnyMako** [comment]
> Well, that should definitely work. Can you please try to see what happens if you switch to plain "Inconsolata"? Typically, these problems occur if fonts don't specify certain glyphs...

Same issue with `font pango:Inconsolata`

**Comment by piozylka** [comment]
Same problem for me after upgrade to 5.7.0-1
switching fonts doesnt change anything

**Comment by tobi-wan-kenobi** [comment]
Have the same issue since the last system update.

For me, funnily, uninstalling ttf-font-awesome fixed the issue. You *might* need to install otf-font-awesome-4 from AUR, though, not sure about that.

Hope this helps!

⁣Sent from TypeApp ​

**Comment by tobi-wan-kenobi** [comment]
@JonnyMako does that solve the issue for you, too? If so, I'd just close the ticket, if that is fine with you.

**Comment by JonnyMako** [comment]
After uninstalling font-awesome-5 and installing font-awesome-4 I don't see the icon that tells me if I'm plugged in or on battery power. Do you also see this? It would be nice if there was a way to get this back.

![status2](https://user-images.githubusercontent.com/6559121/52080486-7d8ba200-255d-11e9-8ff1-d853b0205b3e.png)

**Comment by JonnyMako** [comment]
@tobi-wan-kenobi  you were right about console fonts being used. Actually awesome-fonts-4 can be completely uninstalled without any affect on bumblebee-status. The iconic fonts being used can be installed by awesome-terminal-fonts package on aur, but looks like the plug and lightning icons don't exist in any of the awesome-terminal packages available for Arch. So I'm not sure how to fix this question mark icon for the changing status.

**Comment by JonnyMako** [comment]
I'm closing since the original problem has been solved and this looks more like a fonts issue.
