### ISSUE TITLE
The order of the parameters matters for the datetime module

### ISSUE THREAD

**Issue by RobinVogel** [tobi-wan-kenobi/bumblebee-status#357]
### Bug Report

I just spent some time not understanding this. In my setup, if I write my i3 config file as:
```
status_command ~/Documents/i3/bumblebee-status/bumblebee-status \
            -m redshift weather cpu spotify todo pulseaudio pasink datetime layout \
            -p datetime.format="%a %e %b %Y - %H:%M" \
            -p pulseaudio.limit="100%" \
            -p pasink.limit="100%" \
            -t solarized-powerline
```
then the `datetime.format` is ignored, i.e. I see:
![2019-01-30t20 02 09 01 00](https://user-images.githubusercontent.com/7306538/52005460-0c4edf00-24ca-11e9-8d7b-1cec4908aa09.png)

Otherwise, If I write:
```
bar {
        # position top
        font pango:DejaVu Sans Mono, FontAwesome 10
        # status_command i3status
        status_command ~/Documents/i3/bumblebee-status/bumblebee-status \
            -m redshift weather cpu spotify todo pulseaudio pasink datetime layout \
            -p pulseaudio.limit="100%" \
            -p pasink.limit="100%" \
            -p datetime.format="%a %e %b %Y - %H:%M" \
            -t solarized-powerline
        # "%a %e %b %Y - %H:%M" \
        # amixer apt cmu (no) brightness datetime diskspace (no) layout (doesn't work)
        # load memory redshift todo 
        # -t greyish-powerline
}
```
then my bar is suited to human beings:
![2019-01-30t20 04 34 01 00](https://user-images.githubusercontent.com/7306538/52005561-47e9a900-24ca-11e9-9beb-93fe1bbd7c38.png)

**Comment by tobi-wan-kenobi** [comment]
Heh, that's a fun one :)

I can reproduce the issue on my end. I *think* it's because you are using the `-p` flag every single time. `-p` works the same as `-m`. If you specify multiple parameters, please use `-p` only once, otherwise the last parameter will override all others.

Have to admit, this is not nice behaviour, I will investigate whether there's a way to make that a bit more robust.

**Comment by RobinVogel** [comment]
It is exactly it, once I specify `-p` only once, things behave as expected. Thanks !
