### ISSUE TITLE
[modules/indicator] shows only if num/caps lock are pressed

### ISSUE THREAD

**Issue by haluk** [tobi-wan-kenobi/bumblebee-status#363]
### Feature Request
The module highlights Num/Caps Lock if they are pressed. It would be better if they can be only seen in the bar if they are pressed. Current solution takes up unnecessary space.

**Comment by tobi-wan-kenobi** [comment]
Good idea, will look into that!

**Comment by rad4day** [comment]
A workaround would probably be to keep the signal type as "warning" and add the module to the autohide parameter.

**Comment by tobi-wan-kenobi** [comment]
Ah, I wasn't aware the indicator module was using warning/critical. In that case, what @rad4day suggested is not even a workaround, but the proper solution. Thanks for pointing that out!
