### ISSUE TITLE
Black background to statusbar

### ISSUE THREAD

**Issue by Dobbie03** [tobi-wan-kenobi/bumblebee-status#365]
I'm using version bumblebee-status-git r1042.930c70e-1 from the AUR

#### Support Question
So I have selected greyish-powerline as my theme but for some reason most of my panel is black.  I have tried other themes with the same issue.

![img-2019-02-23-163314](https://user-images.githubusercontent.com/14961904/53281195-6bcaa280-3789-11e9-9ff6-8fb9806efbae.png)

Any ideas?

**Comment by tobi-wan-kenobi** [comment]
Hi,

if you refer to the "rest" of the bar - that's not defined by the status program, but rather by the colors you set directly within the i3bar configuration in your i3 config. bumblebee-status can only determine how its widgets look like, not the remaining space.

Hope that helps!

⁣Sent from TypeApp ​

**Comment by Dobbie03** [comment]
Yes it does.  Thanks for that. For some reason I didn't have a background colour set.

Thanks again.
