### ISSUE TITLE
Failed imports when trying to use nic module

### ISSUE THREAD

**Issue by Yamanee** [tobi-wan-kenobi/bumblebee-status#367]
|    Q        |   A
|------------ | -----
| Version     | 1.7.2

#### Support Question

Hi,

I'm trying to get 'nic' working on my laptop with :
 * OS : OpenSUSE 15.0
 * i3 v4.15
 * Python v3.6.5

The status bar is working just fine with 

    status_command ~/Documents/Installer/bumblebee-status/bumblebee-status -d -m memory battery amixer brightness date time -p time.format="%H:%M CW %V" date.format="%a,%b %d %Y" -t gruvbox-powerline

but when I add 'nic' it failed with exit code 1.

Here is the the file ~/bumblebee-status-debug.log : 

    [2019-02-28 19:07:02,781] WARNING  failed to import docker_ps: No module named requests.exceptions
    [2019-02-28 19:07:02,781] WARNING  failed to import getcrypto: No module named requests
    [2019-02-28 19:07:02,789] WARNING  failed to import spaceapi: No module named requests
    [2019-02-28 19:07:02,792] WARNING  failed to import stock: No module named requests
    [2019-02-28 19:07:02,793] WARNING  failed to import traffic: No module named psutil

I do have installed netifaces, requests, requestsexceptions and psutil. 
Am I missing something ?

Thanks

**Comment by rad4day** [comment]
Can you check if your bumblebee-status is actually running with python 3.6.5? Also have you made sure that you installed the requests package for python3?

**Comment by tobi-wan-kenobi** [comment]
@rad4day Thanks for helping out!

@Yamanee : `nic` requires the modules "subprocess" and "netifaces". It fails silently, though, if those are missing (not nice, will fix that). Maybe those modules are missing?

**Comment by Yamanee** [comment]
@rad4day you were indeed right : bumblebee-status was running with python 2.7.14 so I changed the first line in the bumblebee-status script to 

    #!/usr/bin/env python3

and now everything seems fine. I'll think about it next time ... 

Thanks again both of you I'll close this thread now.

**Comment by rad4day** [comment]
A more reliable fix would probably be to prefix your status_command in i3 config with `python3` or however the binary is called in opensuse. The bumblebee-status script may be overwritten when you pull an update.

Should look like this:
```
status_command python3 ~/Documents/Installer/bumblebee-status/bumblebee-status -d -m memory battery amixer brightness date time -p time.format="%H:%M CW %V" date.format="%a,%b %d %Y" -t gruvbox-powerline
```
