### ISSUE TITLE
Getting Deadbeef to work with bumblebee

### ISSUE THREAD

**Issue by Dobbie03** [tobi-wan-kenobi/bumblebee-status#368]
I'm using version r1042.930c70e-1 from the Arch AUR.

#### Support Question
For some reason I can't get the current song in Deadbeef to display.  I see in the module it requires the "subprocess" library.  I'm not too sure what package that relates to.  

Of course the module has been added to my i3 config.

Any advice would be appreciated.

Thanks
Matt

**Comment by tobi-wan-kenobi** [comment]
`subprocess` is part of the Python Standard Library, so you shouldn't have to install any additional package/library. You need the executable `deadbeef` in your standard path, though, maybe that is the issue? (i.e. maybe it's in your shell path, but Python somehow loses track)

If that's useful for you, I can provide you with a deadbeef module with additional logging?

**Comment by tobi-wan-kenobi** [comment]
Closed due to inactivity. Please reopen if the issue persists.
