### ISSUE TITLE
Bigger Triangles to fit bar correctly

### ISSUE THREAD

**Issue by dillasyx** [tobi-wan-kenobi/bumblebee-status#371]
### Feature Request
It would be nice to choose between the smaller triangles and the bigger ones, so they would fit the bar. I have a comparison between the triangles in this status bar and in NeoVim Airline to see what I mean.
https://imgur.com/a/aXghO4h

#### Summary
Bigger Triangles as Seperator

**Comment by rad4day** [comment]
I just tried to change the separator to test if this looks better. Seems like It's exactly the same character though... and I can't find any references to resizing the character neither in vim-airline nor bumblebee-status. That's rather strange. I'd guess it's font related as fonts seem to render differently in a terminal :/

@tobi-wan-kenobi got any idea why they might look so different?

**Comment by dillasyx** [comment]
I am using same font for both: Droid Sans Mono for Powerline 
That's why I don't understand this issue and yeah I just saw, that's the same icon.
Maybe height of the bar is too big? Just a thought, as font and icon aren't the problem, I guess.

**Comment by rad4day** [comment]
Seems like you're right. https://www.reddit.com/r/unixporn/comments/2rdci0/i3_wip_i3bar_with_arrowstyled_blocks/ suggests that it's a problem with i3 rendering 2 pixels around the supplied bar.

https://gist.github.com/Airblader/72d6a03d05c111d33ad4 In line 26 indicates that there is a 2px border around the statusbar which is not configurable with normal i3. :(

**Comment by dillasyx** [comment]
Is bumblebee-status using i3bar or is it handled differently?
Because this issue looks related to i3bar and yeah there is a border arround it, but if you look on my audio module for example, there is not only a 2px border above it, the module color itself is too big, too. Is this also handled by i3bar? 
![border](https://user-images.githubusercontent.com/11612223/55241886-61923d00-523c-11e9-930b-902f930a8ae7.png)

**Comment by rad4day** [comment]
There is a space of padding around the separators, that's why the colour is "too big". I guess i3bar takes the background color it gets from bumblebee and colors the background and border accordingly.
bumblebee-status just provides the json input to i3bar

**Comment by dillasyx** [comment]
Found a padding setting for i3bar, but it does not do anything, when i use it i my config. https://i3wm.org/docs/userguide.html#_tray_padding 

But I think I have to deal with it.. Still a fancy Statusbar

**Comment by tobi-wan-kenobi** [comment]
Hi,

sorry for being somewhat late to the party :-)

I think that @rad4day is right and this is a restriction coming from i3. I've observed this myself, but was never able to really resolve it.

@dillasyx `bumblebee-status` implements the i3bar protocol, so it's tied to whatever restrictions the bar itself has. I believe @rad4day is right that the padding color is the background color, and therefore, the next element (the volume value, in your case) appears "bigger" than the arrow (the yellow arrow is the foreground color, whereas the yellow in the volume is the background color).

If everyone is fine with that, I think I have to close this ticket as "can't fix", unfortunately.

**Comment by dillasyx** [comment]
Thanks for the information, yeah I am fine with that.

**Comment by rad4day** [comment]
If I find some time I'll look if I find a way to patch i3bar ;)
Now that someone pointed it out it starts to annoy me

**Comment by tobi-wan-kenobi** [comment]
That'd be awesome, it's annoying to me, too :)

**Comment by rad4day** [comment]
Well, found a [hacky way](https://github.com/rad4day/i3/commit/220f351a57819e05d5c046fec020c2faa97bb858). Still I'm not too happy with it right now, seems to work with dpi-scaling though.

**Comment by moshpirit** [comment]
The hacky way is no longer available (404) :disappointed:

**Comment by MaxandreOgeret** [comment]
For everyone having the same issue, as of today setting a `padding` of `-2px` on the bar looks much better:

```
184 bar {
     font pango:FontAwesome 11, FiraCode Nerd Font Propo 11
     position top
     padding -2px
     status_command bumblebee-status \
         -m brightness load memory sensors nvidiagpu pipewire battery date time \
         -p sensors.show_freq="false" nvidiagpu.format="{temp}°C" date.format="%Y-%m-%d" time.format="%H:%M" memory.format="{percent:3.0f}%" \
         -t solarized-powerline
 }
```

<img width="763" height="20" alt="Image" src="https://github.com/user-attachments/assets/0997c0d9-e3dc-4056-9534-328c8a3912bb" />
