### ISSUE TITLE
process exited with code 1

### ISSUE THREAD

**Issue by zetxx** [tobi-wan-kenobi/bumblebee-status#381]
#### Summary
Affected module: <module name>

Description:
right after logged in and not yet connected to network. after network connection is done and reload i3 everything works fine

#### What is the current behaviour and what is the expected behaviour?
if no network it says "proces exited ...." but should run normally 

#### How to reproduce
dissconect from any network and hit reload on i3

#### Expected behavior

plugins that im using are:

`status_command bumblebee-status -m title github amixer brightness battery date time layout dunst -p date.left-click="gsimplecal" time.format="%H:%M CW %V" date.format="%a, %b %d %Y" layout.lang=us battery.warning=25 battery.critical=18 interval=5 github.token=$GIT_TOKEN_STATUS github.interval=30 -t iceberg-powerline`

actually i think that github plugin have to do a lot with this issue.

**Comment by tobi-wan-kenobi** [comment]
Unfortunately, I am unable to reproduce the issue.

I use all the plugins in your example and tried to a) disconnect the network cable and when that didn't work b) to stop NetworkManager, in both situations, no exception occurred.

Looking into the github module, it looks as if all exceptions *should* be caught.

Could you please run your command on the CLI, try to reproduce the issue (reloading i3 should be the same as just starting bumblebee-status again) and let me know the backtrace/log lines, please?

**Comment by zetxx** [comment]
humm, strange, i cant reproduce it after latest boot. closing it for now, till reproduce it.

**Comment by zetxx** [comment]
https://imgur.com/a/XTtdoEG

**Comment by rad4day** [comment]
@eknoes *ping*

**Comment by tobi-wan-kenobi** [comment]
Hope this fixes the issue. I think this might be a startup error because dunst isn't running yet when i3 starts.

**Comment by eknoes** [comment]
Thanks!

**Comment by zetxx** [comment]
fixed
