### ISSUE TITLE
docker_ps and root permissions

### ISSUE THREAD

**Issue by gipert** [tobi-wan-kenobi/bumblebee-status#384]
|    Q        |   A
|------------ | -----
| Version     | master@94427ea

#### Support Question
Am I missing something or the docker_ps module is fully functional only if the current (non-root) user has the rights to invoke docker? I tried to ping the docker daemon from the python shell and I get
```
requests.exceptions.ConnectionError: ('Connection aborted.', error(13, 'Permission denied'))
```

**Comment by zetxx** [comment]
you should add yourself to docker group

**Comment by gipert** [comment]
I did it and now `docker.DockerClient(base_url='unix://var/run/docker.sock').ping()` returns `True` if I run it in the repl. However, it still excepts in the module (`n/a` keeps being displayed). Strange. Any ideas on how to debug this?

**Comment by zetxx** [comment]
did i3 reload ?

**Comment by tobi-wan-kenobi** [comment]
Also, if you could provide some log debug - or an output of bumblebee-status -m docker from the commandline, that would be a big help.

Thanks!

**Comment by tobi-wan-kenobi** [comment]
Also, note that on some distributions, there's multiple python versions - i.e. if you did your tests with python3, but bumblebee-status is invoked with python2, the docker module might not be installed for python2.

**Comment by gipert** [comment]
The log unfortunately does not report useful info:
```console
$ ./bumblebee-status -d -m docker_ps
{"click_events": true, "version": 1}
[
[{"min_width": null, "separator": true, "background": null, "full_text": " containers n/a ", "instance": "003e811d-6bad-40f8-8718-e6978b9ed296", "color": "#aabbcc", "name": "docker_ps", "align": null, "separator_block_width": null}],
[{"min_width": null, "separator": true, "background": null, "full_text": " containers n/a ", "instance": "003e811d-6bad-40f8-8718-e6978b9ed296", "color": "#aabbcc", "name": "docker_ps", "align": null, "separator_block_width": null}],
...

$ cat ~/bumblebee-status-debug.log
[2019-05-13 09:43:20,884] DEBUG    reading configuration file /home/pertoldi/.config/bumblebee-status.conf
[2019-05-13 09:43:20,884] DEBUG    starting click event processing
[2019-05-13 09:43:29,894] DEBUG    exiting click event processing
```
I keep distinct the two python installations, and I already double checked that I made my tests with the same version used by the bar. I also checked that the `docker` module gets correctly imported by removing the exception catching code around `import docker`.

i3 reaload for sure because I had to reboot the system in order to effectively add myself to the `docker` group. In any case, I reaload it manually too.

When I print something on standard output from within a module, where does it get saved? It would be helpful to debug.

**Comment by tobi-wan-kenobi** [comment]
i3 uses stdin/stdout for the protocol, so if you print something on stdout, you will break the bar :(

The easiest debugging would be if you add stdout output but *only* to call it from the CLI (bumblebee-status -m docker_ps). That's what I would do.

Is it possible that you are missing the requests module? I just saw that docker_ps requires that, too.

**Comment by gipert** [comment]
So, if I let the `cli = docker.DockerClient(base_url='unix://var/run/docker.docker')` line except, it reports the following traceback:
```console
$ ./bumblebee-status -m docker_ps
{"click_events": true, "version": 1}
[
[],
Traceback (most recent call last):
  File "./bumblebee-status", line 80, in <module>
    main()
  File "./bumblebee-status", line 74, in main
    output.draw(widget, error)
  File "/home/pertoldi/.dotfiles/.config/i3/bumblebee-status/bumblebee/output.py", line 128, in draw
    padding = self._theme.padding(widget)
  File "/home/pertoldi/.dotfiles/.config/i3/bumblebee-status/bumblebee/theme.py", line 110, in padding
    return self._get(widget, "padding", "")
  File "/home/pertoldi/.dotfiles/.config/i3/bumblebee-status/bumblebee/theme.py", line 241, in _get
    state_themes.append(self._get(widget, state, {}))
  File "/home/pertoldi/.dotfiles/.config/i3/bumblebee-status/bumblebee/theme.py", line 259, in _get
    if mod and not mod.parameter("is-unittest"):
  File "/home/pertoldi/.dotfiles/.config/i3/bumblebee-status/bumblebee/engine.py", line 114, in parameter
    value = self._config["config"].get(name, default)
TypeError: 'Config' object has no attribute '__getitem__'
```
which I don't understand. Does it tell you something? I actually have my own fork of bumblebee, but I just added plugins and never touched core files... I don't think I broke something

**Comment by tobi-wan-kenobi** [comment]
Strange, I see the same. Investigating

**Comment by tobi-wan-kenobi** [comment]
Hm, for me, the module seems to work. Can you please try to roll back to before your local changes and see whether the issue occurs there, too?

If not, you can bisect (go to the commit in the middle and proceed until you've narrowed the issue down to a single commit). I'll gladly have a look at the commit to see what's going wrong, then.

**Comment by gipert** [comment]
Now I realized where I could have broke it, it happend some days ago when I updated my fork and fixed some conflicts, let me debug it and I'll surely find the problem. I'll close this, thank you for your support and sorry for spamming!

**Comment by tobi-wan-kenobi** [comment]
Glad your issue is solved!
