### ISSUE TITLE
click event not firing for bumblebee popup menu entries

### ISSUE THREAD

**Issue by bbernhard** [tobi-wan-kenobi/bumblebee-status#393]
I am experiencing a really strange issue on my workstation. For some reason the menu entries in the bumblebee popup won't fire a click event anymore. At this point, I am not really sure whether that's a bug somewhere in bumblebee or if this is just a "doesn't work on my machine phenomenon". 

I've created a small module (`click-test.py`) which illustrates the issue (at least on my machine). It would be great if someone could give it a try if the same issue also occurs on other machines. 

```
import logging

try:
    import Tkinter as tk
except ImportError:
    try:
        import tkinter as tk
    except ImportError:
        logging.warning("failed to import tkinter - bumblebee popups won't work!")

import bumblebee.input
import bumblebee.output
import bumblebee.engine
import functools

class Module(bumblebee.engine.Module):
    def __init__(self, engine, config):
        super(Module, self).__init__(engine, config,
                bumblebee.output.Widget(full_text=self.click_status)
        )

        self._clicked_button = None
        engine.input.register_callback(self, button=bumblebee.input.LEFT_MOUSE,
                                        cmd=self.popup)

    def update(self, widgets):
        pass

    def click_status(self, widget):
        if self._clicked_button is None:
            return "NONE"
        if self._clicked_button == "first button":
            return "FIRST BUTTON"
        if self._clicked_button == "second button":
            return "SECOND BUTTON"

    def on_button_click(self, name):
        self._clicked_button = name
        logging.info("Button %s clicked", name)

    def popup(self, widget):
        menu = bumblebee.popup.PopupMenu()

        menu.add_menuitem("first button", functools.partial(self.on_button_click, "first button"))
        menu.add_menuitem("second button", functools.partial(self.on_button_click, "second button"))

        menu.show(widget)

    def state(self, widget):
        return []

```

The module is pretty simple - it just creates two menu entries in the popup. Depending on which menu entry is clicked, the text in the status bar changes. 

The first button click after restarting i3 usually works - I can see that the status bar text entry changes successfully (depending on which button I've clicked). But after a few clicks (most of the time it takes only a few clicks until this happens) the status bar text won't changes anymore.

When this happens, I see only the following type of entries in the bumblebee log file: 

```
[2019-06-02 14:02:39,758] DEBUG    new event: {"name":"click-test","instance":"b761d015-e00a-4cc1-ba27-43e8d5fcb24f","button":1,"x":1081,"y":6}
[2019-06-02 14:02:40,380] DEBUG    popup: menu dismissed
```  

It looks like, that the `on_button_click` method doesn't get called anymore - otherwise there would be a log entry? 

Does this only happen on my machine or does anyone else experience the same behavior? (I can't rule out that I have done something wrong in my module either ;). Although I have the same problems with the `bluetooth` module - which also uses the popup functionality). 

(this example requires this [code change](https://github.com/tobi-wan-kenobi/bumblebee-status/pull/392))

**Comment by tobi-wan-kenobi** [comment]
No, I see the same. Maybe @brunosmmm is still active and has an idea. He's the original implementor.

I have to admit my knowledge of Tk is hazy at best, I'll give it a closer look during the weekend, though.

Thanks for raising this!

**Comment by tobi-wan-kenobi** [comment]
I'm closing this, as there's a working alternative now with `popup_v2.py`.

Thanks @bbernhard for the contribution!
