### ISSUE TITLE
documented dependency does not exist

### ISSUE THREAD

**Issue by donfranio** [tobi-wan-kenobi/bumblebee-status#395]
#### Summary
Affected module: apt

Description:
The docu sais it needs a debian-package named "update-notifier-common" but there is no such package in default debian:
https://packages.debian.org/search?keywords=update-notifier-common

#### What is the current behaviour and what is the expected behaviour?
So apparently the hardcoded script to check the apt-state is not available, but bumblebee reports that everything is fine, no updates necessary.
I would expect an error, something in red, maybe.

#### How to reproduce
Use a vanilla debian machine, start bumblebee with the apt module. Make sure, there is no file /usr/lib/update-notifier/apt_check.py in the filesystem.

#### Expected behavior
Three things:
1. If I had the apt_check.py script, bumblebee apt-module should show the number of expected updates.
1. As I don't have it, bumblebee apt-module should visualize an "alerting" color.
1. If the docu suggests to install a debian-package, the package should exist in the debian-repos or there should be a hint to find the repo where it is in.

**Comment by donfranio** [comment]
Just found out, that `update-notifier-common` is a native ubuntu-package. Not helping for debian though. Also the virtual package `update-notifier` is not leading to any file called `apt_check.py` as used in the apt-module :-(

**Comment by tobi-wan-kenobi** [comment]
Hm.... that's not so good.

For the moment (as I don't have a Debian system at hand for testing), I'll mostly treat this as a documentation issue and add a note that the apt module only works for Ubuntu.

Also, you are right that it should display an error instead of a misleading "no updates":

Thanks for raising this!
