### ISSUE TITLE
Wiki says sensors need sensors, a python module that doesn't exist. 

### ISSUE THREAD

**Issue by maikeldotuk** [tobi-wan-kenobi/bumblebee-status#399]
Basically https://github.com/tobi-wan-kenobi/bumblebee-status/wiki/Available-Modules should say the module sensors needs lm-sensors as a command-line executable, not a python module "sensors" that doesn't exist. 

in Ubuntu I solved it with: sudo apt install lm-sensors after trying with:
pip install sensors
pip install lm-sensors
pip install sensor
and waste half an hour trying to figure it out.

**Comment by tobi-wan-kenobi** [comment]
Updated, thanks for the note, and sorry that this caused you issues!

**Comment by maikeldotuk** [comment]
no worries, thank you :)
