### ISSUE TITLE
Battery module without charging/discharging bolt option

### ISSUE THREAD

**Issue by azbshiri** [tobi-wan-kenobi/bumblebee-status#401]
### Feature Request
battery module without charging/discharging bolt

#### Summary
Can we add a `battery.nosuffix` so that it can be more minimal? just showing the battery icon on discharging and making background green on charging?

**Comment by tobi-wan-kenobi** [comment]
Hi,

thanks for the request! I hope this change satisfies your request. You just need to add `-p battery.decorate=false` to you bumblebee-status line and the indicators should be hidden. The widget will still turn yellow/red when the charge is low (unless I introduced a bug... :P)

**Comment by azbshiri** [comment]
You've removed battery icon :D

**Comment by tobi-wan-kenobi** [comment]
Hi!

Yeah, you are right, that was unintentional. I hope that the current change looks better to you.

I'm deviating in one way from your initial suggestion: A charging battery is not indicated by a green icon (I'd like to keep that for the "almost fully charged" case), instead, the battery icon on the left-hand side will be animated, if the battery is currently charging. Hope that fits your requirements.

If not, please feel free to reopen the ticket.

Thanks for the suggestion!

**Comment by azbshiri** [comment]
Thanks man! really appreciate your enthusiasm
