### ISSUE TITLE
can i use it on bspwm

### ISSUE THREAD

**Issue by subhrajyoti-basu** [tobi-wan-kenobi/bumblebee-status#403]
Actually i found that bspwm is a great tiling window manager option. But i like bumblebee-status a lot. Im not sure how to put it in bspwm.

**Comment by tobi-wan-kenobi** [comment]
Unfortunately, the answer is: No

`bumblebee-status` (like other i3bar replacements) simply generates JSON output that is interpreted by i3 itself to display the status bar. You can see that if you execute `bumblebee-status` in a terminal, it will just print JSON. Without i3, that's pretty useless.

Admittedly, it would be cool if somebody wrote a cross-WM bar that "understood" the i3bar protocol. That would automagically open up all i3bar replacements to other WMs. That'd be a lot of work, though.
