### ISSUE TITLE
solarized-dark-awesome theme is missing when build from source

### ISSUE THREAD

**Issue by azbshiri** [tobi-wan-kenobi/bumblebee-status#405]
After I clone the project and built it using `makepkg -sc`  and I've installed it using `pacman`

OS: Manjaro

**Comment by tobi-wan-kenobi** [comment]
weird... I see that the PKGBUILD is severely outdated, but that should not cause that particular issue.

I'll refresh the PKGBUILD file nevertheless, please let me know if the problem persists.
