### ISSUE TITLE
powerline workspaces

### ISSUE THREAD

**Issue by juriscorza** [tobi-wan-kenobi/bumblebee-status#409]
### Feature Request
Add "arrow-style" workspaces.

#### Summary
It would be nice to have "arrow-style" workspaces, something like that:

![image](https://user-images.githubusercontent.com/40194781/61455648-694d2d00-a964-11e9-8baa-5b3f0b4c3370.png)

**Comment by tobi-wan-kenobi** [comment]
Hi,

as far as I know, that's not possible with an i3bar generator, such as bumblebee. The reason for that is that the workspace is drawn by i3, not by bumblebee.

Sorry about that. But maybe it would be possible to write a module that "emulates" the workspaces.
