### ISSUE TITLE
Icons don't appear

### ISSUE THREAD

**Issue by bideaug** [tobi-wan-kenobi/bumblebee-status#41]
Hi, thanks a lot for your work :)

I tried to make this bumblebee-status works on my computer, and it appears that 
it works fine except for the icons part. I have no icons at all, I tried to run the testjson.sh
script and it told me that this is not json so I assume at least a part of the problem comes 
from here but I don't know what to do in order to make it work.

Thanks

**Comment by tobi-wan-kenobi** [comment]
Hi,

the default icons use the "Awesome" fonts: http://fontawesome.io/cheatsheet/

I *think* the font you choose for the i3bar needs to provide those (I'm using "pango:Inconsolata 11"). Maybe it's enough if you install the awesome font package on your distribution (on Fedora, for example, it's called fontawesome-fonts).

Regarding the testjson.sh: That was a bug :-( There are some invalid JSON files in the themes/ directory for unit testing purposes. I've updated testjson.sh to exclude those.

**Comment by bideaug** [comment]
Thanks for your quick response :)

Ok I retried the testjson.sh, told me that Json is valid, I am using the same font as you pango:Inconsolata 11

Maybe I should have mentioned it before but in fact, I don't have the icons but I do have for instance 

audio 21% if in my config file I have : 
bar {
     font pango:Inconsolata 11
     position top
     tray_output none
     status_command bumblebee-status -m pasink
}

for which I should have an icon instead of audio ?

So nothing changes so far :/

**Comment by tobi-wan-kenobi** [comment]
Ah, that's probably even easier to solve :-)

The default theme is an ASCII theme, for maximum compatibility. Try the following:

`status_command bumblebee-status -m pasink -t solarized-powerline`

for the solarized theme, or `-t gruvbox-powerline` for the gruvbox theme.

**Comment by bideaug** [comment]
Ok it works now, I also had to stop using python 3.6 and install the requested modules in python2.7 .Thanks a lot for the help and for your time ! :) 

This project is awesome it looks really nice :)

**Comment by tobi-wan-kenobi** [comment]
Glad to hear it works & you like the project, thanks a lot! Also, thanks for your patience in getting this resolved.

Yeah, right now, the project is only tested against Python 2.7, 3.3, 3.4 and 3.5. I'll have a quick look to see what's going wrong with 3.6, though.

Also, if you have any feature requests, etc. feel free to just open a ticket, I'm always happy about feedback!
