### ISSUE TITLE
theme data not accessible within registered callback?

### ISSUE THREAD

**Issue by bbernhard** [tobi-wan-kenobi/bumblebee-status#415]
I've stumbled accross something really strange. 

If I try to access the theme data within the `text` method everything works fine, but if I try to access the theme data from within a registered callback it doesn't work. 

I _think_ it is related to the `widget` that's passed as parameter to the callback function. For some reason it doesn't contain the `module` property which seems to be needed [here](https://github.com/tobi-wan-kenobi/bumblebee-status/blob/master/bumblebee/theme.py#L239)

e.g: 

```
# pylint: disable=C0111,R0903

"""Test module
"""

import bumblebee.engine
import bumblebee.input
import logging

ALIASES = ["test-alias"]

class Module(bumblebee.engine.Module):
    def __init__(self, engine, config):
        super(Module, self).__init__(engine, config,
            bumblebee.output.Widget(full_text=self.text)
        )

        engine.input.register_callback(self, button=bumblebee.input.LEFT_MOUSE,
                                       cmd=self.popup)

    def text(self, widget):
       logging.info("inside text function: %d" % hasattr(widget, "module"))
       return "test" 

    def popup(self, widget):
       logging.info("inside popup: %d" % hasattr(widget, "module"))
# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4

``` 

Inside the `text` method the `widget` has the `module` parameter. But the `widget` inside the `popup` method doesn't have it. 

Not sure if this is WAD, a bug or if I'm doing something wrong here :sweat_smile:

**Comment by tobi-wan-kenobi** [comment]
I think that's mostly a documentation problem - the first parameter to the callback command is not a widget - it's the raw event data. In order to get the widget, you have to use `self.widget_by_id(event["instance"])`.

See "xrandr" for an example of that.

Hope this helps!
