### ISSUE TITLE
Weather module: RequestException not defined

### ISSUE THREAD

**Issue by lonesomebyte537** [tobi-wan-kenobi/bumblebee-status#418]
After adding the weather module, the module displays `error: global ...` 

In the debug log I found:

`[2019-08-10 18:14:50,376] ERROR    error updating 'weather': global name 'RequestException' is not defined`

Affected module: weather

**Comment by tobi-wan-kenobi** [comment]
Thanks for raising this, should be fixed now!

Please note that the module will still not work as expected, because the python module "requests" is not installed on your system (that's why the exception above occurred).

**Comment by lonesomebyte537** [comment]
Hi, thanks for the quick response! The problem indeed does not happen anymore with the latest version. After installing requests with pip3 I now see a question mark... Probably something with my setup. But the original issue posted has been resolved! Thx!

**Comment by tobi-wan-kenobi** [comment]
Glad to hear it!

Question mark often means that the location either couldn't be detected or the provided location string is unknown to the service.

Hope this helps!
