### ISSUE TITLE
network_traffic not working in Arch Linux

### ISSUE THREAD

**Issue by Damicristi** [tobi-wan-kenobi/bumblebee-status#427]
My i3 config for bumblebee-status is:

```
bar {
        font pango:Inconsolata 9
        position top
        tray_output primary
        status_command bumblebee-status -m disk cpu sensors memory brightness pasink pasource date time battery -p interval=1 time.format="%I:%M:%S %p" date.format="%a>
}
```

All the modules above is working but when I put network_traffic, i3 gives errors (Error: status_command process exited unexpectedly (exit 1)).

Any suggestions?

**Comment by Damicristi** [comment]
[Error] I found that in wiki ([available modules page](https://github.com/tobi-wan-kenobi/bumblebee-status/wiki/Available-Modules)), there should be traffic instead of network_traffic. Using "traffic" as a module name works for me.

**Comment by Damicristi** [comment]
In version 1.8.0-1 (which I installed) did not have network_traffic module that's why I got error. I added manually. Please update the recent version in AUR.

**Comment by tobi-wan-kenobi** [comment]
Ah, yes. Thanks for letting me know!

I'll update the AUR once the current version is stable for a couple of days.

**Comment by tobi-wan-kenobi** [comment]
Just a short update: I haven't forgotten about this, but as luck wills, there's been a more or less continuous stream of PRs over the last couple of weeks & days, and I'd really like to have a stable (unmodified) master for a week or so before releasing.

On the flip side, I don't want to keep PRs open longer than necessary.

Hope this is fine for you, and hope hat I can release a new version soon.
