### ISSUE TITLE
How can I update the wiki?

### ISSUE THREAD

**Issue by Asuza** [tobi-wan-kenobi/bumblebee-status#430]
|    Q        |   A
|------------ | -----
| Version     | latest

#### Support Question
Is it possible for me to edit the wiki? There's a couple places where a command is wrong (`-l module` instead of `-l modules`) or there's an "a" where there should be an "an". I couldn't find a way to change the wiki or request changes to it, though.

**Comment by tobi-wan-kenobi** [comment]
Hi,

you can request changes via an issue, like you just did - many thanks for that!

You have to be project owner/collaborator to modify the wiki, which is currently just me :)

I'll look through the wiki and try to find all the wrong commands, thanks for pointing them out.

**Comment by tobi-wan-kenobi** [comment]
Can you please point me to the issues? I've been trying to find the `-l module`, but didn't manage to. Thanks in advance!

**Comment by Asuza** [comment]
Sorry, I should have pointed that out to begin with. One instance is at the top of https://github.com/tobi-wan-kenobi/bumblebee-status/wiki/Available-Modules. I don't remember exactly where the other typo was, but if I spot it again I'll let you know.

**Comment by tobi-wan-kenobi** [comment]
Fixed, thanks for giving me the pointer!

If you come across any further typos, please let me know. If they are in the README, you can just create a PR, otherwise, I'll just go ahead and fix the wiki.

Thanks!
