### ISSUE TITLE
Battery all returning N/A

### ISSUE THREAD

**Issue by martindoublem** [tobi-wan-kenobi/bumblebee-status#432]
#### Summary
Affected module: battery_all

Description:
battery

#### What is the current behaviour and what is the expected behaviour?
Currently returning NA

#### How to reproduce
Run it on any laptop where one of the /sys/class/power_supply is not present

#### Expected behavior
returning the percentage of battery remaining properly

I investigated and by commenting the path that was problematic it solved it. I will be working on a solution shortly that uses the os library to investigate the directory properly folder where the power supplies are and return the correct values.

**Comment by tobi-wan-kenobi** [comment]
fixed in #443
