### ISSUE TITLE
Trying to write a module

### ISSUE THREAD

**Issue by karthink** [tobi-wan-kenobi/bumblebee-status#434]
|    Q        |   A
|------------ | -----
| Version     | Unknown, can't find version number

Couldn't find the version number in the source file.

#### Support Question
I am trying to write a module (pomodoro timer) for bumblebee-status, but I can't get it to work. It shows up on the status bar, but I can't get the timer to start. 

```
# pylint: disable=C0111,R0903

"""Display and run a Pomodoro timer.
Left click to start timer, left click again to pause.
Right click will cancel the timer.
"""

from threading import Timer
import subprocess

import bumblebee.input
import bumblebee.output
import bumblebee.engine

class Module(bumblebee.engine.Module):
    def __init__(self, engine, config):
        widgets = bumblebee.output.Widget(full_text=self.text)
        self.remaining_time = 25
        self.pomodoro = { "state":"OFF", "type": "n/a" }
        self._text = str(self.remaining_time) + "m " + self.pomodoro["type"] + " " + self.pomodoro["state"]
        super(Module, self).__init__(engine, config, widgets)
        engine.input.register_callback(self, button=bumblebee.input.LEFT_MOUSE,
                                       cmd=self.timer_play_pause)
        engine.input.register_callback(self, button=bumblebee.input.RIGHT_MOUSE,
                                       cmd=self.timer_reset)
        
    def text(self,widget):
        return "{}".format(self._text) 
        
    def update(self,widget):
        self._text = str(self.remaining_time) + "min " + self.pomodoro["type"] + " " + self.pomodoro["state"]
    
    def timer_play_pause(self, widget):
        if self.pomodoro["state"] == "OFF":
            self.pomodoro = {"state": "ON", "type": "WORK" }
            self.remaining_time = 25
            self.run_timer()

        elif self.pomodoro["state"] == "ON":
            self.pomodoro["state"] = "PAUSED"
            self.stop_timer()
            
        elif self.pomodoro["state"] == "PAUSED":
            self.pomodoro["state"] = "ON"
            self.run_timer()

    def timer_reset(self, widget):
        if self.pomodoro["state"] == "ON":
            self.pomodoro = { "state":"OFF", "type": "n/a" }
            self.remaining_time = 25
            self.stop_timer()
    
    def run_timer(self, widget):
        self.one_minute_timer  = Timer(60,self.decrement_remaining_time)
        self.one_minute_timer.start()

    def stop_timer(self, widget):
        try:
            self.one_minute_timer.cancel()
        except:
            pass

    def decrement_remaining_time(self, widget):
        self.remaining_time = self.remaining_time - 1
        if self.remaining_time == 0:
            if self.pomodoro["type"] == "WORK":
                self.pomodoro["type"] = "PLAY"
                self.remaining_time = 5
            elif self.pomodoro["type"] == "PLAY":
                self.pomodoro["type"] == "WORK"
                self.remaining_time = 25
        else:
            self.run_timer()
```

I'm not very good at Python or programming in general, and I wrote this by reading the code for the other modules. I'm hoping someone can see the problem. [Here is the same code](https://pastebin.com/hsAhYmej) on pastebin if that's more convenient.

**Comment by tobi-wan-kenobi** [comment]
Hi,

thanks, this looks like a very useful module, please keep going :)

One thing: Adding logging would help you troubleshooting for sure (see system, stock or sensors for examples)

On first glance, your code looks good, except:
- self.decrement_remaining_time is a callback method for Timer(), I don't see how it should get widget as second parameter. And since that parameter isn't used anyhow, I'd just scratch it.
- Also, if I get correctly what's happening, you shouldn't need separate threads at all. Something like this: When the user left-clicks -> toggle state, record current timestamp. During each regular update, get the current time, calculate diff since last invocation and update state & widget output accordingly. That works because the widget is updated in two cases: During the regular update, and every time you click on it.

Hope this helps!

**Comment by martindoublem** [comment]
I would like to see this implemented and therefore will probably take the relay in the next few days.

**Comment by tobi-wan-kenobi** [comment]
Much appreciated, thanks!

**Comment by martindoublem** [comment]
OK, I just finished one, let me know what you think!

**Comment by martindoublem** [comment]
Ideally, we could also add a config, for how much work time and play time. I just used the 25 and 5 ratio.

**Comment by tobi-wan-kenobi** [comment]
I guess with the merge of #447, this ticket can be closed.

Many thanks to @martindoublem  and @karthink for yet another cool bumblebee module!
