### ISSUE TITLE
wayland support? (vault)

### ISSUE THREAD

**Issue by rotsix** [tobi-wan-kenobi/bumblebee-status#438]
|    Q        |   A
|------------ | -----
| Version     | r14.17cd4c1-1

edit: same issue with 1.9.0

#### Support Question

Hi, I'm using `bumblebee-status` on sway 1.2 (Aug 29 2019).

I'd like to use the vault plugin, but I'm facing a problem: when using -git version (aur), clicking the button won't popup the menu.

Is it wayland specific? TKInter seems to support wayland.

**Comment by tobi-wan-kenobi** [comment]
Hi,

sorry about that. TKInter isn't specific to any kind of X server, as far as I am aware.

What's the output if you just enter "pass" in the CLI (minus anything sensitive, of course)? Possibly, if you don't have any secrets yet, or you use a different password store layout, or special characters, that might throw the module off.

**Comment by rotsix** [comment]
Hi,

`pass` is working in my terminal, expected output.
Weird, but no menu appears, no matter which module. Looks like a Tkinter or wayland bug.

**Comment by tobi-wan-kenobi** [comment]
Hm...

A basic test to check whether Tkinter is working at all would be:

# start interactive python shell
$ python
import tkinter
# the command below should open a window
window = tkinter.Tk()
window.title("test")

# now the title of the window should be test

Does that work for you?

**Comment by rotsix** [comment]
Fuuuu[...]uuuu, tkinter wasn't installed.
My bad, thanks :)
