### ISSUE TITLE
Module dependency listing incomplete 

### ISSUE THREAD

**Issue by GNUke** [tobi-wan-kenobi/bumblebee-status#439]
Cant figure out how to PR a wiki so I figured this would be the way to go. 

The spotify module in the wiki should list python-dbus as a dependency, it's even listen in the module comment's. Would have saved me some time today :D !

**Comment by tobi-wan-kenobi** [comment]
Damn, my bad, I missed that one. I think I mistakenly thought that dbus is part of the Python Standard Library.

Fixed now, sorry for the time you had to waste ;/

**Comment by GNUke** [comment]
No worries, thanks!
