### ISSUE TITLE
Positions for modules

### ISSUE THREAD

**Issue by Silipwn** [tobi-wan-kenobi/bumblebee-status#442]
### Feature Request

Having positions for modules in the bar could allow users to customize their statusbar more.
#### Summary

Could be implemented in having specific positions for a module or could be done by having a generic layout for the statusbar like left, right or justified.

**Comment by tobi-wan-kenobi** [comment]
Hi,

thanks for the feature idea!

The order in which modules appear in the bar is determined by the order in which you specify them on the CLI for bumblebee (-m). Whether the bar is left/right/justified, is something that's determined (and hardcoded, I believe) by the i3 window manager. Unfortunately, the program implementing the i3bar protocol has no say in this.
