### ISSUE TITLE
tests pass without i3ipc, pytz or tzlocal

### ISSUE THREAD

**Issue by jayvdb** [tobi-wan-kenobi/bumblebee-status#457]
### Feature Request
All Python dependencies should be used by the test suite.

Currently the test suite passes, without any skips, if those modules are not present.

#### Summary
datetimetz module uses pytz & tzlocal

sun module uses tzlocal and `suntime` by @lonesomebyte537 da33d295 . c.f. https://github.com/SatAgro/suntime/issues/9

title module uses i3ipc

The test suite should have tests which specifically exercise the code which uses each dependency, and skip if missing, to ensure that the modules and those dependencies are working correctly together.

**Comment by jayvdb** [comment]
I see quite a few other modules also have dependencies which are not being documented anywhere easy for packagers to use.

I'll start compiling a `module-requirements.txt` to help move things forward a bit.

**Comment by tobi-wan-kenobi** [comment]
Perfect, many thanks!

The thing is that those dependencies are optional, ie. if they are not present, the modules in question will not work, but all others will. Not sure how to handle that "correctly" in a test. Given the way the tests are written now, it's pretty hard to skip those.

**Comment by tobi-wan-kenobi** [comment]
should be fixed in latest master
