### ISSUE TITLE
Should "br" prefixes be excluded by default in the nic module?

### ISSUE THREAD

**Issue by Asuza** [tobi-wan-kenobi/bumblebee-status#460]
I'm not a networking expert, but it seems as if all my interfaces that start with "br" are related to Docker. I figured out how to exclude it via parameters, and was wondering if that should be added to the list of defaults to exclude or not.

**Comment by tobi-wan-kenobi** [comment]
I agree, since bridged interfaces typically don't have an IP. Thanks for pointing this out!
