### ISSUE TITLE
Modules datetimtz, datetz and timetz returning [n/a] for time

### ISSUE THREAD

**Issue by arBalasquide** [tobi-wan-kenobi/bumblebee-status#476]
#### Summary
Affected module: datetimetz, datetz, timetz

#### Description:
When calling for time, it returns [n/a]

#### How to reproduce
One Manjaro 4.19.88 using the current master of bumblebee-status as of writing this. Using Python 3.8 and have both dependencies pytz and tzlocal

**Comment by tobi-wan-kenobi** [comment]
Sorry to hear that.

If I gave you some debug code, would you be willing to run it to see what the root cause is? I can easily add some more logging.

If that works for you, please let me know. Thanks!

**Comment by arBalasquide** [comment]
@tobi-wan-kenobi 

Thank you for the reply. 

Most definitely! Just tell me what code to put in and I'll get to it when I can.

**Comment by tobi-wan-kenobi** [comment]
Great, thanks a lot!

I have just pushed a bit more logging, if you execute bumblebee like this on the commandline, it should give you some error messages:

./bumblebee-status -m datetimetz -f stdout -d

If you paste those to me, I might be able to debug further. Thanks a lot in advance!

**Comment by arBalasquide** [comment]
@tobi-wan-kenobi 

Weird. Its working now after I pulled the changes. But I also did restart my PC after a system update so perhaps there was something weird going on with python?

Anyhow, thank you for being quick about this :)!

I'll close the issue now.
