### ISSUE TITLE
Color Emojis

### ISSUE THREAD

**Issue by arBalasquide** [tobi-wan-kenobi/bumblebee-status#477]
### Feature Request

Colored emojis

#### Summary

Currently, the emojis for modules are plain to me and I would like for the ability to use colored emojis to be able to customize my bars.

**Comment by tobi-wan-kenobi** [comment]
What do you mean by "colored emojis"? Using the Themes, you should already now be able to change the font color (foreground color), which *should* also change the emoji color. If you want the emoji to be a different color than the text, I'm afraid that's a restriction of i3wm, and hence not possible to fix in bumblebee-status.

Each "block" in the bar can have one background and one foreground color, not multiple different colors.

If that's what you want, you probably need to look at other bars (lemonbar supports this, I believe, for example).
