### ISSUE TITLE
Config interface change

### ISSUE THREAD

**Issue by JohnDowson** [tobi-wan-kenobi/bumblebee-status#479]
I believe that config should be changed to more hash-like square bracket interface, with declaration of default value moved from getter to the point of declaration. Making it necessary to declare all possible options for a module preemptively would greatly increase readability and maintainability.

**Comment by tobi-wan-kenobi** [comment]
Agreed (to a certain extent, to some, I'd argue this is a matter of taste). For example, I really like the fact that if you need another parameter, that's a change in one place only - where you need the parameter. Forcing a declaration of parameters means that you'll always have to touch at least two places.

Also, I'm not exactly sure what you mean by declaring the options preemptively, could you give an example how you'd envision that to look like?

TBH, realistically, I'm not sure this will happen quickly, if at all, because of the large number of modules that exist already, and a "either/or" solution would inherit the drawbacks of both approaches, without any of the benefits, in my opinion.

**Comment by JohnDowson** [comment]
I'm thinking kinda like this.
You don't need to deal with asbool() and such, you run no risk of using different defaults in different places and forgetting about that, and the params become somewhat self-documenting: you just need to take a look at dunder init.

```
class Module()
    def __init__():
        self.params["some_param"] = newConfigParam("some_param", type='bool', default=False)

    def someFunc():
        if self.params["some_param"]:
            dothing()
```

**Comment by tobi-wan-kenobi** [comment]
Ah, I see, it's an interesting idea for sure.

But wouldn't this kind of type-safety only be a "seeming" risk reduction? I mean, even if you do that, there's nothing in Python preventing you from using the bool "some_param" as a string later down the road.

Don't get me wrong, I am entirely open to the idea, I just believe I am not really getting the hang of the advantage yet, so please bear with me :)

**Comment by JohnDowson** [comment]
https://gist.github.com/JohnDowson/cee03864642f4b151b6caddea698bd7c

Something like that, maybe?
Another thing that is I'm a little less sure how to implement is tree params, so you could do stuff like:
`coolmodule.theme.exclude=prefix, postfix`
in the config

**Comment by JohnDowson** [comment]
I guess that's configfile-centric, but using json for config would work pretty neatly for tree-like params.

**Comment by tobi-wan-kenobi** [comment]
I see, interesting point.

But still, you could only be sure that the *input* is in the correct format (and that can already be guarded against with the current bumblebee.util.asXXX helpers). If somebody then, in the module, mistakenly compares a bool against a string, there's nothing you can do against that, right?

And for the tree structure: I toyed with that idea, but you can get something that "feels" like this for the user already, and so far, there's not a single module that would warrant that complexity. Most modules have 3, maybe 4 parameters, tops.

I guess that is my main concern here, overall: The increase in complexity vs. the use cases. I mean, there's a lot of modules already, and none of them experience any problems with the parameters, and most of them have only a very small number of very simple parameters.

In other parts of bumblebee-status (themes, for example), more complexity and more structure is something necessary, but for the config parameters for the modules, I'm just not seeing it (yet, maybe).

I am sorry if I sound obstinate, but whenever adding complexity to the code base in a central part, I want to make absolutely sure it is warranted and pays back.

Thank you for your patience :)

**Comment by JohnDowson** [comment]
Main thing I would like to do is to allow to access theme parameters as module.widgets.theme in the config.

**Comment by tobi-wan-kenobi** [comment]
Ah, I see. That should be possible to be exposed - but why? To me, it seems like this mixes the concerns of UI / look (the "theme") with how a module should behave (the configuration).

I.e. if you ask me and want to change the theme of a widget, I'd suggest to create a theme.

Can you tell me the concrete use case you have in mind for this?

**Comment by tobi-wan-kenobi** [comment]
I will close this one for now, as it is a sound idea in principle, but hard to achieve with the current structure and - honestly - not realistic in the short term given the amount of time I can dedicate to the project right now.

Many thanks for raising the ticket, though. I appreciate a lot if people care about style and internal workings.
