### ISSUE TITLE
System module not "working" on Debian Buster

### ISSUE THREAD

**Issue by devianpctek** [tobi-wan-kenobi/bumblebee-status#481]
Affected module: **system**

Description:
I'm pretty new to i3, and found out about this great status bar, I'm still figuring out a lot of stuff but my main issue is the **system** module, (running Debian Buster amd64) I added the module to the bar and it shows fine, but none of the options are working for me, when I click the "shutdown", "reboot", "logout" options, I get the confirm dialog and after clicking yes nothing happens, on the other options there's no dialog but still doesn't work, any hints that I might be missing?

**Comment by JohnDowson** [comment]
- "shutdown -h now"
- "reboot"
- "i3exit logout"
- "i3exit switch_user"
- "i3exit lock"
- "i3exit suspend"
- "i3exit hibernate"
Can you run all those commands manually?

**Comment by devianpctek** [comment]
>     * "shutdown -h now"
> 
>     * "reboot"
> 
>     * "i3exit logout"
> 
>     * "i3exit switch_user"
> 
>     * "i3exit lock"
> 
>     * "i3exit suspend"
> 
>     * "i3exit hibernate"
>       Can you run all those commands manually?

the shutdown and reboot commands I can, but only with sudo, the rest I don't have the i3exit, I found on the web that is a script:
`#!/bin/sh
lock() {
    i3lock
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
`
but I don't know where to put it

**Comment by JohnDowson** [comment]
Figured out as much, Debian packages are a bit odd at times.
You can put i3exit script anywhere on your $PATH and it should work.
I'll patch the module to use i3msg directly for portability.

**Comment by tobi-wan-kenobi** [comment]
@JohnDowson I don't think there's i3-msg commands for reboot and stop, though. One way to get around that, I guess, would be to make the commands being executed configurable. @devianpctek would that solve your problem?

Thanks for raising the issue!

**Comment by devianpctek** [comment]
@tobi-wan-kenobi I'm not sure 😅 like I said before, I'm pretty much new, but I can give it I try

**Comment by tobi-wan-kenobi** [comment]
Will try to find some time during the weekend to implement that, then :)

**Comment by tobi-wan-kenobi** [comment]
@devianpctek I've added parameters to override each of the commands. So as long as you have *any* non-interactive command that works for you, you should be good.

Just call `bumblebee-status -m system -p system.reboot='sudo reboot'` or whatever you need to.

Please let me know if you still have issues!

**Comment by KillerwolfX** [comment]
> @devianpctek I've added parameters to override each of the commands. So as long as you have _any_ non-interactive command that works for you, you should be good.
> 
> Just call `bumblebee-status -m system -p system.reboot='sudo reboot'` or whatever you need to.
> 
> Please let me know if you still have issues!

Figured out a way,
system -h shutdown or reboot wont work in debian 10 or later.
Similarly 'sudo shutdown now' won’t work since it needs user interaction for sudo password!
So a non interactive command would be,
-p system.shutdown='systemctl poweroff'
