### ISSUE TITLE
Bug in mpd module?

### ISSUE THREAD

**Issue by somospocos** [tobi-wan-kenobi/bumblebee-status#482]
#### Summary
Affected module: mpd

#### Description:
I am posting this as question because I don't fully understand the code yet.

My use case is that my music files don't have any tags, they are all in **"artist - song name.ogg"** format. So I went to read the source file mpd.py to see what config options do I have and if it's possible to tune the plugin to display what I want.

In the docstring of that file I read about **mpd.format**. For a start, I change it to **"{file}"**. Doesn't work. The first problem is that the default value of mpd.format is not documented properly in the docstring. I scroll down and see:

    self._fmt = self.parameter("format", "{artist} - {title} {position}/{duration}")

at line 52.

So I was probably wrong. Second attempt is to try with **mpd.format="{file} {position}/{duration}"**. This does not work either. I start reading the code further.

    info = bumblebee.util.execute('mpc -f "tag artist %artist%\ntag title %title%"' + self._hostcmd)

this is line 82 and to me it really looks like the **"{artist} - {title}"** is simply hardcoded here into the mpc call, while the docstring advertises I can change it (see above) - at least this is how I understand it.

So is this a bug in the mpd module or am I doing anything wrong?

This is just the first half of my problem. The second one is that when I run **mpc -f "%file%"**, I get a string that looks like **"path/relative/to/mpd/music/directory/root/artist - song name.ogg"**. So even if **"{file}"** would give me what I want, I would still need to post-process the string:

- to remove the ".ogg" extension
- to split it by "/"
- to get the last item which would be "artist - song name" that will get displayed

I'm afraid I don't know how to do this inside the mpd.format option.

Considering all of this, perhaps it would be a better idea for me to just fork this module and hack it to work properly for my particular case?

#### How to reproduce

Described above.

**Comment by tobi-wan-kenobi** [comment]
If I understand you correctly, what you want to have is the file name, without path and extension, correct?

I'm afraid right now, mpd just looks at the tags. But TBH, it shouldn't be too hard to extend the module, give me a moment.

**Comment by somospocos** [comment]
> you'd need to extend the hardcoded string to also include the %filename%

No worries, take your time. I think I'll just go with a private fork of the module and adapt it to my needs.

But when you'll get to look into it, ideally, there should be no hardcoded string anymore. The module should process mpd.format, parse it, find {} tags corresponding to valid %% tags for mpd, build the command line string for mpc call, retrieve the info and populate mpd.format with those values.

**Comment by tobi-wan-kenobi** [comment]
:+1: sounds good to me.

PR is always highly welcome, of course :)
