### ISSUE TITLE
bluetooth: no interface “org.blueman.Mechanism” on object at path /

### ISSUE THREAD

**Issue by piyueh** [tobi-wan-kenobi/bumblebee-status#483]
#### Summary
Affected module: bluetooth

The right-click method is calling a D-Bus method at the wrong D-Bus object path.

#### Description:
(Disclaimer: I'm not a system programmer, so the language and terms I use may be incorrect ...)

The behavior of a right-click at the bluetooth widget is to toggle the bluetooth. This is done with calling a blueman method through D-Bus by using `dbus-send` command, see line [98-100](https://github.com/tobi-wan-kenobi/bumblebee-status/blob/59ad411b2f04ff9916bc84d3cd207550465f7c03/bumblebee/modules/bluetooth.py#L98-L100). The problem I am having now is that, the `org.blueman.Mechanism` interface is not at path `/` on my system. Instead, it's at `/org/blueman/mechanism`. So I have to modify the code to 

```
        cmd = "dbus-send --system --print-reply --dest=org.blueman.Mechanism"\
              " /org/blueman/mechanism org.blueman.Mechanism.SetRfkillState"\
              " boolean:{}".format(state)
```
to make it work.

Not sure if my case is a special case or not. My system is:
* Archlinux, kernel 5.4.2-arch1-1
* Blueman 2.1.1-2
* Not sure if this matters, but I'm using Sway WM and swaybar + bumblebee-status

#### How to reproduce

1. Include the `bluetooth` module in `bumblebee-status`
2. Right click the bluetooth widget
3. See if the right-click toggled the bluetooth on/off

**Comment by tobi-wan-kenobi** [comment]
That's a weird one.

I've added a parameter `bluetooth.dbus_destination` that allows you to change the dbus path. I hope this fixes your issue!
