### ISSUE TITLE
Support PulseAudio running in system mode

### ISSUE THREAD

**Issue by somospocos** [tobi-wan-kenobi/bumblebee-status#484]
### Feature Request

Currently pulseaudio module only works if PulseAudio runs in session mode. It relies on gathering info (like volume) to display by parsing the output of pacmd:

https://github.com/tobi-wan-kenobi/bumblebee-status/blob/9236b5279ecd2a6a7777c61b4053ab5b031e7ab9/bumblebee/modules/pulseaudio.py#L137

If PulseAudio runs in system mode, pacmd fails:

    $ pacmd
    No PulseAudio daemon running, or not running as session daemon.

and the volume value ends looking like "n/a".

Muting/unmuting and changing volume works, because it relies on pactl.

#### Summary

Support for system mode PulseAudio could probably be achieved by trying to gather volume info from the output of pactl instead, because it seems to contain that. Here are relevant pieces of its output from my system:

    $ pactl list sinks
    ...
    Sink #1
        State: RUNNING
        Name: alsa_output.pci-0000_00_1b.0.analog-stereo
    ...
    	Mute: no
	Volume: front-left: 14107 /  22% / -40.02 dB,   front-right: 14107 /  22% / -40.02 dB
	        balance 0.00
	Base Volume: 65536 / 100% / 0.00 dB

Think of a new module parameter like pulseaudio.systemmode=1.

**Comment by tobi-wan-kenobi** [comment]
Ah, that sounds good. I have to admit when I wrote the module, I wasn't able to figure out how to get the volume via pactl.

**Comment by tobi-wan-kenobi** [comment]
The problem still remaining would be how to figure out the default source/sink.

**Comment by tobi-wan-kenobi** [comment]
This should remove pacmd as dependency. If you still have issues, please let me know!

Thanks for the patience!
