### ISSUE TITLE
pacman module causes bar to freeze

### ISSUE THREAD

**Issue by yashar-sb-sb** [tobi-wan-kenobi/bumblebee-status#49]
`pacman.py` does not do it's update in a separate thread and it freezes the bar.
I'm using Arch. So I can fix and test it.

**Comment by tobi-wan-kenobi** [comment]
I'd appreciate that a lot! If you run into any issues, I can also set up an Arch VM and try to investigate this.

Basically, it *should* be possible to model the pacman module after the dnf module (which uses a separate update thread).

**Comment by tobi-wan-kenobi** [comment]
fixed in https://github.com/tobi-wan-kenobi/bumblebee-status/pull/50
