### ISSUE TITLE
Getting one failed test with Python 3

### ISSUE THREAD

**Issue by somospocos** [tobi-wan-kenobi/bumblebee-status#491]
#### Summary
One test is failing with Python 3.

#### Description:
I am using pyenv to switch between Python 2 / 3 and I run nosetests directly instead of runtests.sh:

    pyenv local 2.7.17
    pyenv version
    2.7.17
    nosetests
    Ran 125 tests in 5.601s
    OK
    pyenv local 3.8.1
    pyenv version
    3.8.1
    nosetests
    FAIL: test_list_modules (tests.test_config.TestConfig)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/user/tmp/bumblebee-status/tests/test_config.py", line 70, in test_list_modules
        self.assertTrue(module["name"] in result)
    AssertionError: False is not true

    ----------------------------------------------------------------------
    Ran 125 tests in 4.068s
    FAILED (failures=1)

#### How to reproduce
see above

**Comment by tobi-wan-kenobi** [comment]
That is strange, thanks for the report! I've added more logging to the test in question, if you could give me the updated output, I'd appreciate that a lot.

Many thanks in advance!

**Comment by somospocos** [comment]
Here is the updated output:

    pyenv version    
    3.8.1
    nosetests        
    ....................................................F........................................................................
    ======================================================================
    FAIL: test_list_modules (tests.test_config.TestConfig)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/shadow/tmp/bumblebee-status/tests/test_config.py", line 70, in test_list_modules
        self.assertTrue(module["name"] in result, "module {} missing in result".format(module["name"]))
    AssertionError: False is not true : module battery-upower missing in result

    ----------------------------------------------------------------------
    Ran 125 tests in 4.102s

    FAILED (failures=1)

**Comment by somospocos** [comment]
Update: I succeeded to get rid of the error.

As I understand, it was happening because I did not have python-dbus installed in the Python 3 environment.

After installing it, I got the same test error for network_traffic module. I've got rid of it by installing netifaces, which was missing.

My guess is that inside all_modules() function of engine.py, pkgutil.iter_modules() doesn't include the modules it fails to import (those modules that have missing external dependencies).

Perhaps it would be good to standartize on the approach used in cpu.py module for example - as in for all modules wrap the imports of third party dependencies in a try/except block? That would fix the import errors when modules are simply enumerated, so this test will always pass, yet will still cause tracebacks when something from those third party modules will be used in either bumblebee code or inside some particular unit test.

**Comment by tobi-wan-kenobi** [comment]
I agree, that would be best.

Since modules are mostly community-contributed, I am, however, hesitant to place additional constraints on what people "have to" do (plus, I am not even sure how I would enforce that, given that importing a module probably cannot even be wrapped into a separate method easily).

For now, I'll add it to the wiki here: https://github.com/tobi-wan-kenobi/bumblebee-status/wiki/How-to-write-a-module

and I will remove the corresponding test, since it actually doesn't really add anything useful to the test suite (and, as you have proven, is wrong).

Thanks!
