### ISSUE TITLE
Add pango support to putput

### ISSUE THREAD

**Issue by tobi-wan-kenobi** [tobi-wan-kenobi/bumblebee-status#493]
### Feature Request
As described in #486 , add support for pango formatted output

**Comment by somospocos** [comment]
I have just did a quick test and it works, thank you.

While this opens new perspectives for module writers, end users can benefit from this too, for example by ricing things like the output of their custom scripts that they run with shell module, or labels in shortcut module, or just the text parameter when using spacer module.

For now this new option (which, as I understand, is global, thus not documented in any module header, so it doesn't appear in the output of bumblebee-status -l modules) is hidden.

I suggest at least adding to the Examples wiki page the trivial example that I used to test:

    bar {
        status_command ~/.i3/bumblebee-status/bumblebee-status -m spacer -p spacer.text="foo<span font_family='Terminus' foreground='#ff0000'>bar</span><span font_family='Gohufont' foreground='#0000ff'>baz</span>" -p output.markup=pango -t gruvbox-powerline
    }

Ideally, it would be nice if the user could somehow learn about this option from the output of bumblebee-status -h. Maybe have something like

    -l {modules,themes,parameters}

and document this global parameter there?

**Comment by tobi-wan-kenobi** [comment]
Very good and valid points. I will move this functionality from a generic config parameter ("-p") to its own parameter (-m | --markup), so that it shows up in the bumblebee-status help. Sorry for breaking compatibility with what you've tested already.

I'll also add a note in the Wiki or the README (not sure yet).
