### ISSUE TITLE
Try catching typos in parameter names

### ISSUE THREAD

**Issue by somospocos** [tobi-wan-kenobi/bumblebee-status#494]
### Feature Request

I've just had one of those PEBKAC moments that are frustrating when they happen and become hilarious once the problem is figured out.

I've decided to try how do module aliases work and had a hard time figuring out why this simple example:

    bumblebee-status -m spacer:txt1 spacer:txt2 -p txt1.text="foo" txt2:text="bar"

only displays "foo" in i3bar.

After trying it a dozen times, then switching to running bumblebee directly from console another dozen times and noticing that the problem persists there too, I ended with a baseless conspiracy theory about an eventual collision in some Python namespace and was about to fill a bug report. When I suddenly had that "aha!" moment and noticed that I made a typo: I named the parameter **txt2:text** instead of **txt2.text** (I even know why: because I copypasted the modules part once more then changed it, and the : part of the alias syntax remained in second item). It went visually unnoticed because vim doesn't do syntax highlighting or linting of bumblebee parameter names inside the bar block of i3 config. bumblebee-status didn't display any error either during runtime.

#### Summary

Run some validation on parameter names and warn the user about possible generic typos like the one described above.

**Comment by JohnDowson** [comment]
That's another thing where #479 and declaring all parameters when initializing a module would come in handy.

**Comment by tobi-wan-kenobi** [comment]
That's a pretty cool idea, thanks!

Similar to #479, I am afraid it might take quite a while until I get around to actually implementing something in that direction (just to let you know what to expect), but I'll definitely keep this ticket open, I like the idea a lot!

**Comment by somospocos** [comment]
I was just thinking about something like "check if parameter name consists of lowercase letters, digits, underscores and dots and warn the user otherwise", that's all. This would've caught my typo.

**Comment by tobi-wan-kenobi** [comment]
Good idea - I gave it some thought and for now implemented something that logs a warning into the log file whenever a parameter is not used at all during a single drawing of the bar.

I think it is a pretty generic approach (i.e. there's no restriction at all on the parameter character set), and it would have caught the issue you had.

If you have any doubts about the solution, please let me know!
