### ISSUE TITLE
Module: apt not working for Debian

### ISSUE THREAD

**Issue by P-Storm** [tobi-wan-kenobi/bumblebee-status#502]
From the wiki:

> **Currently only works for Ubuntu - changes for Debian support are highly appreciated**

I was looking to fix this, is this still a problem? Otherwise I will try to have a go at it.

**Comment by tobi-wan-kenobi** [comment]
I think so, because the apt module uses apt_check.py, and I *believe* that's still not available in Debian.

Having said that, I don't run Debian anymore, so I have no easy way of checking that quickly.

If it's still an issue - PR *highly* welcome!

Thanks!

**Comment by tobi-wan-kenobi** [comment]
I think this should be now fixed, with the merge of PR #514
