### ISSUE TITLE
Including a module multiple times

### ISSUE THREAD

**Issue by KrzysiekJ** [tobi-wan-kenobi/bumblebee-status#503]
Is it possible to make the following work:

```
./bumblebee-status -m shell shell -p shell.command="echo foo" shell.command="echo bar"
```

? Currently “bar” is displayed two times, while the desired behaviour is to display “foo” and then “bar”.

**Comment by somospocos** [comment]
Yes, it is possible by using aliases. Just search for "alias" on the main wiki page https://github.com/tobi-wan-kenobi/bumblebee-status/wiki

This shall work:

    ./bumblebee-status -m shell:shell1 shell:shell2 -p shell1.command="echo foo" shell2.command="echo bar"

**Comment by tobi-wan-kenobi** [comment]
@somospocos is exactly spot-on :)
