### ISSUE TITLE
Towards diversifying output options

### ISSUE THREAD

**Issue by somospocos** [tobi-wan-kenobi/bumblebee-status#505]
I have played a bit with the approach that I described here https://github.com/tobi-wan-kenobi/bumblebee-status/issues/486#issuecomment-568448248 and I've ended with https://github.com/somospocos/pytxtbar

I wonder if you mind merging this into bumblebee/output.py to expose the **hbar()** and **vbar()** functions to module writers.

**Comment by tobi-wan-kenobi** [comment]
Not 100% sure how that would look like in detail, but I am certainly open to a PR.

Looking at the demo script output, I am thinking this might make more sense as a module ("graph.py", "chart.py", something like that) that a module could use to produce output (somewhat similar to how popup.py offers functionality to produce popups?

**Comment by somospocos** [comment]
popup.py seems to be using tkinter - that's a whole third party GUI library in contrast with the pure CLI app that bumblebee-status is, so having that kind of stuff in its own module is perfectly justified.

While my demo is simply something like "visual representation of a number in ascii art". I see hbar() and vbar() just as a complement to scrollable() function from output.py (which is just technically "animated text in ascii art").

Or you just mean having the code separated in its own module and then just exposing hbar() and vbar() as functions in output.py?

Technically, I've just tried to implement something similar to gdbar (https://linux.die.net/man/1/dzen2-gdbar) from dzen2.

**Comment by somospocos** [comment]
No pull request yet, but I've got something to show. This is how I imagine it - see https://github.com/somospocos/bumblebee-status/tree/txtbar.

And a couple of trivial examples in https://github.com/somospocos/bumblebee-status/tree/txtbar-examples - just diff the modules pulseaudio.py / pulseaudio1.py / pulseaudio2.py to see the usage and use them together like this:

    bumblebee-status -m pasink1 pasink2 -t gruvbox-powerline

If it gets green light - I will make a pull request for the txtbar branch.

**Comment by tobi-wan-kenobi** [comment]
Pretty cool, I'm looking forward a lot to having this as a PR!

The only thing: It might be nice to tie the actual characters to be used into the icon sets (themes/icons/), instead of hardcoding them, but that can also be done later.

**Comment by somospocos** [comment]
> It might be nice to tie the actual characters to be used into the icon sets (themes/icons/), instead of hardcoding them

For now I'm not sure how to do this, because in my mental model the files from themes/icons contain visual representations (either ascii ones, or FontAwesome icon chars) for prefix/suffix items. The bar chars I have used are part of any unicode font (please correct me if I'm wrong) and are not related to prefixes/suffixes anyhow. If you have a different perspective due to better knowledge of bumblebee codebase design, please share it.

**Comment by somospocos** [comment]
Requesting permission to add support for drawing graphs using Braille chars to **bumblebee.output**.

To see a demo, pull the latest changes from https://github.com/somospocos/pytxtbar and run pytxtbar.py

Code that draws the graph is in the **BrailleGraph** class and its **bgraph()** function. A showcase of using it (this is how module writers could make use of it) is in the **bgraph_demo()** function. The idea is to have a fixed length list of values (one value per bumblebee-status iteration). Each iteration the oldest value in the list (the first one) is thrown away and the newest value is appended to the list. Chart bars are scaled to the current biggest value in the list.

**Comment by tobi-wan-kenobi** [comment]
Sounds good to me, I'd appreciate having that!

**Comment by tobi-wan-kenobi** [comment]
Hope it is OK for you, if we close that in favour of the more general #531
