### ISSUE TITLE
documentation about module use

### ISSUE THREAD

**Issue by Hkyx** [tobi-wan-kenobi/bumblebee-status#511]
### Feature Request
update the documentation about use of modules.

#### Summary
took the documentation form the wiki but when I use it, got some error 
ex: #status_command ~/.config/bumbs/bumblebee-status -m xrandr nic disk:home bluetooth pasink pasource  battery weather date time dunst disk.left-click="nautilus {instance}" time.format="%H:%M CW %V" date.format="%a, %b %d %Y" home.path=/home -t solarized-powerline

all the time.format .... got a error. 
need to change that into the modules directly to get what I need.

don't think it's a bug but more a user problem from the lack of documentation

**Comment by tobi-wan-kenobi** [comment]
Is it possible you are missing the "-p" flag to indicate parameters? If so, that's documented in "Normal Usage" in the README.md.

If you have any ideas on how to make that more prominent, I am always open to suggestions!
