### ISSUE TITLE
--autohide not working?

### ISSUE THREAD

**Issue by tehgibbo** [tobi-wan-kenobi/bumblebee-status#513]
### Bug Report
My understanding of -a is to list modules that will only be shown during warning or critical.
I set up a default disk module to run as -a, yet unable to get it to show when the disk is on warning status. If I list disk under -m, it certainly shows up and with warning colors, however under -a never shows.
#### Summary
Affected module: disk, perhaps others

#### Description:
$ ./bumblebee-status -d -a disk
{"version": 1, "click_events": true}
[
[],
[],

$ ./bumblebee-status -m disk
{"version": 1, "click_events": true}
[
[{"full_text": " hdd 17.08GiB/20.00GiB (85.39%) ", "color": "#aabbcc", "background": null, "separator_block_width": null, "separator": true, "min_width": null, "align": null, "instance": "6a9a242e-378d-472d-9015-790434cdf39e", "name": "disk", "markup": "none"}],
[{"full_text": " hdd 17.08GiB/20.00GiB (85.39%) ", "color": "#aabbcc", "background": null, "separator_block_width": null, "separator": true, "min_width": null, "align": null, "instance": "6a9a242e-378d-472d-9015-790434cdf39e", "name": "disk", "markup": "none"}],

#### How to reproduce

Fill up root disk over 80%
enable -a disk

**Comment by tobi-wan-kenobi** [comment]
Ah, yes, that is indeed a documentation issue. You have to specify '-a' *in addition* to -m (i.e. only because you have the module in the -a list doesn't actually create a widget - you have to use -m).

In you case, that would be "bumblebee-status -a disk -m disk"

I'll update the documentation
