### ISSUE TITLE
Modify the module writing HOWTO in the wiki to encourage using layouts for multiwidget modules

### ISSUE THREAD

**Issue by somospocos** [tobi-wan-kenobi/bumblebee-status#518]
While hacking on the cmus module earlier, I have accidentally discovered that it already implements something really neat that I was planning to suggest. As a new module writer I would've preferred to read about it in the wiki rather than discover it accidentally in the codebase.

The cmus and mpd modules provide similar functionality - they are music players with different backends. But the cmus module has a superior design - instead of hardcoding the widgets like the mpd module - it uses a layout approach. By adding a single config option it allows the user to cherry pick which widgets he wants displayed and in which order.

This is a great design example that adds a lot of flexibility at the expense of almost zero code overhead. Hereby I suggest adding a note about this to https://github.com/tobi-wan-kenobi/bumblebee-status/wiki/How-to-write-a-module that would encourage module writers to use this approach when writing multiwidget modules. And just link to the cmus module as a good, not-too-complex working example that implements it.

**Comment by somospocos** [comment]
As practicing exercise, I have refactored the mpd module. See pull request #519.

**Comment by tobi-wan-kenobi** [comment]
That is a good point, I will extend the wiki right away. Thanks for raising this!

TBH, when I wrote bumblebee-status (and the documentation), I'd never have thought to get over a hundred forks, let alone 600+ stars., I was guessing for a dozen, maybe :) And in the documentation, I thought that any complex module, I'd write myself. The "how to write a module" was something of an after-thought if somebody wanted to do something very simple.

So, the documentation somehow didn't keep up with the amount of people using bumblebee now...
