### ISSUE TITLE
hanging for for a moment when xrandr is enabled

### ISSUE THREAD

**Issue by zetxx** [tobi-wan-kenobi/bumblebee-status#52]
i3 hangs for a ~100 ms when xrandr module is enabled

**Comment by tobi-wan-kenobi** [comment]
Does that happen during each update cycle or only on specific events (i.e. startup, enabling/disabling an output)?

It would also be great if you could post the output of `xrandr -q`, and whether this also takes a while to finish.

Thanks!

**Comment by zetxx** [comment]
i think it is during update cycle because im doing nothing after login, just 1 opened terminal for watching cursor for hangs.. will paste output tomorrow

**Comment by zetxx** [comment]
```
Screen 0: minimum 320 x 200, current 3840 x 1080, maximum 8192 x 8192
VGA-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 509mm x 286mm
   1920x1080     60.00*+
   1680x1050     59.95  
   1280x1024     75.02    60.02  
   1440x900      74.98    59.89  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    72.81    66.67    59.94  
   720x400       70.08  
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-2 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 509mm x 286mm
   1920x1080     60.00*+
   1680x1050     59.88  
   1280x1024     75.02    60.02  
   1440x900      74.98    59.90  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    72.81    66.67    59.94  
   720x400       70.08  
DP-2 disconnected (normal left inverted right x axis y axis)
```

**Comment by tobi-wan-kenobi** [comment]
Did the `xrandr` command return quickly?

Also, just out of curiosity: How are you checking for the hangs?

**Comment by zetxx** [comment]
> Did the xrandr command return quickly?
yes
> Also, just out of curiosity: How are you checking for the hangs?
im opening terminal and waiting for cursor to freeze, and it gets freeze every second for a short period of time, another way to notice that is to play a movie ....
actually im noticing light lag right after executing xrandr command

**Comment by jeffeb3** [comment]
I just updated to 18.04, and I'm seeing this behavior too. I looked at the xrandr module, and I see that the documentation says that the autoupdate defaults to false, but it's actually defaulting to True. I changed it to False, and I haven't yet tried connecting a monitor, but the periodic pauses have gone away.

The thing I saw was that my scrolling in web browsers was slow, and the cursor would occasionally have a pause, but also keep going. It's some weird artifact of xrandr -q though, and running that causes the same glitch.

So issue 1) The documentation is wrong for the default, and 2) Maybe the default should be to not autoupdate? 3) Is there something else I can look for to fix xrandr -q?

I'm happy to make my own issue if you'd like.

I'm running on an nvidia quadro P3200 and nvidia 390 drivers in ubuntu 18.04.

**Comment by jeffeb3** [comment]
Aaand, it doesn't update on it's own anymore after plugging in a monitor (I'm not sure what I expected). :(

**Comment by tobi-wan-kenobi** [comment]
@jeffeb3 thanks, I fixed the xrandr documentation.

Also, the "doesn't update anymore" can be fixed if you install i3py. Then, it should get notifications when the number of i3 workspaces changes and should update automatically. If not, at least you still got the widget for refreshing :(
