### ISSUE TITLE
Add support for custom icon colors

### ISSUE THREAD

**Issue by somospocos** [tobi-wan-kenobi/bumblebee-status#520]
### Feature Request
As I understand, icon unicode chars in bumblebee-status are either prefix or suffix.

#### Summary
In addition to fg/bg theme settings, add something like prefixfg/prefixbg/suffixfg/suffixbg. This would allow having different colors for icons by using that recently added pango markup support.

**Comment by tobi-wan-kenobi** [comment]
Done.

TBH, I'd have preferred a format like "prefix": { "fg": "", "bg": ""}, but since this clashes with the existing "prefix" theme setting, I am hesitant, because I don't want to break existing themes.

Hope this suits you fine.

Cheers
