### ISSUE TITLE
pacman module is broken, or missing a dependency

### ISSUE THREAD

**Issue by Deep-Six** [tobi-wan-kenobi/bumblebee-status#536]
#### Summary
Affected module: pacman

#### Description:
def get_pacman_info(widget, path):
    try:
        result = bumblebee.util.execute("{}/../../bin/pacman-updates".format(path))
    except:
        pass
Which makes result not available:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/bumblebee-status/bumblebee/modules/pacman.py", line 34, in get_pacman_info
    for line in result.splitlines():
UnboundLocalError: local variable 'result' referenced before assignment

I am certain it is because whatever provides "pacman-updates" is missing, but it doesn't show up in any yay or pacman searches, and googling isn't helpful either.

#### How to reproduce
bumblebee-status -m pacman

**Comment by tobi-wan-kenobi** [comment]
Hi,

sorry you're having problem. For me, the pacman module works fine - how did you install bumblebee?

Maybe there's something wrong with the installer scripts (AUR, for instance)

**Comment by Deep-Six** [comment]
Aur via Yay. Is there a better way?

**Comment by tobi-wan-kenobi** [comment]
No, AUR should be fine - did you use the -git or the regular variant? It looks like I somehow messed up including the helper binary for the pacman module.

Will fix that over the weekend, thanks for reporting!

**Comment by tobi-wan-kenobi** [comment]
Hope that fixes the issue for you!
