### ISSUE TITLE
Background is always black

### ISSUE THREAD

**Issue by TomerRon** [tobi-wan-kenobi/bumblebee-status#537]
#### Description:

I'm trying to set up bumblebee-status, but my background seems to always be black regardless of what theme I choose. I've installed both `Font Awesome` and `powerline-fonts`, so I don't think this is the issue.

Here's what `gruvbox` looks like:

![Screenshot from 2020-01-28 14-38-41](https://user-images.githubusercontent.com/9190141/73268943-2bb34180-41dc-11ea-8401-ba01b16b4022.png)

Here's `powerline`:

![Screenshot from 2020-01-28 14-38-53](https://user-images.githubusercontent.com/9190141/73268963-3372e600-41dc-11ea-8b89-93368f2b8eff.png)

Compare to how they look in the [examples](https://github.com/tobi-wan-kenobi/bumblebee-status#examples).

#### How to reproduce

Ubuntu 16, i3 4.11

```
bar {
        position top
        status_command /home/t/.i3/bumblebee-status/bumblebee-status \
                -m memory battery time pasink pasource \
                -p datetime.format="%x %X" \
                -t powerline
}
```

Thanks in advance!

**Comment by TomerRon** [comment]
If I do e.g.

```
bar {
        colors {
                background #000000
        }
        position top
        status_command /home/t/.i3/bumblebee-status/bumblebee-status \
                -m memory battery time pasink pasource \
                -p datetime.format="%x %X" \
                -t powerline
}
```

the background color of the bar does change to white.

**Comment by somospocos** [comment]
bumblebee-status doesn't draw anything itself, all it does is generate text in JSON format that gets processed by i3bar (which is part of i3 and draws stuff).

First of all, I'm noticing that you use a quite old version of Ubuntu as well as a quite old version of i3. I suggest trying to upgrade i3 first and see if the problem persists.

If you feel like willing to waste a bit more time on debugging, I suggest reducing your example to a simpler one, something like:

    bumblebee-status \
            -m spacer:text1 \
               spacer:text2 \
            -p text1.text="foo" \
               text2.text="bar" \
            -t powerline

This gives me the colors from examples, but I'm running i3-4.17.1

And here is one line generated by bumblebee-status when I run it as I show above from command line:

    [{"full_text": "\ue0b2", "separator": false, "color": "#d75f00", "background": null, "separator_block_width": 0}, {"full_text": " foo ", "color": "#ffd700", "background": "#d75f00", "separator_block_width": 0, "separator": false, "min_width": null, "align": null, "instance": "b65f3c36-2cc8-402f-8593-d18407a67ab4", "name": "text1", "markup": "none"}, {"full_text": "\ue0b2", "separator": false, "color": "#0087af", "background": "#d75f00", "separator_block_width": 0}, {"full_text": " bar ", "color": "#ffffff", "background": "#0087af", "separator_block_width": 0, "separator": false, "min_width": null, "align": null, "instance": "4765c24b-e64c-4bf3-a5e0-1d1ee9fb3c50", "name": "text2", "markup": "none"}],

Try matching this output against your own result.

**Comment by TomerRon** [comment]
Thanks for the quick reply!

Yeah, my Ubuntu is super old, but I'm trying to avoid updating it because I use this computer for work, and I have a feeling that if I try to upgrade and start fresh (which I definitely need and want to do), I'll be out of commission for at least a couple of days to get everything working again (I'm not a Linux master by any means).

I confirm that your example also did not work properly:

![Screenshot from 2020-01-28 15-38-00](https://user-images.githubusercontent.com/9190141/73273390-2d810300-41e4-11ea-8d8f-0afa905abe76.png)


The terminal output is:

```[{"color": "#d75f00", "separator": false, "background": null, "full_text": "\ue0b2", "separator_block_width": 0}, {"min_width": null, "separator": false, "background": "#d75f00", "full_text": " foo ", "instance": "8f0f2b3c-19c4-4f33-9ba9-4a5543e050b8", "color": "#ffd700", "name": "text1", "align": null, "markup": "none", "separator_block_width": 0}, {"color": "#0087af", "separator": false, "background": "#d75f00", "full_text": "\ue0b2", "separator_block_width": 0}, {"min_width": null, "separator": false, "background": "#0087af", "full_text": " bar ", "instance": "44ea814c-55dd-4b97-8f24-2939d722e3fd", "color": "#ffffff", "name": "text2", "align": null, "markup": "none", "separator_block_width": 0}]```

**Comment by tobi-wan-kenobi** [comment]
Hi,

please note that before i3 4.12, colored backgrounds were not supported in i3 itself.

Cheers,

t

⁣Sent from TypeApp ​

**Comment by TomerRon** [comment]
Thanks Tobi, that definitely seems like the issue. I guess I am stuck with my background-less bar for now :)

**Comment by tobi-wan-kenobi** [comment]
@TomerRon sorry to hear that.

FYI: Updating to a newer i3 (or i3-gaps) should be doable in Ubuntu, that'd give you a much more awesome i3 experience :)
