### ISSUE TITLE
Revision fbbfc84031 broke some tests

### ISSUE THREAD

**Issue by somospocos** [tobi-wan-kenobi/bumblebee-status#538]
### Bug Report

It seems like revision fbbfc84031 broke some tests, if I did the git bisection right (never did it before).

#### How to reproduce

    $ git checkout 9fa8b43477 # last working version
    $ nosetests # pass
    $ git checkout fbbfc84031
    $ nosetests # tests in many modules related to Popen() fail
    $ git checkout master # just go back to HEAD

Only tested with Python 3 (3.8.1)

I usually try running tests manually everytime I'm about to touch the code and before git pushing (if I added some new tests too). While bumblebee-status doesn't have 100% test coverage, seeing tests passing makes me feel comfortable. Can we have them fixed please, before any new changes make it into master?

**Comment by tobi-wan-kenobi** [comment]
Yeah, I noticed that, as well. Is at the top of my todo list for the weekend coding :-)
