### ISSUE TITLE
refresh interval

### ISSUE THREAD

**Issue by zetxx** [tobi-wan-kenobi/bumblebee-status#54]
how can we set this arg:
https://github.com/tobi-wan-kenobi/bumblebee-status/blob/master/bumblebee/engine.py#L161
i need lets say, run update every minute not every second ?

**Comment by tobi-wan-kenobi** [comment]
Oh, that's missing in the documentation.... it works like this:

`bumblebee-status -m <modules> -p interval=10`

But right now, that is bugged :-( You need to apply this patch first:

```
diff --git a/bumblebee/engine.py b/bumblebee/engine.py
index 67234fe..0909e6a 100644
--- a/bumblebee/engine.py
+++ b/bumblebee/engine.py
@@ -158,7 +158,7 @@ class Engine(object):
             self._output.flush()
             self._output.end()
             if self.running():
-                self.input.wait(self._config.get("interval", 1))
+                self.input.wait(int(self._config.get("interval", 1)))
 
         self._output.stop()
         self.input.stop()
```

I will fix that on the weekend, sorry for the inconvenience!

**Comment by zetxx** [comment]
no worries :)
