### ISSUE TITLE
-p interval=1 seems to be affected when pasink/pulseaudio is loaded

### ISSUE THREAD

**Issue by jjgarcianorway** [tobi-wan-kenobi/bumblebee-status#543]
Affected module: all them if pasink/pulseaudio is loaded

Description:
-p interval=1 seems to be affected

Is reproducible? 
Yes, just load the bar with:
bumblebee-status -m pasink time -p interval=1 time.format="%H:%M:%S" 

Current status_command in i3:
bumblebee-status -m title spotify cpu sensors memory arch-update pasink date time system -p interval=1 memory.format="{used}" date.format="%a, %b %d %Y" time.format="%H:%M:%S" -t wal-powerline

**Comment by jjgarcianorway** [comment]
As interesting, if I scroll my mouse over any of the modules, it refreshes immediately...

**Comment by tobi-wan-kenobi** [comment]
I'm sorry, but I don't understand the issue yet.

What's (not) happening that should?

The immediate refresh when scrolling is a known problem that unfortunately has no trivial fix :(

**Comment by tobi-wan-kenobi** [comment]
Also, I pushed a fix to the pulseaudio module right now, maybe that fixes your issue as well?

**Comment by jjgarcianorway** [comment]
Hello sir!

When I was testing I was in a x2go session and it was happening more often
but now at home the seconds of the time are not all time one by one,
sometimes they jump like having some lag... so right now, observing, it’s
21:28:12... and before arriving to 21:28:30 it’s not showing 21:28:19 for
example...

It’s nothing serious really :) I’m too picky xd

Have a great evening!

**Comment by tobi-wan-kenobi** [comment]
Ah, that's weird. I don't get that.

My assumption is: The pulseaudio module uses CLI tools (pactl, in particular), can you please check on your system whether the following commands lag sometimes:

pactl info
pactl list sources
pactl list sinks

Maybe there's some weird input/output device that causes a stalling?

**Comment by jjgarcianorway** [comment]
Hello sir,
`Server String: /run/user/1001/pulse/native
Library Protocol Version: 33
Server Protocol Version: 33
Is Local: yes
Client Index: 346
Tile Size: 65472
User Name: lhoqvso
Host Name: ColonialOne
Server Name: pulseaudio
Server Version: 13.0
Default Sample Specification: float32le 2ch 48000Hz
Default Channel Map: front-left,front-right
Default Sink: alsa_output.pci-0000_00_03.0.hdmi-stereo-extra2
Default Source: alsa_output.pci-0000_00_03.0.hdmi-stereo-extra2.monitor
Cookie: 3c1a:6cd8
Source #0
	State: SUSPENDED
	Name: alsa_output.pci-0000_00_03.0.hdmi-stereo-extra2.monitor
	Description: Monitor of Built-in Audio Digital Stereo (HDMI 3)
	Driver: module-alsa-card.c
	Sample Specification: s32le 2ch 48000Hz
	Channel Map: front-left,front-right
	Owner Module: 6
	Mute: no
	Volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
	        balance 0.00
	Base Volume: 65536 / 100% / 0.00 dB
	Monitor of Sink: alsa_output.pci-0000_00_03.0.hdmi-stereo-extra2
	Latency: 0 usec, configured 0 usec
	Flags: DECIBEL_VOLUME LATENCY 
	Properties:
		device.description = "Monitor of Built-in Audio Digital Stereo (HDMI 3)"
		device.class = "monitor"
		alsa.card = "0"
		alsa.card_name = "HDA Intel HDMI"
		alsa.long_card_name = "HDA Intel HDMI at 0xefc34000 irq 53"
		alsa.driver_name = "snd_hda_intel"
		device.bus_path = "pci-0000:00:03.0"
		sysfs.path = "/devices/pci0000:00/0000:00:03.0/sound/card0"
		device.bus = "pci"
		device.vendor.id = "8086"
		device.vendor.name = "Intel Corporation"
		device.product.id = "0c0c"
		device.product.name = "Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller"
		device.form_factor = "internal"
		device.string = "0"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card-pci"
	Formats:
		pcm

Source #1
	State: SUSPENDED
	Name: alsa_output.pci-0000_00_1b.0.iec958-stereo.monitor
	Description: Monitor of Built-in Audio Digital Stereo (IEC958)
	Driver: module-alsa-card.c
	Sample Specification: s32le 2ch 48000Hz
	Channel Map: front-left,front-right
	Owner Module: 7
	Mute: no
	Volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
	        balance 0.00
	Base Volume: 65536 / 100% / 0.00 dB
	Monitor of Sink: alsa_output.pci-0000_00_1b.0.iec958-stereo
	Latency: 0 usec, configured 0 usec
	Flags: DECIBEL_VOLUME LATENCY 
	Properties:
		device.description = "Monitor of Built-in Audio Digital Stereo (IEC958)"
		device.class = "monitor"
		alsa.card = "1"
		alsa.card_name = "HDA Intel PCH"
		alsa.long_card_name = "HDA Intel PCH at 0xefc30000 irq 51"
		alsa.driver_name = "snd_hda_intel"
		device.bus_path = "pci-0000:00:1b.0"
		sysfs.path = "/devices/pci0000:00/0000:00:1b.0/sound/card1"
		device.bus = "pci"
		device.vendor.id = "8086"
		device.vendor.name = "Intel Corporation"
		device.product.id = "8ca0"
		device.product.name = "9 Series Chipset Family HD Audio Controller"
		device.form_factor = "internal"
		device.string = "1"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card-pci"
	Formats:
		pcm
Sink #0
	State: SUSPENDED
	Name: alsa_output.pci-0000_00_03.0.hdmi-stereo-extra2
	Description: Built-in Audio Digital Stereo (HDMI 3)
	Driver: module-alsa-card.c
	Sample Specification: s32le 2ch 48000Hz
	Channel Map: front-left,front-right
	Owner Module: 6
	Mute: no
	Volume: front-left: 15570 /  24% / -37.45 dB,   front-right: 15570 /  24% / -37.45 dB
	        balance 0.00
	Base Volume: 65536 / 100% / 0.00 dB
	Monitor Source: alsa_output.pci-0000_00_03.0.hdmi-stereo-extra2.monitor
	Latency: 0 usec, configured 0 usec
	Flags: HARDWARE DECIBEL_VOLUME LATENCY SET_FORMATS 
	Properties:
		alsa.resolution_bits = "32"
		device.api = "alsa"
		device.class = "sound"
		alsa.class = "generic"
		alsa.subclass = "generic-mix"
		alsa.name = "HDMI 2"
		alsa.id = "HDMI 2"
		alsa.subdevice = "0"
		alsa.subdevice_name = "subdevice #0"
		alsa.device = "8"
		alsa.card = "0"
		alsa.card_name = "HDA Intel HDMI"
		alsa.long_card_name = "HDA Intel HDMI at 0xefc34000 irq 53"
		alsa.driver_name = "snd_hda_intel"
		device.bus_path = "pci-0000:00:03.0"
		sysfs.path = "/devices/pci0000:00/0000:00:03.0/sound/card0"
		device.bus = "pci"
		device.vendor.id = "8086"
		device.vendor.name = "Intel Corporation"
		device.product.id = "0c0c"
		device.product.name = "Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller"
		device.form_factor = "internal"
		device.string = "hdmi:0,2"
		device.buffering.buffer_size = "768000"
		device.buffering.fragment_size = "384000"
		device.access_mode = "mmap+timer"
		device.profile.name = "hdmi-stereo-extra2"
		device.profile.description = "Digital Stereo (HDMI 3)"
		device.description = "Built-in Audio Digital Stereo (HDMI 3)"
		alsa.mixer_name = "Intel Haswell HDMI"
		alsa.components = "HDA:80862807,80860101,00100000"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card-pci"
	Ports:
		hdmi-output-2: HDMI / DisplayPort 3 (priority: 5700, available)
	Active Port: hdmi-output-2
	Formats:
		ac3-iec61937, format.rate = "[ 32000, 44100, 48000 ]"
		eac3-iec61937, format.rate = "[ 32000, 44100, 48000 ]"
		mpeg-iec61937, format.rate = "[ 32000, 44100, 48000 ]"
		dts-iec61937, format.rate = "[ 32000, 44100, 48000 ]"
		mpeg2-aac-iec61937, format.rate = "[ 32000, 44100, 48000 ]"
		pcm

Sink #1
	State: SUSPENDED
	Name: alsa_output.pci-0000_00_1b.0.iec958-stereo
	Description: Built-in Audio Digital Stereo (IEC958)
	Driver: module-alsa-card.c
	Sample Specification: s32le 2ch 48000Hz
	Channel Map: front-left,front-right
	Owner Module: 7
	Mute: no
	Volume: front-left: 64526 /  98% / -0.40 dB,   front-right: 64526 /  98% / -0.40 dB
	        balance 0.00
	Base Volume: 65536 / 100% / 0.00 dB
	Monitor Source: alsa_output.pci-0000_00_1b.0.iec958-stereo.monitor
	Latency: 0 usec, configured 0 usec
	Flags: HARDWARE HW_MUTE_CTRL DECIBEL_VOLUME LATENCY SET_FORMATS 
	Properties:
		alsa.resolution_bits = "32"
		device.api = "alsa"
		device.class = "sound"
		alsa.class = "generic"
		alsa.subclass = "generic-mix"
		alsa.name = "ALC1150 Digital"
		alsa.id = "ALC1150 Digital"
		alsa.subdevice = "0"
		alsa.subdevice_name = "subdevice #0"
		alsa.device = "1"
		alsa.card = "1"
		alsa.card_name = "HDA Intel PCH"
		alsa.long_card_name = "HDA Intel PCH at 0xefc30000 irq 51"
		alsa.driver_name = "snd_hda_intel"
		device.bus_path = "pci-0000:00:1b.0"
		sysfs.path = "/devices/pci0000:00/0000:00:1b.0/sound/card1"
		device.bus = "pci"
		device.vendor.id = "8086"
		device.vendor.name = "Intel Corporation"
		device.product.id = "8ca0"
		device.product.name = "9 Series Chipset Family HD Audio Controller"
		device.form_factor = "internal"
		device.string = "iec958:1"
		device.buffering.buffer_size = "768000"
		device.buffering.fragment_size = "384000"
		device.access_mode = "mmap+timer"
		device.profile.name = "iec958-stereo"
		device.profile.description = "Digital Stereo (IEC958)"
		device.description = "Built-in Audio Digital Stereo (IEC958)"
		alsa.mixer_name = "Realtek ALC1150"
		alsa.components = "HDA:10ec0900,18491151,00100001"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card-pci"
	Ports:
		iec958-stereo-output: Digital Output (S/PDIF) (priority: 0)
	Active Port: iec958-stereo-output
	Formats:
		ac3-iec61937, format.rate = "[ 32000, 44100, 48000, 88200, 96000, 192000 ]"
		mpeg-iec61937, format.rate = "[ 32000, 44100, 48000, 88200, 96000, 192000 ]"
		dts-iec61937, format.rate = "[ 32000, 44100, 48000, 88200, 96000, 192000 ]"
		pcm
`

I'm pretty newbie with these things so I do not know really how to help you... but here it's the output of all three commands.

**Comment by tobi-wan-kenobi** [comment]
Ah, I see.

That all looks OK, so unfortunately, I am not sure why pulseaudio would stall your output.

When it happens the next time, could you please enter "dmesg" on the commandline and see whether any of the logs indicate an issue with any of your audio devices?

Thanks a log in advance!

**Comment by jjgarcianorway** [comment]
Sure sir :) it works pretty well it’s just that I’m provably too picky xd

I will see if I can find what it is.

On the meanwhile, I discovered something else about title module but I
believe I should create a new issue... (again nothing very serious but
annoying for OCD people ;))

Thanks a lot!

Best regards,

**Comment by tobi-wan-kenobi** [comment]
Yes, a separate ticket for the title module would be much appreciated - thanks!

**Comment by jjgarcianorway** [comment]
Hello,

I have done a bit of testing here but I cannot find anything... dmesg and journalctl do not report anything at all so I do not know what is causing it. Maybe is just something about my computer. I believe you can close it if no one else is having that issue.

**Comment by tobi-wan-kenobi** [comment]
Will close - and sorry that I was not able to help more, but without reproducing the issue, there's not really a lot I can do.

**Comment by jjgarcianorway** [comment]
It’s ok, I can understand it :)

Maybe it was only on my computer or one day someone else will have
something similar... don’t know.

In any case... thanks for trying!
