### ISSUE TITLE
add dnf module explanation to wiki

### ISSUE THREAD

**Issue by lockejan** [tobi-wan-kenobi/bumblebee-status#546]
### Feature Request

It's already as comment in the code but I would suggest to add this sort of explanation to the wiki to help people right from the beginning to understand the meaning of the numbers:
`(<security>/<bugfixes>/<enhancements>/<other>)`

**Comment by tobi-wan-kenobi** [comment]
Hi,

do you have any proposal? I'm not sure how to more concisely describe that they show the number of security updates, bugfixes, enhancement updates pending in DNF.

I think that maybe I am misunderstanding your point :(

**Comment by lockejan** [comment]
Hi,
sorry for the rough explanation. I just wanted to address that it might be helpful for inexperienced and new users to have this sort of explanation in the wiki like [here](https://github.com/tobi-wan-kenobi/bumblebee-status/blob/master/Modules.md) and [here](https://github.com/tobi-wan-kenobi/bumblebee-status/wiki/Available-Modules)

Actually I didn't get the meaning till I looked in the source code and spotted that comment.
So just adding `(<security>/<bugfixes>/<enhancements>/<other>)` to the wiki's might be helpful.

**Comment by tobi-wan-kenobi** [comment]
Got it, now I see why I was confused: 

The information is in the "main" wiki entry, and should be in the Modules.md as well, it's just for lack of escaping :P (ie. <security> is treated as HTML tag)... Will fix.
