### ISSUE TITLE
Scrollable spotify is left aligned

### ISSUE THREAD

**Issue by fintara** [tobi-wan-kenobi/bumblebee-status#550]
#### Summary
Affected module: spotify

#### Description:
Thanks to #451 longer text is now scrolled, however if the title is shorter than the maximum allowed, it looks as if it floats in the middle of nothing. I can see the logic behind, but it does look weird I think, to me at least.

Possible solutions:
1. make text (and icon) right-aligned (or make it configurable) - this in essence was the behavior before
1. make scrollability configurable (enabled/disabled)

I think 1st option would be best.

#### How to reproduce
![Screenshot_2020-02-12_20-40-34](https://user-images.githubusercontent.com/4290594/74370835-15aaa100-4dd8-11ea-9121-c5425b5602d2.png)

**Comment by tobi-wan-kenobi** [comment]
The right-alignment would unfortunately break as soon as you have widgets on the left side of the spotify module, no?

Making it configurable is a good idea, I will look into it.

**Comment by fintara** [comment]
Yes, then probably there will be empty space on the left. Perhaps making the width of the field as min(str.len, VALUE), where VALUE is the max allowed, though I don't know how feasible this is.

**Comment by tobi-wan-kenobi** [comment]
Yeah, I was thinking about that, but that makes the bar realign every time a new song starts, which is also not really nice :(

**Comment by fintara** [comment]
Yeah, it can be annoying if it's in the middle of other modules. I don't know if it's the same thing, but for example the `traffic` module would sometimes change its width, which doesn't bother me personally (maybe because it's changing only slightly).
Maybe making it optional (e.g. autoresize: true/false), in addition to max-width option.

**Comment by tobi-wan-kenobi** [comment]
Hope the alignment fixes your issue :)

**Comment by fintara** [comment]
Thank you for that! However I can't try it out yet. Installing the git version from aur results in this error upon launching Spotify. Tried to run bumblebee-status in debug mode, but there is nothing connected with it in the log.

![Screenshot_2020-02-19_22-15-19](https://user-images.githubusercontent.com/4290594/74878022-c67be780-5366-11ea-8831-00623e5e3166.png)

**Comment by tobi-wan-kenobi** [comment]
:-/ Which theme are you using?

**Comment by fintara** [comment]
I tried with: `powerline`, `gruvbox`, `iceberg-dark-powerline`, `solarized` and `default` -- all result in the same error.

**Comment by ljupchokotev** [comment]
I have the same issue with the Spotify module. It only happens if the song name is short.

This works:
```
bumblebee-status -m spotify  -t gruvbox-powerline

{"version": 1, "click_events": true}
[
[{"full_text": "\ue0b2", "separator": false, "color": "#1d2021", "background": null, "separator_block_width": 0}, {"full_text": "  \uf1bc  SiR - That's Why I Love You (f ", "color": "#ebdbb2", "background": "#1d2021", "separator_block_width": 0, "separator": false, "min_width": null, "align": null, "instance": "6b0ceafe-757b-4d78-83ad-e55a2f7b576a", "name": "spotify", "markup": "none"}],
```

This fails, I'm assuming because of `alignment: left`:
```
bumblebee-status -m spotify  -t gruvbox-powerline

{"version": 1, "click_events": true}
[
alignment: left
[{"full_text": "\ue0b2", "separator": false, "color": "#1d2021", "background": null, "separator_block_width": 0}, {"full_text": "  \uf1bc  SiR - LA                       ", "color": "#ebdbb2", "background": "#1d2021", "separator_block_width": 0, "separator": false, "min_width": null, "align": null, "instance": "a2bec3df-80a2-498c-85ef-c10901622f4e", "name": "spotify", "markup": "none"}],
```

**Comment by ljupchokotev** [comment]
I just tested and this can be fixed by removing the print statement: https://github.com/tobi-wan-kenobi/bumblebee-status/commit/5134ce3b5b5e9a3ad0c5d7dbacbe870217615021#diff-b42fcd5b9415549b5140b1761bd20e47R77
