### ISSUE TITLE
Wiki/README documentation for hddtemp module needs fixes

### ISSUE THREAD

**Issue by somospocos** [tobi-wan-kenobi/bumblebee-status#551]
#### Summary
Affected module: hddtemp

#### Description:

hddtemp is listed here https://github.com/tobi-wan-kenobi/bumblebee-status/wiki/Available-Modules as required Python module. It should be listed as required commandline executable instead. Currently this is slightly misleading, because there are hddtemp related modules (like https://pypi.org/project/hddtempnc/) and one of them is actually named hddtemp (https://pypi.org/project/hddtemp/). Just like the description on the modules page says, the bumblebee-status fetches data directly without any middleman third party module.

This dependency info is also missing from the "Required commandline utilities" section of the README.

**Comment by tobi-wan-kenobi** [comment]
thanks for noticing!
