### ISSUE TITLE
Announce: some additional docs

### ISSUE THREAD

**Issue by somospocos** [tobi-wan-kenobi/bumblebee-status#554]
Shameless plug: I wrote down some of my bumblebee-status adventures in a (hopefully!) newbie-friendly way. They cover the usage of bleeding edge features like **--iconmarkup** that didn't make it yet into the official wiki.

You can see the repository here https://github.com/somospocos/bumblebee-status-contrib

Feel free to link to it, I'll be glad if it will be useful to other new bumblebee-status users.

**Comment by tobi-wan-kenobi** [comment]
Very, very nice, thanks a lot!

Also thanks for the kind words in the introduction :)
