### ISSUE TITLE
Question: how to add stateless data to a theme?

### ISSUE THREAD

**Issue by somospocos** [tobi-wan-kenobi/bumblebee-status#556]
Affected module: cpu2

Now that a Nord theme was bundled, I am willing to improve the cpu2 module a bit. Back when I implemented it - I "cheated": I got confused by these states things and just hardcoded the colors for the cpu load bars. See here

https://github.com/tobi-wan-kenobi/bumblebee-status/blob/5134ce3b5b5e9a3ad0c5d7dbacbe870217615021/bumblebee/modules/cpu2.py#L95

But Nord theme has its own colors. They are here: https://www.nordtheme.com/ (search for Aurora).

I would like to be able to query the theme from that method and if it has some (stateless, not tied to a particular module state!) things like let's say "loadcolor1", "loadcolor2", "loadcolor3", "loadcolor4" - use them. If not - just use the default  green, yellow, orange and red colors.

Problem is, I still have no idea how to do it, because so far I didn't find any example to "steal" from. Existing themes operate with states (states of the entire module!) and define some custom colors there. cpu2.Module.add_color() only computes the state of a piece of a widget.

Does the current design from the master branch allow to do it?

**Comment by tobi-wan-kenobi** [comment]
Interesting idea!

Off the cuff, I can think of 2 ways: Either extend the Theme class to allow generic access to attributes (theme.get("cpu2").get("color1"), or maybe theme.get("cpu2.color1")) or to allow something like "palettes" or something like that, and you can retrieve those (theme.palette() would return a dict of - i don't know - 6-7 colors with predefined names red, yellow, blue, etc. similar to how solarized defines their palette.

Or maybe allow "extended attributes" that can be retrieved in the Theme class 

All doable - relatively easy. I tend to favour the palette approach, it seems cleanest and most reusable to me.

What are your thoughts?

**Comment by somospocos** [comment]
I am fine with whichever approach is faster for you to implement. The palette approach is ok, as long as it will take care of two things:

1. If the theme is missing a palette item, the getter (for the whole palette) must let the module writer accessing it specify a whole default dict.

2. If there is a palette dict, but it lacks a certain required key (color), again the getter (for that color) must let the module writer specify a default value.

You can easily notice this is the pattern that config objects follow, so you might need to make Theme a subclass of Store and also have a Palette class that will subclass Store as well.

The API exposed to the modules would probably be something like

    Theme.palette()
    Theme.color(name)

**Comment by tobi-wan-kenobi** [comment]
Funny, seems the colorset support is already (partially) there, with the WAL support I added ages ago.

I've extended that so that you can specify either a file (which will be loaded, WAL format only, for now), or directly specify a dict, which will be merged into the colorset.

As an example, I've added partial support of named colors to gruvbox-powerline.json, hope this is sufficient docu for you, for now?

Also, I've added an accessor "theme.color(<color name>, <optional default value, defaults to None>)"
