### ISSUE TITLE
pasink module broken when left and right volume values are different and -p pasink.showbars=1

### ISSUE THREAD

**Issue by somospocos** [tobi-wan-kenobi/bumblebee-status#557]
#### Summary
Affected module: pulseaudio

#### Description:
I see it in 0751b7c, it was introduced by me, so I'll spend some time right now trying to fix it.

#### How to reproduce

Modify left or right sound volume so values are different, then  run bumblebee like this:

    bumblebee-status \          
        -m pasink \                                                         
        -p pasink.showbars=1                    

Reference traceback:

    File "bumblebee-status/bumblebee/modules/pulseaudio.py", line 147, in volume
    vol,
    UnboundLocalError: local variable 'vol' referenced before assignment

**Comment by tobi-wan-kenobi** [comment]
fixed in #558
