### ISSUE TITLE
BatteryAll not working properly

### ISSUE THREAD

**Issue by martindoublem** [tobi-wan-kenobi/bumblebee-status#572]
#### Summary
Affected module: battery_all

#### Description:
Exception occured: '<' not supported between instances of: 'NoneType' and int in bumblee.modules.battery_all.

#### How to reproduce
Run the lastest battery_all on the latest arch version.

I will be taking a look at this later today (hopefully!)

**Comment by tobi-wan-kenobi** [comment]
Thanks for the report, should be fixed, hopefully!
