### ISSUE TITLE
Spotify buttons

### ISSUE THREAD

**Issue by richibrics** [tobi-wan-kenobi/bumblebee-status#577]
### Feature Request
Hi, I wonder if it is possible to add play/pause, next and previous buttons to the spotify module.

**Comment by martindoublem** [comment]
Already implemented, did you try left click, right click, middle click on it?

**Comment by richibrics** [comment]
Yes, and they work perfectly, but I was thinking about implementing buttons that you can see in this bar: ![image](https://github.com/tobi-wan-kenobi/bumblebee-status/blob/master/screenshots/themes/iceberg-dark-powerline.png)

**Comment by martindoublem** [comment]
Ha, I see. If I am not wrong that is another player but I am not sure which.

perhaps a parameters could be added to make these extras buttons visible as I quite like it without it (I have so many modules running, it is taking almost my entire screen width.)

Maybe you can look into it, if you have the knowledge in Python?

**Comment by martindoublem** [comment]
I just took a look at the module and it looks like a whole new module would be needed so probably not easily doable.

**Comment by richibrics** [comment]
Thanks anyway

**Comment by martindoublem** [comment]
You can leave your request open, it is something, I could do eventually, but I won't lie as it is not something I need, it may wait a bit before I get to it.

**Comment by tobi-wan-kenobi** [comment]
I like the idea a lot! However, since I am not using spotify myself, I'll have to wait for a PR from somebody else, which I will be happy to review and merge :)

**Comment by richibrics** [comment]
> Ha, I see. If I am not wrong that is another player but I am not sure which.
> 
> 
> 
> perhaps a parameters could be added to make these extras buttons visible as I quite like it without it (I have so many modules running, it is taking almost my entire screen width.)
> 
> 
> 
> Maybe you can look into it, if you have the knowledge in Python?

Maybe I will take a look at it

**Comment by martindoublem** [comment]
@tobi-wan-kenobi do you know which module has those buttons?

**Comment by tobi-wan-kenobi** [comment]
@martindoublem cmus has them for sure, and mpd as well, I think. mpd even has a fancy "layout" parameter that allows to specify which widgets to show.

**Comment by somospocos** [comment]
Both cmus and mpd modules have a layout parameter. IIRC cmus had that feature originally, and I liked it a lot, so I refactored the mpd module to add that as well, because being able to show a subset of widgets is a great way to save space in the bar + being able to specify their order makes the visual look of the module more customizable. Unfortunately I don't use spotify at all, so I can't help with this :(

**Comment by martindoublem** [comment]
I have regained some interest in this this week as I would like the buttons only with no text now and therefore might be implementing the feature in spotify

**Comment by tobi-wan-kenobi** [comment]
That would be awesome!

**Comment by martindoublem** [comment]
Sorry for dropping the ball on this. I moved away from i3 and back to gnome for user-friendliness reasons. I would like to move back to i3 but might be a little while till I have a setup for this purpose.

**Comment by tobi-wan-kenobi** [comment]
No worries @martindoublem , I get the usability "challenges" :)

I mean, that's what community and open source is for, if there's sufficient interest, maybe somebody else will start on this.

Have fun!

**Comment by somospocos** [comment]
Just FYI, if you need to do something related to bumblebee-status, you don't need to run a full, "real" i3 setup. You can just launch i3 using Xephyr

**Comment by tobi-wan-kenobi** [comment]
fixed by #663
