### ISSUE TITLE
New module parameters

### ISSUE THREAD

**Issue by richibrics** [tobi-wan-kenobi/bumblebee-status#579]
### Module parameters
Hi, I'm creating a module to manage Apple devices, and write iDevices battery status on the bar.
I need a tip: Apple email and password configuration should be put in the bar parameters (-p) or in an external file to  avoid showing password in the config ?
Thanks

**Comment by martindoublem** [comment]
I would avoid storing passwords in config files wether I3 or the module. You could easily call an appropriate cli like pass or a cli to a keyring to do so using subrpocesses.

**Comment by tobi-wan-kenobi** [comment]
I agree with @martindoublem .

Having said that, if you want to do something "light-weight", what I have seen other binaries do is provide a parameter "password-file" or similar that points to a file that *contains* the password.

Then, if you are restrictive enough on the file permissions (400, essentially), you *should* be safe in a lot of situations.

**Comment by somospocos** [comment]
The Github module accepts a token as parameter for example.
