### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by elshize** [tobi-wan-kenobi/bumblebee-status#58]
Hi, is there a way to access error logs once executed in i3bar? I'm having problems with xrandr module, whenever I click on it, nothing happens and no click events work anymore on any modules. I'd like to debug that but I'm having problems figuring out how to do it. I'd appreciate some pointers.

Best
—Michal Siedlaczek

**Comment by tobi-wan-kenobi** [comment]
Hi,

unfortunately, right now, the only way is to start bumblebee-status on the commandline (e.g. `bumblebee-status -m xrandr`) and "simulate" the i3 event (using https://i3wm.org/docs/i3bar-protocol.html).

For example, starting the tool and then writing `{ "name": "<display name>", "instance": "<instance ID from regular output>", "button": 1 }` and pressing enter should simulate a left-click on the widget.

I will keep this issue open, anyhow, and work on a way to debug (optional debug file, maybe a debug widget?) as soon as I have time.

In case you encounter further issues, the following information would help me troubleshoot the problem:
* output of `xrandr -q`
* output of `bumblebee-status -m xrandr` for a few seconds (just to see names, IDs, etc.)

Thanks!

**Comment by elshize** [comment]
Thanks for the response! This actually seems like a quite reasonable way to debug it.
I'll look into this when I get the chance. I'll let you know if I find something interesting.

And here's the outputs you asked for:

```
$ xrandr -q
Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 32767 x 32767
eDP1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 310mm x 170mm
   1920x1080_60.00  59.96*+
   1920x1080     60.02 +  59.96  
   1400x1050     59.98  
   1600x900      60.00  
   1280x1024     60.02  
   1280x960      60.00  
   1368x768      60.00  
   1280x720      60.00  
   1024x768      60.00  
   1024x576      60.00  
   960x540       60.00  
   800x600       60.32    56.25  
   864x486       60.00  
   640x480       59.94  
   720x405       60.00  
   640x360       60.00  
DP1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 510mm x 290mm
   1920x1080_60.00  59.96*+
   1920x1080     60.00 +
   1680x1050     59.95  
   1280x1024     60.02  
   1440x900      59.89  
   1280x720      60.00  
   1024x768      60.00  
   800x600       60.32  
   640x480       59.94  
   720x400       70.08  
HDMI1 disconnected (normal left inverted right x axis y axis)
HDMI2 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
```
```
$ bumblebee-status -m xrandr
{"version": 1, "click_events": true}[
[{"full_text": "  off  eDP1 ", "color": "#aabbcc", "background": null, "separator_block_width": null, "separator": true, "instance": "dc44e4ea-faab-478c-bb8f-5bda41d434bc", "name": "xrandr"}, {"full_text": "  off  DP1 ", "color": "#aabbcc", "background": null, "separator_block_width": null, "separator": true, "instance": "1e9639d6-c6f4-4757-90c7-41575ea11320", "name": "xrandr"}],
[{"full_text": "  off  eDP1 ", "color": "#aabbcc", "background": null, "separator_block_width": null, "separator": true, "instance": "dc44e4ea-faab-478c-bb8f-5bda41d434bc", "name": "xrandr"}, {"full_text": "  off  DP1 ", "color": "#aabbcc", "background": null, "separator_block_width": null, "separator": true, "instance": "1e9639d6-c6f4-4757-90c7-41575ea11320", "name": "xrandr"}]
```
It doesn't change after that.

**Comment by elshize** [comment]
There actually seems to be a bigger problem because for some reason, the entire status fails if one of my outputs is available but not `on`.

I'm not saying I know I'll be able to do that, but would you be open to receiving a patch from me with a fix? Or any other if I had some time to work on something in the future?

**Comment by tobi-wan-kenobi** [comment]
Absolutely, patches and pull requests are **always** welcome! :-)

Could you maybe paste the error that happens when you execute bumblebee-status with one output off? It's probably an exception related to the way I'm parsing the xrandr output.

**Comment by tobi-wan-kenobi** [comment]
Could you please do a `git pull` and retry? Maybe the problem reported in #59 also caused your issues...

**Comment by elshize** [comment]
Hi, just did it, all of my problems ceased to exist.

Thanks for the help. I'm loving the status bar so far! I'll keep an eye on any bugs or potential enhancements.

**Comment by tobi-wan-kenobi** [comment]
Glad to hear that, thanks! (And thanks to @llomellamomario , who actually found the issue).

BTW, on a completely unrelated note: Since you are using the xrandr module, you might be interested in https://github.com/tobi-wan-kenobi/bumblebee-status/wiki/xrandr, an undocumented feature I've just got around to documenting :smile:

**Comment by elshize** [comment]
Wow, that hidden magic looks interesting. I'll definitely check it out ;)
