### ISSUE TITLE
apt module error: no module named "parse"

### ISSUE THREAD

**Issue by ProspectPyxis** [tobi-wan-kenobi/bumblebee-status#584]
#### Summary
Affected module: apt

#### Description:
Upon trying to use the apt module, the bar exits out with the error `status_command process exited unexpectedly (exit 1)`. Running bumblebee-status with only the apt module active results in this error:
```failed to import apt: No module named 'parse'
Traceback (most recent call last):
  File "/home/pyxis/.local/bin/bumblebee-status", line 80, in <module>
    main()
  File "/home/pyxis/.local/bin/bumblebee-status", line 51, in main
    theme=theme,
  File "/home/pyxis/.local/lib/python3.6/site-packages/bumblebee/engine.py", line 152, in __init__
    self.load_modules(config.modules())
  File "/home/pyxis/.local/lib/python3.6/site-packages/bumblebee/engine.py", line 221, in load_modules
    mod = self._load_module(module["module"], module["name"])
  File "/home/pyxis/.local/lib/python3.6/site-packages/bumblebee/engine.py", line 264, in _load_module
    raise bumblebee.error.ModuleLoadError("unable to load module {}: {}".format(module_name, str(err)))
bumblebee.error.ModuleLoadError: unable to load module apt: No module named 'parse'
```
I have already installed python-parse and aptitude, so I'm not sure if I'm still missing something here.

As a side note, the listing for apt in the available modules page on the wiki seems to be outdated, since it still says it requires `update-notifier-common` and only works on Ubuntu, even though #514 seems to have fixed this.

#### How to reproduce
1. Run the command `bumblebee-status -m apt`
2. bumblebee-status should throw an error

**Comment by ProspectPyxis** [comment]
Okay, so not too long after making this issue, I've found the problem: it requires `python3-parse`, not just `python-parse`. I'm going to close this issue, though the documentation should likely still be updated.

**Comment by tobi-wan-kenobi** [comment]
I agree that this is confusing, but for the current version of bumblebee-status, it's unfortunately hard to document:

bumblebee-status supports both Python 2.x and Python 3.x, and depending of which one you want to use, you need to use python-parse or python3-parse (and the details of how the packages are called also differ slightly from distribution to distribution).

I'd *love* to have documentation on how to install bumblebee-status for all kinds of OSes, but sadly, I don't have enough time to provide it.

Sorry that this caused you to lose time, but I'm glad you found a solution!
