### ISSUE TITLE
VPN popup not displayed under ubuntu 19.10

### ISSUE THREAD

**Issue by albinscode** [tobi-wan-kenobi/bumblebee-status#588]
#### Summary
Affected module: vpn

#### Description:
I've got the "off" label displayed but when I click with mouse, I don't have the popup.

#### How to reproduce

Try to click on the "off" label.

#### Resolution

By debugging bumblebee (with -d directive), I've found in the log that tkimport could'nt be imported by python (I'm using python 2.7).

I've solved the problem by installing the library like this `sudo apt install python-tk`.

If it could be specified on the module that is working great, it would be good for others not to troubleshoot this.

Thank you for this wonderful bar!

**Comment by tobi-wan-kenobi** [comment]
I'll update the documentation, thanks for raising this!
