### ISSUE TITLE
Calendar not displayed according to configuration

### ISSUE THREAD

**Issue by albinscode** [tobi-wan-kenobi/bumblebee-status#589]
### Bug Report

Hello !

#### Summary
Affected module: datetime

#### Description:
When clicking on the date (left button), no calendar is dislayed.

#### How to reproduce

Click on the datetime.

#### Resolution

By default, it is using "calendar" command which is a terminal command.

The proposed parameter `-p date.left-click="gsimplecal"` is not taken into account by the datetime.py so I hardcoded it with "gsimplecal". 
It shall take this parameter into account it would be easier to use (or I misunderstood the way to provide parameters?).

Thanks by advance.

**Comment by tobi-wan-kenobi** [comment]
That depends, if you loaded the module as `-m date`, then `-p date.left-click="gsimplecal"` should work.

If you used `-m datetime`, then you need to provide `-p datetime.left-click="gsimplecal"`

For me, specifying the parameter works. Can you show the full invokation, please?

**Comment by albinscode** [comment]
Yes @tobi-wan-kenobi, I just understood how the special parameter left-click was working by using another module... By specifying `-p datetime.left-click="gsimplecal"` this is working like a charm.

Sorry to have bothered you with my newbie question! (I've used a module that can have several names ;)).

Thanks a lot !

**Comment by tobi-wan-kenobi** [comment]
No worries at all! With bumblebee, I always think: If it doesn't work for the user, that's *always* a bug, even if it is "just" a usability bug :)
