### ISSUE TITLE
[modules/xrandr] Switching off a display crashes the module, and bumblebee-status

### ISSUE THREAD

**Issue by llomellamomario** [tobi-wan-kenobi/bumblebee-status#59]
It is a dual monitor setup. Running it on a console shows where the problem lies. The bug seems to be related to be using python 3, since sys.maxint (line 40) is not available on python 3. Switching it to sys.maxsize seems to be the fix if I'm understanding python documentation properly (and switching it locally seems to fix the issue).

**Comment by tobi-wan-kenobi** [comment]
thanks for reporting this!
