### ISSUE TITLE
[development] shell module text placement

### ISSUE THREAD

**Issue by tehgibbo** [tobi-wan-kenobi/bumblebee-status#592]
#### Summary
Affected module: shell

#### Description:
As shown below, shell output text isn't centered vertically/horizontally in the bar. 
I did test with some other variables with the same result however it could be user error on my part, I had to export the command from bumblebee.conf into i3 config. I never had an issue with the command in bumblebee.conf yet in i3 config couldn't get the sh style to work so I put it into a bash script to be executed after -p in i3 conf. 

![battery-module-bug](https://user-images.githubusercontent.com/37912362/78527751-f80e1c80-7807-11ea-9438-1f9dbe08cfa6.png)
![shell-text](https://user-images.githubusercontent.com/37912362/78527753-f93f4980-7807-11ea-8ffb-47766ec603f1.png)

**Comment by tehgibbo** [comment]
Nevermind about the battery error, I was also going to submit that however seems the latest pull solves that issue which happened while charging and battery <100%

**Comment by tobi-wan-kenobi** [comment]
:+1: 

Thanks for the report, the shell module was missing some trimming on the result, should be fixed now.

**Comment by tehgibbo** [comment]
> Thanks for the report, the shell module was missing some trimming on the result, should be fixed now.

Fixing issues quicker than corona is spreading ;) well done, pulled the commit and confirm fixed.
Thanks so much :D
