### ISSUE TITLE
Vault always copies the same password

### ISSUE THREAD

**Issue by TheEdgeOfRage** [tobi-wan-kenobi/bumblebee-status#593]
#### Summary
Affected module: vault

#### Description:
The popup opens as expected, but clicking on any password always copies the one for Wikipedia in my case. The password menu is longer than can fit on my screen, ~so it might be something to do with that~(see comment), as the Wikipedia list item can't be seen on the list. It appears to be at the cut off end of the list.

![Screenshot](https://pyazo.theedgeofrage.com/0uIGzEB2KZuoL5kDoLEmwv0BRu4mzQKu.png)

I pixelized the password names, they render normally for me.

#### How to reproduce
~Have a really long password list (have fun populating that :D) and use the `vault` module. I might be completely wrong on the issue, it's just the only thing that came to mind.~(see comment)

#### Proposal
I'm not sure if tk supports it, but a multi-column menu might fix the issue. I'll look into the code, but I haven't used tk until now.

**Comment by TheEdgeOfRage** [comment]
Okay, so I looked more into it, it doesn't look like my initial suspicion was right. I restructured the menu to have a tree structure separated by the first letter of each password name so that it would fit on my screen, but it still always copies the Wikipedia password.

![Screenshot](https://pyazo.theedgeofrage.com/mHT6ygGwaH4REvI1opeLUDsuL2h37Qe6.png)

```python
with os.scandir(current_directory) as it:
    entries = [entry for entry in it if not entry.name.startswith(".")]

letters = sorted({entry.name[0] for entry in entries})
submenus = {}
for letter in letters:
    submenus[letter] = bumblebee.popup_v2.PopupMenu(parent, leave=False)
    parent.add_cascade(letter, submenus[letter])

for entry in entries:
    name = entry.name[:entry.name.rfind(".")]
    logging.warning(os.path.join(current_directory, name))
    submenus[name[0]].add_menuitem(
        name,
        callback=lambda: callback(os.path.join(current_directory, name))
    )

```

This is the code that handles the menu creation. The logging call prints all the passwords just as they are supposed to be, and the lambda expressions seem to be mapped correctly. But when the callback actually gets called, it always prints just Wikipedia. I'm starting to think it's either a bug in Tkinter or a reference to something that gets overwritten every time a new menu entry is added.

**Comment by tobi-wan-kenobi** [comment]
Hm, this sounds weird. I've stopped using the module, but gave it another spin today - latest git "master" (on Arch Linux with Python3) and it worked for me.

Can you please let me know the version you're using?

**Comment by TheEdgeOfRage** [comment]
Pretty much the same.

- Latest master commit `079f87e0468cd12181d74a7b274c093590945219`
- Up to date ArchLinux with python3.

**Comment by tobi-wan-kenobi** [comment]
Does the debug log say anything wrt. to which command was actually executed?

Honestly, I'm a bit stumped, and unsure how to continue, since I can't reproc.

Maybe it would be helpful if I update the master branch to have more diagnostic logging?

**Comment by tobi-wan-kenobi** [comment]
@TheEdgeOfRage One possible explanation: Do you unlock your GPG key during login? If not, it might be that "pass" doesn't work correctly with bumblebee-status because it's waiting for the unlock.

At least, that's the only way I was able to reproduce "vault" not working.

**Comment by tobi-wan-kenobi** [comment]
Also, I've updated the vault module experimentally in the `development` branch, if you'd like to give it a go, maybe it works better for you now?

**Comment by TheEdgeOfRage** [comment]
OK so I tried the dev branch and still the same thing happened. I added a log to the vault module in the callback to just print the secret name

```
[2020-04-12 12:57:04,781] vault            INFO     /home/<user>/.password-store/wikipedia
[2020-04-12 12:57:04,781] cli              DEBUG    pass -c wikipedia
```

Only this time it didn't even copy it to the clipboard. I think I'll just give up on this since I'm using the pass rofi plugin anyway and that works with multiple entries and has autotype.

You can close this issue if you want to, if someone else comes across it they can reopen it.

**Comment by tobi-wan-kenobi** [comment]
Thanks for testing!

I think that probably means that "pass" is waiting at a password prompt. Maybe the environment doesn't get passed along cleanly.

I'll do some more testing, as I can reproduce the error now.

**Comment by TheEdgeOfRage** [comment]
Oh yeah, I forgot to mention that. I start i3 using xinit from a normal login shell and unlock my keyring (and with it my gpg key) using [gkeyring](https://github.com/kparal/gkeyring). It should have access to the key, since rofi has access and that gets started from i3 as well.

**Comment by tobi-wan-kenobi** [comment]
I'm sorry @TheEdgeOfRage , but I will close that ticket for now, as I completely fail to reproduce it :(

**Comment by tobi-wan-kenobi** [comment]
HAH!

**Comment by TheEdgeOfRage** [comment]
I cant really wrap my heard around what happened? I guess it was some issue with scoping, but then why did it work for you and not me?

**Comment by tobi-wan-kenobi** [comment]
Yeah, I also don't fully get it, it seems the reference to the lambda was somehow reused, really weird stuff. I found a reference somewhere on stackoverflow.

As to why it didn't happen to me: Bad/careless testing :-) Yesterday, I could reproc just fine.

Hopefully, it works now for you!

⁣Sent from TypeApp ​
