### ISSUE TITLE
Let VPN plugin handle wireguard connections

### ISSUE THREAD

**Issue by dotslashme** [tobi-wan-kenobi/bumblebee-status#595]
### Feature Request
It would be nice if the VPN plugin could also handle VPN connection of the wireguard type.

#### Summary
Currently, looking at the VPN plugin, it seems to be looking for connection of the type _vpn_. This, however does not cover wireguard connection, since they will register as wireguard and not vpn.

In the code, this can be seen at lines 41 and 56 of the VPN plugin. Listing my connections using the nmcli commands used in the plugin, I get the following output (line 34):
```
SSID:802-11-wireless
VPN-profile-name:wireguard
docker0:bridge
```
and (line 51):
```
SSID:802-11-wireless:wlp2s0
VPN-profile-name:wireguard:VPN-iface
docker0:bridge:docker0
```

**Comment by tobi-wan-kenobi** [comment]
I don't have a wireguard setup myself and would appreciate if you could try to see whether the change I'm going to commit fixes the issue for you.

Thanks a lot in advance!

**Comment by dotslashme** [comment]
That did fix my issue and I can now handle my wireguard connections through the plugin. Thanks for the swift fix!
