### ISSUE TITLE
Allow NIC module to only show certain interfaces

### ISSUE THREAD

**Issue by jcbhghy** [tobi-wan-kenobi/bumblebee-status#601]
### Feature Request
First of all, wanted to say that I'm a huge fan of this project and really enjoying using it as my status bar! 
When using the nic module, it shows all interfaces. Since my laptop has both wifi and ethernet available, it shows two interfaces, with one down and in bright red. An optional parameter for the module to select an interface would alleviate this issue and make the bar look nicer.

**Comment by tobi-wan-kenobi** [comment]
Thanks a lot for the kind words!

The nic module already has two parameters - include and exclude - to specify a list of interfaces that should be used exclusively ("include") or that should be excluded from display ("exclude").

Does that do what you want?

Or are you looking for something else?

**Comment by jcbhghy** [comment]
That's exactly what I was looking for, I just failed to look properly at the -l modules command. Thanks!
