### ISSUE TITLE
Spotify extra space after song name

### ISSUE THREAD

**Issue by Bahnasawy** [tobi-wan-kenobi/bumblebee-status#602]
#### Summary
Affected module: Spotify

#### Description:
There is a large extra space after the text ends in the widget, like this: "The Weekend - Heartless            " for example. My configuration only has the song name so it will look like the attached picture.

#### How to reproduce
I was using the default method and didn't change anything in the module file, I will put my i3bar status_command in case the mistake is there.

`status_command bumblebee-status -m spotify nic battery pasink weather datetime -p interval=1 spotify.format="{title}" time.format="%H:%M CW %V" date.format="%a, %b %d %Y" \
            home.path=/home/bahnasawy nic.format="{ip} {ssid}" -t iceberg-powerline`

![DeepinScreenshot_select-area_20200425194824](https://user-images.githubusercontent.com/53174128/80286848-1a6fc780-872e-11ea-978b-dd48c851ccfb.png)

**Comment by tobi-wan-kenobi** [comment]
Did you find a solution that works for you?

**Comment by Bahnasawy** [comment]
Yeah I did but it was so terrible and hacky, I'll post it on the issue so
you can judge for yourself, I didn't like how it looked but maybe it'll be
more useful to you..

**Comment by Bahnasawy** [comment]
`if len(text) <= 25:
            width = widget.get("theme.width", int(module.parameter("width", len(text))))
        else:
            width = widget.get("theme.width", int(module.parameter("width", 25)))`
That's all I did at output.py, it didn't have anything to do with the Spotify module, it was the scrolling module that was the issue.

**Comment by tobi-wan-kenobi** [comment]
I think this is something you should be able to "fix" via configuration.

Can you please try to add `-p spotify.width=25` to the commandline?

**Comment by Bahnasawy** [comment]
Tried it, did nothing.

**Comment by tobi-wan-kenobi** [comment]
I'm really sorry to make you go through hoops, but I don't have a spotify account, so testing this is a bit hard for me (it's a user-contributed module).

Could you please try one more thing?

`bumblebee-status -m spotify -p spotify.scrolling.makewide=false`

**Comment by Bahnasawy** [comment]
That one worked.
I'll close this issue now.
