### ISSUE TITLE
Autohide nvidiagpu

### ISSUE THREAD

**Issue by elroxar** [tobi-wan-kenobi/bumblebee-status#603]
Hi together,

as I am using a Laptop with a NVIDIA graphics card running optimus, I often do not have the card itself enabled. However, I still wanted to use the module nvidiagpu but I didn't want it to hang around empty all the time.
Since I couldn't find a function to automatically hide it from the bar I changed the module code to set that state to "warning" if a card was enabled and added -a "nvidiagpu" to my status_command.
Maybe someone could work out a better way to do this. Thanks!

**Comment by tobi-wan-kenobi** [comment]
Hi @elroxar !

I think the cleanest way to do that would be to add a parameter to the nvidiagpu module that hides it unless the card is enabled.

I don't have a nvidia card, so I cannot test it, really. Would you be willing to do so, if I commit a corresponding change?

**Comment by elroxar** [comment]
I'd sure do so!

**Comment by tobi-wan-kenobi** [comment]
Tried something in the previous commit, but not sure whether it works.

It would be helpful for me to have the exact output of `nvidia-smi -q` when the card is inactive. Thanks a lot in advance!

**Comment by elroxar** [comment]
`$ nvidia-smi -q
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.`

**Comment by tobi-wan-kenobi** [comment]
Yeah, in that case, I assume my changes *should* work :) - Do they?

You just have to add `-p nvidiagpu.hide=true` to the invocation

**Comment by elroxar** [comment]
How do I update bumblebee-status? I installed it via AUR and I believe you didn't push it there yet.

**Comment by somospocos** [comment]
If you want to run the bleeding edge version, I think bumblebee-status will run fine from a local clone of the github repository. I've never had problems running it so (at least the master branch) as long as I used a full path to the bumblebee-status executable.

**Comment by elroxar** [comment]
I just cloned the repo, confirmed the changes were loaded and added the parameter `-p nvidiagpu.hide=true`. At this point I can't confirm the changes from 6f9abf616d63c569f8357547c74a14a9aa0ce888 work. The module is still shown in my bar whether the card is active or not. I'll try to restart my xserver and my whole system but I don't believe anything will change.

**Comment by elroxar** [comment]
@tobi-wan-kenobi I might have found the solution. line 21 in 6f9abf616d63c569f8357547c74a14a9aa0ce888 shows that the module gets hidden on the output `"not found: 0°C 0/0 MiB"` yet the output in my status bar is `not found: °C / MiB` I checked whether I interfered with `-p nvidiagpu.format` but that's not the case.

**Comment by elroxar** [comment]
I can confirm that is the error. I changed it to `if hide and self._utilization == "not found: °C / MiB":` and it works as expected. I'm just too dumb to create a pull request at the moment...

**Comment by tobi-wan-kenobi** [comment]
Thanks a lot for investigating the issue further! I hope the commit above does fix the issue, but I'm pretty confident it does :)

Also, thanks for using bumblebee-status!
