### ISSUE TITLE
Sensors -u and cpu2

### ISSUE THREAD

**Issue by hypedad** [tobi-wan-kenobi/bumblebee-status#604]
Affected module: cpu2.py

Description:
More verbose documentation or an example of widget pattern use

Tobi, sorry if this isn't the right channel, but I was hoping to see an example of how you would implement CPU temp and Fan speed using the output of sensors -u in the cpu2.py code. I'm unsure of the exact syntax of what to replace in cpu2.py to read my cpu and fan information.

**Comment by tobi-wan-kenobi** [comment]
Just out of curiosity: Why do you need that? In case you just want to read out sensors, there's two modules that do that already (sensors and sensors2), I believe they report fan speed, as well.

**Comment by hypedad** [comment]
You’re absolutely right, that actually solved my issue. I’ll use cpu2 for the graph and sensors2 for everything else. Thanks man, really love your work.

**Comment by tobi-wan-kenobi** [comment]
Perfect, great that this works for you :)

And thank you very much for the kind words, I appreciate them a lot!
