### ISSUE TITLE
"default-separators" option does not work

### ISSUE THREAD

**Issue by nlucia** [tobi-wan-kenobi/bumblebee-status#605]
#### Summary
Affected module: Themes

#### Description:
Themes with `"default-separators": true` option in "defaults" do not show default i3 separators, they show the separator in icons .json file if it's defined. Excuse me if this is the desired behaviour.

#### How to reproduce
Make a theme with:
```
{
	"icons": [ "awesome-fonts" ],
	"defaults": {
		"default-separators": true
	}
}
```

**Comment by tobi-wan-kenobi** [comment]
It's not exactly "works as designed", but I think it makes sense to a degree, right? If you have your own separator, why the default one?

Is that causing issues for you? If so, I think it should be fairly straight-foward to fix :)

**Comment by nlucia** [comment]
I see your point, but then, what is the purpose of the "default-separators" option? It doesn't seem to make any difference in a theme (as far as I've tried). 
It is not a big issue, for me it would be convenient to be able to inherit the separator (or its color) from i3 bar config (maybe there is another way to do it?), and that is what I thought this option was for.

**Comment by tobi-wan-kenobi** [comment]
You are right. Actually, that parameter wasn't used at all so far :(

I've changed the code so that default separators are now always drawn when the parameter is set - note that the separator block width needs to be > 0 for this to actually do something.

Thanks for raising this issue!
