### ISSUE TITLE
[module/cmus] The icons for all the buttons are the same

### ISSUE THREAD

**Issue by TheEdgeOfRage** [tobi-wan-kenobi/bumblebee-status#607]
#### Summary
Affected module: cmus
Version: development

#### Description:
On the development branch the cmus module shows the same icon (play/pause depending on the state) for all the action buttons (previous, play/pause, next, shuffle, repeat). The buttons still work as intended, only the icons are wrong.

![screenshot](https://pyazo.com/c761f91d-6b51-413e-a82c-016506d6eb64.png)

#### How to reproduce
Switch to the development branch
Use the cmus module
I use the default configuration except that I have cmus set up to run on a tcp socket and the parameters from #578

I'll take a look at it after work today (17:00 CEST, 15:00 GMT)

**Comment by tobi-wan-kenobi** [comment]
should be fixed now  - thanks for reporting!
