### ISSUE TITLE
[dev] *.interval does not seem to be working

### ISSUE THREAD

**Issue by martindoublem** [tobi-wan-kenobi/bumblebee-status#609]
#### Summary
Affected module: battery-upower date time sensors2

#### Description:
the interval parameter for a specific module crashes the status bar for these modules (not tested elsewhere)

#### How to reproduce
try to run an interval parameter on one of the above modules not tested for others.

**Comment by tobi-wan-kenobi** [comment]
What is the exact error message and how do you invoke bumblebee-status?

For me, it works as long as I just provide an integer as interval. Strings such as "5m" break, though. Is that what you mean?

**Comment by martindoublem** [comment]
Those are the only ones I tried so yes.

**Comment by martindoublem** [comment]
All good now, both work! thanks!
