### ISSUE TITLE
[dev] no icons showing for sensors2

### ISSUE THREAD

**Issue by martindoublem** [tobi-wan-kenobi/bumblebee-status#612]
### Bug Report
Icons are not showing. I have spent some time trying to fix it, but I can't seem to figure out how it is handled.

#### Summary
Affected module: sensors

#### Description:
<description>

#### How to reproduce
bumblebbe-status -m sensors2 -t iceberg

**Comment by martindoublem** [comment]
Can you check if it is an issue with icons on modules with multiple widget. I can seem to get them to work in smartstatus after adding icons to the json as well.

**Comment by martindoublem** [comment]
I have been investigating, sadly going nowhere.

**Comment by tobi-wan-kenobi** [comment]
This is a stupid bug from my side, widgets *need* a reference to their module.

I'll fix it in sensors for now, but probably it makes sense to add a "generator" method to the module that produces widgets, so that this issue doesn't pop up more often.

Thanks for reporting!

**Comment by martindoublem** [comment]
well I have the same in smartstatus once I add an icon.
