### ISSUE TITLE
[dev] Error: unrecognized arguments: --markup=pango

### ISSUE THREAD

**Issue by TheEdgeOfRage** [tobi-wan-kenobi/bumblebee-status#619]
#### Summary
Affected module: All modules that utilize pango rendering

#### Description:
The `--markup=pango` flag seems to be deprecated in the new version. Everything still works when removing it, so my guess is that it gets applied automatically now?

I just wanted to document this and check whether my assumption is true. Close this issue if that's the case.

**Comment by tobi-wan-kenobi** [comment]
Yes, exactly. The kind of markup required is now automatically inferred from the theme/modules.

There's some preliminary documentation on this in `doc/HOWTO_THEME.md`, but I'm planning to extend that a bit.
