### ISSUE TITLE
cannot start bumblebee after last update

### ISSUE THREAD

**Issue by zetxx** [tobi-wan-kenobi/bumblebee-status#62]
i think that this commit introduced this issue: https://github.com/tobi-wan-kenobi/bumblebee-status/commit/251f8d2e9f6c068bb7735e28416116e8c50c9852#diff-8cd86bca63308fc9023fb6f0117ce31eR16

output:
```
╰─ bumblebee-status -m kernel
Traceback (most recent call last):
  File "/usr/bin/bumblebee-status", line 64, in <module>
    main()
  File "/usr/bin/bumblebee-status", line 17, in main
    filename="{}/debug.log".format(os.path.dirname(os.path.realpath(__file__)))
  File "/usr/lib/python3.6/logging/__init__.py", line 1776, in basicConfig
    h = FileHandler(filename, mode)
  File "/usr/lib/python3.6/logging/__init__.py", line 1025, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.6/logging/__init__.py", line 1054, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/usr/share/bumblebee-status/debug.log'
```

**Comment by dumyan** [comment]
@zetxx I had the same issue and manually changed that the logs are written in my home folder. Just look for `/usr/share/bumblebee-status/debug.log` in the code and change accordingly.

It looks like there are differences between the permissions of `/usr/share/` on different distros, but I'm almost certain that users should not have write access there. I'm running Arch, what do you use @zetxx  and @tobi-wan-kenobi? I have installed `bumblebee-status` from AUR, but I don't think that's much relevant here.

@tobi-wan-kenobi do you think that adding an optional flag when running `bublebee-status` that the user can use to specify a file where the log will be written is a good idea?

**Comment by zetxx** [comment]
same story
dist: arch
changed log destination in order to run properly

**Comment by tobi-wan-kenobi** [comment]
Damn, that was a bad change from my side. Sorry for the inconvenience :-(! I have a patch ready, but I'm on the road right now. Will fix this today in the evening.

Default will be to log into `~/`, with the option to specify the file path, as suggested by @dumyan .

**Comment by zetxx** [comment]
fix is working

**Comment by tobi-wan-kenobi** [comment]
Yay, thanks for the quick testing! And sorry again for the bug ;-(

**Comment by zetxx** [comment]
no worries :)
