### ISSUE TITLE
[development] pipes with solarized-powerline theme

### ISSUE THREAD

**Issue by fredj** [tobi-wan-kenobi/bumblebee-status#623]
When using the solarized-powerline theme on the development branch, "pipes" are displayed between the widgets:
![20200505_08h52m13s_grim](https://user-images.githubusercontent.com/100959/81041451-2c7c0380-8eae-11ea-89f0-748cd1e84447.png)

They are not shown on master:
![20200505_08h52m50s_grim](https://user-images.githubusercontent.com/100959/81041520-5a614800-8eae-11ea-87d9-463b88e48a69.png)

**Comment by tobi-wan-kenobi** [comment]
Weirdly, I cannot reproduce this. *BUT* I did change some stuff around the default separators, let me try something.

**Comment by tobi-wan-kenobi** [comment]
Does this improve the situation?

**Comment by fredj** [comment]
forgot to mention that I'm using sway. And yes, 39f70a9 fixes the issue, thanks !
