### ISSUE TITLE
[development] issues with arch-update

### ISSUE THREAD

**Issue by martindoublem** [tobi-wan-kenobi/bumblebee-status#624]
#### Summary
Affected module: arch_update

#### Description:
arch-updates seems to crash often with exit code 1 or 2. I have stopped using the module in my status bar as I deem it too unstable. 

#### How to reproduce
bumblebee-status -m arch-updates -p arch-updates.interval="1h"

I can probably look more in the debugging but that might have to wait a bit as I am absolutely swamped at the moment with other things.

**Comment by tobi-wan-kenobi** [comment]
Does only that one module crash, or the whole status bar?

Thanks for reporting, I'll try to investigate (have switched from Arch myself, unfortunately, but let's see where I can scare up a test system)

**Comment by martindoublem** [comment]
Just the module, actually. Might be the actual checkupdate commands that generate errors however might be good to handle them with a try: except: .

**Comment by tobi-wan-kenobi** [comment]
@martindoublem did that in the previous commit. Would still like to get to the bottom of this, though :)

Not sure what the correct error behaviour is, either - just display the last successful count? Make it a warning status? Really hard to say for me, I tend to do the latter - show the last successful count, but indicate via a warning status that something went wrong. What do you think?

**Comment by martindoublem** [comment]
@tobi-wan-kenobi, I agree with you, on this last part. I think the last count + a warning is the way to go!

Let me try it out again on my setup and we shall see how it goes.

I think a lot of it has to do with the fact that sometimes I forget to finish the full update, and still have yay -Syu open in a terminal.

**Comment by tobi-wan-kenobi** [comment]
Got it! `checkupdates` returns exit code 2 if there are no pending updates. I'll keep to myself what I think about a tool that returns a non-zero exit code when everything is fine.
