### ISSUE TITLE
[development] psutil not found

### ISSUE THREAD

**Issue by tehgibbo** [tobi-wan-kenobi/bumblebee-status#626]
### Bug Report
I recently fetched and pulled the latest dev branch and after realizing cpu module has now been changed to cpu2 and traffic has changed to network_traffic i've updated my i3 bar config - yet they both state "No module named 'psutil'".

psutil is certainly installed both via Gentoo portage & pip (& reinstalled for good measure):
 * Searching for psutil ...
[IP-] [  ] dev-python/psutil-5.7.0:0

$ pip install --user psutil
Requirement already satisfied: psutil in ./.local/lib64/python3.6/site-packages (5.7.0)

Guessing this is a distro specific issue of it being in a different location to where bumblebee is looking.

#### Summary
Affected module: network_traffic & cpu2

**Comment by tobi-wan-kenobi** [comment]
First, thanks for giving the development branch a spin!

Then:

1. The modules "cpu" and "traffic" still exist, the others are just different modules that were contributed (and exist in master as well, I think)
2. bumblebee-status still uses the system-wide default Python version - is it possible that it's still running on 2.7 and psutil is missing there? The easiest way to check that is to enter "python" in a commandline and then write "import psutil". If that fails, this is likely the problem.
