### ISSUE TITLE
[dev] cmus not scrolling

### ISSUE THREAD

**Issue by TheEdgeOfRage** [tobi-wan-kenobi/bumblebee-status#629]
### Bug Report

I now remember why I didn't make it so that when the text changes the scroller decorator resets to the beginning. Because the cmus module has the current time of the song in the output and that changes every second :smile:.

One other solution might be to track whether the scroller needs to reset in the cmus module and when the song changes, set it to True so that the scroller knows to reset it. It's not a great solution and I'm not sure if my original solution in #622 would be better than this one or not, so I decided to open an issue and discuss it.

#### How to reproduce
1. checkout the dev branch
2. use the cmus module
3. play a song that doesn't fit completely in the module
4. observe nothing happening

**Comment by tobi-wan-kenobi** [comment]
Tricksy one, @TheEdgeOfRage , thanks for the challenge :)

I *think* I came up with something nice - albeit heuristic, and I usually don't like heuristics.

The following commit checks whether two strings are *similar* enough, and I found that to be pretty reliable. Please let me know what you think and whether it works for you.

**Comment by TheEdgeOfRage** [comment]
It seems to be working fine now. Thanks :)
