### ISSUE TITLE
vault can disable all click events

### ISSUE THREAD

**Issue by SemjonKerner** [tobi-wan-kenobi/bumblebee-status#633]
#### Description
Affected module: vault
Version used: latest AUR 1.10.4-2

bumblebee-status becomes not clickable until restarting (with i3-msg restart in my case) when you open the drop down menu from vault and close it without selecting a password.

#### How to reproduce
Closing the drop down menu without selecting a password is not totally easy. You'd need a password tree like "website > login". When you click _login_ you get your password as expected.

To reproduce the bug you need to click _website_ and then you click anywhere else and the drop down menu will "close".
This will disable any click event on any bumblebee module, probably because the drop down menu is still active in the background.
For example this will block me from muting the pulseaudio module.

This does not happen with the drop down menu from system module. This is probably due to the feature of vault to position the drop down menu.

I guess this should be fixed by clicking anywhere to close the drop down menu.
Alternatively the drop down menu could have a Close-Button or clicking a second time on the vault module could close it.
Another option is dropping the positioning feature, although I am using it. My monitor is not at y=0 of my screen (multiple monitor setup) and the drop down menu will move below the visible area without this feature.

**Comment by tobi-wan-kenobi** [comment]
Hope this helps!

Unfortunately, I cannot find a tkinter event for "this menu was destroyed, so please exit the main loop" - but this changes *seems* to do the trick.

Please let me know if it doesn't work for you!

**Comment by tobi-wan-kenobi** [comment]
Please note that you need to check out the git "master" branch for that.

**Comment by SemjonKerner** [comment]
Well, sadly it didn't do the trick. (yes I pulled master ;)
So, since I am not in the mood setting up pass now it's not a big deal to me, but eventually it will.

**Comment by tobi-wan-kenobi** [comment]
Damn, didn't see the second implication, thanks for raising!

Just curious: If you haven't set up pass yet, how are you testing this?

**Comment by tobi-wan-kenobi** [comment]
@SemjonKerner Thanks for you patience, I'm pretty sure I got to the root cause of the issue now (deletion events of a submenu were not propagated to the parent menu), and the problem should be gone now.

**Comment by SemjonKerner** [comment]
> Just curious: If you haven't set up pass yet, how are you testing this?

I meant setting it up for all my accounts - I have set up exactly one password for a rather unimportant website ;)

>  I'm pretty sure I got to the root cause of the issue now (deletion events of a submenu were not propagated to the parent menu), and the problem should be gone now.

Something kinda works - the dropdown menu will close now when I click a parent entry and only then.
However, I can now click multiple times on the vault module and the drop down menu will reopen after closing.
Sorry for testing so much, I fear to find even more bugs xD.

**Comment by tobi-wan-kenobi** [comment]
>  Sorry for testing so much, I fear to find even more bugs xD.

On the contrary: *Thank you* for testing so much and for your patience :) I hope you find more bugs ;)

**Comment by tobi-wan-kenobi** [comment]
After doing some investigation, this will stay "works as designed" - There doesn't seem to be a way to reliably close the menu, if it's not closed when "Leaving" the menu area.

Also, it seems to be impossible to run the tkinter mainloop in a separate thread, so this pretty much *has* to be blocking, unless I rework the whole popup class to spawn the popup in a *separate* thread and only "commandeer" the popup from the API, and that seems a pretty big change, given that only a handful of modules even make use of the popup code.

I'm actually more tempted to replace the tkinter implementation with something less arcane :P

**Comment by SemjonKerner** [comment]
There is a close button now! But it will still reopen when I click the module on the bar multiple times, though this is probably neglectable. Thank you for the quick responses. Almost like you earn money with this.

Another thing about those threads - the github module sometimes takes ages to load and the bar won't appear; should this be in another thread to not stall the rest of the bar? Should I open a feature request for this?

**Comment by tobi-wan-kenobi** [comment]
Thanks for the kind words, I just like the project and the people using it a lot :-)

Yes, the "Close" is my stopgap measure :-)

Yes, updates taking a long time *is* a known issue, it's something I eventually want to tackle in the core framework, but for now, every module has to take care of that itself, and the framework code is a bit too unstable to release.

I think opening a ticket would be a good idea to keep track of this.

⁣Thanks a lot for your feedback!
