### ISSUE TITLE
Overwriting icon theme from command line via -i argument doesn't work

### ISSUE THREAD

**Issue by somospocos** [tobi-wan-kenobi/bumblebee-status#634]
#### Description
Affected module: probably core/theme
Version used: latest master at issue creation time 6e7340f

Note for @tobi-wan-kenobi : if you need to assign priorities, please treat this issue as lowest priority. I consider it incomplete, as in - it contains only the bare minimum for reproducing. I did not do yet deeper digging like narrowing it down by trying a minimal config, running bumblebee-status with logging/debugging enabled or diving into the code, but I do intend to do that and add more details next time I'll be posting in this issue, so feel free to treat it like just a placeholder for now, unless you'll instantly spot the cause of the issue.

My current goal is to port the single-bar example with a big config from https://github.com/somospocos/bumblebee-status-contrib#if-one-bar-is-not-enough to the new bumblebee-status codebase.

What I did:

1. removed the `--markup` and `--iconmarkup` arguments from the bumblebee-status invocation, since they are obsolete now

2. modified https://github.com/somospocos/bumblebee-status-contrib/blob/master/themes/mustang-powerline.json to merge the content of the aforementioned `--iconmarkup` argument into the theme

Currently the theme looks like this:

    {
        "icons": [ "awesome-fonts" ],
        "defaults": {
            "default-separators": false,
            "separator-block-width": 0,
            "prefix": {
                "pango": {
                    "foreground": "#ff8700",
                    "font_desc": "Iosevka 15",
                    "rise": -3500
                }
            }
        },
        "cycle": [
            {
                "fg": "#7e8aa2",
                "bg": "#202020"
            },
            {
                "fg": "#b1d631",
                "bg": "#2d2d2d"
            }
        ]
    }

And it doesn't look at all like

![1bar](https://raw.githubusercontent.com/somospocos/bumblebee-status-contrib/master/screenshots/1bar.png)

It has some empty gaps between widgets and different icons.

But if I hardcode the icon theme name as

     "icons": [ "nerd-fonts" ],

I get the correct look.

At this point I assume that bumblebee-status doesn't overwrite the icon theme specified in a theme file with the icon theme that is specified explicitly via the -i command line argument.

**Comment by tobi-wan-kenobi** [comment]
Thanks for the report!

Looking at the code, I *think* I found the issue, but I didn't have time to actually test it.

If you could report back whether the situation improved for you with the change above, that'd be great.

Thanks a lot & have a nice day!

**Comment by somospocos** [comment]
The problem is indeed fixed now. Thank you.
