### ISSUE TITLE
behavior change in the battery module?

### ISSUE THREAD

**Issue by existme** [tobi-wan-kenobi/bumblebee-status#636]
#### Description
Affected module: battery
Version used: latest git

The battery module doesn't work as before. I had the same config for my laptop and desktop computer and it was working on both machines. On my desktop computer of course `/sys/class/power_supply/` is empty, and this wasn't an issue before. After I used the latest version of bumblebee-status I am getting the following error on my desktop configuration:

**no batteries configured/found**

I am guessing this is because of the following block in `/modules/contrib/battery.py` (line 117):
``` python
        if len(self._batteries) == 0:
            raise Exception("no batteries configured/found")
```

#### How to reproduce
On a computer without a battery try:
```
~/git/bumblebee-status/bumblebee-status -d -m battery

[2020-05-27 02:11:00,203] input            DEBUG    registering callback ::wheel-up
[2020-05-27 02:11:00,203] input            DEBUG    registering callback ::wheel-down
[2020-05-27 02:11:00,204] module           DEBUG    importing debug from core.debug
[2020-05-27 02:11:00,204] module           DEBUG    failed to import battery: No module named 'modules.core.battery'
[2020-05-27 02:11:00,205] battery          WARNING  unable to import module "power": Time estimates will not be available
[2020-05-27 02:11:00,205] module           DEBUG    importing battery from contrib.battery
{"version":1}
[
[{"full_text": " no batteries configured/found ", "background": "#ff0000", "color": "#ffffff", "name": "error", "instance": "the-only-one"}],
```

before the same command was producing (git checkout 26d16958df1773):
```
~/git/bumblebee-status/bumblebee-status -d -m battery
{"version": 1, "click_events": true}
[
[{"full_text": " ac ac ", "color": "#aabbcc", "background": null, "separator_block_width": null, "separator": true, "min_width": null, "align": null, "instance": "0f898cf8-9246-4c03-9d85-88038f0d319f", "name": "battery", "markup": "none", "_raw": "ac", "_prefix": " ", "_suffix": " ac "}],
```

**Comment by tobi-wan-kenobi** [comment]
I am not 100% sure that this is a bug - it seems to me that the new behaviour is "better" than the old one.

OTOH, I like backwards compatibility, and it looks like the behaviour made sense in your use case, so I will try to restore the old behaviour.

Thanks for the report!

**Comment by existme** [comment]
Thank you very much for the quick fix, it works as expected now :+1:
