### ISSUE TITLE
Triangles not showing up

### ISSUE THREAD

**Issue by meain** [tobi-wan-kenobi/bumblebee-status#64]
![img](http://i.imgur.com/FWEFOT6.png)

How to fix this, or at least even get rid of the triangles all together.

`gruvbox` theme

**Comment by tobi-wan-kenobi** [comment]
Hi,

the triangles are only displayed if you are using a "powerline" compatible font. Personally, I am using "Inconsolata", you can find a list here: https://github.com/powerline/fonts

Alternatively, you can open the theme file (`themes/icons/awesome-fonts.json`) and replace the defaults -> separator entry to your liking.

Hope this helps!

**Comment by meain** [comment]
Cool, thanks!
