### ISSUE TITLE
Speed up bar creation by threaded github update

### ISSUE THREAD

**Issue by SemjonKerner** [tobi-wan-kenobi/bumblebee-status#640]
### Feature Request

Since the github module sometimes takes a while to update notifications, I suggest letting it update in a separate thread in order to avoid blocking the rest of the bar.

Solving this by providing a core framework for threaded updates may be preferred as it allows other modules to make easy use of it as well.

**Comment by tobi-wan-kenobi** [comment]
@SemjonKerner Please let me know whether this works now for you.

For future improvement, this could be used to simplify code in:
- apt
- octoprint
- pacman
- shell
- spaceapi
- title
- ping
- redshift
- vault (?)

**Comment by SemjonKerner** [comment]
It works like a charm. Thanks again for this quick fix and so delicate. Well done.
