### ISSUE TITLE
Unit tests for modules

### ISSUE THREAD

**Issue by tobi-wan-kenobi** [tobi-wan-kenobi/bumblebee-status#641]
### Feature Request
Right now, the project's unit test coverage is ~15%. The core framework is covered with 90+%, but the module's make up the brunt of the code - and those are barely tested.

Any code that adds tests for modules would be much appreciated.

(Incidentially, also moving over to pytest would be highly appreciated)

**Comment by rosalogia** [comment]
Kinda wanna help out with this... I do need to spend some time looking into good testing practices and pytest first though. I'll try to stay in touch over it!

**Comment by tobi-wan-kenobi** [comment]
Any help on that would be much appreciated!

Fair warning: It's a huge task, as modules make roughly 85% of the code, and we really need a module by module decision what a meaningful test is (ie it must still be standalone, not requite internet access etc.). As such, heavy mocking will be involved, I guess.

Thanks a lot in advance, always glad for people who are up to a challenge :-)

**Comment by rosalogia** [comment]
I appreciate the warning! How about this: I'll look over the modules right now, and if I have any ideas off the top of my head, I'll let you know. If you have the time to be working on this at the same time as me, or at least to be in discussion with me about it, let's find a place to have that continuous conversation. If we can bounce ideas off of one another, we should be able to make progress in test _design_ much faster. Totally understand if that's not something you presently have time for though!

**Comment by tobi-wan-kenobi** [comment]
Yes, I fully agree, that sounds like a very good plan.

Unfortunately, the amount of time I can currently spend on the project is sporadic and at odd hours, so for me, "discussing" offline via the ticket works "best". It also invites others to participate, so that's a plus (I agree with you that real-time discussions would make for much quicker progress, though).

A first step could be to just migrate the existing kernel.py test over to pytests - it also shows how a very very simple module could maybe be mocked.

Thanks!

**Comment by rosalogia** [comment]
I'll take a look and see if I can get started on this today!

**Comment by rosalogia** [comment]
Taking a look at `kernel.py` and there are two things I'm trying to figure out:

If I'm understanding correctly, should `someKernel` and `module` be defined as the return values of functions decorated with `@pytest.fixture`?

I'm trying to understand how the [`mock.patch` line](https://github.com/tobi-wan-kenobi/bumblebee-status/blob/master/tests/modules/test_kernel.py#L15) can be replicated with pytest. Admittedly, I'm not super well read or practiced with mocking or monkey patching, so I'll take some time to read and experiment before making any pull requests.

**Comment by tobi-wan-kenobi** [comment]
Reg. the fixtures: Yes, that's what I figure, too. Especially the `someKernel` might be a bit of overkill, though, as this is done purely for having more expressive code (e.g. when reading the test, I prefer "check that if the kernel version is someVersion, that is reflected in the module's output", rather than hardcoding a specific version. So if it makes the pytest easier, I am all for scrapping that and just hardcoding a value instead :)

Reg. the mocking: Same for me, mocking is something I never *fully* wrapped my head around in Python, so any idea/approach you come up with that looks easy to use and easy to read is much welcome. If you have a look at `pytests/core/test_config.py`, I've experimented with `mocker` a bit, there. Not sure I like the result, though :(

**Comment by rosalogia** [comment]
Thanks for all the info! Gonna do some reading today and hopefully that will better inform how I approach all this. Specifically looking at [this blog post](https://circleci.com/blog/how-to-test-software-part-i-mocking-stubbing-and-contract-testing/).

**Comment by rosalogia** [comment]
I'm having trouble running the tests and generally working with the repository due to import errors

![image](https://user-images.githubusercontent.com/66163965/84963626-e7b3d100-b0d7-11ea-94be-6f1940233d8d.png)

Any chance we could get more detailed build instructions to make sure things work as they should? Sorry for the somewhat trivial request :pray:

**Comment by tobi-wan-kenobi** [comment]
Not trivial at all, when it's a lack of documentation :) I've pushed https://bumblebee-status.readthedocs.io/en/master/development/general.html, hope that helps!

In particular, I *think* you have 2 issues:

1. You need to install pytest (for Python3)
2. I think you created the directory `pytests/modules/`, right? If so, you also need to put a file `__init__.py` inside, so that module resolution works correctly.

Hope this helps!

BTW: That looks like a really awesome vim setup!

**Comment by rosalogia** [comment]
That definitely was an error I made, but this issue seems to be beyond that fix. I say this because even outside of the tests, I get issues across the codebase where Python isn't able to read local modules
![image](https://user-images.githubusercontent.com/66163965/85009943-3b9cd500-b12d-11ea-8b18-7680981306af.png)

Am I forgetting something obvious?

Re: vim setup

Thanks :) I pushed my dotfiles up today so feel free to seek inspiration from what little configuration I've done in there so far

**Comment by tobi-wan-kenobi** [comment]
Ah, yeah, the local modules probably are my fault.

Due to PyPI restrictions, all local modules are *actually* `bumblebee_status.<bli>.<bla>`, for example `bumblebee_status.core.input`, but lazy me added a discovery submodule (see the `pytests/__init__.py` - you only need it there, nowhere else). Likely, that throws off your autocomplete setup (deoplete?).

Will def. check out the dotfiles, thanks!

**Comment by rosalogia** [comment]
That would explain why the linter complains but the tests generally still run :sob: thank you!

**Comment by rosalogia** [comment]
So with all this I was able to replicate the kernel module test (see: #653). Let me know how you feel about it, and from there we should be able to progress!

**Comment by tobi-wan-kenobi** [comment]
:+1: thanks! also, sorry about the linter issues, i'm just lazy :P i noticed the issues i had with pypi after ~80% of the modules were migrated, and going through the whole code to prepend `bumblebee_status` in hundreds of places was just beyond me. maybe the linter has a way to add a custom search path?

**Comment by rosalogia** [comment]
No worries! I've found I can operate well enough without the linter for now. If I need it later I'll find a way.

I've been messing around with testing for the mpd module (#656) because it's probably the one I mess with the most. I was able to get a really simple one going that ensures shuffle is off by default, which was easy enough. However, testing methods is something I ran into difficulty with. Something I tried early on looked like this

```python
def test_shuffle_state(mocker, mpd_module):
    widget = mocker.patch('core.widget', name='mpd.shuffle')
    if mpd_module._shuffle:
        assert mpd_module.state(widget) == 'shuffle-on'
    else:
        assert mpd_module.state(widget) == 'shuffle-off'
```

However, `mpd_module.state(widget)` returned None and so the test failed. It's probably an issue with how I'm trying to mock the widget, but honestly I'm struggling to find resources that do a good job of explaining how I'm supposed to do it if not like this. Any ideas? If not I'll keep looking for information on how to go about mocking properly. I haven't asked on any forums yet so I'm probably headed there next.

**Comment by rosalogia** [comment]
Just figured this one out, actually. I'll do some more work before making a PR though :)

**Comment by rosalogia** [comment]
One thing I'm curious about is how I should go about testing similar functionality. E.g. if I wanted to test not only that the mpd module's state method returns the proper output when the widget it's passed is the shuffle widget, but also that all the other possibilities return the proper values: would I write separate but similar looking tests for all of them? Should I write an abstraction to reduce repetition within the test file itself?

**Comment by rosalogia** [comment]
Tried writing a helper function to handle the above. I think it could be better, but it does work. How do you feel about it?

![image](https://user-images.githubusercontent.com/66163965/85116965-191dc100-b1ec-11ea-9f93-cf582743e011.png)

**Comment by rosalogia** [comment]
New challenge I'm facing is finding a way to test different parameter inputs, e.g. testing that when `self.parameter("host")`, `self._hostcmd` accurately reflects the contents of the parameter. Not sure how to modify the contents of the parameters before `__init__` is called. Any insight would be appreciated! Sorry for all the comments by the way; had a lot of time left over tonight so I thought I'd explore some more and I think I'm making progress!

**Comment by tobi-wan-kenobi** [comment]
> One thing I'm curious about is how I should go about testing similar functionality. E.g. if I wanted to test not only that the mpd module's state method returns the proper output when the widget it's passed is the shuffle widget, but also that all the other possibilities return the proper values: would I write separate but similar looking tests for all of them? Should I write an abstraction to reduce repetition within the test file itself?

I tend to think that an abstraction would make more sense, but to a certain extent, that probably also depends on the resulting code :P Feel free to experiment! I like the results in the screenshot you sent very much, looks very clean!

One aside: You seem to prefer single-quoted strings, which is totally fine for me, just please be aware that I occasionally run `black -t py34` on the code, and that will revert those to double quotes.

> New challenge I'm facing is finding a way to test different parameter inputs, e.g. testing that when self.parameter("host"), self._hostcmd accurately reflects the contents of the parameter. Not sure how to modify the contents of the parameters before __init__ is called. Any insight would be appreciated! 

That one should be rather easy, actually. When you instantiate a module, you pass in an instance of `core.config.Config()`, which essentially models the CLI parameters. That way, you can set arbitrary parameters of that module.

For some examples of exactly that, you can have a look at `tests/core/test_module.py` (e.g. `test_error_widget()`).

> Sorry for all the comments by the way; had a lot of time left over tonight so I thought I'd explore some more and I think I'm making progress!

On the contrary, thank you very much for the time and effort you are investing! To me, it also looks like you are making great progress :+1:

**Comment by rosalogia** [comment]
> One aside: You seem to prefer single-quoted strings, which is totally fine for me, just please be aware that I occasionally run `black -t py34` on the code, and that will revert those to double quotes.

So I actually started using single quotes because that's what was requested in the [module creation documentation](https://bumblebee-status.readthedocs.io/en/main/development/module.html#coding-guidelines) :sweat_smile: Was that an accident perhaps?

> That one should be rather easy, actually. When you instantiate a module, you pass in an instance of `core.config.Config()`, which essentially models the CLI parameters. That way, you can set arbitrary parameters of that module.

I figured this out by following the super constructor back actually, so now we have a good amount of tests for the mpd module which I'll make a PR for in a moment :+1: 

Thanks for all your help! This has been rewarding :)

**Comment by rosalogia** [comment]
Logging off for the night, but I wanted to mention that [this resource](https://realpython.com/python-mock-library), although it's for `unittest.mock`, has gone a long way in helping me understand how mocking works. Hopefully you or anyone else interested in contributing to this particular issue will find it useful as well!

**Comment by tobi-wan-kenobi** [comment]
> So I actually started using single quotes because that's what was requested in the module creation documentation sweat_smile Was that an accident perhaps?

*sigh* My bad, that's a documentation bug :) Will fix right away.

> Thanks for all your help! This has been rewarding :)

Glad to hear that & happy to help. Thanks for improving `bumblebee-status`!

**Comment by tobi-wan-kenobi** [comment]
@rosalogia One thing that came to my mind reviewing the test code again: Right now, `test_mpd.py` depends on implementation details (e.g. that there's something called `_hostcmd`) in some places. In particular, `test_host()`, `test_no_host()` and `test_update_calls_load_song()` look like they are prone to breakage when the internal implementation of the module changes (refactoring, for instance).

I think it might be more robust to test against something that'll not change likely - i.e. relevant parts of the CLI invocation itself.

To get a feeling for what that would actually look like, I've implemented `test_host2()`, which mocks the `cli.execute()` call and ensures that it gets the `-h <host>` arguments. This will break if a) `mpc` ever changes its flags (unlikely) or b) the `mpd` module is changed so that it doesn't use `util.cli.execute()` anymore.

What do you think of this approach?

**Comment by rosalogia** [comment]
This makes sense, thanks for bringing it up :) I'll check out what you've done and keep it in mind as I continue.

**Comment by rosalogia** [comment]
Alright, now looking at the code and fixing mistakes where I can, I think maybe there is some discussion to be had on the extent to which tests should be immune to refactoring and such. I think you're right that we should have our tests center on things that are least likely to change like external command invocations. However, I do think there are some cases where this is difficult to implement, e.g.
```python
def test_default_layout(mpd_module):
    assert mpd_module._layout == "mpd.prev mpd.main mpd.next mpd.shuffle mpd.repeat"
```
So it's up to you how you want to handle cases like this where it's not really easy or clear how to make the test more independent of implementation details. I can delete it if you'd rather not have any such tests, or we can hang onto it and accept that some tests are probably going to need to be changed along with implementation details if anyone ever chooses to modify the latter.

Hope I got my point across, thanks!

**Comment by tobi-wan-kenobi** [comment]
Good point!

Thinking about it, I'd say: A robust test that tests *external* behaviour ("public" API calls, CLI calls, output, etc) is best, but code coverage is more important than having only "best of class" tests - we can always improve or disable tests that fail too often.

The layout test is fine, I think - maybe it could be tweaked to look at the actual output in terms if i3blocks (like test_output does), but that complicates the test a lot, just to remove the dependency on _layout...

Maybe what we really need are support libs for that kind of test (like test.util.get_output_json() or st. like that)

What is your take on that?

**Comment by rosalogia** [comment]
> Maybe what we really need are support libs for that kind of test (like test.util.get_output_json() or st. like that)

This is a good idea; I think it's the best way to go about it really. I haven't looked into how output works yet. How difficult would a function like this be to implement do you think? If it's nothing too complicated I can start taking a look and working on getting it implemented today or tomorrow. I'll gladly accept any explanations, advice, pointers, etc. if you have any for implementing it though :)

**Comment by tobi-wan-kenobi** [comment]
Top off the head, it should be relatively easy, because the output splits content generation from the actual writing to stdout.

I think the tests in test_output make use of that - they do checks on the array of dicts that the output module generates.

⁣Hope that helps!

**Comment by martindoublem** [comment]
After a quick turn on gnome, I am back on I3 and getting your status bar up and running. I am available and have some free time and therefore will propably be writting some of those test for the modules I wrote, (I will have to check to see which are they, but yep)!

**Comment by rosalogia** [comment]
> After a quick turn on gnome, I am back on I3 and getting your status bar up and running. I am available and have some free time and therefore will propably be writting some of those test for the modules I wrote, (I will have to check to see which are they, but yep)!

Best of luck! I've been running low on readily available free time, but I'll happily answer any questions I can if @tobi-wan-kenobi doesn't get to them first :)

**Comment by tobi-wan-kenobi** [comment]
Great to have you back to i3 @martindoublem !

Also, to you and @rosalogia - it's great and humbling to see this kind of community interaction, many thanks for being such a active, dedicated and helpful part of the small bumblebee-status "family" :)

**Comment by jayvdb** [comment]
I would love to see *very* basic test modules for each module - the tests could be very generic, just checking that the module loads, and the test for each module is skipped if the dependencies are missing.  That will help greatly for distro packaging, because then we can look at the skipped tests to determine which modules have missing dependencies in our packaging, and also help for new modules being added here because then you can do the same to ensure that the docs (c.f. https://github.com/tobi-wan-kenobi/bumblebee-status/pull/683) are complete.

**Comment by tobi-wan-kenobi** [comment]
@jayvdb Good point, didn't think about the distro packaging advantages.

Will need to think about a way to (semi) automated that to ensure that the tests are up-to-date.

**Comment by tobi-wan-kenobi** [comment]
@jayvdb hope this is what you had in mind, at least partially :)

**Comment by tobi-wan-kenobi** [comment]
Closing, as migration to pytest is done, and increasing test coverage would better be done on small-sized tickets.
