### ISSUE TITLE
status_command process exited unexpectedly (exit 1)

### ISSUE THREAD

**Issue by arminimamovic99** [tobi-wan-kenobi/bumblebee-status#645]
After installing and setting up my config, when i reload my i3 i get - status_command process exited unexpectedly (exit 1)
This is my bar config:
bar {
	font pango:Inconsolata 10
	position top
	tray_output none
	status_command ~/.config/i3/bumblebee-status/bumblebee-status -m nic disk:root cpu \
		memory battery date time pasink pasource dnf \
		-p root.path=/ time.format="%H:%M CW %V" date.format="%a, %b %d %Y" \
		-t iceberg
}

**Comment by somospocos** [comment]
What happens if you run the status command from console?

**Comment by somospocos** [comment]
Also, your i3 config snippet looks invalid to me: if you split the status_command line into multiple lines in the config text file, you must have backslashes at the end of lines, so i3 knows to treat it as single line.

**Comment by ZlatkoGusic** [comment]
I have same problem 
my config
bar {
        status_command i3status
	#status_command ~/.i3/bumblebee-status/bumblebee-status -m datetime memory \
	#-t powerline 
        position top
        font pango:dank mono 12
       
}

**Comment by tobi-wan-kenobi** [comment]
@arminimamovic99 @ZlatkoGusic The most likely reason is the one @somospocos pointed out - linebreaks in the i3 configuration require "\" at the end, like so:

```
bar {
  status_command ~/.i3/bumblebee-status/bumblebee-status -m datetime memory \
    -t powerline
}
```

If that does not resolve your issue, can you please let me know the output of the command, when you run it in a terminal (ideally with `--debug`)?

Thanks a lot in advance!

**Comment by ZlatkoGusic** [comment]
I will repeat my code in config now exactly as it is

`bar {

        #status_command i3status
	status_command ~/.i3/bumblebee-status/bumblebee-status -m datetime memory \
	-t powerline 
        position top
        font pango:dank mono 12
       
}`
This did not solve my problem and still the error is the same, please tell me how to run --debug

**Comment by somospocos** [comment]
> how to run --debug

https://bumblebee-status.readthedocs.io/en/master/features.html#errors

**Comment by tobi-wan-kenobi** [comment]
@ZlatkoGusic If you could open a terminal, run the following command and paste the exact output, that would be very helpful to me:

```
~/.i3/bumblebee-status/bumblebee-status -m datetime memory -t powerline
```

Thanks a lot in advance!

**Comment by arminimamovic99** [comment]
@tobi-wan-kenobi 
Traceback (most recent call last):
  File "/home/commercecare1/.config/i3/bumblebee-status/bumblebee-status", line 16, in <module>
    import core.config
  File "/home/commercecare1/.config/i3/bumblebee-status/bumblebee_status/core/config.py", line 4, in <module>
    from configparser import RawConfigParser
ImportError: No module named configparser

This is the exact output after executing the command you suggested we do

**Comment by somospocos** [comment]
What python version and what operating system are you using?

**Comment by arminimamovic99** [comment]
Ubuntu 19.10
Python 2.7.17

**Comment by tobi-wan-kenobi** [comment]
@arminimamovic99 Python 2.7 isn't supported anymore by `bumblebee-status`, sorry about that!

If you switch to Python3, things should start working again, hopefully.

**Comment by somospocos** [comment]
Quote from the README:

> Supported Python versions: 3.4, 3.5, 3.6, 3.7, 3.8

If you are using the modern, non-legacy bumblebee-status version, you are at least not meeting the requirements.

There's a very recent, older release that still supports Python 2. And there's a "legacy" tag in the git repository if you run bumblebee-status straight from a repo clone.

There's something else that you can check. As far as I know, Debian (and likely Debian-based distros like Ubuntu, but I don't know this for sure) have a bad (IMHO) habit of splitting Python into multiple distinct packages. Do an apt-cache search to check that.

And regarding configparser, there's also this https://packages.debian.org/sid/python-configparser

**Comment by tobi-wan-kenobi** [comment]
Closing, as this is most likely a Python 2.7 issue
