### ISSUE TITLE
[question] How to use the same theme with two different setups?

### ISSUE THREAD

**Issue by somospocos** [tobi-wan-kenobi/bumblebee-status#648]
I have a situation where I need to use the same theme with two different setups. First setup involves using a powerline-like theme and requires adjusting size/position of icon chars and the theme also changes the color of those icons to a different one. Second setup involves using an ascii-like theme that only has alphanumeric string prefixes where I only need to change the color of them. While I can have one theme that contains a hardcoded icon theme and just switch to another icon theme by using the -i argument, in case of pango it gets iffy. In the legacy version, the custom pango stuff was tuned through a command line argument as well and I could just have two different invocations of bumblebee-status with different sets/values of arguments. In the new version the pango markup became a hardcoded part of the theme. So what are my options to solve the problem now? The easiest way is to just have two copies of the same theme with different pango settings, this entirely solves my particular problem. But this feels a bit redundant and in theory it doesn't scale well for multiple combinations of different settings. However, the purpose of this question is to make sure I'm not missing other way of doing it, not to advocate adding even more complexity to the code.

**Comment by tobi-wan-kenobi** [comment]
I am not 100% sure if I completely got your problem, but:

With the latest commit (034e8ee), it's possible to *override* existing settings from the theme in the iconset (on an arbitrary level).

So you can put all the "common" attributes in a theme file that both setups use and configure the differences (even if they overwrite existing parameters) in a separate iconset file (in the "icons" subdirectory).

For pango, that should also work for individual attributes.

Would that work?

**Comment by somospocos** [comment]
This is a good improvement that helps solving exactly my problem: I can keep the prefix icon color in the theme and different sets of pango settings in different icon themes. This way I can have only one theme file and use it in both setups by controlling which icon theme it uses via -i argument.

However, this is still not the silver bullet (or at least it doesn't make it obvious for me). For example, if an end user uses a stock (or call it "official" if you want) theme (that comes with bumblebee-status), but he wants to change just the color the prefixes - it would be still required to make a copy of that theme to another file with a different name, add (or modify) the pango attribute and tell bumblebee-status to use that custom theme.

The reasoning above is not a call to increase the complexity of layering settings even more. It is rather a statement of fact that integrating the pango markup straight into themes (and now icon themes with this commit) is slightly less flexible that tuning them per-bumblebee-status call via command line arguments. But I think it's fair to see it as tradeoff, after all copying a text file containing JSON, making a few small changes to it, dropping it into `~/.config/bumblebee-status` and instructing bumblebee-status to use it as theme is not that resource demanding and simplifies the bumblebee-status command as well.

**Comment by tobi-wan-kenobi** [comment]
> if an end user uses a stock (or call it "official" if you want) theme (that comes with bumblebee-status), but he wants to change just the color the prefixes - it would be still required to make a copy of that theme to another file with a different name, add (or modify) the pango attribute and tell bumblebee-status to use that custom theme.

I don't think so (haven't tested it, though). In the custom iconset, you can override *any* attribute (not only icons),for example also the "defaults": { "pango": { "foreground": "..." } } attribute, and that **should** take precedence over anything provided in the theme.

That is not obvious from the name "iconset" or "icons", but the primary use-case was to specify a common set of icons, and I couldn't come up with any sufficiently clear name that explains the general concept (i.e. "overrides" would be confusing to anybody just trying to add an iconset).

From my perspective, you should be able to override *any* attribute (including individual pango attributes) via the iconset. So you shouldn't have to copy and modify themes, ever, because you can just override.

Hm, I see that this has a small bug still - will fix in a minute or so.

**Comment by somospocos** [comment]
My hypothetical example above (the one that you are quoting) doesn't involve the iconset at all.

There is:

1. a stock theme
2. an iconset which the stock theme uses - the iconset name is hardcoded in the theme

If I wanted to only change the color of icon prefixes for a second setup that uses the same theme, I couldn't do it in the theme file - because then all setups using the theme would have it changed. I couldn't do it in the iconset file either - because then all setups using the iconset (either through the theme those setups would be using, or through -i argument) would have the color of icons changed.

The legacy version allowed to do that via --iconmarkup argument, in the new version the only way to do it without modifying the theme or the iconsiet would be to make a copy of either the theme or the iconset under a new name, add pango markup that would change the icon colors there, and use that. At least this is how I see it.

**Comment by tobi-wan-kenobi** [comment]
Right: Now, you need to create a custom theme file in ~/.config/bumblebee-status/themes/icons/ (I think ...) and override that one attribute you need. Then, you specify it as a custom iconset via "-i" when calling bumblebee-status.

A bit more cumbersome, but also more uniform and flexible :-)

⁣Sent from TypeApp ​

**Comment by somospocos** [comment]
Feel free to consider the issue closed then. Everything works for me now and I also finished porting the contrib and bridge repos today. I even switched to the new bumblebee-status codebase as well for my "main" setup which uses the dwm bridge and it's been running fine for a couple of hours already. If I won't spot any problems till next weekend, it'll mean that everything works for me as well as it used to do before the merge. So once you exhaust your own list of high priority things to sort out, feel free to consider a new release. With these recent bugfixes and small feature additions the codebase is already better than right after the big merge. As I expected, first practical usage, even limited, provided valuable feedback about misc things related to backwards compatibility.

**Comment by tobi-wan-kenobi** [comment]
That is great news, I am glad that the master branch works that well for you! And thanks for taking the time to switch over the contrib/bridge repos.

Yeah, I'm basically just waiting for 1 week without major report, then I will release v 2.0.0 :)
