### ISSUE TITLE
Wiki developer page doesn't contains state information

### ISSUE THREAD

**Issue by P-Storm** [tobi-wan-kenobi/bumblebee-status#651]
I was looking into the state information to set a warning color to the spotify module if it paused. I have looked at other modules to include a warning module.

I have found the following:

```python
    def state(self, widget):
        if self.retrieve().get("playbackStatus") == "Paused":
            return ["warning"]
        return None
```

Returning `warning` for warning, `critical` for critical. When deeling with a float you can use the helper `threshold_state`.

Am I missing something? And what are the guidelines for the status?

**Comment by tobi-wan-kenobi** [comment]
Good points, I will add that to the developer documentation (which is still incomplete)

**Comment by tobi-wan-kenobi** [comment]
Hope this helps, @P-Storm !

Please let me know if anything's not clear in the documentation!

**Comment by somospocos** [comment]
> it's easier to determine the state of a widget from the module, rather than from the module itself.

Shouldn't this be

> it's easier to determine the state of a widget from the module, rather than from the widget itself.

?
