### ISSUE TITLE
Plugged-In icon shows up as a question mark

### ISSUE THREAD

**Issue by rosalogia** [tobi-wan-kenobi/bumblebee-status#652]
#### Description
Affected module: battery
Version used: AUR 1.10.4-2

When laptop is plugged in, instead of displaying the plugged-in icon, a question mark icon is displayed. This is rather strange, since the issue clearly isn't an invalid character. The question mark is _the_ question mark icon provided by Font Awesome. All the other icons are rendering perfectly fine, just to be clear.

#### How to reproduce

1. Install bumblebee-status from the AUR
1. Install `powerline-fonts` and `awesome-terminal-fonts`
1. Run bumblebee-status in i3 bar configuration like so
```i3
bar {
    font pango:Inconsolata, FontAwesome, PowerlineSymbols 11
    position top
    tray_output none
    status_command bumblebee-status\
        -m battery datetime nic pasink pasource\
        -p datetime.format="%a. %b %d %H:%M" nic.exclude="lo,wlan0"\
        -t gruvbox-powerline
}
```

**Comment by tobi-wan-kenobi** [comment]
Hi,

sorry you are having issues!

battery *typically* shows a question mark if it cannot determine the charging state of the battery.

Could you please execute the following command in a terminal and let me know the output?

```
cat /sys/class/power_supply/BAT*/status
cat /sys/class/power_supply/BAT*/capacity
cat /sys/class/power_supply/BAT*/energy_full
cat /sys/class/power_supply/BAT*/energy_now
```

Alternatively, you can also try the `battery-upower` module, it shows the same information, but uses a different approach to retrieve the information.

Thanks a lot in advance!

**Comment by rosalogia** [comment]
That makes a lot of sense! I'm away from my computer right now but I'll be sure to get back to you after testing it out tomorrow. Thank you!

**Comment by rosalogia** [comment]
Okay hi! For the record I woke up the next day and the icon was actually working? But today it's not so I'm going to give this a try haha

**Comment by rosalogia** [comment]
1. You're right that the issue here is that the battery charging status is unknown (`cat /sys/class/power_supply/BAT*/status` outputs Unknown) so good call! No idea how to fix that but obviously it's not _always_ an issue, and furthermore it's not really within the scope of this project

1. `battery-upower` DOES work! Interesting, thank you for the solution!

**Comment by tobi-wan-kenobi** [comment]
Glad that there was a solution to your problem!

The distinction happened because `battery` works on almost any system (when /sys produces the correct output... :P ), whereas `battery-upower` uses the UPower middlewhere, and therefore depends on dbus being available on the system.
