### ISSUE TITLE
Module traffic error after suspend/resume

### ISSUE THREAD

**Issue by existme** [tobi-wan-kenobi/bumblebee-status#655]
#### Description
Affected module: traffic
Version used: latest git

Hi,
Recently, every time that I put the OS into sleep when it's resumed, the status bar looks like this:
![image](https://user-images.githubusercontent.com/3057279/85106872-3fa02400-b20d-11ea-9939-b6fe47f6671b.png)

I am using the following modules: `cpu memory traffic datetime battery layout-xkbswitch pasink`
if I issue: `~/git/bumblebee-status/bumblebee-status -d -m cpu memory traffic datetime battery layout-xkbswitch pasink`
I get:
``` json
{"full_text": " debug ", "color": "#aabbcc", "name": "debug", "instance": "5c0f85e5-a6f8-4f0a-9ad4-611b19b7711a", "_raw": "debug", "_suffix": " ", "_prefix": " ", "align": null}, {"full_text": " cpu 33.3% ", "color": "#aabbcc", "name": "cpu", "instance": "16cf95e5-5604-44a6-87aa-f94feba70fc7", "_raw": "33.3%", "_suffix": " ", "_prefix": " cpu ", "min_width": "100.0%", "align": null}, {"full_text": " ram 29.68% ", "color": "#aabbcc", "name": "memory", "instance": "7abe89cd-0960-407b-ad1c-ce51c315cf7b", "_raw": "29.68%", "_suffix": " ", "_prefix": " ram ", "align": null}, {"full_text": " down 0.00B/s ", "color": "#aabbcc", "name": "traffic", "instance": "1e618b04-f9a1-4319-a932-48e1368a468e", "_raw": "0.00B/s", "_suffix": " ", "_prefix": " down ", "min_width": "1000.00KiB/s", "align": null}, {"full_text": " up 0.00B/s ", "color": "#aabbcc", "name": "traffic", "instance": "ee9f81e6-7577-472e-8506-842698486988", "_raw": "0.00B/s", "_suffix": " ", "_prefix": " up ", "min_width": "1000.00KiB/s", "align": null}, {"full_text": " 09:15  \uf18c Jun(06)-19 ", "color": "#aabbcc", "name": "datetime", "instance": "0f434cc5-6212-42ba-8381-2067e72812d4", "_raw": "09:15  \uf18c Jun(06)-19", "_suffix": " ", "_prefix": " ", "align": null}, {"full_text": " ac ac ", "color": "#aabbcc", "name": "battery", "instance": "9becab68-e5e4-4154-bb21-054f97beb491", "_raw": "ac", "_suffix": " ac ", "_prefix": " ", "align": null}, {"full_text": " us ", "color": "#aabbcc", "name": "layout-xkbswitch", "instance": "eca011a1-dbde-4234-946b-0f7fade31092", "_raw": "us", "_suffix": " ", "_prefix": " ", "align": null}, {"full_text": " audio 40% ", "color": "#aabbcc", "name": "pasink", "instance": "72b7e2a2-5e94-4426-a187-2850f45d55bc", "_raw": "40%", "_suffix": " ", "_prefix": " audio ", "align": null}]
```
which looks fine, and if do `i3 restart` everything goes back to normal. I cannot understand what is the problem and how can I avoid this problem without restarting i3

The status bar is still working and I can see if I adjust the volume, status-bar is getting updated. However, it's unclear why the traffic module remains in the failed state in the already running process.

After `i3 restart` it goes to normal again:
![image](https://user-images.githubusercontent.com/3057279/85107584-7e82a980-b20e-11ea-8c60-ecd844e9fb0a.png)

#### How to reproduce
put the computer in sleep and resume it

**Comment by tobi-wan-kenobi** [comment]
That looks like an uncaught exception to me - would you mind enabling debug mode (`-d`) and write a logfile (`-f <logfile name>`) & paste the error you get here?

Thanks!

**Comment by existme** [comment]
Thanks for the quick reply, I will do it. I realized at least it's not reproducible with a quick sleep/resume. I will put the computer to sleep for more time and get back to you when I have the logs.

**Comment by tobi-wan-kenobi** [comment]
Thanks! I assume it's either a race because the interface isn't fully available yet, or `psutil` gets thrown off if there's too large gap between measurements. Hopefully, the log will show which.

**Comment by existme** [comment]
Hi, I put the computer into sleep from:

2020-06-19 10:13 to 
2020-06-20 08:35, 

after the resume, this time bumblebee status was completely red and a message was displayed as something like "unable to read json". Unfortunately, I found nothing in the log which was relevant to what was wrong or even the error that was shown.

I will upload the log here but I am not sure if it will help.

[c-log.txt](https://github.com/tobi-wan-kenobi/bumblebee-status/files/4807469/c-log.txt)

**Comment by tobi-wan-kenobi** [comment]
Hm, that is very weird :( I'll try to put a generic workaround in place, let's hope it helps you!

**Comment by existme** [comment]
Thank you, I have pulled and will use it for a while to see if that commit helps or not. I will update the issue once I know more.

**Comment by existme** [comment]
Hi, just wanted to update the ticket after a week. The problem seems to be gone now and I haven't seen the issue again. I will close this ticket.
Thanks a lot for your quick response and the fix.

**Comment by tobi-wan-kenobi** [comment]
Glad to hear the issue is solved for you!
