### ISSUE TITLE
Icons not showing up.

### ISSUE THREAD

**Issue by mijoharas** [tobi-wan-kenobi/bumblebee-status#66]
Hi, I'm having a problem with a few of the icons not showing up. I am unable to see the icon for the `time` module and the `pasink` module. All other icons appear to have rendered correctly, and this happens with multiple different fonts. 

font-awesome is installed, and the icons render correctly when I open the json file with emacs configured to use the same font.

I tried using `pango:Inconsolata` as I saw that's what you used in another issue.

Have you got any advice on how to troubleshoot this issue?

Finally, thanks for the tool, much appreciated. 👍

**Comment by tobi-wan-kenobi** [comment]
Hi,

my first guess would have been that the particular icon is not supported by the font, as font-awesome has different versions.

Having said that, it seems that the icons in questions are part of the font since a long time, so that looks unlikely... Maybe it's some kind of weird unicode encoding issue?

Can you please try to run the command in a shell and paste the output?

For me, `time` looks like this, for example:

```
$ ./bumblebee-status -m time -t solarized-powerline
[{"color": "#002b36", "separator": false, "background": null, "full_text": "\ue0b2", "separator_block_width": 0}, {"name": "time", "full_text": " \uf017 18:46:12 ", "color": "#93a1a1", "separator_block_width": 0, "instance": "3b82d7fe-d0df-46d5-8117-3406225ecd24", "separator": false, "background": "#002b36"}],
```

**Comment by mijoharas** [comment]
I get this:
```
$ ./bumblebee-status -m time -t solarized-powerline
[{"full_text": "\ue0b2", "separator": false, "color": "#002b36", "background": null, "separator_block_width": 0}, {"full_text": " \uf017 18:49:47 ", "color": "#93a1a1", "background": "#002b36", "separator_block_width": 0, "separator": false, "instance": "4be9987b-2146-4c4e-b0ba-7f7e89dc6197", "name": "time"}],
```

**Comment by tobi-wan-kenobi** [comment]
OK, so the unicode is fine, that's something at least :-)

The more I research that on the net, the more it looks like a missing glyph from the font.

I have 2 more ideas:

1. Could you please try using the font "Awesome" or "FontAwesome" as fallback? (like described in http://stackoverflow.com/questions/32596646/font-awesome-and-i3bar):
```
bar {
    ...
    font pango:DejaVu Sans Mono, FontAwesome 8
    ...
}
```
2. Could you please tell me the distro and version you're using? I can try reproducing this on a VM and see whether something turns up.

Thanks!

**Comment by mijoharas** [comment]
Ahhh, setting the fallback font to `FontAwesome` worked. Thanks!

**Comment by ntjn** [comment]
The `ttf` font wasn't right, but the `otf` made icons to be displayed.

**Comment by mijoharas** [comment]
A note for anyone else that finds this. If you're on arch (and possibly other distros) you need to explicitly install the fontawesome 4 fonts. Available here on arch: `aur/ttf-font-awesome-4` (default is now fontawesome 5.)

**Comment by rubiin** [comment]
I was getting the same issue, the fallback fontawesome font solved it !!
Cheers

**Comment by rubiin** [comment]
> A note for anyone else that finds this. If you're on arch (and possibly other distros) you need to explicitly install the fontawesome 4 fonts. Available here on arch: `aur/ttf-font-awesome-4` (default is now fontawesome 5.)

Thanks mate helped me with the fa-4 install
