### ISSUE TITLE
Middle click to collapse not working

### ISSUE THREAD

**Issue by deadpyxel** [tobi-wan-kenobi/bumblebee-status#661]
#### Description
Affected module: All I use: (cpu, mem, nic, pacman, sensors, brightness, pasound, date, time, shutdown menu)
Version used: latest AUR

Before a recent update bumblebee-status would collapse a module I clicked and un-collapse when I middle-clicked again. 

#### How to reproduce

1. Install bumblebee-status from AUR;
2. Enable some modules;
3. Try to middle click in an element at the bar.
4. No collapsing happens.

Notes:
- The update was made yesterday (2020-06-22);
- I am using i3-gaps and latest archlinux version;
- I didn't saw any change that would result in this behaviour, unless the AUR version was really out of date.

**Comment by tobi-wan-kenobi** [comment]
Yes, this feature was accidentially dropped from 1.x -> 2.x

working on re-enabling that now, sorry for the inconvenience!

**Comment by deadpyxel** [comment]
No problem, good thing it was already reported. If there's any debug information I can provide let me know. :D

**Comment by tobi-wan-kenobi** [comment]
Hi,

@deadpyxel You were the first person noticing :)

I've fixed it now in `main`, it would be great if you could try it out! If there are no issues over the next 1-2 days, I'll go ahead and do another release, but the change is a bit too big for my liking to immediately push out 2.0.3 :)

Thanks for the report!

**Comment by deadpyxel** [comment]
I'll try to test it ASAP on my system. Thanks for the quick fix.

**Comment by deadpyxel** [comment]
I just tested latest commit on `main`. I can toggle the modules with middle click, but it's not responding that well for some (like the `nic` modules) while for others it's just like before (`pacman` module for examples). I also noticed that sometimes if I try middle click more times is making the colors for the modules get a visual glitch (they swap the colors for the modules). See the screenshot. 
![screen](https://user-images.githubusercontent.com/8644691/85424586-7e581600-b54e-11ea-963e-7f03a22dd01b.png)

So, in this case, it would swap the dark tones of solarized dark with the lighter ones and vice versa.

I yet to restart my system, so maybe it will go away, but I thought maybe it is related. This may also system related, since I don't have the greatest of machines.

**Comment by tobi-wan-kenobi** [comment]
I can reproduce the "color artifacts", and also that some modules don't play nice with it. 

Will investigate

**Comment by deadpyxel** [comment]
Alright, did some testing with different configs, for me only the `nic` elements seem to fail to collapse on middle click. Also, I am trying to reproduce the colour switch in a consistent manner. It seems to be related to multiple "collapsing" actions in sequence.

**Comment by tobi-wan-kenobi** [comment]
The `nic` (and stuff like `traffic` etc) should now be fixed. The problem was that those modules recreate their widgets during each iteration.

Still investigating the colors, thanks for the hint!

**Comment by tobi-wan-kenobi** [comment]
I think I found it: If the update of the bar because of a mouse click happens at the same time as the regular sync, the colors get mixed up.

It would be great if you could let me know whether the 2 fixes above solve your issues.

Thanks for your patience!

**Comment by deadpyxel** [comment]
Alright, I can toggle and I can't make the colours mess up. It looks to be fixed to me :D. As a side note, I don't know why, but the toggle seems to be running smoother IMO, so I guess this is a good side effect of the rewrite.

Thanks for the hard work and quick fix.
