### ISSUE TITLE
Weather unit issues

### ISSUE THREAD

**Issue by JonnyMako** [tobi-wan-kenobi/bumblebee-status#664]
Since upgrading to v2 of bumblebee-status, weather unit is having problems.

1. The location that is being automatically picked up is wrong (Is there a way to specify this?)
2. Does not respect the units setting

My bar command:
```
bumblebee-status -m cpu load sensors traffic disk memory battery date time weather -p time.format="%H:%M:%S" weather.unit="Imperial" -t gruvbox-powerline
```

**Comment by tobi-wan-kenobi** [comment]
Thanks for the bug report!

I think the unit needs to be all lowercase, if that worked with uppercase previously, that is a regression I will fix.

You can set the location manually via `weather.location` (to a city name). What is the error for you? I.e. which location is chosen vs. which should be?

**Comment by JonnyMako** [comment]
Thanks for that. Using lowercase "imperial" fixed the issue. I've also set the location now. Without location being explicitly set, I'm getting weather in Canton, OH instead of Chicago.

**Comment by tobi-wan-kenobi** [comment]
The location issue likely is because your ISPs gateway is there. Did that work better before the update?

I switched the lookup service, so maybe the new one is less accurate, in which case I'd swich back.

Thanks a lot!

**Comment by JonnyMako** [comment]
> The location issue likely is because your ISPs gateway is there. Did that work better before the update? I switched the lookup service, so maybe the new one is less accurate, in which case I'd swich back.

I didn't have any issues before v2. I think its not a big deal since I can set it manually. Thanks for the help. I'll go ahead and close this issue.

**Comment by tobi-wan-kenobi** [comment]
Glad that your issue is gone! I'll add a few improvements that hopefully address your issues, regardless.
