### ISSUE TITLE
[brightness] add back the capability of reading ACPI interface file

### ISSUE THREAD

**Issue by piyueh** [tobi-wan-kenobi/bumblebee-status#665]
### Feature Request

Commit bda153720f6380a88797d88a7c756003f9fdb3d0 removed reading backlight level through ACPI interfaces (for example, `/sys/class/backlight/intel_backlight`). And `brightness` module since then has been relying only on third-party tools. Is it possible to add that capability back to the module?

I use Sway WM, which is Wayland based, so `xbacklight` does not work for me. And I don't use other 3rd party tools either for this. I mainly rely on reading and modifying files in `/sys/class/backlight`. So it will be cool if `birghtness` module can also have an option to read brightness from ACPI files.

If it's OK, I can submit a PR.

**Comment by tobi-wan-kenobi** [comment]
Yes, of course. And a PR would be much appreciated, otherwise, I'll try to have a look into this during the next weekend.

Thanks!
