### ISSUE TITLE
[theming] Cannot disable separators on latest release

### ISSUE THREAD

**Issue by gkeep** [tobi-wan-kenobi/bumblebee-status#666]
### Bug Report
Version: 2.0.4-1 (AUR)
#### Description

You can no longer disable separators and use padding in themes.

**Relevant theme.json lines**
These two lines disable separators and create padding around modules.
```json
"separator-block-width": 5,
"separator": "",
```
Which looks like this (taken on a commit shortly after 1.10.4 release):
![image](https://user-images.githubusercontent.com/20600053/85953126-efe0fb80-b976-11ea-9890-d722cad663dc.png)

And how it looks on the latest release (should look like the screenshot above):
![image](https://user-images.githubusercontent.com/20600053/85953176-261e7b00-b977-11ea-915d-ba941c27f24f.png)

<details>
    <summary>Relevant i3 config lines</summary>

    status_command bumblebee-status \
                -m caffeine nic pasink redshift time date \
                -p time.format="%H:%M" date.format="%A, %B %d" \
                -t iceberg-dark

</details>

<details>
    <summary>Full theme file</summary>

```json
{
    "icons": [ "awesome-fonts" ],
    "defaults": {
        "separator-block-width": 5,
        "separator": "",
        "warning": {
            "fg": "#0f1117",
            "bg": "#e2a478"
        },
        "critical": {
            "fg": "#0f1117",
            "bg": "#e27878"
        }
    },
    "cycle": [
        { "fg": "#d2d4de", "bg": "#161821" },
        { "fg": "#d2d4de", "bg": "#262939" },
        { "fg": "#d2d4de", "bg": "#353a50" },
        { "fg": "#d2d4de", "bg": "#454b68" },
        { "fg": "#d2d4de", "bg": "#353a50" },
        { "fg": "#d2d4de", "bg": "#262939" },
        { "fg": "#d2d4de", "bg": "#1e212d" }
    ],
    "dnf": {
        "good": {
            "fg": "#b4be82",
            "bg": "#161821"
        }
    },
    "apt": {
        "good": {
            "fg": "#b4be82",
            "bg": "#161821"
        }
    },
    "pacman": {
        "good": {
            "fg": "#b4be82",
            "bg": "#161821"
        }
    },
    "battery": {
        "charged": {
            "fg": "#0f1117",
            "bg": "#b4be82"
        },
        "charging": {
            "fg": "#0f1117",
            "bg": "#84a0c6"
        }
    }
}

```

</details>

**Comment by tobi-wan-kenobi** [comment]
Ah. I think that slipped in with #648 , thanks for the notification.

Will come up with a better solution.

**Comment by tobi-wan-kenobi** [comment]
Please let me know whether this fixes your issue (latest commit in "main"). If so, I'll draft a new release in the next couple of days.Please let me know whether this fixes your issue (latest commit in "main"). If so, I'll draft a new release in the next couple of days.

Thanks a lot!

**Comment by tobi-wan-kenobi** [comment]
Darn, that actually broke other themes :( Sorry, I have to revert and think about it some more.

**Comment by gkeep** [comment]
It is definetly a progress, but not quite there yet.

![image](https://user-images.githubusercontent.com/20600053/85954901-80bdd400-b983-11ea-8609-39bdde93e079.png)

**Comment by tobi-wan-kenobi** [comment]
@gkeep I hope I got it correctly this time :) At least on my machine, your theme looks good now, and also the gruvbox-powerline theme still works :)

**Comment by gkeep** [comment]
Looks good, thank you :+1:

**Comment by tobi-wan-kenobi** [comment]
Great to hear!
