### ISSUE TITLE
[modules/spotify] Action spamming on click

### ISSUE THREAD

**Issue by gkeep** [tobi-wan-kenobi/bumblebee-status#668]
#### Description
Affected module: contrib/spotify
Version used: 2.0.4-1

> Something a little strange (this might even be isolated to my machine), but since I overwrote the original spotify with the new version, most clicks on a button seem to register many times (for example skipping the entire playlist instead of one song, or playing and pausing super fast until the music just sounds like static) and it even blocks playing and pausing on the spotify window itself. I don't know what would cause this though (or how to fix it), and in case it's not isolated, I just wanted to let you know.

https://github.com/tobi-wan-kenobi/bumblebee-status/pull/663#issuecomment-649737159

Reproducible, created an issue for easier tracking.

**Comment by tobi-wan-kenobi** [comment]
@gkeep @LtPeriwinkle I'd appreciate it a lot if you could let me know whether this fixes the issue for you.

If yes, I'll get another release out asap.

Thanks for the report!

**Comment by gkeep** [comment]
Still happens on my machine :( @tobi-wan-kenobi

**Comment by gkeep** [comment]
@tobi-wan-kenobi Hmm... Actually works great, guess I spoke too soon.

**Comment by tobi-wan-kenobi** [comment]
Thanks a lot for the feedback!
