### ISSUE TITLE
Read theme & modules from the config file

### ISSUE THREAD

**Issue by fenilgandhi** [tobi-wan-kenobi/bumblebee-status#678]
### Feature Request

Currently the config file only supports configuring individual moduiles for bumblebee-status
But i wanted to also specify my theme & list of modiules , right into the config file. I tried searching for a way to do it but couldn't find any. Having these values in a default config file, saves the effort of maintaining consistency if the user invokes the "bumblebee-status" from different application scripts.

**Comment by fenilgandhi** [comment]
@tobi-wan-kenobi : I could not find any developer documentation for contributing to the project itself. Can you atleast specify  the minimal things how to generate a build

**Comment by tobi-wan-kenobi** [comment]
That's a nice FRQ, thanks!

OK, so that is true, I didn't document that. You don't need a build, just check out the git and run bumblebee-status :)

**Comment by adgai19** [comment]
> ### Feature Request
> Currently the config file only supports configuring individual moduiles for bumblebee-status
> But i wanted to also specify my theme & list of modiules , right into the config file. I tried searching for a way to do it but couldn't find any. Having these values in a default config file, saves the effort of maintaining consistency if the user invokes the "bumblebee-status" from different application scripts.

Can someone add some documentation for this?? I am really excited for this feature.

**Comment by tobi-wan-kenobi** [comment]
should be in the "Features" section now
