### ISSUE TITLE
Multiple shell module do not work (all shows the same command)

### ISSUE THREAD

**Issue by leminhman0312** [tobi-wan-kenobi/bumblebee-status#685]
#### Description
Affected module: shell
Version used: AUR

<description>
If I use more than 1 shell to  show different terminal outputs on the status bar, then only 1 command is shown, the other shell module also prints the exact command.
For example, if I have 2 commands: `wakatime --today` and `uptime -p` to show 2 different things, then my config within i3 will look like this:

```
bar {
       status_command /usr/bin/bumblebee-status -m shell shell -p shell.command='wakatime --today` shell.command=`uptime -p`
}

```

Upon refreshing, only the second shell command is read and printed to the bar.  In other words, I only get the output of `uptime -p` printed twice.  Is there a way to differentiate between multiple shell commands?

**Comment by nayaverdier** [comment]
You should be able to parameterize with an alias:

```
bumblebee-status -m shell:wakatime shell:uptime -p wakatime.command="wakatime --today" uptime.command="uptime -p"
```

**Comment by leminhman0312** [comment]
Thanks @nayaverdier , this solves my problem.  Close the topic
