### ISSUE TITLE
DNF Module shows wrong counts

### ISSUE THREAD

**Issue by Yali0n** [tobi-wan-kenobi/bumblebee-status#697]
#### Description
Affected module: dnf
Version used: latest

DNF get wrong counts

#### How to reproduce
src/bumblebee-status/bumblebee-status -m dnf
{"version": 1, "click_events": true}
[
[{"full_text": " dnf 0/0/0/0 ", "color": "#aabbcc", "name": "dnf", "instance": "df949941-0127-45a7-8a21-089fdd93eb56", "_raw": "0/0/0/0", "_suffix": " ", "_prefix": " dnf ", "align": null}],
[{"full_text": " dnf 0/0/0/0 ", "color": "#aabbcc", "name": "dnf", "instance": "df949941-0127-45a7-8a21-089fdd93eb56", "_raw": "0/0/0/0", "_suffix": " ", "_prefix": " dnf ", "align": null}],
[{"full_text": " dnf 0/0/0/0 ", "color": "#aabbcc", "name": "dnf", "instance": "df949941-0127-45a7-8a21-089fdd93eb56", "_raw": "0/0/0/0", "_suffix": " ", "_prefix": " dnf ", "align": null}],
[{"full_text": " dnf 4/7/1/1 ", "color": "#aabbcc", "name": "dnf", "instance": "df949941-0127-45a7-8a21-089fdd93eb56", "_raw": "4/7/1/1", "_suffix": " ", "_prefix": " dnf ", "align": null}],
[{"full_text": " dnf 4/7/1/1 ", "color": "#aabbcc", "name": "dnf", "instance": "df949941-0127-45a7-8a21-089fdd93eb56", "_raw": "4/7/1/1", "_suffix": " ", "_prefix": " dnf ", "align": null}],

while no updates open

**Comment by Yali0n** [comment]
Seems the updateinfo has informations about updates before they are available for installation.
So no issue at all

**Comment by tobi-wan-kenobi** [comment]
Interesting to know, thanks for reporting!
