### ISSUE TITLE
pulseaudio bug

### ISSUE THREAD

**Issue by ternaus** [tobi-wan-kenobi/bumblebee-status#708]
#### Description
Affected module: pulseaudio
Version used: latest git

When I add pulseaudio to the list of modules I get an error:
```
__init__() missing 1 required positional argument: 'channel'
```

**Comment by tobi-wan-kenobi** [comment]
The module "pulseaudio" is a meta module not intended for direct use, could you please try to use "pasink" or "pasource" instead?

The latest git shouldn't even *have* that module, is it possible the .pyc is a leftover from a previous update?
