### ISSUE TITLE
Document min length and max length

### ISSUE THREAD

**Issue by martindoublem** [tobi-wan-kenobi/bumblebee-status#710]
Hi Tobi,

A while ago we discussed this issue (min length and max lengths for modules) in the feature requests and I know something was added to this purpose. Would it be possible to add something with regards to this in the documentation?

While building a new setup with I3, I could not find this being documented anywhere.

Thanks!

**Comment by tobi-wan-kenobi** [comment]
Yes, very good point!

Will try to do so soon, unfortunately, it is quite a busy time right now, apologies forvtaking longer than usual.

**Comment by tobi-wan-kenobi** [comment]
https://bumblebee-status.readthedocs.io/en/main/features.html#additional-widget-theme-settings has the minwidth, I will add width there. Does that sound OK to you?

**Comment by martindoublem** [comment]
Seems good to me for the minwidth. Was there a maxwidth setting too? If so, it would be good to mention as well, don't you think?

**Comment by tobi-wan-kenobi** [comment]
No, there's not. *BUT* there is the whole scrolling which I did not document, which I will add presently.

@martindoublem Do I understand correctly that the ticket can be closed now?
