### ISSUE TITLE
Modules names with hyphens (-)

### ISSUE THREAD

**Issue by izn** [tobi-wan-kenobi/bumblebee-status#713]
Hey, ya.

Should we rename the modules below to match the [Python Naming Conventions](https://www.python.org/dev/peps/pep-0008/#package-and-module-names)?

```sh
modules/core/layout-xkb.py
modules/contrib/layout-xkbswitch.py
modules/contrib/arch-update.py
modules/contrib/battery-upower.py
```

These modules work as expected (I think) in the status bar, but I can't import these modules into a test file using `import`.

```sh
E       import modules.contrib.arch-update
E                                  ^
E       SyntaxError: invalid syntax
```

Any ideas?

**Comment by tobi-wan-kenobi** [comment]
Maybe a symlink, so that both names work?
I would like to keep the current naming, as an option, at least, because of backwards compatibility, mostly.

**Comment by izn** [comment]
Indeed. I will open a PR later creating the symlinks.

Also I believe we could add a section into the docs with the recommended module naming convention. WDYT?

**Comment by tobi-wan-kenobi** [comment]
Sounds good to me, many thanks!
