### ISSUE TITLE
Question regarding fonts

### ISSUE THREAD

**Issue by andrewschott** [tobi-wan-kenobi/bumblebee-status#715]
I have the bar working find and all.  However I had an issue with the "connector" arrow from I believe FontAwesome not showing up.  After screwing around I found that if I changed my font, that corrected things.  

So, here's the question  -- is there a trick to figuring out what fonts are compatible?  I have been going thru my fonts, and out of what feels like a thousand fonts, only a very small number actually work.

Or am I being a moron in my bar config?

Thanks!
Andrew.

**Comment by tobi-wan-kenobi** [comment]
Yeah, unfortunately, font config is always a bit finnicky...

There's a set of "<xyz> for Powerline" fonts that include the connector (https://github.com/powerline/fonts), those should all work.

What also should do the trick is adding thr Awesome font as fallback font (second font in the font list) in the i3 config. That, however, only works if the main font does not define the glyph in question at all.

Hope that helps!

**Comment by andrewschott** [comment]
Thanks, I did play around with what was listed there.  But some work, others do not.  Oh well, thanks anyhow for your help.
