### ISSUE TITLE
Hacktoberfest Opt-in?

### ISSUE THREAD

**Issue by joshbarrass** [tobi-wan-kenobi/bumblebee-status#719]
This project is one that I am reasonably familiar with and enjoy contributing to because it is written in a language I love and is a project I actively use every day. Hacktoberfest last year gave me the encouragement I needed to get some PRs I had planned and thought were useful, but didn't have the time to implement most of the year round, out of the door, and the same is true this year. However, DigitalOcean has taken the stance this year to [require maintainers to opt-into Hacktoberfest](https://github.com/digitalocean/hacktoberfest/pull/596) in an attempt to combat spam. Is this something you would be willing to do for this project?

**Comment by tobi-wan-kenobi** [comment]
Yes, absolutely! I am glad somebody finds the project useful enough for something like that :-)

Do you have a link or something, to let me know what I need to do? TBH, I did not know about Hacktober until now :P

Thanks a lot for the message!

**Comment by izn** [comment]
Excellent idea! ✨ 

We must add the `hacktoberfest` to the repository topics. 🚀 

Reference [here](https://hacktoberfest.digitalocean.com/hacktoberfest-update).

```
PRs count if:
Submitted in a repo with the hacktoberfest topic AND
during the month of October AND (
  The PR is merged OR
  The PR is labelled as hacktoberfest-accepted by a maintainer OR
  The PR has been approved
)
```

**Comment by tobi-wan-kenobi** [comment]
should be done, thanks for letting me know!

also, *thrilled* that two people care about that :) thanks!
