### ISSUE TITLE
[themes] No separator icon in fontawesome 

### ISSUE THREAD

**Issue by benschme** [tobi-wan-kenobi/bumblebee-status#72]
The separator icon that's used in awesome-fonts.json doesn't exist anymore in the newer version of fontawesome

**Comment by tobi-wan-kenobi** [comment]
Actually, this particular icon was never part of fontawesome. There's no suitable left-pointed triangle for a powerline-theme in the font, so I used the left-pointed arrow from the powerline set instead (U+E0B2 from the private area, see https://apw-bash-settings.readthedocs.io/en/latest/fontpatching.html "glyph table").

So essentially, it's "works as intended", **but** it should be documented, many thanks for pointing that out!
