### ISSUE TITLE
Help with getting this working with sway

### ISSUE THREAD

**Issue by andrewschott** [tobi-wan-kenobi/bumblebee-status#724]
If I use the status bar config block below, I just get the bar (which does show up) with in the right corner "[error reading from status command]".  This works perfectly in i3.  What am I missing here?  I couldn't locate anything of clear use in the sway docs.  

And of course there is the obvious cause -- brain damage.

My bar section (slightly redacted):
```
bar {
  status_command bumblebee-status \
            -m sensors2 spacer load spacer memory \
                 spacer pasink pasource spacer spacer weather \
                 spacer indicator spacer time system \
            -p weather.location=redact,ed weather.showcity=true \
                weather.unit=imperial \
                weather.apikey=redacted \
            sensors2.chip_field_include=coretemp-isa-0000.temp1,amdgpu-pci-0100.temp1 \
            time.format="%d %b %Y - %I:%M:%S %P" \
            indicator.include=capslock,numlock,scrolllock \
            -t dracula-powerline
  
  position top
  
  font pango: Liberation Mono Bold 9
}
```

Thanks much!
Andrew.

**Comment by tobi-wan-kenobi** [comment]
Could you please post the output of running the commanf in a shell?

Also, having the debug log (--debug) would be a big help.

Thanks a lot in advance!

**Comment by andrewschott** [comment]
OK, as I am not sure what I should be looking for so bear with me if I misunderstood.  I have the debug one (bumblebee-status --debug --the-rest-of-my-bar-stuff > file.log).  Let me know if you want/need more.

Thank you so much,
Andrew!

[bb-status-debug.txt](https://github.com/tobi-wan-kenobi/bumblebee-status/files/5367253/bb-status-debug.txt)

**Comment by gkeep** [comment]
I think it's something in your settings for one of the modules.

In the screenshot below I removed all your settings (
```i3
sensors2.chip_field_include=coretemp-isa-0000.temp1,amdgpu-pci-0100.temp1 \
time.format="%d %b %Y - %I:%M:%S %P" \
indicator.include=capslock,numlock,scrolllock \
```
) and bumblebee-status launched just fine.
![image](https://user-images.githubusercontent.com/20600053/95850083-f42ff980-0d58-11eb-8f57-cba7eab713ee.png)

**Comment by andrewschott** [comment]
An empty bar also fails.  I figured it had to be the modules -- one of them not liking something.  One by one -- still fails at zero modules.

I have to ask -- am I Invoking it correctly?

**Comment by gkeep** [comment]
From everything I've seen it *should* work. 

Can you drop your full sway config on something like [hastebin](https://hasteb.in)?

**Comment by andrewschott** [comment]
Sure thing, once I get home from work.

**Comment by andrewschott** [comment]
My ~/.config/sway/config:

https://hasteb.in/azozazec.pl

**Comment by gkeep** [comment]
Hmm... Works just fine on my machine. 

I'm guessing this is either an installation issue or an environment issue.

Can you tell how did you install bumblebee-status (git, AUR, PyPI)? And what Python version do you have installed?

**Comment by andrewschott** [comment]
Your comment made me try something -- the full damn path to the bb-status binary.  That fixed things.

And for the record, pip userinstall.

Must be a sway thing that wants the full path for this.  Noticed while tinkering around, a few things that are just ... different.  That said, thanks so much for putting up with this nonsense with me!

Must say, I am impressed with how well things are going with sway now that I can toy around and get stuff finished up.
