### ISSUE TITLE
XResources theme

### ISSUE THREAD

**Issue by Aliuakbar** [tobi-wan-kenobi/bumblebee-status#731]
### Feature Request
Read a colorscheme from .Xresources

**Comment by Aliuakbar** [comment]
I have an ugly solution with subprocess calls to xgetres.
Some git stuff got messed so I don't have a PR ready...

**Comment by tobi-wan-kenobi** [comment]
@Aliuakbar sounds like a good approach to me, given that this happens only once during startup, and i did not find any widely used xresource parser in python.

if you can create a diff and attach it to the issue, i can have a look at it, if pr does not work for you.

thanks!

**Comment by Aliuakbar** [comment]
[https://gist.github.com/Aliuakbar/3deff9cbaabeb7128983ece5ae6100dd](https://gist.github.com/Aliuakbar/3deff9cbaabeb7128983ece5ae6100dd)
