### ISSUE TITLE
Linux wireless tools are a dependency of the nic module when using iwgetid

### ISSUE THREAD

**Issue by cdbrkfxrpt** [tobi-wan-kenobi/bumblebee-status#734]
This isn't really a bug that makes anything not run, just a request to document (unless already changed).

#### The Request
On the `main` branch, [the `nic` module uses `iw`](https://github.com/tobi-wan-kenobi/bumblebee-status/blob/0fc1782e0b751bdfffc829e1533df1e8d122c1f2/bumblebee_status/modules/core/nic.py#L51). However in the version packaged in pip, `iwgetid` is used instead. `iwgetid` is a component of Linux wireless tools, which isn't installed by default on some distros (e.g. Void Linux).

Perhaps the pip package needs updating, or the docs need to specify this dependency. It's not a straight forward to find issue.

Thanks for the though, great job! I'm really enjoying bumblebee-status!

**Comment by tobi-wan-kenobi** [comment]
Oh, that is a good catch! I think the core problem is that PIP has only released versions, and the readthedocs page only shows main.

I will try to add doc builds for the released versions.

Thanks for noticing!

Also, I will try to push out another release soon-ish :(

Glad you enjoy bumblebee-status!

**Comment by tobi-wan-kenobi** [comment]
Documentation for version 2.0.5 should be building now :)

Will keep the ticket open until I was able to verify that this fixes the issue.

**Comment by tobi-wan-kenobi** [comment]
Unfortunately not, it was wrong in the 2.0.5 documentation, as well :(

I will add a note to the current documentation, but fixing 2.0.5 probably is not worth it, as readthedocs defaults to the "latest" (main) doc, and a lot of people probably will not switch.
