### ISSUE TITLE
nm-applet with the nic module

### ISSUE THREAD

**Issue by MarcoPasta** [tobi-wan-kenobi/bumblebee-status#735]
### Feature Request
Hey, so simply - is it possible to include a feature that opens a nm-applet like menubar when you rightclick on the nic module? Because everytime i need to add a new network or vpn i need to change the i3 config to enable system trays, then add the things and remove the tray again... 
Because of space i only use a few modules and the nic just shows if i have wifi signal or not - no name or ip etc. but it would be neat if there was a little network-manager inside it (or it could just open the connection editor)! :)

**Comment by tobi-wan-kenobi** [comment]
Opening the connection editor on click is easy - every module has a "left-click" and "right-click" module that takes a command as parameter (that is then executed on click).

Adding a menu directly is possible (see vpn module for example), but cumbersome and would also make the nic module tightly integrated with NetworkManager, for example.

For that reason, I would suggest #1if that is fine with you.

If you are hiding the menu by default, there is a module called "spacer" that is empty by default (but has a configurable text) that also has the "left-click" parameter and can be used as simple "launcher".

Hope that helps!
