### ISSUE TITLE
bumblebee-status display greyed out

### ISSUE THREAD

**Issue by dboneham** [tobi-wan-kenobi/bumblebee-status#737]
#### Description
Affected module: all modules used
Version used: latest aur

the status bar arrows are greyed out. I think this is just a display issue. I think the underlying modules are loaded (you just cannot see them). My strong suspicion is that this was a cosequence of running (for the first and last time!) an electron utiliity called Stacer. Amongst other things, it seemed to delete various files in ~/.cache - which has caused other problems.

I installed bumblebee-status from the AUR. Obv I am an arch user. I have tried installing from pip and from git. Neiter of these cured the problem. I am a long term bumblebee-status user.

Screenshot attached.
![Screenshot_2020-11-25_14-15-54](https://user-images.githubusercontent.com/25729774/100239585-7b13ec80-2f29-11eb-8a51-5bfcc1a11d95.png)

#### How to reproduce
Not really sure, but I suspect (as above) it has to do with Stacer deleting files, possibly in ~/.cache/

Thanks fo any help with this

**Comment by tobi-wan-kenobi** [comment]
huh, that looks strange.

can you please execute the same cmd you have in your i3 config on the cli and particularly note the values for "color" and "background"?

those determine the colors i3 *should* show.

bumblebee-status isn't using any temp files, so unless the tool deleted oarts of bumblebee-status, you should be good.

also, trying to switch themes might give us clues.

sorry that you have issues and thanks for being a long term user :)

**Comment by dboneham** [comment]
Extracts from my i3 config: -

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango: FuraMono Nerd Font Mono,fontawesome-webfont,fontello 10

# Colour scheme
set_from_resource $fg i3wm.color15 #f0f0f0
set_from_resource $bg i3wm.color0 #f0f0f0
set_from_resource $ws1 i3wm.color4 #f0f0f0
set_from_resource $ws2 i3wm.color9 #f0f0f0

# class                 border  backgr. text indicator child_border
client.focused          $bg     $bg     $fg  $bg       $bg
client.focused_inactive $bg     $bg     $fg  $bg       $bg
client.unfocused        $bg     $bg     $fg  $bg       $bg
client.urgent           $bg     $bg     $fg  $bg       $bg
client.placeholder      $bg     $bg     $fg  $bg       $bg

client.background       $bg

# bar
bar {
   font pango:Inconsolata 10
    position top
    tray_output primary
#    mode hide
#    status_command /usr/bin/bumblebee-status -m pasink nic brightness pacman  caffeine time date -p brightness.use_acpi="True" interval=2.5 time.format="%H:%M" date.format="%a, %b %d %Y" nic.states="^down" pacman.sum="True" -t wal-powerline
     status_command /usr/bin/i3status

For the life of me, I cannot now remember what the "set_from_resource" statement refers to. I have a sneaking feeling th\t this hs something to do with pywal, which I used to use but now don't.

**Comment by dboneham** [comment]
In fact I note that my bar command refers to wal-powerline. And I do recall that one of the files that Stacer wiped from my .cache directory was wal/sequences or something like. Maybe that was doing something.

**Comment by tobi-wan-kenobi** [comment]
yes, that is likely. probably regenerating the wal scheme helps. fingers crossed!

**Comment by dboneham** [comment]
Yes that worked! Ran pywal, which regenerated the wal/sequences file in ~/.cache. Bumblebee-status then could apply the wal-powerline theme. All good in time to watch the Liverpool/Atalanta game.
