### ISSUE TITLE
[module/gpmdp] The module does not use unicode, this causes the whole bar to crash when the song with non-latin symbols is playing

### ISSUE THREAD

**Issue by graynk** [tobi-wan-kenobi/bumblebee-status#74]
The title, basically. This is a fairly common mistake, the python 3 uses unicode in strings by default, AFAIK, but in python 2 the developer has to specify the encoding and use string.encode()/string.decode()
Here's how the bug looks.
![2017-04-24-213110_824x166_scrot](https://cloud.githubusercontent.com/assets/3626328/25347806/8a00e1ce-2935-11e7-8f3f-3fb25a5cf09f.png)
This is a fairly simple fix, but I am not really sure how to make pull request, sorry.
![2017-04-24-215622_591x167_scrot](https://cloud.githubusercontent.com/assets/3626328/25348806/eb8c637a-2938-11e7-8209-11644467fde4.png)

**Comment by tobi-wan-kenobi** [comment]
Hi,

thanks for the bug report and the PR!

I've had a look at the issue, and I think ea7227d provides a clean and all-compassing solution for all modules. As part of that, I also reverted your PR changes, as they **should** not be required any more.

If this commit breaks things for you (at least cmus works fine now), please tell me and I will have another go :)

**Comment by graynk** [comment]
Yes, that does seem to work now, cheers!
