### ISSUE TITLE
Module Python dependency errors

### ISSUE THREAD

**Issue by jayvdb** [tobi-wan-kenobi/bumblebee-status#741]
Looking at master, preparing for packaging of the next release, I notice that there are a few dependencies which appear odd.

`requirements/modules/dunst.txt:dunst`

`dunst` does not exist: https://pypi.org/search/?q=dunst .  And dunst isnt being imported by the status module.

`requirements/modules/hddtemp.txt:hddtemp`

https://pypi.org/project/hddtemp/ exists, but it is not being imported by the status module.  It looks like that package has useful code, but I couldnt find where the source is located, and it doesnt have tests in its PyPI sdist, so I wouldnt recommended using that package until the author has published a repository of the code, so that tests can be added, and bugs can be reported.

`requirements/modules/spaceapi.txt:json`
`requirements/modules/spaceapi.txt:time`

`time` and `json` are part of stdlib, so shouldnt be an external requirement.
c.f. https://docs.python.org/2/library/time.html

Installing https://pypi.org/project/time/ may break the Python stdlib if it installs a module called `time`.

`requirements/modules/yubikey.txt:yubico`

https://pypi.org/project/yubico/ is old.  https://pypi.org/project/python-yubico/ (https://github.com/Yubico/python-yubico) is probably the correct dependency.

**Comment by jayvdb** [comment]
Also zpool imports pkg_resources, which means it depends on `setuptools`

**Comment by jayvdb** [comment]
octoprint says it depends on tkinter , but that is part of stdlib.  The usual way to declare that dependency is to depend on `Pillow`.

Undeclared dependencies:
- currency has an optional dependency on Babel.
- battery has an optional dependency on power.
- libvirtvms depends on libvirt
- octoprint depends on simplejson - very likely this could be just `json` which is stdlib, or at least it could fallback to `json` if simplejson does not exist.

**Comment by jayvdb** [comment]
https://bumblebee-status.readthedocs.io/en/main/modules.html#deadbeef mentions 'subprocess', but that is stdlib

https://bumblebee-status.readthedocs.io/en/main/modules.html#spaceapi mentions `regex`, but I can not see `regex` being imported.

**Comment by tobi-wan-kenobi** [comment]
Thanks a ton! I will look into all of those!

One small note: The main development/release line is "main", I keep master around only for backwards compat and it is not always up to date.

Thanks!

**Comment by jayvdb** [comment]
All of the above applies to `main` as well.

I am happy to do the necessary updates here.  I think I know the process better now after my last failed attempt at helping.

**Comment by tobi-wan-kenobi** [comment]
That would be much appreciated, indeed!

Otherwise, I can have a look tomorrow.

Thank you very much!

**Comment by tobi-wan-kenobi** [comment]
hope this looks better now, thanks again!
