### ISSUE TITLE
pulseaudio: error: pactl info exited with code 1

### ISSUE THREAD

**Issue by jayvdb** [tobi-wan-kenobi/bumblebee-status#746]
#### Description
Affected module: <pulseaudio
Version used: 2.0.5

<description>

#### How to reproduce
I ran `startx` as a normal user (rather than the usual boot straight into X), and my two pulseaudio modules both show this error message instead of the small picture they usually provide.

I know why the error is happening, but many users may not be able to guess what the cause is.  The error tells me nothing except an error code number, and it takes a aweful lot of screen real-estate to do that, _twice_.  In my case I dont want to fix it, because doing so is a waste of time and would likely disturb my normal environment.

It would be nice if there was a less intrusive way of reporting the failure, including possibly the error code, and ideally even grouping all failed modules together into a unified failure info block.

Alternatively an "ignore all failing modules" or "allow failure module list" could be a way of the user choosing to auto-remove modules if they fail, rather than see the failure message in the bar itself.  The typical user of bumblebee-status is likely preferring to be reading a log file to identify the problem.

**Comment by tobi-wan-kenobi** [comment]
Hm, there *are* ways to display errors in a different widget (the `error` widget). However, you need to explicitly add that to the list of modules, or you would not see the error at all. Generally, that concept would need some extending to be useful for multiple modules (right now, it only shows the last error received).

Having said that, I like your idea of "list of silently failing modules" a lot, especially for things that will recover over time.

I will think about ways to achieve this and keep this ticket open, but please do not expect activity very soon, this is something that requires planning and thinking (and time, which I unfortunately don't have a lot of, right now)

Thank you very much for your input!
