### ISSUE TITLE
running bumblebee-status -m cpu results in referencing contrib instead of core

### ISSUE THREAD

**Issue by marijnmur** [tobi-wan-kenobi/bumblebee-status#747]
#### Description
Affected module: core/psutil and core/cpu
Version used: <e.g. latest git, AUR, PIP>

<description>

#### How to reproduce
clone the repo  and run ./bumblebee-status -m cpu

I get the following error: 

` CRITICAL failed to import cpu: No module named 'modules.contrib.cpu'`
~~if you then copy the cpu.py file from core/ to contrib/  I get this error:~~
~~CRITICAL failed to import cpu: No module named 'psutil'~~

~~Seems like the psutil is missing completely at the moment in the main branch. I would expect cpu to work since it is in the core modules.~~

**Comment by tobi-wan-kenobi** [comment]
Can you please try zo install the python module "psutil"?

This is a standard python module that is not part of the PSL, unfortunately.

**Comment by marijnmur** [comment]
yeah, sorry have that one fixed. my bad
But the reference to contrib is still there. while the cpu.py module lives in core.

**Comment by marijnmur** [comment]
works after you copy cpu.py from core to contrib. so is some ref somewhere.

**Comment by tobi-wan-kenobi** [comment]
The reference is actually "just" an unclear error message. Loading the cpu module from core fails (because of the missing psutil), so it tries to find a working cpu module in contrib as fallback, but since there is none at all, the resulting error message is confusing :(

**Comment by marijnmur** [comment]
ah. indeed. thanks
Can close this issue, or do you want to make a better error message?

**Comment by tobi-wan-kenobi** [comment]
please keep it open, I will try to improve this behaviour.

**Comment by marijnmur** [comment]
Cool. Thanks.
Really like your work!

**Comment by brccabral** [comment]
Hi, I've just had the same problem. Can you set `psutil` as dependency of `bumblebee-status`, this way, when we `pip install --user bumblebee-status` it would install `psutil` too... Thanks
