### ISSUE TITLE
Pulseaudio error

### ISSUE THREAD

**Issue by CatinPajama** [tobi-wan-kenobi/bumblebee-status#748]
### Bug Report
Pulseaudio module giving errors
#### Description
Affected module:Pulseaudio
Version used: latest git

<description>
Error : __init__() missing 1 required positional argument: 'channel'
#### How to reproduce

Cloning the repo and adding pulseaudio module in i3-gaps

**Comment by tobi-wan-kenobi** [comment]
Hello,

the "pulseaudio" module is not meant for direct usage, please use"pasource" or "pasink" instead.

Sorry that the documentation is not clear on that.
