### ISSUE TITLE
timetz doesn't work

### ISSUE THREAD

**Issue by davisi3** [tobi-wan-kenobi/bumblebee-status#749]
#### Description
Affected module: <timetz>
Version used: <latest git>

Hi! timetz module doesn't work. "timetz: No module named 'pytz'
Same error shows up also with parameter added.

 Here is screenshot https://0x0.st/iFVe.png

**Comment by davisi3** [comment]
https://0x0.st/iFVe.png
screenshot

**Comment by tobi-wan-kenobi** [comment]
pytz is not part of the Python Standard Library, and you need to install it via your package manager or via pip.

Hope this helps!

**Comment by davisi3** [comment]
Oh, yes. I don't have pytz. Thanks!

otrd., 2020. g. 15. dec., plkst. 23:07 — lietotājs tobi-wan-kenobi (<
notifications@github.com>) rakstīja:
