### ISSUE TITLE
Is it possible to run spotifyd with bumblebee-status ?

### ISSUE THREAD

**Issue by davisi3** [tobi-wan-kenobi/bumblebee-status#750]
Hello! 
How would I make status bar to read spotifyd? That would be so awesome!

**Comment by tobi-wan-kenobi** [comment]
There is a user-contributed module "spotify", does that work for you?

**Comment by davisi3** [comment]
It doesn't work. That's why I asked about spotifyd. It's to use
spotify-tui. That's not standard way of listening to spotify.
Seems like spotify.py should be edited to read from spotifyd but I'm not
sure how to do that.

otrd., 2020. g. 15. dec., plkst. 23:07 — lietotājs tobi-wan-kenobi (<
notifications@github.com>) rakstīja:

**Comment by tobi-wan-kenobi** [comment]
I see. Well, that depends a lot on whether spotifyd has a Python client library or some kind of documented interface.

And then, as you say, it is a matter of extending the spotify module to support this approach.

I will keep this ticket open and mark it as help wanted, maybe somebody wanta to take ownership of it.

Many thanks for the suggestion!

**Comment by davisi3** [comment]
Thanks for your fast reply!

otrd., 2020. g. 15. dec., plkst. 23:12 — lietotājs tobi-wan-kenobi (<
notifications@github.com>) rakstīja:

**Comment by gkeep** [comment]
Per [spotifyd's readme](https://github.com/Spotifyd/spotifyd#media-controls):

 > Media controls
Spotifyd implements the MPRIS D-Bus Interface Specification, meaning that it can be controlled by generic media playback controllers such as *playerctl* as well as some tools specifically designed for use with the official Spotify client such as sp.

Try using the `playerctl` module and see if that works.

**Comment by davisi3** [comment]
playerctl shows up in menu. It doesn't read spotifyd activity though.

piektd., 2020. g. 18. dec., plkst. 08:48 — lietotājs Gennady Koshkin (<
notifications@github.com>) rakstīja:

**Comment by gkeep** [comment]
That's weird. I'll take a look at it later today.

**Comment by gkeep** [comment]
Working fine for me...

![image](https://user-images.githubusercontent.com/20600053/102596759-b2417c00-412a-11eb-8790-5a0abd6a8dd8.png)

Make sure you install spotifyd with all features ([spotifyd-full-git](https://aur.archlinux.org/packages/spotifyd-full-git/) for AUR)

**Comment by davisi3** [comment]
Hm. It could be that spotifyd I got is lacking something. I used spotifyd
from repo (voidlinux). I will check with community.

piektd., 2020. g. 18. dec., plkst. 11:21 — lietotājs Gennady Koshkin (<
notifications@github.com>) rakstīja:

**Comment by gkeep** [comment]
Huh, after further testing it appears that playerctl does not always catch the metadata. I'm trying to make spotifyd compatible with the `spotify` module...

**Comment by davisi3** [comment]
huh.. Ok, let me know how things are going.

piektd., 2020. g. 18. dec., plkst. 12:00 — lietotājs Gennady Koshkin (<
notifications@github.com>) rakstīja:

**Comment by gkeep** [comment]
Hey, I think I got it working, will make a PR shortly!

**Comment by davisi3** [comment]
oh, great!

piektd., 2020. g. 18. dec., plkst. 12:10 — lietotājs Gennady Koshkin (<
notifications@github.com>) rakstīja:

**Comment by davisi3** [comment]
playerctl doesn' show artist. Only song name.

piektd., 2020. g. 18. dec., plkst. 13:50 — lietotājs tobi-wan-kenobi (<
notifications@github.com>) rakstīja:

**Comment by gkeep** [comment]
Yes, that was one of the reasons why I decided to work on 'spotify' module instead.

**Comment by davisi3** [comment]
Oh, btw.. I'm very ashamed to say but I solved my "problem" by installing
playerctl. I don't know what I was (or rather wasn't) thinking. So, it's
all good and it works.
Last thing is to figure out how to put playerctl in the middle of bar.

piektd., 2020. g. 18. dec., plkst. 17:54 — lietotājs Gennady Koshkin (<
notifications@github.com>) rakstīja:

**Comment by tobi-wan-kenobi** [comment]
@davisi3 if you'd like to have `playerctl` extended, please open a separate ticket for that. I had a quick look at the code and I think it might not be too much work to add a format string (similar to how other media player modules do it)

Thanks a lot for your feedback!

**Comment by davisi3** [comment]
Hi!
How would I get spotify-tui in the middle of bar? Can't figure it out.

sestd., 2020. g. 19. dec., plkst. 14:08 — lietotājs tobi-wan-kenobi (<
notifications@github.com>) rakstīja:

**Comment by tobi-wan-kenobi** [comment]
@davisi3 what exactly do you mean by that? if you talk about centering the spotify module, i am afraid there is no reliable way to do that that i know of.

or do you want to open the spotify-tui on click?

**Comment by davisi3** [comment]
Yeah, I mean centering spotify module. I see.. ok, no problem.

pirmd., 2020. g. 28. dec., plkst. 19:09 — lietotājs tobi-wan-kenobi (<
notifications@github.com>) rakstīja:

**Comment by tobi-wan-kenobi** [comment]
The problem is that centering is not something that the i3 bar protocol supports for widgets. If the module is the only one, it might be possible, but that sounds like a corner case.

Generally, you could try to add an empty "spacer" module and set its width so that it pads until the middle of the screen, but that only works if everything on the lefthand side is constant.

ie

bumblebee-status -m spacer:mypad spotify -p mypad.width="aaaaaaaaaaaaaaaaaaaaaaa"

**Comment by giuskywalker** [comment]
> Per [spotifyd's readme](https://github.com/Spotifyd/spotifyd#media-controls):
> 
> > Media controls
> > Spotifyd implements the MPRIS D-Bus Interface Specification, meaning that it can be controlled by generic media playback controllers such as _playerctl_ as well as some tools specifically designed for use with the official Spotify client such as sp.
> 
> Try using the `playerctl` module and see if that works.

I don't know why, but this worked to me for some reason, i was using the spotify module yesterday and everything was fine, but it stopped worked anyhow, then i swapped to playerctl, and back to spotify, then it worked again...
