### ISSUE TITLE
Theme path has to be hardcoded

### ISSUE THREAD

**Issue by Tonus1** [tobi-wan-kenobi/bumblebee-status#753]
#### Description
Affected module: core program
Version used: 2.1.1

bumblebee-status crashes with theme not found :
```
Traceback (most recent call last):
  File "/usr/bin/bumblebee-status", line 18, in <module>
    import core.output
  File "/usr/lib64/python3.9/site-packages/bumblebee_status/core/output.py", line 134, in <module>
    class i3(object):
  File "/usr/lib64/python3.9/site-packages/bumblebee_status/core/output.py", line 135, in i3
    def __init__(self, theme=core.theme.Theme(), config=core.config.Config([])):
  File "/usr/lib64/python3.9/site-packages/bumblebee_status/core/theme.py", line 54, in __init__
    self.__data = raw_data if raw_data else self.load(name)
  File "/usr/lib64/python3.9/site-packages/bumblebee_status/core/theme.py", line 80, in load
    raise RuntimeError("unable to find theme {}".format(name))
RuntimeError: unable to find theme default
```

#### How to reproduce
Packaging for slackware using
```
python3 setup.py install --root=$PKG
```
where evrything installs in tmp directory in `$PKG/usr/{bin,doc,lib64,share}`
And then
```
cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
```

Fix for me is to code the full path for themes in `/usr/lib64/python3.9/site-packages/bumblebee_status/core/theme.py` to `/usr/share/bumblebee-status/themes`

**Comment by tobi-wan-kenobi** [comment]
Ah, I see.

Right now, themes can reside in 3 different locations:

* relative to the "theme.py" file (two directories below)
* in ~/.config/bumblebee-status/themes/
* In ~/.local/share/bumblebee-status/themes

First, I am extremely humbled somebody is packaging this software for Slackware :)

Second, I will add /usr/share/bumblebee/status/themes as theme path right away!

**Comment by tobi-wan-kenobi** [comment]
I would appreciate if you could let me know whether that fixes the issue.

Thanks!

**Comment by Tonus1** [comment]
Thank you for your blazzing fast answer !
I'll check that in a few hours ! 

I will then submit the SlackBuild to Slackbuilds.org :-)

**Comment by tobi-wan-kenobi** [comment]
Looking forward to that, many thanks!

If there is anything you want me to consider for future changes, so as to not break the Slack build, please let me know!

**Comment by Tonus1** [comment]
Thank you, it works as expected ! For know I've add the commit as a patch till next release.

Slackbuilds scripts tend to be very conservative and keep things as vanilla as possible, so no worry. I'll let you know when it will be avaible at slackbuilds.org.
