### ISSUE TITLE
How to assign bindsym XF86AudioVolume to pasink pasource (Pulseaudio) module???

### ISSUE THREAD

**Issue by AndresEGonzalez** [tobi-wan-kenobi/bumblebee-status#756]
### Feature Request

Is possible to assign bindsym XF86AudioVolume external keys to pasink pasource (Pulseaudio) module???

For example: (increase, decrease and mute)

bindsym XF86AudioRaiseVolume exec --no-startup-id #increase sound volume
bindsym XF86AudioLowerVolume exec --no-startup-id #decrease sound volume
bindsym XF86AudioMute exec --no-startup-id # mute sound

Thanks!

**Comment by tobi-wan-kenobi** [comment]
@AndresEGonzalez Not directly via bumblebee-status, but I think the best approach would be anyhow to directly use pulseaudio CLIctools for that - have a look at https://github.com/tobi-wan-kenobi/dotfiles/blob/master/.i3/config.template from my dotfiles, that should help get you started.

Hope that helps!

**Comment by AndresEGonzalez** [comment]
Thanks, perfect!!
This lines working like a charm! 

bindsym XF86AudioMute exec pactl set-source-mute @DEFAULT_SOURCE@ toggle
bindsym XF86AudioRaiseVolume exec pactl set-sink-volume @DEFAULT_SINK@ -2%
bindsym XF86AudioLowerVolume exec pactl set-sink-volume @DEFAULT_SINK@ +2%

gracias!
