### ISSUE TITLE
Add support for custom modules

### ISSUE THREAD

**Issue by deadbeef2000** [tobi-wan-kenobi/bumblebee-status#757]
### Feature Request

I'd like to be able to add my own custom modules, as I've written some for my personal use that are tailored to my needs and are therefore not very useful to others.

I happily share the modules, but as I mentioned above, I don't see any point for anyone else to use them and I didn't test them too well (they do work though :D)

Obviously, I've found a way to add them, but I'd like to add them on a per user basis instead of systemwide (where all the other modules reside).

**Comment by tobi-wan-kenobi** [comment]
Will look into that, this should not be too hard, hopefully!

**Comment by deadbeef2000** [comment]
Thank you for your very quick reply and for looking into my request! I'm not that good a coder in my opinion, but if you need any help, I could give it a try :D

**Comment by tobi-wan-kenobi** [comment]
Short update: Unfortunately, it seems tricker than anticipated to get importlib to import from a non-standard location. I am on it, but it might take a while.

**Comment by deadbeef2000** [comment]
Thanks for the update!

As I said, I don't mind helping :)

Take as much time as you need, there's no point in rushing it, especially if you have other things to do as well!

**Comment by deadbeef2000** [comment]
Thanks for putting in the effort, but sadly, it's not working for me.

Whenever I create the directory `~/.config/bumblebee-status/modules` and put a module inside of it, bumblebee-status just "dies".

If I call bumblebee-status from cli without args then I get the following error: 
`module 'importlib' has no attribute 'machinery'`

If I call bumblebee-status from cli with args (e.g. `bumblebee-status -m playerctl.py`), then it just tells me that's it's unable to find **this** module, no matter if it's installed system wide or in the home directory. It doesn't matter with module I choose.


I'm running version 2.1.2-1 from the Arch AUR.

If you need any more information, feel free to ask me and thank you again for your really awesome work regarding `bumblebee-status`!

**Comment by tobi-wan-kenobi** [comment]
Hm, possibly, this is a problem with the Python version used...

I will investigate and hopefully have a fix soonish :)

Thanks for reporting!

**Comment by deadbeef2000** [comment]
Thanks for making an effort to fixing the issue :)
