### ISSUE TITLE
Multiple Disk elements

### ISSUE THREAD

**Issue by Deep-Six** [tobi-wan-kenobi/bumblebee-status#758]
### Multiple Disk Entries
Hello, I am trying to have multiple disk entries, I had found somewhere that disk:<path> seemed to create uniqueness, however when I tried that along with disk:<path>.<path> as a parameter, it just replicates the same data.

**Comment by tobi-wan-kenobi** [comment]
Yes, you can use aliases to assign different parameters, as well, like this:

-m disk:root disk:home -p root.path=/ home.path=/home

hope that helps!

**Comment by Deep-Six** [comment]
I have tried that, maybe there's a regression somehow: here's my config:
```
status_command  /usr/bin/bumblebee-status -m todo watson pomodoro pacman \                                                                                                                       
          github sensors traffic disk:root disk:home load cpu memory pasink mpd weather sun \
         battery datetime -p \
         disk:root.path="/" disk:home.path="/home" disk:home.open="termite -e ranger /home" \
         todo.file=~/Documents/todo/todo.txt datetime.format="%a-%b-%d-%Y %H:%M" \
         pomodoro.notify="notify-send Time!" 
```

I get duplicate  root definitions  https://ibb.co/r4NQMfp

**Comment by Deep-Six** [comment]
@tobi-wan-kenobi  I apologize, I miss read, your note the -p makes all the difference. I wonder if it could be added to the disk modules section?
