### ISSUE TITLE
Header block should be terminated by a newline

### ISSUE THREAD

**Issue by ianyfan** [tobi-wan-kenobi/bumblebee-status#76]
According to the i3bar input protocol, and in fact breaks programs like swaybar.

However, it seems to be a simple fix on https://github.com/tobi-wan-kenobi/bumblebee-status/blob/master/bumblebee/output.py#L82 (if you want a pull request)

**Comment by tobi-wan-kenobi** [comment]
Good catch, didn't notice that in the protocol spec. Thanks!

Please let me know in case I misunderstood the problem & 02f3559 does not fix the issue.
