### ISSUE TITLE
Sunrise on the left, sunset on the right

### ISSUE THREAD

**Issue by poetician** [tobi-wan-kenobi/bumblebee-status#765]
### Feature Request
In the sun module the sunset time displays on the left, but it should come after sunrise therefore on the right ...
I looked in the module and decided not to experiment blindly. :)

**Comment by tobi-wan-kenobi** [comment]
Actually, the module always puts the "next" event first - during the day, it's the next sunset, and at night, it's the next dawn.

Since it's a user contributed module, I am a bit hesitant to change that behaviour. Does it make sense to you, explained like that?

**Comment by poetician** [comment]
Certainly does. I hadn't noticed that behavior but I know to look for it now.
