### ISSUE TITLE
playerctl not displaying all information

### ISSUE THREAD

**Issue by poetician** [tobi-wan-kenobi/bumblebee-status#767]
#### Description
Affected module: playerctl
Version used: latest git

Only displays previous and next icons for output from Vlc. Other icons don't display. Pause/resume works clicking on the blank space between the buttons. Current song does not display. No right mouse functionality, whether there is supposed to be any. The icons are in the awesome-fonts.json.

#### How to reproduce
simply run it. Haven't tried with other players since none are installed.

**Comment by tobi-wan-kenobi** [comment]
as far as i can remember, there have been playerctl issues in the past already.

what does "playerctl status" give you on the cli?

the module has no right click action, unless you specify one with the "playerctl.right-click" parameter

**Comment by poetician** [comment]
I think I mentioned it before, but I went through a new round scouring the modules, and it was one. Right now Vlc is playing a track but playerctl status returns paused. That's odd.

**Comment by tobi-wan-kenobi** [comment]
can you please compare that to the output of the command "playerctl status"?

I seem to remember a bug that the tool sometimes is pretty laggy, and if that is the case, there is not a lot that bumblebee can do about it, unfortunately...

**Comment by poetician** [comment]
It's not a module I would use, so it was more for general knowledge and whether there was anything on your end about this. If I try with different media players and get different results, I'll let you know, otherwise, I suppose we can close.

**Comment by tobi-wan-kenobi** [comment]
Ah, I see.

Well, I am not using playerctl myself, and since it is a user-contributed module, I tend to keep those in the current state until a user has an issue that requires me to have a closer look.

Until then, I assume it either works for everyone or nobody is using it :)

**Comment by poetician** [comment]
Works for me, :)

**Comment by xRealNeon** [comment]
I have the same issue when I run `playerctl status` it says Playing and  `playerctl metadata` returns the right data but it's not displayed in the bar.
