### ISSUE TITLE
Grammar check

### ISSUE THREAD

**Issue by poetician** [tobi-wan-kenobi/bumblebee-status#769]
#### Description
Affected module: How to write a module webpage

https://bumblebee-status.readthedocs.io/en/latest/development/module.html

If you want to do me favour, run your module through black -t py34 before submitting >> If you want to do me a favour ...

When you feel comfortable with what you’ve developed, please just open a PR, somebody will look at it eventually >> ... open a PR. Somebody will look at it eventually.

... which translates to individual blocks in the i3bar >> ... blocks in the i3bar.

**Comment by tobi-wan-kenobi** [comment]
Thanks a lot, good hint!

Me no good talk, me no native :P
