### ISSUE TITLE
Not loading modules

### ISSUE THREAD

**Issue by Qpernicus** [tobi-wan-kenobi/bumblebee-status#770]
Hello

I am quite sure this is not a issue on bumblebee perse. But I installed via git, on manjaro on a 'blank' i3 (no community edition) although the laptop ran manjaro gnome previously. Long story short: the Bluetooth and System module error and say 'unable to load module'. How do I troubleshoot this since both don't seem to need specific dependencies.

**Comment by tobi-wan-kenobi** [comment]
Hello,

bluetooth needs blueman installed, I think. Plus, as it uses popups, also tkinter (the Python module) needs to be present.

Also system requires tkinter, so my guess would be that this is missing? Usually, the module is named something like python-tkinter

Hope this helps!

**Comment by Qpernicus** [comment]
> Hello,
> 
> 
> 
> bluetooth needs blueman installed, I think. Plus, as it uses popups, also tkinter (the Python module) needs to be present.
> 
> 
> 
> Also system requires tkinter, so my guess would be that this is missing? Usually, the module is named something like python-tkinter
> 
> 
> 
> Hope this helps!

- [ ] This was the exact problem so many thanks. This can close 😁
