### ISSUE TITLE
Arrows offset to the left 

### ISSUE THREAD

**Issue by Cyber-04** [tobi-wan-kenobi/bumblebee-status#771]
#### Description
Version used: git

Hello, i tried looking for an arrow display bug report everywhere and i did not find anything similar except for one thread where there is also a screenshot included and that is the exact issue i am having. I tried the suggested answer, but changing the separator-block-width doesn't change anything at all, for both positive and negative values. (Virtual machine with Arch)

#### How to reproduce
The issue is the same as https://askubuntu.com/questions/912725/bumblebee-status-display-problems
(Not sure of how to reproduce, from what i recall it was like that since the first time it started working)

**Comment by tobi-wan-kenobi** [comment]
Can you please let me know the font and theme you are using?

The fact that the separator width doesn't help sounds like a bug :(

**Comment by Cyber-04** [comment]
font pango:Inconsolata for powerline 5, FontAwesome 6

**Comment by Cyber-04** [comment]
Oh, forgot about theme, right now nord-powerline but also tried multiple powerline themes and none worked, Solarized Powerline, One Dark Powerline, Dracula Powerline, and possibly one more that i can't recall at the moment

**Comment by tobi-wan-kenobi** [comment]
I just tested with latest git - `separator-block-with` should work and offset characters to the left (positive) or right (negative).

Can you please show the exact changes you did to the nord-powerline theme?

**Comment by Cyber-04** [comment]
Changes to the theme itself? I didn't change anything about that, only changes i made were to the awesome-font file in the icons folder so that they would show up properly because they weren't recognized at first. And since i tried multiple themes that all had the same issue i would guess it's not a theme related issue. Maybe i'm not understanding what you mean properly though, could you let me know what exactly i should show?

**Comment by tobi-wan-kenobi** [comment]
So, the best way to change the "separator-block-width" is to add that option to the theme you are using, in the "defaults" section.

I am away from the computer right now, but I can send you a diff later, if that helps.

Also, I think I should improve the documentation. for that and/or make that easier accessible.

Hope this helps!

**Comment by Cyber-04** [comment]
It worked, thank you very much, i didn't think that you could also change it from theme file itself

**Comment by tobi-wan-kenobi** [comment]
Glad to hear it and thanks for using bumblebee :)
