### ISSUE TITLE
Add icon to workspace number

### ISSUE THREAD

**Issue by JartX** [tobi-wan-kenobi/bumblebee-status#772]
I have searched but cant found anything about this point, any can help me please?

**Comment by tobi-wan-kenobi** [comment]
Which bumblebee module do youvmean?

If you talk about i3 workspace names, those are not touched by bumblebee.

Generally, you can use anything your font offers, and a lot of fonts (awesome, powerline, nerd) contain characters that look like icons.

Is that what you are looking for?

**Comment by JartX** [comment]
> Which bumblebee module do youvmean?
> 
> If you talk about i3 workspace names, those are not touched by bumblebee.
> 
> Generally, you can use anything your font offers, and a lot of fonts (awesome, powerline, nerd) contain characters that look like icons.
> 
> Is that what you are looking for?

like this:
https://forum.archlabslinux.com/uploads/default/original/2X/7/71c04b5194a182fda82ea92b529e322e0d406f6f.png

**Comment by tobi-wan-kenobi** [comment]
Yes, that is not part of the i3 bar, but you can do it by using font icons in the i3 config of the workspace names.

**Comment by JartX** [comment]
> Yes, that is not part of the i3 bar, but you can do it by using font icons in the i3 config of the workspace names.

Many thanks! :) https://boddy.im/i3-workspace-names.html .. i am idiot

**Comment by tobi-wan-kenobi** [comment]
no worries, this part of i3 can be pretty confusing. glad it works for you now!
