### ISSUE TITLE
Time is delayed on statusbar.

### ISSUE THREAD

**Issue by Green-Robot-Dev-Studios** [tobi-wan-kenobi/bumblebee-status#774]
#### Description
Affected module: time
Version used: AUR

#### Issue
The time is delayed by ~30 seconds on the statusbar. Might be an easy fix by updating the time module more often. My other modules update much more frequently.

#### How to reproduce
Use the time module `time:strf` and `strf.format="%l:%M"`

**Comment by tobi-wan-kenobi** [comment]
Yes, by default, the time module only updates once a minute or so, I think (less resource consumption and usually sufficiently accurate, I believed)

This has been brought up so often that I will likely undo that decision.

In the meantime, the easiest fix is to manually increase the interval by using `-p time.interval=1`

Hope this helps!
