### ISSUE TITLE
Clicking on shell module blocks future click events

### ISSUE THREAD

**Issue by es80** [tobi-wan-kenobi/bumblebee-status#776]
#### Description
Affected module: shell
Version used: latest (issue pre-dates at least v.2.0.0)

<description>

#### How to reproduce

Have some output from the shell module preferably with a slow update time, e.g `shell.command='date +%S' shell.interval=1m`.

Click on the shell output.

Debug log shows the event but the output does not update. Furthermore, click events are now stuck and blocked for any other module.

#### Possible resolution

I found that simply commenting out lines 51 and 52 which were registering the left and right click not only fixed the issue but gave the desired behaviour that clicking on the shell output causes a refresh. However I'm not sure I understand why. Maybe this behaviour is by default inherited from somewhere?

```
diff --git a/bumblebee_status/modules/contrib/shell.py b/bumblebee_status/modules/contrib/shell.py
index cb7bc38..3295351 100644
--- a/bumblebee_status/modules/contrib/shell.py
+++ b/bumblebee_status/modules/contrib/shell.py
@@ -48,8 +48,8 @@ class Module(core.module.Module):
             self.__current_thread = threading.Thread()
 
         # LMB and RMB will update output regardless of timer
-        core.input.register(self, button=core.input.LEFT_MOUSE, cmd=self.update)
-        core.input.register(self, button=core.input.RIGHT_MOUSE, cmd=self.update)
+        #core.input.register(self, button=core.input.LEFT_MOUSE, cmd=self.update)
+        #core.input.register(self, button=core.input.RIGHT_MOUSE, cmd=self.update)
 
     def set_output(self, value):
         self.__output = value
```

**Comment by tobi-wan-kenobi** [comment]
oh. yes. this is pretty outdated, since 2.x, all modules are automatically updated when interacting.

Thanks once more for a nice bug report.

Will try to fix everything at latest during the weekend :)

**Comment by tobi-wan-kenobi** [comment]
Thanks for the report, and hope this is fixed now!

As soon as I have your confirmation, I will push out a new release on git, aur and pip.

**Comment by es80** [comment]
Hi, 

Thanks that's great! Working nicely for me.

All the best.
