### ISSUE TITLE
Uptime in /themes/icons/awesome-fonts.json

### ISSUE THREAD

**Issue by poetician** [tobi-wan-kenobi/bumblebee-status#780]
#### Description
Affected module: uptime
Version used: AUR

<description>
Seems I'd mentioned this once, so here it is again :) I've disentangled uptime from todo, that is to say, it's done. The irony is just too cool. The module worked though had no icon. So I took a look.

This is the correction I've used on my system, using the half-hourglass font.
  },  
  "uptime": {
   "prefix": ""
  },

cheers

**Comment by tobi-wan-kenobi** [comment]
Good to hear it is working for you now!

What you describe sounds like Font Awesome is not properly used as fallback font.

Can you please check that Font Awesome (version 4, *not* 5) is installed on your system and used as fallback font in the i3 configuration of the bar?

**Comment by poetician** [comment]
My bad - had to install 4. Might have been some update? Or it was simply self-inflicted lol :)

Also, grammar check in the shortcut module:
https://github.com/tobi-wan-kenobi/bumblebee-status/wiki

"Please note: So far, it this tool ..." >> ... So far, this tool ...

I get the 'Click me' text in the bar, the link works, however I'm still working on making a command work. I get no error message, and no desired output. I tried a tidy simplified example:
-m shortcut -p shortcut.cmd='ls' shortcut.label='L' \
yet nothing shows. Is this because a specific terminal is expected? I'm running Alacritty, but I have a few others installed but not xterm or urxvt which i3 might be looking for. ??

**Comment by tobi-wan-kenobi** [comment]
Will fix the grammar


Reg. commands: You need to specify something that actually spawns a new program - e.g. "alacritty" would give you a new terminal on click. To get the output of ls in a terminal, try "alacritty -e ls"

**Comment by poetician** [comment]
Still nothing, and the default 'Click me' remains. I can see how it works (well enough) in the shortcut.py module, though I'm not messing with that. Tried alacritty by itself even.

**Comment by tobi-wan-kenobi** [comment]
Are you using i3 or sway? I remember people having issues with spaening processes in the past, in sway.

**Comment by poetician** [comment]
i3. This one is a head-scratcher atm.

**Comment by tobi-wan-kenobi** [comment]
Can you show me your exact bumblebee-status invokation? I tested on 4.19.1 with Alacritty 0.7.2, and the following works as expected:

`~/src/bumblebee-status/bumblebee-status -m shortcut -p shortcut.cmds="alacritty;alacritty -e top" shortcut.labels="term;top"`

Clicking on "term" opens a new terminal, clicking on "top" opens a new terminal that runs top. Please note that any command you specify after "-e" must be "long-running" (i.e. "ls" will open a terminal, execute ls, and close the terminal immediately after ls finishes). That is just how this module (or, more particularly, alacritty) is implemented.

**Comment by poetician** [comment]
It works now. Thanks much. :)
