### ISSUE TITLE
404 on twmn contributor's GitHub

### ISSUE THREAD

**Issue by poetician** [tobi-wan-kenobi/bumblebee-status#781]
#### Description
Affected module: twmn
Version used: AUR

Link 404's 

#### How to reproduce

https://github.com/Pseudonick47 is a dead link on the contrib modules page. https://bumblebee-status.readthedocs.io/en/latest/modules.html#twmn

I've been looking at twmn. I can load it without errors, however I can't reproduce any expected behaviour for it. I tried it with notifications on from DIscord and no responsiveness. I have most notifications off but I get those chosen few through Xfce-notify. Could it be over-riding twmn?

**Comment by poetician** [comment]
On the subject of 404's - for shortcut: https://github.com/cacyss0807

**Comment by tobi-wan-kenobi** [comment]
Yes, 404s are contributors who deleted their github account in the meantime.

This is intentional, I would say.

Reg. twmn, I will try to look into it, but I am not using it myself, so it might take a while to get to the bottom of it.

**Comment by poetician** [comment]
Indeed. It's at times like these I wouldn't mind a programmer's brain and knowledge, but I defer that to upstream.

I'm in no rush. Still have a few modules I might use to check out. And I'd like to tweak the themes I've made a bit more. I turned someone on to bb-s yesterday and they grabbed one of my themes for a triple-monitor system, and it's slick. :) He said he'd like to make a module for himself, so you might have a new contributor on the way.

Again, my compliments on this project. Mine is to get the bar included in Arco i3 and flagship.

**Comment by tobi-wan-kenobi** [comment]
That sounds great, many thanks! And thank you for the kind words :)

**Comment by tobi-wan-kenobi** [comment]
Regarding twmn: Are you on a system that has systemd?

**Comment by poetician** [comment]
You're welcome. Yes. Is there a log file that might help?

**Comment by tobi-wan-kenobi** [comment]
Enabling debug mode and logging to a file might show something useful - with only the twmn module enabled, to reduce clutter.

Thanks!

**Comment by poetician** [comment]
Will do soon +/-.

**Comment by tobi-wan-kenobi** [comment]
Just for testing - if you enter 'systemctl --user stop twmn', are notifications paused?

Do you use systemctl to manage twmn, or do you start it directly in your i3 config?

**Comment by poetician** [comment]
I start it in i3. I switched to my other i3 to not mess with the one which is running better.
This is the installation where system is not working, and twmn needed to be installed.
I ran the daemon and twmnd is in .xinitrc.
I pasted the twmn.conf example into ~/.config/twmn/twmn.conf
The awesome-fonts.json shows the bell as "muted" but that's reversed.
A bell with a backslash through it is muted.
That needs to be clarified for me.
It does therefore appear in the bar.
I'll reboot because: twmn.service: Unit twmn.service not loaded.
I'll skip the rest of what I did till after the reboot.

**Comment by poetician** [comment]
I start it in i3. I switched to my other i3 to not mess with the one which is running better.
This is the installation where system is not working, and twmn needed to be installed.
I ran the daemon and twmnd is in .xinitrc.
I pasted the twmn.conf example into ~/.config/twmn/twmn.conf
The awesome-fonts.json shows the bell as "muted" but that's reversed.
A bell with a backslash through it is muted.
That needs to be clarified for me.
It does therefore appear in the bar.
I'll reboot because: twmn.service: Unit twmn.service not loaded.

... so now it's perhaps a question of enabling the service which I have attempted in the usual manner to no avail.

**Comment by tobi-wan-kenobi** [comment]
Yes, twmn beeds to run as user-level systemd service, otherwise, mute/unmute won't work.

Unfortunately, I cannot be a lot of help there - I learned today that systemd has user-level services and the distro I am using does not even have systemd.

**Comment by poetician** [comment]
I've leave it at that for now. Not that much of a priority.
