### ISSUE TITLE
Rotation cycles colours in modules

### ISSUE THREAD

**Issue by poetician** [tobi-wan-kenobi/bumblebee-status#782]
#### Description
Affected module: rotation
Version used: AUR

On reloading it instantly cycles the current theme's colours through all modules in lock step.

#### How to reproduce

Added -m rotation

Here's a rough and ready video: https://youtu.be/IMPXTmeHHiQ

**Comment by tobi-wan-kenobi** [comment]
Thanks for the report, that was a clear bug :) Should be fixed in current main.
