### ISSUE TITLE
More options for separator glyphs (rounded)

### ISSUE THREAD

**Issue by Deep-Six** [tobi-wan-kenobi/bumblebee-status#783]
### Feature Request
Hello, I've recently switched to using a rounded (       )  type of theme in my oh-my-zsh config, It is still "Powerline" ish in that colours are a gradient, but now my status line seems out of place with it's < style glyphs. I tried playing around with separator, but it didn't seem to yield the results I was hoping for.

![scrn-clip-2021-04-10-07-26-26](https://user-images.githubusercontent.com/23326167/114273240-1c2dac00-99ce-11eb-97c8-6932f33ca8f4.png)

**Comment by tobi-wan-kenobi** [comment]
Oh, that would be nice to have :)

I think it should be possible by overriding the iconset (`-i`). The files in `themes/icons/` can serve as example. How to do the alternating open/close half-circles, I am not yet sure (prefix and postfix, maybe?)

**Comment by stuart-warren** [comment]
@tobi-wan-kenobi was prefix/postfix separators ever made possible? I'm not seeing anything obvious. thanks

**Comment by tobi-wan-kenobi** [comment]
It is a bit hidden - themes/icons/awesome-fonts.json, for example
