### ISSUE TITLE
Implementing millisecond into intervals

### ISSUE THREAD

**Issue by solar-core** [tobi-wan-kenobi/bumblebee-status#784]
### Feature Request
Hello, i love bumblebee-status, thank you!
Could we have a feature, that change language layout display, not in 1s but in maybe 100ms, so it changes immediately. So one of the solution will be impelemting millisecond into the intervals, thank you.

**Comment by tobi-wan-kenobi** [comment]
You can set the update interval to 100ms, by using the value 0.1, however, that would update *every* module at that frequency ( the main interval is basically zhe "polling" interval for all modules.

I think that would increase cpu usage quite a bit.

However, as long as you change the layout via bumblebee, it *should* update immediately.

**Comment by solar-core** [comment]
I am using `exec --no-startup-id setxkbmap -layout us,ru -option grp:ctrl_shift_toggle` to change layout, and the bumblebee change it after 1 second. Is there any solution like if i toggle ctrl+shift using setxkbmap, so i send some signal to bumblebee, and refresh its status, so it would not work every time on 0.1 seconds?

**Comment by solar-core** [comment]
I set interval to 0.6s i think this is fine. Displaying the switch not happens immediately, but if there is no other tool, that update the layout display on layout change, its good.

**Comment by tobi-wan-kenobi** [comment]
@solar-core Not sure whether this helps you, but I just added a way to trigger an update for a module via an external tool (i.e. you could call `bumblebee-ctl -m cpu -b update` to "force" all loaded cpu modules in all bumblebee-status bars to refresh.
