### ISSUE TITLE
About standard cpu core module

### ISSUE THREAD

**Issue by solar-core** [tobi-wan-kenobi/bumblebee-status#785]
Hello, is there any way to create multiple cpu? Using standard core module?

**Comment by tobi-wan-kenobi** [comment]
You mean habing separate values per core? No, that is not possible currenlty (nice feature, though!)

The cpu2 module does have per-cpu load graphs, which might help you a bit?

**Comment by solar-core** [comment]
Thank you, i think yes, but not sure because i don't see anything in docs about warning status if cpu >= somevalue  but will try it.

**Comment by solar-core** [comment]
Yes, there is no configuration for warnings, but anyway this better than nothing. Thanks.

**Comment by tobi-wan-kenobi** [comment]
Reopen: I'd like to implement that in the core CPU module

**Comment by solar-core** [comment]
That was fast! Thank you :)

**Comment by tobi-wan-kenobi** [comment]
Let's hope it works for you!

Feedback much appreciated!

**Comment by solar-core** [comment]
No problem, will write here feedback whey i try it

**Comment by solar-core** [comment]
@tobi-wan-kenobi Tried that, works great!
