### ISSUE TITLE
Module <layout> not showing changes

### ISSUE THREAD

**Issue by enrico223** [tobi-wan-kenobi/bumblebee-status#788]
### Bug Report
I'm Kubuntu 20.04 LTS, using i3wm. I set up the keybinding Super+space to change the keyboard layout. 
The module does its work of changing the keyboard layout and showing the change if clicked on. When the layout is changed with the shortcut, then the layout changes, but the change is not shown in the module. 
#### Description
Affected module: layout
Version used: latest git
Relevant i3 section: 
`# Start i3bar to display a workspace bar (plus the system information i3status
finds out, if available)`
`bar {
position top
status_command /home/enrico/bumblebee-status/bumblebee-status -m datetime pomodoro battery layout memory \
                pasink pasource -p time.format="%H:%M" -t iceberg-rainbow
}
`

#### How to reproduce
Simply install the bumblebee status bar and set a keybinding in the system for changing keyboard layout.

**Comment by tobi-wan-kenobi** [comment]
Yes, unfortunately, the layout module doesn't pick up on that :(

Can you please give `layout-xkbswitch` and/or `layout_xkb` a go? If I remember correctly, one of them *should* have that capability,

**Comment by enrico223** [comment]
The `layout_xkb` doesn't work at all. 
The `layout-xkbswitch` gives me this in the screenshot
![image](https://user-images.githubusercontent.com/72576597/117707692-24485980-b1cf-11eb-9516-949574949fc9.png)

**Comment by tobi-wan-kenobi** [comment]
`layout-xkbswitch` requires the tool `xkb-switch` to be installed, but then, it should work.

`layout_xkb` is pretty special and requires `libX11.so.6` and the Python module `xkbgroup`, so it's hard to set up.

Hope this helps!

**Comment by enrico223** [comment]
Installed `xkb-switch`, same problem as `layout`. Do you have any other suggestions?

**Comment by tobi-wan-kenobi** [comment]
No, I am very sorry, if the tool (e.g. `xkb-switch`) does not report the change, then I don't know what else to try.

The only thing I can think of is more of a workaround - using an explicit i3 binding that invokes `xkb-switch` for changing the layout - that *should* make `layout-xkbswitch` work (because then it's a single too that's being used).

**Comment by enrico223** [comment]
I think I found the problem, but I don't know how to solve it. I'm now using `xkb-switch` and a bluetooth keyboard. When the input comes from the bluetooth keyboard, the module shows the change only after a few seconds, so this is one problem. The other is, of course, that the module still doesn't show the change when the input comes from my laptop's keyboard. 
So I have two question, how can I set up the module so that it shows the changes right after I press the shortcut buttons? How can I make the input from the laptop's keyboard show up?

**Comment by tobi-wan-kenobi** [comment]
Regarding the update interval:

The only way bumblebee has to get the layout is to poll - by default, once prr second. And then, it shows the new layout only when the underlying tool -xkb-switch - shows it.

So unless you use a poll interval lower than the default 1s, Icdon't think there is a lot of possibility to speed that up.

If you are using multiple keyboards - is it possible that both of them have different layouts and bumblebee is showing only the layout of one of them? I.e. if the other changes layout, bumblebee does not update?

**Comment by enrico223** [comment]
oh ok, got it! I think it is possible. But right now even the changes from the bluetooth keyboard don't show up. 
If I manage to solve this problem, I'll let you know, thank you!

**Comment by tobi-wan-kenobi** [comment]
Sounds great, thanks for the update!

I have only recently figured out that different keyboards can have different layouts in X11, but have no clue how to query that in Python reliably.

If you find something, I can update the layout module.

Thanks!

**Comment by tobi-wan-kenobi** [comment]
One update to this: I found out that `setxkbdmap` supports a `-device` parameter for selecting the input device. Unfortunately, on my box, it seems this parameter is *ignored* when querying the current configuration :(

**Comment by tobi-wan-kenobi** [comment]
Note sure if this helps, but: I wrote a small C tool that seems to (finally) correctly determine the keyboard layout:

```
#include <stdio.h>
#include <stdlib.h>

#include <X11/XKBlib.h>

void err_if(int condition, const char* msg)
{
	if (condition) {
		fprintf(stderr, "fatal: %s\n", msg);
		exit(1);
	}
}

int main(int argc, char** argv)
{
	Display* display = XOpenDisplay(NULL);
	err_if(!display, "unable to open display");

	int kbd = argc == 1 ? XkbUseCoreKbd : atoi(argv[1]);

	XkbStateRec state;
	XkbGetState(display, kbd, &state);

	XkbDescPtr desc = XkbGetKeyboard(display, XkbAllComponentsMask, kbd);
	char *group = XGetAtomName(display, desc->names->groups[state.group]);
	printf("Group: %s\n", group);
	char* symbols = XGetAtomName(display, desc->names->symbols);
	printf("symbols: %s\n", symbols);

	XFree(group);
	XFree(symbols);
	XFree(desc);

	XCloseDisplay(display);

	return 0;
}
```

You need the X11 library headers (usually something like X11-devel or X11-dev) and compile it with:
`gcc -g -o get-layout ./get-layout.c -Wall -Werror -lX11`

./get-layout gives you the "core" layout then, and you can specify a device ID (from xinput -list|grep key) to get the layouts of a specific keyboard.

*IF* that works for you, that would be a first step towards a clean solution :)

**Comment by enrico223** [comment]
Thank you! Where should I specify the device ID? And for which of the three modules?

**Comment by tobi-wan-kenobi** [comment]
Well, right now, that is not for any module, just to see whether this way retrieves the layout correctly.

You can get the ID of the keyboard by executing "xinput -list|grep key" - this gives you a list of your keyboard input devices along with their ID.

I am trying to call this directly in Python (by loading libX11), but ctypes is giving me a lot of grief :(

**Comment by enrico223** [comment]
It does retrieve the layout correctly

**Comment by tobi-wan-kenobi** [comment]
Great! Then I just need to call those functions with ctypes correctly, and bumblebee will finally have a working layout module :)

Thanks a lot for your patience!

**Comment by enrico223** [comment]
It's you who doing the work, thank you!

**Comment by tobi-wan-kenobi** [comment]
@enrico223 There is now a new module "layout" that accepts a parameter "device" that should be the device ID - e.g. for me, `bumblebee-status -m -m layout:kbd1 layout:kbd2 -p kbd1.device=9 kbd2.device=15` shows two different layouts.

It's very much alpha (i.e. no switching keyboard layouts via the module yet), but if it works fine for you, I will extend it to be "the" main module in the future.

**Comment by tobi-wan-kenobi** [comment]
Closing for now, further changes will be tracked in #790
