### ISSUE TITLE
How to theme 'disk' module with specific paths

### ISSUE THREAD

**Issue by leggettc13** [tobi-wan-kenobi/bumblebee-status#79]
How do you theme the 'disk' module when you give it a specific path (e.g. `disk:root` or `disk:home`)? It themes fine when you just use `disk`, but I also have a disk module checking my home directory and I would like to theme that as well. The icons also don't show up when you specify a path, and I imagine the problem behind this is similar or even identical.

**Comment by tobi-wan-kenobi** [comment]
You can theme it by providing the alias name (e.g. "root" or "home") instead of the module name, that should work then.

For example:

```
        "home": {
                "fg": "#ababab"
        },
```

Regarding the icon: That's definitely a bug you spotted, the module theme is **not** applied at all when you assign an alias.

**Comment by leggettc13** [comment]
Thanks for the help. FYI the same thing worked to get the icons to display.

**Comment by tobi-wan-kenobi** [comment]
Got it, thanks for pointing out the issue!

With the last fix, the icons should also display correctly without modifying the theme.
