### ISSUE TITLE
[Question/Feature Request] Toggling Hiding/Showing Information on Click Event

### ISSUE THREAD

**Issue by OrderlyUnicode** [tobi-wan-kenobi/bumblebee-status#791]
I worded this as a question and a feature request in the event that what I'm asking about is not currently something you can do. There is probably a better way to make this work the way I'm thinking, so I admit the wording maybe could be better.

My question is whether or not it's possible to, in my particular use case, hide the date information with the "datetime" module until a click event is issued, and then use that to toggle showing or hiding the date so as to save space on the bar.

If this is not something that is currently possible, one potential solution that comes to mind is to create a new parameter to hide information by default and toggle it with a specified event.

**Comment by tobi-wan-kenobi** [comment]
That *should* work out of the box by clicking the widget with the middle mouse (you will see 3 dots instead)

There is currently no way to *start* widgets in that state, though. If you need that, I can certainly investigate.

Have fun :)

**Comment by OrderlyUnicode** [comment]
First, I want to thank you for your prompt reply!

> That _should_ work out of the box by clicking the widget with the middle mouse (you will see 3 dots instead)

Is there a way to configure what is shown instead of the 3 dots? I could use that in a way that would solve the issue for me if I can have it show either a shortened or extended version of the default text.

> There is currently no way to _start_ widgets in that state, though. If you need that, I can certainly investigate.

While it would be nice to be able to start it that way, I don't think it's necessary to solve the issue

**Comment by tobi-wan-kenobi** [comment]
No, the alternate text is not configurable right now. Changing it to an arbitrary fixed string ahould be straight forward, but making it consensed info would probably be a per-module implementation, which is tricky and not scalable.

Can you give an example of what you have in mind?

**Comment by OrderlyUnicode** [comment]
> No, the alternate text is not configurable right now. Changing it to an arbitrary fixed string ahould be straight forward, but making it consensed info would probably be a per-module implementation, which is tricky and not scalable.
> 
> Can you give an example of what you have in mind?

The first thing that came to mind is more of an inverse of that. In the case of this particular module, having the default format be something simplified like "%H:%M", but having one of the click events, likely middle click since it seems to already have similar functionality implemented, change the format to "%d/%m/%Y %H:%M" and back again when clicked a second time. I suspect this would also be "tricky and not scalable" for similar reasons, though.

Another thing that comes to mind is to maybe have middle click not hide the entire thing, but simply enforce a character limit on the particular module, but I don't know how viable that is as a solution, though.

**Comment by tobi-wan-kenobi** [comment]
Hmmm... having the possibility to change the input parameters based on the state of the widget might be viable. Interesting idea, I will give that a try.

Fair warning: I do not have a lot of spare time right now, so it might take a while for me to produce results.

**Comment by tobi-wan-kenobi** [comment]
@OrderlyUnicode Most recent git `main` has a test version of this.

I have tested only with the modules `date` and `time`:

`bumblebee-status -d -m date -p date.format="%Y" date.minimized.format="%d" date.minimize=True date.start-minimized=True`

As you can see, you need to do a couple of things:
- Set the parameter `<module>.minimize` to `True` to enable the behaviour
- Provide alternative parameters using `<module>.minimized.<parameter name>`
- Optionally, set `<module>.start-minimized` to True (defaults to False) to *start* in minimized mode

I noticed that this needs a certain degree of module support (no caching of the parameters), so please report back any modules you want to use that do not work. The required changes should be straight-forward in most cases.

Thanks for your patience!

**Comment by OrderlyUnicode** [comment]
Hello again, I'd been rather busy, so unfortunately, I was only just able to test this today.

This is certainly a step in the right direction. Though, I can't tell if I'm just missing the syntax to make it toggled on a click event or if that functionality has not been added.

In case it helps, this is what I currently have for the command I'm running from the i3 config file. I haven't had time to clean up the formatting, so forgive me if it's difficult to parse.

```status_command ~/Source/bumblebee-status/bumblebee-status -t nord-powerline\
        -m nic pasource pasink memory cpu brightness battery date time\
        -a battery\
        -p memory.format={used}/{total} nic.format={intf} {state} cpu.left-click="urxvt -e httop"\
        memory.left-click="urxvt -e watch free -h"  date.format=%d/%m/%Y \
        date.minimized.format=  date.start-minimized=True date.left-click="date.minimized=!date.minimized"```

**Comment by tobi-wan-kenobi** [comment]
Thanks for the feedback!

Toggle does not need a special config and is done via the middle mouse button click, I should have mentioned that.

Hope that works!

**Comment by OrderlyUnicode** [comment]
Ah, there may be a bug then, as middle clicking the minimized item still shows an ellipsis (...) instead of the formatting I set.
