### ISSUE TITLE
Addition of hooks. 

### ISSUE THREAD

**Issue by adgai19** [tobi-wan-kenobi/bumblebee-status#799]
### Feature Request

I would love it if there was a hook to run a script after update of module. One use case for me would be to change backgrounds when external monitor is connected or disconnected. Is it possible to do using current setup? Or anything like this can be added?

**Comment by tobi-wan-kenobi** [comment]
Interesting idea. For some use cases, this would already be possible by overriding mouse events (e.g. "xrandr.left-click"), but esp. for xrandr, that could be annoying, as the base functionality (enable/disable) is fine and cumbersome to reproduce in a shell script.

Maybe something like "xrandr.left-click.hook" that is executed *in addition* to the regular action?

**Comment by adgai19** [comment]
I was thinking about something on the line of a script that ran nitrogen or feh after new monitor was connected /disconnected.

**Comment by tobi-wan-kenobi** [comment]
For that particular task, I think something external to bumblebee would be better suited, udev, possibly?

bumblebee does not detect monitor additions and removal as such, and doing so via polling (like bumblebee would) is pretty inefficient.

**Comment by tobi-wan-kenobi** [comment]
Closing due to a) inactivity and b) the fact that with `bumblebee-status` you cannot hook into system events, such as monitors being connected/disconnected.
