### ISSUE TITLE
No Modules / Error: status_command not found or is missing a library dependency (exit127)

### ISSUE THREAD

**Issue by MoonlightProphecy** [tobi-wan-kenobi/bumblebee-status#809]
#### Description
Affected module: i3, Arch Linux
Version used: latest aur

While using i3 and using a configure code as a reference, I ran into an issue where in one of the corners there is an error
`Error: status_command not found or is missing a library dependency (exit 127)`

I don't know if I need to install a module, but my code is:
`bar {
        font pango:ttf-liberation 10
        position top
        tray_output
        status_command ~/.config/bumblebee-status/bumblebee-status \
         -m cpu memory time pasink pasource \
         -p time.format="%H:%M" \
         -t solarized-powerline
 }`
![2021-08-11_03-54](https://user-images.githubusercontent.com/87376477/128991513-96e6f03e-1f93-4ba9-ae42-7e17bb8acdaf.png)

**Comment by tobi-wan-kenobi** [comment]
Sorry you are having issues!

What is the output of you execute that command directly in a shell?

**Comment by MoonlightProphecy** [comment]
i usually restart the i3 inplace, so `$mod+shift+r`

**Comment by MoonlightProphecy** [comment]
`No such file or directory`
is there a possibility that the directory might not have been created during installation? Or could I have missed something while reading through the documentation?

**Comment by tobi-wan-kenobi** [comment]
How did you install bumblebee-status?

If it is in a default path, "which bumblebee-status" will give you the full path.

**Comment by MoonlightProphecy** [comment]
i used the aur directions and makepkg -sicr, /usr/bin/bumblebee-status.

im really sorry, i feel like im being difficult when i don't intend to.

**Comment by tobi-wan-kenobi** [comment]
No issue at all, we have all been there :)

Can you try using /usr/bin/bumblebee-status instead of ~/.config/bumblebee-status/bumblebee-status ?

I think the issue is that the config refers to a binary path that does not exist.

**Comment by MoonlightProphecy** [comment]
That definitely worked, it lead me to the source code.

**Comment by tobi-wan-kenobi** [comment]
I am not sure I understand - is your issue solved now?

**Comment by MoonlightProphecy** [comment]
sadly no, but ill try reinstalling and see if that works

**Comment by MoonlightProphecy** [comment]
@tobi-wan-kenobi Hey sorry man, it's been 2 days. I've been a little busy irl.
I've reinstalled i3-gaps and reinstalled bumblebee-status and everything seems to be working normal now.

I'm not exactly sure what the issue was but I redid everything and now bumblebee-status works fine, it was most likely a file didn't get downloaded or I mistakenly did something wrong. There is currently no errors so I think I'm good.

I'm incredibly glad that you're very helpful and open with your community trying to help others fix their issues. Thank you so much ^^

**Comment by tobi-wan-kenobi** [comment]
Thank you very much for your kind words, means a lot to me! And I am happy your issue is resolved!
