### ISSUE TITLE
playerctl.py has typo and makes playerctl not display correctly

### ISSUE THREAD

**Issue by Zinnaca** [tobi-wan-kenobi/bumblebee-status#814]
#### Description
Affected module: playerctl
Version used:  manjaro AUR 2.1.4-1

playerctl.py has typo on line 109
is "metadata xesam:albumArtist"
and should be "metadata xesam:artist"

#### How to reproduce

just add playerctl to bumblebee-status and load i3 config

**Comment by tobi-wan-kenobi** [comment]
Thanks for the report and the detailed analysis!

**Comment by tobi-wan-kenobi** [comment]
Actually, this has been fixed as part of 51f68addcdb3dbf266a89c1510935ad230eacb5a, so if you use the latest git (or the `-git` AUR package), the issue should hopefully be gone. Note, though, that this change was breaking backwards compatibility, and requires slightly different parameters.

Hope this helps!

**Comment by Zinnaca** [comment]
Good to know it was fixed! I was bit tired when i did the bug hunting so i only did it on my computer :D
Fixed by hand and when i have time i will switch to the -git package!!
Big thanx by the way for this program!
