### ISSUE TITLE
nm-tray/nm-applet (NetworkManager)

### ISSUE THREAD

**Issue by davisi3** [tobi-wan-kenobi/bumblebee-status#815]
### Feature Request
Hi! Is there NetworkManager applet module already? I just installed nm-tray for NetworkManager but I only see black icon instead of related icon. I assumed I have to add it as module but I couldn't find related module.

**Comment by tobi-wan-kenobi** [comment]
Hi!

Trays are something provided by i3 directly, not the status bar generator (such as bumblebee).

For me (on Arch), nm-applet works fine, including the icon. I am not really sure what could cause a missing icon, maybe missing theme packages?

**Comment by tobi-wan-kenobi** [comment]
Closed due to timeout
