### ISSUE TITLE
pulseaudio broken

### ISSUE THREAD

**Issue by L0L1P0P1** [tobi-wan-kenobi/bumblebee-status#816]
Affected module: pulseaudio, 

Description:
pulseaudio breaks the status bar and just shows the exception: "__init()__ missing 1 required positional argument: 'channel' "

im trying my best to try and fix it and if i could i'll share it.

**Comment by tobi-wan-kenobi** [comment]
The module pulseaudio cannot be used directly, can you please try to use pasink (for output) or pasource (for microphones)?

Hope that helps!

**Comment by L0L1P0P1** [comment]
Hi tobi,
Can I have a link to pasource repo,aur,etc ? I couldn't find it .

**Comment by L0L1P0P1** [comment]
great! that worked!

great job on the project by the way :)

**Comment by tobi-wan-kenobi** [comment]
Thanks a lot for the kind words!

**Comment by 3301n** [comment]
It worked , but can anyone add it here [](https://bumblebee-status.readthedocs.io/en/main/modules.html) so that new users will not find it confusing
