### ISSUE TITLE
JSON parse error

### ISSUE THREAD

**Issue by Torchtopher** [tobi-wan-kenobi/bumblebee-status#817]
#### Description
Affected module: All, nothing works
Version used: Git

I installed with git. Here is my config, its just the sample one. I get an error saying, could not parse JSON (parse error: after array element, I expect "," or ']') Not sure what I did wrong installing.

bar {
        font pango:Inconsolata 10
        position bottom
        tray_output none
        status_command /home/torchtopher/.config/i3/bumblebee-status/bumblebee-status -m nic disk:root cpu \
                memory battery date time pasink pasource dnf \
                -p root.path=/ time.format="%H:%M CW %V" date.format="%a, %b %d %Y" \
                -t solarized-powerline
}

#### How to reproduce
I just did git clone, ran chmod +x on bumblebee-status and the wrote my config. Its strange because it shows up for like half a second and then gives the error.

**Comment by tobi-wan-kenobi** [comment]
Most likely, you are missing some core python module. Can you please try to run the command in a shell and see what output you get (and paste any errors here)?

Thanks a lot in advance!

**Comment by Torchtopher** [comment]
_**This is what happens when I run from shell as root.**_ 

torchtopher@Ubuntu-desktop:~$ sudo bumblebee-status
[sudo] password for torchtopher:
Traceback (most recent call last):
  File "/usr/local/bin/bumblebee-status", line 4, in <module>
    __import__('pkg_resources').run_script('bumblebee-status==2.1.4+57.g9c463fc', 'bumblebee-status')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'bumblebee-status==2.1.4+57.g9c463fc' distribution was not found and is required by the application

**_So it appears that I need to install it, so I then ran_** 

torchtopher@Ubuntu-desktop:~$ pip install bumblebee-status==2.1.4
Requirement already satisfied: bumblebee-status==2.1.4 in ./.local/lib/python3.8/site-packages (2.1.4)

**_And it says its already installed. Any advice?_**

**Comment by tobi-wan-kenobi** [comment]
Do you have bumblebee-status available in `~/.local/bin/bumblebee-status`? If so, please try running it from there.

**Comment by tobi-wan-kenobi** [comment]
Sorry for taking abwhile to get back to you. I tried to reproduce the issue on a fresh install, but failed.

Can you tell me which distribution you are using?

Also, could you please try to see if the git version works better for you? (just clone the git repo and execute bumblebee-status from the checkout folder)

Thanks a lot!

**Comment by tobi-wan-kenobi** [comment]
closed due to timeout. please feel free to reopen with new information
