### ISSUE TITLE
Bluetooth module not toggling on/off, also freezing other modules

### ISSUE THREAD

**Issue by dantemogni** [tobi-wan-kenobi/bumblebee-status#818]
#### Description
Affected module: bluetooth
Version used:  2.4.1 (git)

'bluetooth' _('bluetooth2' also)_ module does not work properly: it shows that the bluetooth is on and when I click it, it opens the blueman-manager correctly, BUT it does NOT toggle on/off. 

The curious thing about that, is that as soon as I right-click on the bluetooth module, **ANY** other module that has click-funcionality _(e. g.:  system, cpu, pomodoro, ...)_ would stop responding to that click (e. g.: pomodoro won't start/pause/reset, and so on). 

So, 
- Left click:
    - opens blueman-manager
    - bar is clickable :)
- Right click:
    - doesn't toggle on/off
    - bar is unclickable :( 

There was a similar issue opened a time ago (https://github.com/tobi-wan-kenobi/bumblebee-status/issues/166) that I think maybe it has something to do with this issue.

#### How to reproduce
1. Insert bluetooth module intro the status bar
2. Right-click bluetooth module
3. Check other modules that have click-funcionality

**Comment by tobi-wan-kenobi** [comment]
Looking at the module `bluetooth`, it looks as if this is behaviour that requires configuration. By default, a right-click opens a popup menu (which in your case likely fails because - a lot of people have that issue - you don't have the python Tk module installed).

If you set `-p bluetooth.right_click_popup=false`, you should get toggle functionality on right click instead.

Hope this helps (and works)!

**Comment by dantemogni** [comment]
Thanks for your quick reply.
But I'm afraid that is not the issue, before installing `Tk`, the `bluetooth` module said something like "unable to load module" in red, but with `Tk` installed, it shows the bluetooth icon and the status (On/Off). So `Tk` is not the problem.

So I set `bluetooth.right_click_popup=false` but nothing changed, the issue remains.

This is my bar in the i3 config file:
```
bar {
	font pango:Inconsolata 8
	position top
	tray_output none
	status_command bumblebee-status -m nic cpu \
		memory battery bluetooth date time pasink pasource \
		-p time.format="%H:%M" date.format="%a, %b %d %Y" bluetooth.right_click_popup=false \
		-t solarized-powerline
}
```
Also, I tried to run _bluetooth.py_ and this was the output:

```
 Traceback (most recent call last):
   File "/usr/share/bumblebee-status/bumblebee_status/modules/contrib/bluetooth.py", line 19, in <module>
     import core.module
 ModuleNotFoundError: No module named 'core'
```
I don't know if that has anything to do with this, because all the other modules gave the same output. Sorry, I'm not quite a developer so I don't know if that is suppose to happen

**Comment by tobi-wan-kenobi** [comment]
Hm... Could you please run bumblebee-status with "-d -f /tmp/bumblebee.log" and paste the contents of the log file after the bar crashes with a right click?

Thanks a lot and sorry for the trouble!

**Comment by dantemogni** [comment]
This is the /tmp/bumblebee.log:

```
[2021-09-09 15:49:22,951] input            DEBUG    registering callback ::wheel-up
[2021-09-09 15:49:22,952] input            DEBUG    registering callback ::wheel-down
[2021-09-09 15:49:22,952] module           DEBUG    importing debug from core
[2021-09-09 15:49:22,952] input            DEBUG    registering callback ::middle-mouse
```
Doesn't show much. I've ran "-d -f /tmp/bumblebee.log" multiple times, clicking (left, right, wheel) in different modules, then clicking the bluetooth one, and then again clicking the other modules (reproducing the issue) but the log file is always the same, those 4 lines. 

Am I doing this right?

_PS: English is not my main language. Sorry for typos & grammar!_

**Comment by tobi-wan-kenobi** [comment]
Hello,

many thanks!

With the latest commit, the bar should not stop responding anymore, however: The error comes from the fact that the dbus command for toggling the bluetooth status is incorrect.

Basically, it works like this:

For toggling, bumblebee calls this:

dbus-send --system --print-reply --dest=<dbus_destination parameter> <dbus_destination_path> org.blueman.Mechanism.SetRfkillState boolean:<true|false>

destination defaults to "org.blueman.Mechanism" and destination path defaults to "/"

That means you need to find out the correct values for your system that make the dbus-send command work & use the corresponding parameters as configuration parameters for bumblebee.

Does that make sense?

**Comment by dantemogni** [comment]
Yes, thanks! I'll check that up.
