### ISSUE TITLE
travis ci security leak

### ISSUE THREAD

**Issue by bbernhard** [tobi-wan-kenobi/bumblebee-status#819]
Hi,

fyi: https://twitter.com/peter_szilagyi/status/1437646118700175360

Just stumbled across that and as you were/are using travis ci as well, I thought I would let you know too. :)

**Comment by bbernhard** [comment]
Closed, as its not an issue with bumblebee-status

**Comment by tobi-wan-kenobi** [comment]
Oh, nice one! Many thanks for the heads-up!
