### ISSUE TITLE
Powerline themes render too small triangles

### ISSUE THREAD

**Issue by korteroppi** [tobi-wan-kenobi/bumblebee-status#82]
When I use a Powerline theme, the triangles are a bit off and seem to be too small.
Because of this, there is a small gap between the adjacent module and the triangle.

[Screenshot of the gaps](https://i.imgur.com/6YRl7TN.png)

I use a slightly modified version on the example in readme.md and I have installed a package called powerline-fonts-git off of AUR.

**Comment by tobi-wan-kenobi** [comment]
Can you please tell me which font you are using specifically, and how you invoke `bumblebee-status`? Ideally, could you maybe paste the relevant `bar {}` section from your `~/.i3/config`?

**Comment by korteroppi** [comment]
`bar {
	font pango:Inconsolata 10
	position top
	tray_output none
	status_command bumblebee-status -m cmus ping traffic disk:root cpu memory pasink pasource date time dnf -t gruvbox-powerline
	colors {
     	   	background #282828
		focused_workspace #637200 #859900 #002b36
    	}
}`

**Comment by tobi-wan-kenobi** [comment]
Hm, that looks good when I paste it into my config.

Some distributions (not sure whether Arch is one of those) have different names for the Powerline fonts (e.g. "Inconsolata for Powerline" instead of "Inconsolata").

Could you maybe try to search for the font you want using a tool like "gnome-font-viewer" or see whether using "Inconsolata for Powerline" or st. similar gives better results?

**Comment by tobi-wan-kenobi** [comment]
By the way, you get the same effect you have if the parameter "separator-block-width" in the theme configuration is set to something bigger than 0. Could you maybe check that your gruvbox-powerline.json contains something along the following lines?

```
        "defaults": {
                "default-separators": false,
                "separator-block-width": 0
        },

```

**Comment by korteroppi** [comment]
Seems like I have the line there
```
	"defaults": {
		"warning": {
			"fg": "#1d2021",
			"bg": "#d79921"
		},
		"critical": {
			"fg": "#fbf1c7",
			"bg": "#cc241d"
		},
		"default-separators": false,
		"separator-block-width": 0
	},
```

I need to try to find whether the font name matters in Arch.

**Comment by tobi-wan-kenobi** [comment]
Glad to hear that :-)
