### ISSUE TITLE
Using config file and possible feature request regarding autohide

### ISSUE THREAD

**Issue by Zinnaca** [tobi-wan-kenobi/bumblebee-status#822]
### Feature Request

1. Is it possible to define autohide in config file?
2. If it would be possible to use different config for each monitor (not workspace) for example if i could only autohide some of the modules on one monitor and not autohide anything on other two.
As currently i have two horizontal (1980x1080) and one vertical (1200x1980) so there is less space on one of the monitors.

**Comment by tobi-wan-kenobi** [comment]
Hi,

1. not yet, but should be a big change. Will look into it, thanks for the suggestion!

2. Yes, that is certainly possible, but outside bumblebee. You need to write your i3 config in a way that each monitor has a separate "bar" config with different invocations for bumblebee.

Hope that helps!
