### ISSUE TITLE
Tilde symbol in datetime

### ISSUE THREAD

**Issue by bananapoweruser** [tobi-wan-kenobi/bumblebee-status#831]
#### Description
Affected module: Arch Linux, i3

Hello, 
I have a weird tilde symbol next to my datetime. Playing around with FontAwesome made the tilde disappear on my other machine.
<img src="https://i.imgur.com/FjL73ry.png" width="250" />

My screen capture tool messed up on the time there, you can ignore that.

My bar settings from .config/i3/config:

 bar {
        font pango: Inconsolata 11 \                                          
        status_command ~/.config/bumblebee-status/bumblebee-status -m nic cpu datetime \                                      
        -p datetime.format="%a %e %b %Y - %H:%M" \
        -t iceberg
 }    
 
 I know that FontAwesome 5 is not supported and I do not have it as of now on my faulty system. 
 I'm pretty sure that this is a font-related issue, but then again I am a total noob.
 
 Can someone help?

**Comment by tobi-wan-kenobi** [comment]
closed due to timeout
