### ISSUE TITLE
i3 error - cant use themes

### ISSUE THREAD

**Issue by wawawiwo** [tobi-wan-kenobi/bumblebee-status#833]
It appears that the bar cant use any theme. If i use "-t", the theme stays the same and i get an error in the i3 config file pointing to the line where i tried to set the theme.

I've tried having the themes both in .config and .local, but it doesn't work. Where should the themes be located then? Or how can i point to bumblebee-status that the themes are?

`ERROR: CONFIG: Line 205:        status_command ~/.config/bumblebee-status/bumblebee-status 
-m cpu memory battery time \ 
ERROR: CONFIG: Line 206:        -t solarized-powerline
ERROR: CONFIG:                  ^^^^^^^^^^^^^^^^^^^^^^`

**Comment by tobi-wan-kenobi** [comment]
Can you please show the bar configuration in your i3 config? This error looks like it is related to the i4 config rather than bumblebee's invocation.

**Comment by tobi-wan-kenobi** [comment]
It looks a bit like you are having a newline in your i3 config, which would break the invokation (it would try to interpert "-t solarized-powerline" as an i3 command.
