### ISSUE TITLE
Is autohide feature functional?

### ISSUE THREAD

**Issue by Jack-Indaboks** [tobi-wan-kenobi/bumblebee-status#835]
Sorry if this is a dumb question.

Affected module: all

Description:
Autohide feature as documented [here](https://bumblebee-status.readthedocs.io/en/latest/features.html#configuration-files) doesn't appear to do anything. I may be misunderstanding the documentation. As I understand it, any module I list on the `autohid=` line in my config file should only appear when in warning or error state. Do I understand that correctly? I'm pretty sure I'm just missing something obvious. If it _is_ a bug, just let me know what info to submit to help with troubleshooting.

Thanks for such an awesome status line! Way better than i3config. Autohide would just be icing on the cake.

**Comment by tobi-wan-kenobi** [comment]
Yes, that is how it works, exactly. I am pretty sure the feature is functional, in principle, since I am using it daily :)

It works like this:

bumblebee-status -m cpu -a cpu

This would show the cpu module only if it is in warning or error state.

If you show me the command you are using, we can troubleshoot it. Maybe some modules are broken.

Thanks!

**Comment by tobi-wan-kenobi** [comment]
Ah, I just saw you are using the config filr.

The documentation has a typo! It should be "autohide" (note the trailing e that makes it also grammatically sound)

I am SO sorry! Will fix that as soon as I am in front of a PC.

**Comment by Jack-Indaboks** [comment]
Thanks for the quick response!
I had tried `autohide` already. Figured it might have been a typo. No dice. I can confirm that the -a flag works as intended on my system, so I can use that until we get this figured out. I must just be getting something wrong with the config syntax:
```[core]
modules = progress,pasink,pacman,cpu,memory,disk,nic,shell,battery,time
autohide = progress,pacman,cpu,memory,disk,battery
theme = firefox-dark-powerline

[module-parameters]
time.format = %Y.%m.%d %H.%M
disk.format = {used}/{size}
memory.format = {percent:05.02f}%
nic.states = up
nic.format = {ssid} {ip}
battery.decorate = False
pacman.sum = True
progress.placeholder =
shell.command = wget http://checkip.dyndns.org/ -O - -o /dev/null | cut -d: -f 2 | cut -d\< -f 1 | sed 's/^//'
```

I have both with and without spaces around the `=` and after the commas. Module parameters and everything else work as intended, simply calling `status-command bumblebee-status` in the `bar{}` section of my i3 config. Here's a thought: Do I have to specify the warning threshold for each module for autohide to work? I've been just trying to use the defaults.

Thanks again!

P.S. Bonus question: is there a way to tell the progress module to autohide whenever it has nothing to display? If not it's no big deal, the extra blank section on the bar doesn't look bad.

**Comment by tobi-wan-kenobi** [comment]
Congratulations, you found a bug in the implementation :)

I think I just fixed that, I would appreciate feedback from you a lot!

Also, regarding the progress module: It was not possible until now, but I also pushed a small change that should make it possible to use "autohide" to hide the progress module when it is not actually showing a copy.

Also, if you could let me know whether this works for you, that would be great.

Many thanks!

**Comment by Jack-Indaboks** [comment]
I'll test it out as soon as I get a chance. I'll have to switch to building from source, as I can't expect you to update the AUR package before testing. Should have an answer later today.

**Comment by tobi-wan-kenobi** [comment]
Sounds good, many thanks!

PS.: There should be a bumblebee-status-git AUR as well.

**Comment by Jack-Indaboks** [comment]
That was actually really painless. Forgot for a second it was python - no compiling. Autohide works! Is there a trick to implementing the progress autohide other than just including it on the autohide line? That one is still there.

And thanks for the tip on the git package. I'll switch to that.

**Comment by tobi-wan-kenobi** [comment]
No, the progress should "just work", I probably overlooked something... Will look into it as soon as I can.

Thanks for the feedback and for raising the bug :)

**Comment by tobi-wan-kenobi** [comment]
@Jack-Indaboks Indeed, I overlooked something, I made a rather stupid logic inversion error :)

Now, the autohide for progress should actually work.

Thanks for your patience!

**Comment by Jack-Indaboks** [comment]
It worksperfectly! This is an awesome app and you are an awesome developer. Thanks!

**Comment by tobi-wan-kenobi** [comment]
Thank you for your kind words, I appreciate them a lot!

Also: I have simplified the autohide functionality of progress a bit - I tested it and everything should work, but if it breaks for you, please do let me know.

Thanks!

**Comment by Jack-Indaboks** [comment]
Still works
