### ISSUE TITLE
force refresh

### ISSUE THREAD

**Issue by kiselina2** [tobi-wan-kenobi/bumblebee-status#837]
Is it possible to force refresh? I would like to force refresh when I change the volume so I can see the change instantly.

**Comment by tobi-wan-kenobi** [comment]
If you change the volume via bumblebee, it should update immediazely.

If you use something else, there is no way, right now.

There is the tool "bumblebee-ctl" to send commands to bumblebee-status, and it would be pretty straight-forward to extend that to allow refreshs. Would that help?

**Comment by Tonus1** [comment]
I was thinking at something these days : how to reload bumblebee bar without reloading i3 config ? (I have an issue with pactl throwing an error in the bar when a workspace blins urgent)

If possible, would it match @kiselina2 request ?

**Comment by tobi-wan-kenobi** [comment]
@Tonus1 @kiselina2 Looking at the code right now, I believe this is implemented already and I forgot about it :see_no_evil: 

`bumblebee-ctl -b update -m <module name> -i <module ID>` (where ID is optional)

So, for the module "cpu", for instance, you would do `bumblebee-ctl -b update -m cpu` to update the module.

@Tonus1 To refresh the whole bar, sending SIGUSR1 to the process should do the trick. If you could send me a debug log for the error in pactl, I can look at that separately, errors in CLI tools *should* be handled gracefully.

Thanks!

**Comment by Tonus1** [comment]
@tobi-wan-kenobi 
The command did not do it for pacsink/pasource :
`usage: bumblebee-ctl [-h] [-b {left-mouse,right-mouse,middle-mouse,wheel-up,wheel-down}] [-i ID] -m MODULE
bumblebee-ctl: error: argument -b/--button: invalid choice: 'update' (choose from 'left-mouse', 'right-mouse', 'middle-mouse', 'wheel-up', 'wheel-down')`
The error is : 
`pactl infol exited with error 1`
Strange enough, it has the error in one of the two bars I have...

**Comment by tobi-wan-kenobi** [comment]
Would it be possible to change to the latest git version? Possibly, this is not yet part of the latest release...

**Comment by Tonus1** [comment]
For now I can't see the initial error (when the bar blinks as I have an alert on another workspace).

Seems great to me. Perhaps worth a release ?

Thanks for your so quick answers !

**Comment by tobi-wan-kenobi** [comment]
Yes, another release is on my schedule since quite a time, but real life tends to interfere :P

Glad it works for you!
