### ISSUE TITLE
Showing only active network device

### ISSUE THREAD

**Issue by rawsta** [tobi-wan-kenobi/bumblebee-status#84]
Is it possible to have only the active network device showing in the bar? 
Currently i have always eth+wifi showing which is why i have always a red block.
Disabling one device is not an option for me, since i regularly switch between networks.

**Comment by tobi-wan-kenobi** [comment]
Hi,

it's not possible yet, but I like the idea and will try to implement it as soon as possible (I'm thinking along the lines of having a config parameter that allows you to hide devices in a given state).

Thanks for the idea!

**Comment by tobi-wan-kenobi** [comment]
Please let me know if this does not fix the issue in a way that is useful for you :)

**Comment by rawsta** [comment]
It doesn't seem to work for me. i pulled the latest nic.py and did a reboot to be sure.
Still got the red eth-block showing up. 
Do i have to add something to my config?

**Comment by tobi-wan-kenobi** [comment]
Oh, yeah, I knew i forgot something :P

Yea, please add "-p nic.states=up" to filter for "up" states only. If you only want to have interfaces that are "not down",  please use "-p nic.states=^down".

**Comment by rawsta** [comment]
Nice! It works. Thanks for the quick fix ;)

**Comment by ibrokemypie** [comment]
any chance of the same for the traffic module?
