### ISSUE TITLE
Strange behavior of modules

### ISSUE THREAD

**Issue by matejp0** [tobi-wan-kenobi/bumblebee-status#847]
Version used: latest AUR bumblebee-status

### First weird behavior
I am sure this probably is an error on my side, but I have encountered this strange behavior of modules in the bar. It looks like the arrows are "missing a piece".
![plugged](https://user-images.githubusercontent.com/57071246/150558766-71a7f60b-2f80-4a68-95e0-6c66d27a3aae.png) (Sorry for the watermark)
This error happened with every theme I tried, so I don't think that it's bond to any theme. For the screenshot I used this inside the `bar{}` block in the `.config/i3/config`
```
font pango:Noto Sans Regular 10, FontAwesome 10, Powerline 10
status_command bumblebee-status -t powerline \
     -m time date spacer battery
```
I found someone having the same problem on [AskUbuntu](https://askubuntu.com/questions/912725/bumblebee-status-display-problems), but it didn't solve the problem.

### Second weird behavior
Next weird behavior i came across is in the battery module. When the laptop is plugged in, it shows a question mark in a circle (shown in the first part). When I unplug it, however, it shows the charging symbol.
![unplugged](https://user-images.githubusercontent.com/57071246/150562523-56592697-5a93-407d-bf1c-ab745c65963a.png).

Do you know if these problems are caused by fonts, system (I use arch btw) or if this is a bug?
Thank you!

**Comment by tobi-wan-kenobi** [comment]
Most likely fonts - do you maybe have font awesome version 5 configured?

Sorry about that, but the font config is an ongoing headache that is different for each distribution...

**Comment by matejp0** [comment]
I have `awesome-terminal-fonts`, which has Font Awesome 4.7.0, so I don't think this is the problem.

**Comment by matejp0** [comment]
Update: the second problem was caused by a hardware problem :)

**Comment by tobi-wan-kenobi** [comment]
@matejp0 Were you able to fix the second issue? Sorry for taking a while to get back to you!

**Comment by matejp0** [comment]
That's okay! :) The second issue was just a malfunctioning battery in my laptop, `acpi` was returning `Unknown` as the state of the battery. The first issue was, like you said, a problem with my font configuration. I tried changing my fonts etc. and eventually somehow got it to work :).
