### ISSUE TITLE
[modules/contrib] network module exits with error and breaks bumblebee-status

### ISSUE THREAD

**Issue by deadbeef2000** [tobi-wan-kenobi/bumblebee-status#849]
### Feature Request

I'd like to see the strength of the current wifi signal (in dBu, % or whatever you prefer) in the `nic` module and, if the signal turns really bad, a change of the background color to make it visible to the user. This is implemented in the default `i3status`.

(The part where it starts with W: in green letters)

![wifi_i3status](https://user-images.githubusercontent.com/30485424/153435362-8763577e-cf19-4beb-9ed8-952274db323e.png)

**Comment by tobi-wan-kenobi** [comment]
Hello!

There is a module similar to `nic` that, I believe, does what you want it to do - `network`. It's user-contributed, and as far as I can see, it shows signal strengths and reports a warning if the strength is below 75 (%, I assume?) and critical if it's below 50.

The limits are not configurable (yet), but that shouldn't be a lot of effort, if you require it.

Is that sufficient for your needs?

**Comment by deadbeef2000** [comment]
Thank you for your response ;)

I didn't see that module, as bumblebee 2.1.5 has just been updated in the aur (within the last few weeks).

Sadly though, it doesn't work for me. I'm sure it's a minor issue, but for anyone who'd like to fix it, here is the error: 

```
Error: Could not parse JSON (parse error: after array element, I expect ',' or ']')
```

**Comment by tobi-wan-kenobi** [comment]
Can you please add the command (theme, full list of modules, etc) that you used?

I just tested the network module in isolation, and that seemed to work (plus, it's not using JSON, I think)

Looks like there might be a regression in the latest release...

**Comment by deadbeef2000** [comment]
Command is just `bumblebee-status`

This is my current config file:

```
[core]
modules=pasink,neo,weather,network,cpu,load,memory,sensors,battery,uptime,time
theme=purple-powerline

[module-parameters]
time.format=%a %d.%m.%Y %H:%M:%S
time.interval=1s

# Playerctl: Hide buttons (Not used anymore)
#playerctl.layout=playerctl.song
#playerctl.format={title}
#playerctl.limit=20

# Notify me on pomodoro timer (Not used anymore)
#pomodoro.notify=notify-send "Pomodoro says: 'Time is up!'"

# Display only free memory to save space
memory.format={free}

# Hide traffic interface name (Not used anymore)
#traffic.showname=false
#traffic.exclude=lo,virbr,docker,vboxnet,veth,tun

# Hide interface name and status
nic.format={ssid} {ip} ({intf})
nic.states=^down
#nic.exclude=lo,virbr,docker,vboxnet,veth,br,.*:avahi,tun

# Hide I/O-Stats of zpool, hide pool name (Not used anymore)
#zpool.list=zroot,zroot-laptop
#zpool.showio=false
#zpool.format={shortstatus} {used}/{size}

# Hide weather city
#weather.showcity=false

# Disable overwriting of i3 config, exclude main screens (Not used anymore)
#xrandr.overwrite_i3config=false
#{% if yadm.hostname == "klaus" %}
#xrandr.exclude=DVI-I-1,DP-0
#{% endif %}
```

I'm using `yadm` for config file management, if you wonder what those `{% if xxxx %}` blocks are used for ;)

**Comment by tobi-wan-kenobi** [comment]
Can you please create a debug log (`-d`) or try without a theme? For JSON errors, the most likely culprit is the theme (though the file you posted parses just fine).

**Comment by deadbeef2000** [comment]
I figured it out, I needed to install `wireless_tools` in Arch for the `iwgetid` binary ;)

**Comment by tobi-wan-kenobi** [comment]
Glad it works for you now!

**Comment by deadbeef2000** [comment]
But I'm not quite done ;)

I'd like to have a combination of the `nic` and the `network` module, because I want to see the ip address and the strength... I think I look into merging those two and adding a swich to the `nic` module, which allows displaying of the wifi strength. I'll get back to you as soon as I've got a working build (if you're okay with extending the `nic` module with that functionality)

**Comment by deadbeef2000** [comment]
Okay, I've got a working version now, do we need a switch to disable the bandwidth measurement and the effects of it (e.g. warning state when signal strength < 75 and critical state when signal strength < 50). The limits are configurable though ;)

**Comment by tobi-wan-kenobi** [comment]
no, i think your PR is good the way it is - unless somebody complains :)

I'd say this issue can be closed, if that is fine with you.

Thank you very much for the PR!

**Comment by deadbeef2000** [comment]
Almost, just correct my typo in line 180: it should be `minimum` not `minium` :D
