### ISSUE TITLE
publicip prints "SPEC_VIOLATION: full_text is NULL!"

### ISSUE THREAD

**Issue by mihaimorariu** [tobi-wan-kenobi/bumblebee-status#853]
#### Description
Affected module: `modules/contrib/publicip.py`
Version used: latest (git)

If the Internet connection is down and the publicip module is running, "SPEC_VIOLATION: full_text is NULL!" is printed instead of "n/a".

![image](https://user-images.githubusercontent.com/1044197/153875838-bfea9ad9-21a3-4374-881e-75f2a78b2b52.png)

#### How to reproduce

1. Disable the Internet connection
2. Reload bumblebee-status

**Comment by tobi-wan-kenobi** [comment]
Should be fixed, many thanks for the report!

**Comment by mihaimorariu** [comment]
The __sun__ module is affected by this bug as well. Calling __data.get(name, default) (in the __get method of util/location.py) results in no exception being raised if a key is not available (such as when an Internet connection is down and __data does not get filled). In this case, the update method of __publicip__ will not execute the except branch, but return `None` instead.

**Comment by tobi-wan-kenobi** [comment]
Maybe the more general fix would be to throw in the location accessor methods, but I am not 100% confident about that approach....
