### ISSUE TITLE
Module arrows aren't displaying properly

### ISSUE THREAD

**Issue by BussySussy** [tobi-wan-kenobi/bumblebee-status#862]
#### Description
Affected module: all of them
Version used: AUR

<description>
The arrows that are usually at the end of the module is now a small square.
#### How to reproduce
I don't know how to reproduce this, I was doing some epic gaming and I quit the game and I notice the arrows are no longer there. I thought maybe because I closed the game with alt+f4 pressing that combination effected something with i3 but those buttons don't seem to do anything. It wouldn't make sense either because I've closed the game with alt+f4 in the past. I also tried a backup config I had and restarted my system.

https://ibb.co/F3NDTfN

I have the bar set to top by the way.

**Comment by tobi-wan-kenobi** [comment]
Sorry you are having issues!

The only 2 things that I can think of that cause this behaviour are either a bug in bumblebee (will check that), or that the awesome-fonts (version 4) package is missing.

Did you do an update or changed your i3 config (esp. the bar font config) recently?

**Comment by BussySussy** [comment]
I did not make any changes before I got this problem, I booted up my computer then ran startx and after playing this video game from steam I noticed this problem. I actually reinstalled my operating system yesterday but I kept a copy of the config file on a USB drive and put it into the folder and everything was fine after I reinstalled everything all day yesterday and today. The only font awesome package I have is just from pacman I don't really know how to specifically get version 4. Also using the font pengo (however it was spelled) to specify FontAwesome just made i3 bar huge. I even tried redoing makepkg to see if that would fix it and nothing.

**Comment by tobi-wan-kenobi** [comment]
Could you please post the "bar" section from your i3 config (just fonts plus bumblebee statis bar line), so that I can try to reproc the issue?

**Comment by BussySussy** [comment]
Here is the bumblebee status bar line in the config. I do not have a section for font, as before it only made the entire i3 bar huge and that is it. 

position top
        status_command /bin/bumblebee-status \
-m pasink disk date time \
-p time.format="%H:%M CW %V" date.format="%a, %b %d %Y" \
-t iceberg-rainbow

**Comment by tobi-wan-kenobi** [comment]
I can reproduce zhe issue, but only if I comment out all font definitions in my i3 config.

Can you please do 2 more things?

1. Please tell me which "font" config you have in your i3 config (outside the bar)

2. Please try - inside the bar section - adding "font pango:Hack 12" (and install ttf-hack, if necessary), to see if that fixes the issue

**Comment by BussySussy** [comment]
Alright, I found the font section and the one that it has is called "monospace 8". 

I changed it to "hack 12" and all it did was make everything huge and the arrows are still squares.

**Comment by tobi-wan-kenobi** [comment]
Ok, then it's definitely the font config - if you reduce 12 to 8, is the font size better?

Generally, for the powerline style themes, you need a powerline font (maybe installing the "powerline-fonts" package helps). If you still have the patience, could you please give that a try, and then use the "Inconsolata for Powerline" font?

Sorry to not have a clear answer, it's been a loooong time since I set up my Arch.

**Comment by BussySussy** [comment]
Yes, setting it to 8 made it the correct size, I assumed the number meant font size. I installed powerline fonts and tried using the Inconsolata for Powerline by putting
`font pango:Inconsolata for Powerline 8` 
in both the regular font section, plus the one I made in the bar section, tried using hack in one and inconsolata for powerline in the other and vice versa and nothing is working. I don't understand why it just broke to begin with since it was working fine yesterday, on my previously installed system and in the virtual machine I made before. I'd think if it was a missing font problem it wouldn't work from the get go? 

Is there possible a file saved by bumblebee status I could edit, delete or replace? Maybe I need to completely reinstall i3 or the status bar? Maybe there's a problem with xorg???

**Comment by tobi-wan-kenobi** [comment]
Yeah, that part (that it stopped working suddenly) also confuses me a lot.

I'd rule out X issues, bexause what's happening behind the scenes is this:

bumblebee-status produces text output (JSON) that i3 interprets and draws. The arrow is simply another character - but a special one that is only defined in the powerline fonts (otherwise you DO get the box character for "unknown glyph)

Just out of curiosity, do you think you could clone bumblebee-status from git and try that version (just configure the path to the bumblebee-status binary of the git checkout)? That would tell us if any of the files in the themes of bumblebee were modified.

**Comment by tobi-wan-kenobi** [comment]
One more thing you can try on the i3 "bar" section is a config like this:

font: pango:Hack 8, pango:FontAwesome 8

That *should* define FontAwesome as fallback and might give you the separator arrow

**Comment by BussySussy** [comment]
Adding font: pango:Hack 8, pango:FontAwesome 8 just completely broke the status bar. screenshot: https://ibb.co/JqGx0T0

The reason I used the AUR version is because I don't know how to use the git version and I don't really know where this binary would be located.  I assume the "bin" folder is short for binary, but directing the status to the folder gives me an error (status_command is not executable (exit 126)) instead of a theme, I tried doing the "sh" command on the sh files and tried specifying different folders in the file I got from git, I really don't know how to use it. 

Now the only thing I did differently from what I would usually do before I noticed is that I ran "steam-runtime" instead of just steam, but I don't think that would effect this and I didn't really look at it before launching the game as I just booted up my computer.

**Comment by BussySussy** [comment]
I'd say it's possible there's conflicting fonts. I used pacman to installed ttf-liberation and then I used yay to install some windows 10 fonts because I thought I needed them for something and haven't rebooted until today. Is there a way I can verify the required fonts for the bumblebee-status bar?

**Comment by BussySussy** [comment]
Ok, after completely messing up i3 for messing with copies of the config file and rebooting, then deleting the font section under the bar section, reloading i3 the arrows are back, BUT the offset is weird. I think I saw something about this in an older post on here so I will check that out. I will still appreciate a reply to fix that too but I'll be sure to update this if something goes wrong. 
In the config I only have the one font section at the start and with the font "monospace 8" selected and it's working with what I said earlier in this message.

**Comment by BussySussy** [comment]
Although it looks to be just a millimeter off, the arrow itself looks too small comparing to a screenshot I took before I got any problems. Changing font sizes makes the whole bar bigger which isn't what I want and it seems specifying any font for any reason in any way other than monospace turns the arrows into squares again.

**Comment by tobi-wan-kenobi** [comment]
Yeah, a lot of fonts seem to have this "arrow is slightly off" issue :(

The only other thing I can think of is tocmanually try to install the Powerline fonts from github, but not sure how much that would bring...

**Comment by BussySussy** [comment]
Do you think it would be effective to completely delete all traces of bumblebee status and reinstalling?

**Comment by tobi-wan-kenobi** [comment]
I honestly don't think so, because bumblebee just provides the text, how it is actially rendered is purely up to the font config.

**Comment by BussySussy** [comment]
Sorry for the late reply, I fell asleep and was busy when I woke up. I just tried installing the powerline fonts from github and using Hack on the first font section fixed the size of the arrow, and I believe the offset was caused by it being too small. Everything is good now.

**Comment by tobi-wan-kenobi** [comment]
Happy to hear that, glad you were able to solve the issue!
