### ISSUE TITLE
add modules next to workspaces

### ISSUE THREAD

**Issue by mjgritli** [tobi-wan-kenobi/bumblebee-status#867]
### Feature Request

Dear dev team

Thank you for your awesome work on this status bar.
But, can we get the ability to add some modules after the workspaces, for example (window title) instead of stacking all modules to the right.

Thank you

**Comment by tobi-wan-kenobi** [comment]
Hello,

thank you for yout kind words!

Unfortunately, what you are mentioning is a limitationin the i3bar itself, and bumblebee-status can do nothing about it (i.e. left align of the bar is not possible)

If you need that functionality, I would recommend looking into differet bars, such as lemonbar or the excellent polybar.
