### ISSUE TITLE
Shadow for each cycle

### ISSUE THREAD

**Issue by EliaHKM** [tobi-wan-kenobi/bumblebee-status#879]
### Feature Request
Hi 🙋,
I would like to 
make the bar 
similar to elementary
gtk theme (not flat)
so if possible to add 
shadow to each cycle 
thank you a lot for 
that masterpiece

**Comment by tobi-wan-kenobi** [comment]
Thank you for your kind words :)

Unfortunately, adding a shadow for each element is not possible.

It works like this: i3 itself (the i3bar, to be precise) draws the status bar, bumblebee-status simply provides the data and a bit of styling info (colors, mostly) as plain text (JSON).

I guess you might be able to achieve a shadow effect for the bar by using a compositor such as picom, maybe, but I am not very knowledgable about that.

**Comment by EliaHKM** [comment]
thank you 
a lot 
☺️
it's the 
fastest reply 
on github
thank you
a lot and 
keep the
great
working 
 
have a 
good day

**Comment by tobi-wan-kenobi** [comment]
Have a good day, as well!

(speed is thanks to the great github mobile app)
