### ISSUE TITLE
Add manual pages

### ISSUE THREAD

**Issue by benthetechguy** [tobi-wan-kenobi/bumblebee-status#882]
### Feature Request
It's generally recommended to include manual pages for any programs you install to `[/usr]/bin`, and many distributions' packaging policies require it. I'm packaging this program for Debian, so I had to write manpages for `bumblebee-status` [1] and `bumblebee-ctl` [2].
All I'm asking for is the inclusion of these manpages in this repo, but installing them to `/usr/share/man/man1` would be a nice bonus.

[1] https://salsa.debian.org/python-team/packages/bumblebee-status/-/raw/master/debian/bumblebee-status.1
[2] https://salsa.debian.org/python-team/packages/bumblebee-status/-/raw/master/debian/bumblebee-ctl.1

**Comment by tobi-wan-kenobi** [comment]
Very nice,bmany thanks!

I will definitely include those!

Apologies in advance if it takes a while, but I am quite busy with my day job right noelw, and it might take a bit until I can do this properly, sorry!
