### ISSUE TITLE
Prebuilt C binary in source

### ISSUE THREAD

**Issue by benthetechguy** [tobi-wan-kenobi/bumblebee-status#883]
Instead of having an x86_64 Linux binary hanging around in your source, maybe it would be better to compile it at build time. There are other architectures out there, you know.
It would be preferable if there were no C code in this Python module at all, because the built package could be architecture independent.

**Comment by anarcat** [comment]
agreed. this seems to converge towards #790 as well: there should be just one layout module, and I personally think it should be the python version, not the C stub.

(or, if it's a C stub, it should be a pyx stub. :)

**Comment by tobi-wan-kenobi** [comment]
Just removed everything precompiled and fall back to the python xkb module.

Now, I am waiting for the bug reports about broken layout module coming in :)

Thanks for your valuable input everyone!
