### ISSUE TITLE
can you say me how can i use pulse audio 

### ISSUE THREAD

**Issue by chinmayasamant007** [tobi-wan-kenobi/bumblebee-status#894]
#### Description
Affected module: <pulseaudiio>
Version used: <e.g. latest git, AUR, PIP>

<description>

**Comment by tobi-wan-kenobi** [comment]
`bumblebee-status -m pasink pasource`

pasink is output (headphones) and pasource is microphone, iirc.

Hope this helps!

**Comment by chinmayasamant007** [comment]
Thank you

**Comment by chinmayasamant007** [comment]
Can you say me how can I use Bluetooth in Linux

**Comment by tobi-wan-kenobi** [comment]
@chinmayasamant007 If I understand your question correctly, this is unfortunately the wrong place to ask.

For understanding bluetooth in Linux, there is a lot of documentation on the internet, specific for each distribution. Arch Linux has extensive docs on it, for example: https://wiki.archlinux.org/title/bluetooth

If the documentation of your diszribution is insufficient, please try their forums or subreddits.

Thanks!
