### ISSUE TITLE
vpn module will make bumblebee-status spike cpu if no vpn profile is selected

### ISSUE THREAD

**Issue by nwildner** [tobi-wan-kenobi/bumblebee-status#898]
#### Description
Affected module: `vpn`, but additionally, maybe some other `bumblebee-status` component that handle menus.
Version used: main branch, directly from git.

If you have multiple OpenVPN profiles on NetworkManager, and by accident you hover your mouse out of the VPN drop-down menu or, you decide to not connect on a vpn by going back to the module and clicking on it, this will make the drop-down menu unavailable, and cpu usage spike on bumblebee-status processes. 

#### How to reproduce
1 - Have multiple vpn profiles configured on NetworkManager(currently, tested only with OpenVPN ones)
2 - Click on the vpn module(currently off) to activate drop-down menu
3 - "Accidentally" move your mouse out of the menu
4 - Open `top` or `htop` and check out that `bumblebee-status` will be consuming a lot of cpu. Laptop users will hear the fans start to work louder:

![image](https://user-images.githubusercontent.com/11742211/177461860-620cfa4a-6f90-42d6-8dbb-c2c04070f1ad.png)

#### Workaround
1 - Reload your DE(in my case, `i3wm`)

#### Expected behavior
1 - Moving the mouse out of the menu or clicking back on the module should only collapse/hide the menu without using extra CPU.

**Comment by tobi-wan-kenobi** [comment]
@bbernhard I think that module is originally developed by you - have you observed that as well, or do you have any idea where that could come from?
Thank you!

**Comment by bbernhard** [comment]
@nwildner what do you exactly mean by "move your mouse out of the menu"? When I do that, the popup window immediately closes. Is that the same for you? For me, `bumblebee-status` only consumes more CPU while the popup is shown. As soon as the popup closes (which it does when I move the mouse outside of the popup), the CPU usage drops again.

Unfortunately, I do not know much about the internals of tkinter, but I think most GUI frameworks paint in the main thread. So I guess a higher CPU usage could be normal while the popup is shown?

**Comment by tobi-wan-kenobi** [comment]
Closing due to a combination of inactivity and "could not reproduce" (many thanks to @bbernhard for testing!)
