### ISSUE TITLE
Scrolling on spotify module doesn't work

### ISSUE THREAD

**Issue by Syzygianinfern0** [tobi-wan-kenobi/bumblebee-status#903]
#### Description
Affected module: spotify
Version used: master branch

#### How to reproduce

```python
spotify.concise_controls = True
spotify.layout = spotify.song
spotify.scroll.width = 10
spotify.scroll.speed = 1
```

I have this in my config, but the spotify module doe not seem to have scrolling text.

**Comment by Syzygianinfern0** [comment]
@tobi-wan-kenobi 

> I think you need to set a fixed width, as well.

I do set a fixed width (`spotify.scroll.width = 10`). 

> Also, how is it broken?

It doesn't scroll at all. Just behaves like a normal widget.

**Comment by Syzygianinfern0** [comment]
Thanks!

**Comment by tobi-wan-kenobi** [comment]
@Syzygianinfern0 finally got around to fixing this. I tried to test it with fake binaries, but since the module uses dbus, I am not 100% sure I didn't break anything.

If you could let me know whether the module now works as intended for you, I'd appreciate that a lot!

**Comment by Syzygianinfern0** [comment]
@tobi-wan-kenobi Thanks! It works splendidly!! :hugs: :heart:
