### ISSUE TITLE
publicip doesnt catch changes

### ISSUE THREAD

**Issue by HappyCthulhu** [tobi-wan-kenobi/bumblebee-status#909]
#### Description
Affected module: publicip
Version used: git

When i use VPN, my publicip doesnt change at all. Why is this happening and how can we fix it? I know about this:
https://github.com/tobi-wan-kenobi/bumblebee-status/pull/899. And that why i was supriced with this behaviour.

I recorded this bug: https://youtu.be/QZ-bHsPlI_U

#### Enviropment: 
- Ubuntu 20.04

#### How to reproduce
- enable VPN

part of my i3-config:
```
bar {
	#status_command i3status --config $HOME/.config/i3/i3status.conf  | /bin/_change_layouts
	tray_output eDP1
	position top
    
    font pango:Inconsolata 10
	status_command ~/.config/i3/bumblebee-status/bumblebee-status \
        -m layout-xkb \
        -m pasink \
        -m battery \
        -m time \
        -m date \
        -m nic \
        -m publicip \
        -m disk:root \
        -m cpu \
        -m memory \
        -m docker_ps \
        -m arandr \
		-p root.path=/ \
        -p time.format="%H:%M" \
        -p date.format="%a, %-d %-m" date.left-click="zenity --calendar" \
        -p battery.device="BAT1" \
        -p nic.exclude="lo,enp0s25,docker0,br-0e4b347152f3" \
        -p nic.format="{ssid} {ip}" \
        -p memory.format="{percent:05.02f}%" \
        -p disk.format="{left}" \
		-t nord-powerline

    colors {
    background #2f343f
    # statusline старого цвета. Нужно заменить, когда цвет шрифта i3status изменю
    statusline #ffffff
    separator #4b5262

    # colour of border, background, and text
    focused_workspace   #2f343f #4779e6 #d8dee8
    active_workspace    #2f343f #bf616a #d8dee8
    inactive_workspace  #2f343f #2f343f #d8dee8
    urgent_workspace    #2f343f #ebcb8b #2f343f
    }

}
```

**Comment by tobi-wan-kenobi** [comment]
If you click on the module, does it change then?

I see two possible reasons:

A)
I fixed a bug in the module where the module wouldn't shut down, thus blocking autotest.

At that time, I believe, I accidentially changed the code so that changes take an hour to register :(

B) Does the VPN introduce a default route?

I think A is more likely, if so, the module will change the public IP if you click on it.

Thanks a lot in advance!

**Comment by HappyCthulhu** [comment]
yeah, after click it changes O_o. 

Can u decrease register time? Or u wanna leave it like that like a feature? If u choose last option, i have many questions for this feature)

**Comment by tobi-wan-kenobi** [comment]
OK, great that there is a workaround at least.

I definitely want to fix it, like this: There is a check for changes in the default route, and I will fix it so that this is done more frequently. Ie your default route changes -> public IP updates instantly.

I will just need a couple of days (maybe the weekend) to get around to that.

**Comment by HappyCthulhu** [comment]
sounds great)
Cant wait to pull this

**Comment by HappyCthulhu** [comment]
sounds great)
Cant wait to pull this

**Comment by tobi-wan-kenobi** [comment]
@HappyCthulhu Hope this works for you, please let me know!

(I was not able to fully test this, as I have no VPN that changes my default route, but the changes *look* save)

**Comment by tobi-wan-kenobi** [comment]
Sorry to hear that, will continue investigating!

**Comment by tobi-wan-kenobi** [comment]
@HappyCthulhu Hope this works now - I did some testing with removing/readding my own default route, and it *seems* to work stable now.

**Comment by HappyCthulhu** [comment]
yeah, rn its working stable. Big thanks for improvement! Should i close this issue?

Btw, another error happened: "error: pactl info exited with code 1"

How should i understand, what happened? I`ve seen this issue: https://github.com/tobi-wan-kenobi/bumblebee-status/issues/746, but this guy didnt tell, waht caused this problem)

**Comment by tobi-wan-kenobi** [comment]
Yes, if you see another issue, please definitely open another ticket.

Thank you for your patience!
