### ISSUE TITLE
Public IP documentation and attribution

### ISSUE THREAD

**Issue by tfwiii** [tobi-wan-kenobi/bumblebee-status#910]
### Feature Request

Hi, would you update the Public IP module documentation please. I would also really appreciate the attribution being included as I'm trying to bulk out my dev portfolio at the moment :)

![image](https://user-images.githubusercontent.com/877400/183239984-3de11ed3-dd36-4926-a5ac-892938d71077.png)

**Comment by tobi-wan-kenobi** [comment]
Sure enough! Sorry that slipped through.

I will do that as soon as I am in front of a laptop again, for sure today!

**Comment by tobi-wan-kenobi** [comment]
Should be live now, @tfwiii !

Again, thank you kindly for your contribution!

**Comment by tfwiii** [comment]
> Should be live now, @tfwiii !
> 
> Again, thank you kindly for your contribution!

Thank you :)
