### ISSUE TITLE
Counter intuitive color of pulseaudio in nord-powerline theme

### ISSUE THREAD

**Issue by HappyCthulhu** [tobi-wan-kenobi/bumblebee-status#913]
#### Description
Affected module: pulseaudio
Theme: nord-powerline
Version used: git

Thats not some crusial bug. Just proposal:

When sound enabled, color in more red, that when audio disable.
Check it out:

Enabled:

![image](https://user-images.githubusercontent.com/23531195/184097581-e3fa325a-5d5d-4d29-aef0-57b97d3003dd.png)

Disabled:
![image](https://user-images.githubusercontent.com/23531195/184097603-fe10bc3c-e01b-499a-b492-746688a145b6.png)

Maybe will be better to swap with each other? Or take another colors

**Comment by tobi-wan-kenobi** [comment]
Ah, I see.

Yes, on first glance, that does look strange, but consider it like this:

- Disabled is in state "warning" (typically yellow/orange-ish) - because muted might be totally fine, but it's worth noting
- The first picture is red because it is in a "severe" state (> 100% volume) - if you tone down the volume to less than 100%, you should have it revert to a green-ish color.

Does that match your expectation better?

**Comment by HappyCthulhu** [comment]
And now thats looks fine. What the hell...

![image](https://user-images.githubusercontent.com/23531195/184337332-242c8441-15c8-49d5-ad8d-37181a2f1e4a.png)

**Comment by HappyCthulhu** [comment]
Oh, now i understand. I have old Thinkpad and 100% volume is never enough, so i could understand, why red color were used. Bc for me >100% volume is totally fine behaviour.

**Comment by HappyCthulhu** [comment]
For me, red color is not cool solution, but, mb for another users that makes sense. Idk...

**Comment by tobi-wan-kenobi** [comment]
I get your point, and will think about a way to fix this.

**Comment by tobi-wan-kenobi** [comment]
@HappyCthulhu Thank you for your patience, I removed the code in question, the volume should now be shown as normal also at more than 100% volume.

**Comment by HappyCthulhu** [comment]
Appreciate it, u did great job! 

I have another question:
When i set up i3status without bumblebee-status, it response much quicker. Like, instantly. And with bumblestatus it takes second to display volume changes. Is it something, that u could fix in few minutes or this is hard to fix?

**Comment by tobi-wan-kenobi** [comment]
It is on my TODO list, but is a bigger change (right now, volume is polled and I will need to switch to an event-based mechanism)

Hint: In the meantime, if you change the volume via bumblebee-status (mouse wheel), the change is instant.

**Comment by HappyCthulhu** [comment]
Wow, that's cool. Didn't know about that actually

**Comment by tobi-wan-kenobi** [comment]
@HappyCthulhu I added some (experimental) code in `main`, can you please let me know if it works for you?

All you need is `pactl` installed. Then, the modules should monitor the pulseaudio events & do some filtering to not consume too much CPU.

**Comment by HappyCthulhu** [comment]
![image](https://user-images.githubusercontent.com/23531195/187529235-888e848a-923d-48d6-a9c7-047fb16b3789.png)
Oh man)))

Should i reverse that pull?

**Comment by tobi-wan-kenobi** [comment]
give me a sec, i probably missed a print...

**Comment by tobi-wan-kenobi** [comment]
Weird, works for me. I will pull out the changes & look at them in the next couple of days, it's getting late here :)

**Comment by tobi-wan-kenobi** [comment]
Changes should be reverted, if you do another pull, sorry for the hassle!

**Comment by HappyCthulhu** [comment]
No worries)
I can give u link to my i3 config of it can be useful

**Comment by tobi-wan-kenobi** [comment]
yes, please!

**Comment by HappyCthulhu** [comment]
What, maybe I didn't enable pactl? I thought, that I enabled it, but now I see, that I didn't. Can I switch to some branch and test your feature again?

**Comment by HappyCthulhu** [comment]
Can u create new branch and push recent changes to it?

**Comment by tobi-wan-kenobi** [comment]
Will do that tomorrow & let you know!

**Comment by tobi-wan-kenobi** [comment]
@HappyCthulhu tracking that as #917 , the topic deserves its own ticket :)

Also, I created the branch `917-event-based-pulseaudio` for the changes.
