### ISSUE TITLE
an issue with tray_output

### ISSUE THREAD

**Issue by Lithi27** [tobi-wan-kenobi/bumblebee-status#915]
Affected module: <module name>
none
Description:
<description>
the only way for me to see tray icons (which is something i need because of network manager applet) is to leave tray_output as blank, but whenever i do that, i3 gives me an error warning.

this is the output:

 ERROR: CONFIG: Expected one of these tokens: <word>
ERROR: CONFIG: (in file /home/lithi/.config/i3/config)
ERROR: CONFIG: Line 187:        position top
ERROR: CONFIG: Line 188:        tray_output
ERROR: CONFIG: Line 189:        status_command ~/.local/bin/bumblebee-status -m pasink pasource network_traffic cpu             memory battery date time           -p root.path=/ time.format="%H:%M CW %V" date.format="%a, %b %d %Y"             -t nord-powerline
ERROR: CONFIG:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR: CONFIG: Line 190: }
ERROR: FYI: You are using i3 version 4.20.1 (2021-11-03)
ERROR: Received ConfigureNotify for unknown window 0x00a00000
ERROR: Received ConfigureNotify for unknown window 0x00a00000
ERROR: Received ConfigureNotify for unknown window 0x00a00008
ERROR: Received ConfigureNotify for unknown window 0x00a00008
ERROR: Received ConfigureNotify for unknown window 0x00a0000d
ERROR: Received ConfigureNotify for unknown window 0x00a0000d
ERROR: Received ConfigureNotify for unknown window 0x00a00012
ERROR: Received ExposeEvent for unknown window 0x00a00012
ERROR: Received ConfigureNotify for unknown window 0x00a00012

**Comment by tobi-wan-kenobi** [comment]
I think it needs to be "tray_output none", but that means you will *not* have a tray on this screen (which is ok if you have multiple screens)

Otherwise, it should be "tray_output <whatever screen this is, as per xrandr output>", for example "tray_output eDP1"
