### ISSUE TITLE
Unable to load module arandr, weird looking status bar

### ISSUE THREAD

**Issue by HappyCthulhu** [tobi-wan-kenobi/bumblebee-status#922]
#### Description
Affected module: arandr
Version used: AUR

<description>
Im installing bumblestatus on new system. All modules looks good, except arand.
Also, what are thoose weird arrows on the edge of every module? How can i fix them?

![image](https://user-images.githubusercontent.com/23531195/189534163-bf4a93c3-6ced-4e5e-99af-9699643ed5de.png)

**Comment by HappyCthulhu** [comment]
Ofc, arandr is installed:

```
> arandr --version
arandr 0.1.10
```

**Comment by HappyCthulhu** [comment]
Ofc xrandr is installed. Or u r talking about smth else?

```
> whereis xrandr
xrandr: /usr/bin/xrandr /usr/share/man/man1/xrandr.1.gz
[N] [11:58:22] user@ArchLinuxDesktop /home/user
> file /usr/bin/xrandr
/usr/bin/xrandr: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=da732b08a895a0376cbbf685e76820386a048d44, for GNU/Linux 3.2.0, stripped
```

Idk, arandr is bad package, i dont think, that i`ll be using it. But, if u r interesting in investigation this issue, i can help.

P.S. Yeah, u were right about fonts. Change to Hack and everything is fine now

**Comment by tobi-wan-kenobi** [comment]
Cool, thanks!

Ah, I think I know: For the `arandr` module, you need the `tkinter` python package, and people usually miss that one.

I should *really* find a way to point that out gracefully (maybe by showing that somewhere prominent)

**Comment by HappyCthulhu** [comment]
That's easy. Just add it to your wiki. I didn't install Tkinter only bc wiki part, related to arandr module doesn't consist info about a Tkinter

![image](https://user-images.githubusercontent.com/23531195/190848480-15202d74-86e6-45c1-b26a-e52f4853d5ef.png)

**Comment by tobi-wan-kenobi** [comment]
heh, yes it's an indirect dependency pulled in by the popup, i think.

does it work now?

**Comment by HappyCthulhu** [comment]
Btw, I have an idea. Idk, is it good or not, so, IA wanna feedback 

Maybe it will be cool, if this repo will consist requirements file with all dependencies, that needed for all modules? Whet I installed bumbestatus for first time, I spend some time to collect all of them. From my point of view, requirements file will save time for users

**Comment by tobi-wan-kenobi** [comment]
yeah, if it is up to date that would be good.

also, some deps are optional, so a bit difficult :(

**Comment by HappyCthulhu** [comment]
> yeah, if it is up to date that would be good.
> 
> also, some deps are optional, so a bit difficult :(

Yeah. But. I mean, who cares?)))
If someone don't want to install additional deps, he can do manual installation.

Also, maybe nice desidion to create pyqt or web app with nice easy interface:
U have list of all modules, u pick ip only modules, that u want to install and this app create u bash command with all modules, that u need to install. If u like this idea, a can help with realization

**Comment by tobi-wan-kenobi** [comment]
Heh, true.

A website or something like that for generating configs would be really cool, I think. Maybe even with a preview.

If you can do something like that, that'd be great to see (I am a backend dev, and don't have a lot of spare time, so I'd be pretty useless for that, honestly)

**Comment by tobi-wan-kenobi** [comment]
addition: actually, there *is* the requirements/ folder, but it seems outdated and is missing arandr altogether

**Comment by HappyCthulhu** [comment]
Yeah, i can try. I was nice python automation engineer previously. But i wanna be backend dev rn. So, i can craft some shit code (because im not greate in this rn) on Django on smth else. 

How should we do this? Like, i will create git repo, host on some site, so u can test it. When i finish this projects, u will host this app on one of your services? I understand, that i can just make fork. But im not sure, that this project must be part of bumblee-status repo. I mean, that look like smth, that doesnt need to be in this repo... Am i wrong?

**Comment by tobi-wan-kenobi** [comment]
that is a good question. tbh, i would prefer that to be a community-driven project (ie something i am not responsible for), bumblebee-status already binds a lot of my free time. also, i don't have any kind of hosting infrastructure.

i think that theoretically, it should be possible to host such a site purely statically on something like github pages and do the logic in client-side javascript, but i don't know for sure. but that is the way i would suggest to approach it.

**Comment by tobi-wan-kenobi** [comment]
and absolutely can and should be in a separate repo, in my opinion.

**Comment by HappyCthulhu** [comment]
yeah, ok. Hosting is never a problem. I have small server, which i can use for this purpose, if this will be needed

**Comment by HappyCthulhu** [comment]
U know, what will be cool? Did interface, that could work from shell. Curl queries. Somethink like:
```
curl cheat.sh/psql
```

(just type it in console if u r not familiar with cheat.sh)

**Comment by tobi-wan-kenobi** [comment]
oh yeah, that'd be nice :) thanks for the ideas!

**Comment by tobi-wan-kenobi** [comment]
Tracking this idea as #928 , so as to not "pollute" this ticket, which is resolved.

Thanks a lot @HappyCthulhu !
