### ISSUE TITLE
nic module: SPEC VIOLATION: full_text in NULL!!

### ISSUE THREAD

**Issue by HappyCthulhu** [tobi-wan-kenobi/bumblebee-status#925]
#### Description
Affected module: nic
Version used: AUR

#### How to reproduce
Try to disable your network. This is what u will see:
![image](https://user-images.githubusercontent.com/23531195/190359368-e6d9563d-9108-4b98-a6b1-e98798a04121.png)

Thats looks like code-error. Like smth, that doesnt need to be in statusbar)

**Comment by tobi-wan-kenobi** [comment]
Could you please check if this issue is gone in the git AUR? I cannot reproduce it there, and I am about to release a new version anyhow...

**Comment by tobi-wan-kenobi** [comment]
Please let me know if this still occurs with 2.1.6, thank you!

**Comment by HappyCthulhu** [comment]
Checked on AUR version of bumblee-status. Everything is fine, u can close this issue

**Comment by tobi-wan-kenobi** [comment]
Thanks for reporting back!
