### ISSUE TITLE
Slow-response of pasink block

### ISSUE THREAD

**Issue by HappyCthulhu** [tobi-wan-kenobi/bumblebee-status#931]
#### Description
Affected module: pasink
Version used: AUR, git

<description>

So, i remember, that u fixed this issue. But now its happening again. Im now on AUR version, also tested this issue on git version (main branch). I have nice PC right now, so it doesnt related with weak CPU. 

Can u reproduse it? Maybe u just merge something wrong on main?

**Comment by tobi-wan-kenobi** [comment]
Could you please try to use pulsein and pulseout instead?

I created those two modules (using the pulsectl python module, which you will need to install) to fix the issues you reported.

They are drop-in replacements for pasource and pasink and have exactly the same parameters.

**Comment by HappyCthulhu** [comment]
Got it. Yeah, pulseout is really fast
