### ISSUE TITLE
[Brightness] I can't change brightness level 

### ISSUE THREAD

**Issue by theWhiteRabbit511** [tobi-wan-kenobi/bumblebee-status#936]
#### Description
Affected module: brightness
Version used: latest git

<description>

#### How to reproduce
i just installed the package and all the suggested dependencies, then i add the brightness module in the status command of my i3 config.
However for some reason that i didn't get, the brightness module on the bar is completely static, through it i cannot change brightness level by scrolling or in any other interactive way.  What can be the causes?

**Comment by tobi-wan-kenobi** [comment]
If you use commandline tools such as xbacklight or light, does the backlight change?

**Comment by theWhiteRabbit511** [comment]
> 

neither :(

**Comment by tobi-wan-kenobi** [comment]
OK, then it probably is not an issue caused by bumblebee, but something on the system.

Is it a laptop? And if so, can you please let me know the graphics chip (lspci)? Sometimes, you need specific drivers or settings to support backlight.

**Comment by theWhiteRabbit511** [comment]
I have two graphics card in my laptop one dedicated nvdia rtx 3050 m and one integrated amd ati 05:00.0 Lucienne that i think i'm using right now

**Comment by tobi-wan-kenobi** [comment]
Hmmmm, maybe you have to use the other one? Or maybe you need special drivers or userspace tools.

Sorry for not being able to help more, but maybe this gives you some pointers already.

**Comment by theWhiteRabbit511** [comment]
don't worry i thank you so much anyway, you're really helpful

**Comment by tobi-wan-kenobi** [comment]
no worries!

I foind this pretty thorough, maybe t is useful:

https://wiki.archlinux.org/title/backlight

**Comment by theWhiteRabbit511** [comment]
thanks to the wiki i achieve to make xbacklight working but brightness still static and not interactive, and if want it to display the exact value of brightness i have to reload i3

**Comment by tobi-wan-kenobi** [comment]
Can you please uninstall light again, afaicr, bumblebee uses light and falls back to xbacklight, if light is not available.

**Comment by theWhiteRabbit511** [comment]
Problem solved ty!
I give  sudo pacman -Rns light acpilight brightnessctl then reboot and then i reinstalled them and now everything work fine.

**Comment by tobi-wan-kenobi** [comment]
Oh, that is great to hear, thanks!
