### ISSUE TITLE
MPD Module has no facility to specify port

### ISSUE THREAD

**Issue by l1dge** [tobi-wan-kenobi/bumblebee-status#941]
#### Description
Affected module: mpd
Version used: AUR 2.1.6-1

If your mpd server is running on a non-default port there is no way to specify the port in the module settings.

#### How to reproduce

If you run the mpd module in your bumblebee config it will not appear in the status bar if your mpd server runs on a non-default port.

A simple fix I did was to change the code in the mpd.py file as follows:

Added the second line to the docstring:

```COMMENT
    * mpd.host: MPD host to connect to. (mpc behaviour by default)
    * mpd.port: MPD port to connect to. (mpc behaviour by default)
```

Replaced this code:
```PYTHON
if not self.parameter("host"):
            self._hostcmd = ""
        else:
            self._hostcmd = " -h " + self.parameter("host")
```

with this:
```PYTHON
if not self.parameter("host"):
            self._hostcmd = ""
        elif self.parameter("host"):
            if not self.parameter("port"):
                self._hostcmd = " -h " + self.parameter("host")
            else:
                self._hostcmd = " -h " + self.parameter("host") + " -p " + self.parameter("port")
```

Everything functions as expected after the change.

**Comment by tobi-wan-kenobi** [comment]
Thanks for the report @l1dge , and for the fix suggestion!

Hope this commit fixes it (I am not using mpd, so I have a hard time checking it). I slightly cleaned up the code while at it, if I introduced any issues, please do let me know.

Thank you kindly!

**Comment by l1dge** [comment]
@tobi-wan-kenobi Works great, thanks for the quick turnaround.
