### ISSUE TITLE
BumbleBee not working

### ISSUE THREAD

**Issue by Bcez** [tobi-wan-kenobi/bumblebee-status#944]
Affected module: none
Description:
Installed  Bumblebee status using pip,  when put in config with the modules,  paramters,  and theme i get an error
![Screenshot from 2022-12-05 14-54-39](https://user-images.githubusercontent.com/80232341/205730847-bbaba8c6-59aa-42f4-a13a-ac57431c790b.png)
 

here is my config for the bar
` bar {
    position top
    height 30
    status_command ~/.local/bin/bumblebee-status -m network playerctl pulseaudio arch_update battery bluetooth2 date time \
        -p time.format="%H:%M CW %V" date.format="%a, %b %d %Y" \
        -t solarized-powerline
    font pango: FontAwesome 10, JetBrainsMono Nerd Font Bold

    colors {
        separator               $text
        background              $background
            statusline          $text
        focused_workspace       $text           $text           $background
            active_workspace    $inactive       $inactive       $background
            inactive_workspace  $background     $background     $text
            urgent_workspace    $error          $error          $background
    }
} `

If you are having problems with fonts, please read:
https://github.com/tobi-wan-kenobi/bumblebee-status/issues/228
https://github.com/tobi-wan-kenobi/bumblebee-status/issues/210
https://github.com/tobi-wan-kenobi/bumblebee-status/issues/197
https://github.com/tobi-wan-kenobi/bumblebee-status/issues/233

Please note FontAwesome 5 is currently not supported:
https://github.com/tobi-wan-kenobi/bumblebee-status/issues/239

**Comment by tobi-wan-kenobi** [comment]
Hi,

most likely, a Python module is missib.

2 options:

* Please install the latest git version to get a nicer error message
* enable debug mode with "-d -f /tmp/bumble.log" and look at the error message in /tmp/bumble.log

Hope that helps!

**Comment by tobi-wan-kenobi** [comment]
yes, there is wal-powerline.

the log looks ok, can you narrow it down to a specific module my removing one at a time, maybe?

Sorry for the issues!

**Comment by Bcez** [comment]
ok so i still get the same error. idk what is happening

**Comment by Bcez** [comment]
i removed every modules
one by one

**Comment by tobi-wan-kenobi** [comment]
Can you please tun the command directly in the terminal and paste the output here, please? just to check the format?

**Comment by tobi-wan-kenobi** [comment]
Also: Which version are you using?

**Comment by Bcez** [comment]
~/.local/bin/bumblebee-status -m pulseaudio \
    -p time.format="%H:%M CW %V" date.format="%a, %b %d %Y" \
    -t solarized-powerline  
and the lastest package from pip

**Comment by Bcez** [comment]
{"version": 1, "click_events": true}
[
{"version":1}
[
[{"full_text": " Module.__init__() missing 1 required positional argument: 'channel' ", "background": "#ff0000", "color": "#ffffff", "name": "error", "instance": "the-only-one"}],
[{"full_text": " Module.__init__() missing 1 required positional argument: 'channel' ", "background": "#ff0000", "color": "#ffffff", "name": "error", "instance": "the-only-one"}],

**Comment by tobi-wan-kenobi** [comment]
Yeah, pulseaudio cannot be used directly, you need to use pulsein and/or pulseout instead.

If you remove pulseaudio and use a simpler module such as cpu, dies it work then?

**Comment by Bcez** [comment]
I have to check later since i am at school rn

**Comment by Bcez** [comment]
yea it does,  what should i use to show volume then?

**Comment by tobi-wan-kenobi** [comment]
So, pulseaudio is actually managed by two modules:

pulsein for microphones and pulseout for headsets etc.

Do those two work for you?

BTW: You are by far not the first person to be falling into the pulseaudio trap, I need to find a better solution for this :(

Thank you for your patience!
