### ISSUE TITLE
Bumblebee status doesn't register clicks after a while

### ISSUE THREAD

**Issue by wwsmiff** [tobi-wan-kenobi/bumblebee-status#948]
#### Description
Affected module: all modules
Version used: AUR and latest git
i3 WM version: 4.22

After some time, the bar doesn't seem to register clicks, for example if i click on the spotify module to control music, or if i click on the pactl module to mute my output, none of it works. It seems to be an issue with the bar and not any particular module

#### How to reproduce
Just have i3 running for a while with bumblebee status

**Comment by tobi-wan-kenobi** [comment]
That sounds like an unhandled exception. Could you please tell me the modules you are using and provide a debug log (-d -f <filename>), so that I can investigatr in-depth?

Thank you very much!

**Comment by wwsmiff** [comment]
> That sounds like an unhandled exception. Could you please tell me the modules you are using and provide a debug log (-d -f ), so that I can investigatr in-depth?
> 
> Thank you very much!

The modules im using are:
-  arch-update
- aur-update
- cpu
- memory
- battery
- time
- spotify
- pasink
- pasource
- network
- caffeine

this is my status bar config:
```
bar {
       position top \
       status_command /home/batman/.bumblebee-status/bumblebee-status \
      -m arch-update aur-update cpu memory battery time spotify pasink pasource network caffeine \
      -p spotify.interval=0.01 pasink.interval=0.01s pasource.interval=0.01s time.format="%H:%M:%S" \
      -t gruvbox-powerline
       
       colors {
         separator #444444
         background #1b1b1b
         statusline #1b1b1b
         focused_workspace  #e30071 #e30071 #ffffff
         active_workspace #333333 #333333 #888888
         inactive_workspace #2f343a #333333 #f1f1f1
         urgent_workspace #2f343a #eb709b #ffffff
       }
}

```
Also, im not too sure on how to get the debug log. Can you please explain that part?

**Comment by tobi-wan-kenobi** [comment]
Please add "-d -f /tmp/bumblebee.log" to the status bar invocation, and send over the contents of the log (or ideally, the error at the bottom, if you can identify it)

Also, you can try using pulsein and pulseout instead of pasink and pasource, those should be more stable.

Thank you kindly!

**Comment by wwsmiff** [comment]
> Please add "-d -f /tmp/bumblebee.log" to the status bar invocation, and send over the contents of the log (or ideally, the error at the bottom, if you can identify it)
> 
> Also, you can try using pulsein and pulseout instead of pasink and pasource, those should be more stable.
> 
> Thank you kindly!

Well, i turned on debugging and it seems that whenever i did something which sent a notification it caused an error since i had no notification daemons installed. Now im using dunst and its working perfectly well.

Sorry for the inconvenience and thank you for your amazing support and this project!

**Comment by wwsmiff** [comment]
> Please add "-d -f /tmp/bumblebee.log" to the status bar invocation, and send over the contents of the log (or ideally, the error at the bottom, if you can identify it)
> 
> Also, you can try using pulsein and pulseout instead of pasink and pasource, those should be more stable.
> 
> Thank you kindly!


Please add "-d -f /tmp/bumblebee.log" to the status bar invocation, and send over the contents of the log (or ideally, the error at the bottom, if you can identify it)

Also, you can try using pulsein and pulseout instead of pasink and pasource, those should be more stable.

Thank you kindly!

Well, i turned on debugging and it seems that whenever i did something which sent a notification it caused an error since i had no notification daemons installed. Now im using dunst and its working perfectly well.

Sorry for the inconvenience and thank you for your amazing support and this great project!
