### ISSUE TITLE
Launcher for certain application

### ISSUE THREAD

**Issue by martindoublem** [tobi-wan-kenobi/bumblebee-status#953]
### Feature Request
This is a feature I just though about.
We could use a launcher for application, where upon clicking on the part of the bar in question we launch the application.
The graphics would be an Icon that we specify

**Comment by tobi-wan-kenobi** [comment]
You can actually do that already, with the spacer module.

It takes text as parameter, which can be an icon, and you can assign it a left-click action, and if that is an application, it gets executed.

Does that help?

**Comment by tobi-wan-kenobi** [comment]
yes, you can give them aliases (-m spacer:myname -p myname.left-click=firefox)

is that what you mean?

**Comment by martindoublem** [comment]
Indeed it is, is there a mention of this in the documentation? Apologies if I did not look closely enough.

**Comment by tobi-wan-kenobi** [comment]
Yes, aliases are part of the docs, but I think pulling all of this (spacer, aliases, left-click attribute) together is not easy to get from the docs :(
