### ISSUE TITLE
Transparent bar theme

### ISSUE THREAD

**Issue by martindoublem** [tobi-wan-kenobi/bumblebee-status#954]
### Feature Request
Not sure if this is possible at all. But would it be possible to get a transparent them for the bar?

**Comment by tobi-wan-kenobi** [comment]
I would need to check it in practice, but since i3-gaps was merged into i3, I *think* you should just be able to specify the alpha channel in the RGB spec, and if you run a compositor, that gets applied.

**Comment by martindoublem** [comment]
Did you implement it? Or just wanting to close tickets?

**Comment by tobi-wan-kenobi** [comment]
Oh, soery. I rhink using the alpha channel "just works", but have to admit i cannot remember if i tested it (specify rgba for color schemes)

**Comment by martindoublem** [comment]
Can we perhaps reopen this, then? I will test it when I have a minute.

**Comment by tobi-wan-kenobi** [comment]
Sure thing, thanks!

**Comment by Tonus1** [comment]
I for one have a transparent bar.

I use picom with

```
opacity-rule = [
   "95:class_g = 'URxvt' && !_NET_WM_STATE@:32a",
   ***@***.***:32a *= '_NET_WM_STATE_HIDDEN'",
   ***@***.***:32a *= '_NET_WM_STATE_HIDDEN'",
   ***@***.***:32a *= '_NET_WM_STATE_HIDDEN'",
   ***@***.***:32a *= '_NET_WM_STATE_HIDDEN'",
   ***@***.***:32a *= '_NET_WM_STATE_HIDDEN'",
   "100:class_g = 'vlc'",
   "100:class_g = 'mpv'",
   "100:class_g = 'mutt'",
   "100:class_g = 'libreoffice-writer'",
   "100:class_g = 'libreoffice-calc'",
   "100:class_g = 'libreoffice-base'",
   "100:class_g = 'libreoffice-draw'",
   "100:class_g = 'libreoffice-impress'",
   "100:class_g = 'libreoffice-startcenter'",
   "100:class_g = 'Nsxiv'",
   "100:class_g = 'MPlayer'",
   "100:class_g = 'Rofi'",
   "95:class_g = 'Surf'",
   "50:class_g = 'i3bar'"
];

focus-exclude = [
   "name~='i3lock'"
];

inactive-dim = 0.5;

inactive-opacity = 0.60;
active-opacity = 0.80;
frame-opacity = 0.80;

backend = "glx";

vsync = true;

blur: {
	method = "dual_kawase";
	strength = 2;
};
```

Regards,

Tonus

**Comment by tobi-wan-kenobi** [comment]
Yes, picom is also a good option to achieve that - as long as you are OK with the font being transparent as well.
