### ISSUE TITLE
exclude anbox and lxc bridges

### ISSUE THREAD

**Issue by Toni500github** [tobi-wan-kenobi/bumblebee-status#955]
Affected module: nic

Description:
title and how can i do that? ik about the nic.exclude parameter but it doesn't go away anyways
![image](https://user-images.githubusercontent.com/88878648/222263284-b611c2f0-ea6b-4219-98c8-a1a47ae0696c.png)

**Comment by tobi-wan-kenobi** [comment]
nic has a parameter called "exclude", which is a comma-sparated list:

bumblebee-status -m nic -p exclude="lo,anbox,lxc"

You mentioned you tried that, can you please paste the config that did not work?

**Comment by Toni500github** [comment]
> nic has a parameter called "exclude", which is a comma-sparated list:
> 
> bumblebee-status -m nic -p exclude="lo,anbox,lxc"
> 
> You mentioned you tried that, can you please paste the config that did not work?

i'm so sorry for this late reply, however i just fixed this issue by upgrading the version to the latest trough `pip` because it was at a 1.10.x version. strange...
