### ISSUE TITLE
smarstatus issue with the sudo component of it.

### ISSUE THREAD

**Issue by martindoublem** [tobi-wan-kenobi/bumblebee-status#956]
#### Description
Affected module: smartstatus
Version used: git on endeavousOS (arch-based distribution)

#### How to reproduce
run smartstatus on an arch-based distro and attempt with visudo and smartctl to get it to work (I could not recently, but maybe my brain is just a bit fried).

**Comment by tobi-wan-kenobi** [comment]
Cn you please explain what the eeror was that you saw?

Thanks!

**Comment by tobi-wan-kenobi** [comment]
ah, i am pretty sure you need to set up password-less sudo for this to work...

**Comment by martindoublem** [comment]
Got it to work. There was an issue with visudo having an extrafile in it.
