### ISSUE TITLE
Arrows/chevrons not appearing

### ISSUE THREAD

**Issue by SolColtman** [tobi-wan-kenobi/bumblebee-status#960]
My status bar currently looks like this

![img](https://i.imgur.com/yEaK8d0.png "Title")

I have awesomefonts installed (from apt) but I can't seem to get it working.

My bar config is as follows

`bar {
	font pango: JetBrains Mono Nerd Font FontAwesome 11
	status_command ~/.local/bin/bumblebee-status \
		-m kernel apt date time \
		-t nord-colorful
	position top
	workspace_min_width 28
}`

**Comment by tobi-wan-kenobi** [comment]
depending on your exact OS, i think the font line needs to be something like this:

font pango: JetBrains Mono Nerd, FontAwesome 11

Note no second "font" and the semicolon. hope this helps!

**Comment by SolColtman** [comment]
Thanks for the reply, still no success unfortunately.

If it helps I'm on Debian 11

**Comment by SolColtman** [comment]
Seems I didn't have nerd fonts installed correctly. Re-installing fixed issue.
