### ISSUE TITLE
Time and pasource modules not displaying

### ISSUE THREAD

**Issue by random-prism** [tobi-wan-kenobi/bumblebee-status#961]
Affected module: time, pasource (maybe pomodoro)
Version used: 2 (in .readthedocs.yaml)

Hello! I'm using bumblebee status for a week, I liked it and everything was fine until decided that I needed a pomodoro. When I added the pomodoro module, the icon for the time module changed  to  a ` (or a ~, not sure) and the pasource module to a dot. Also there is a weird bar between them.

How it is right now:
![bumblebee-status1](https://user-images.githubusercontent.com/110065284/229564728-648cd086-06ee-492b-9dc7-c213ae57ea74.png)

![bumblebee-status2](https://user-images.githubusercontent.com/110065284/229564737-b9026285-cab8-4774-a133-75a3ce033d11.png)

This is my i3config:
```
bar {
	position top
        font pango: monospace 8
	status_command /home/Garbinowo/.config/i3/bumblebee-status/bumblebee-status \
		-m time date pomodoro pasink pasource battery \
		-p pomodoro.work=50 pomodoro.break=10 time.format=%H:%M date.format="%d/%m/%Y" \
		-t greyish-powerline
}
``` 

It used to look like this:
![bumblebee-status3](https://user-images.githubusercontent.com/110065284/229564741-36477f9e-6112-4eb0-bb57-cb90c531f0b9.png)

Thank you for reading this.

**Comment by tobi-wan-kenobi** [comment]
I think you might have changed the font configuration of the i3 bar at the same time, is that possible? module selection does not affect fonts at all.

For the bar, you need a font-awesome compatible font (i.e. one of the nerd fonts)
