### ISSUE TITLE
Loading custom modules fails with 'importlib' has no attribute 'util'

### ISSUE THREAD

**Issue by wngrtn** [tobi-wan-kenobi/bumblebee-status#962]
Affected module: custom modules

Description:

Loading any custom module fails with `AttributeError: module 'importlib' has no attribute 'util'`.

I am on python 3.11.3 and, apparently, `importlib` no longer exports `util` (see [corresponding thread on discuss.python.org](https://discuss.python.org/t/python3-11-importlib-no-longer-exposes-util/25641)).

The fix is probably as easy as adding `import importlib.util` in `core/module.py` but my python experience is very limited and I am not sure how to test and build the project.

**Comment by tobi-wan-kenobi** [comment]
Thanks a lot! Will look into this right away.

One question: What do you mean by "custom module"?

**Comment by wngrtn** [comment]
Thanks! Ah, custom module = module placed in `~/.config/bumblebee-status/modules`.

I was looking into writing a custom module, copied the [Hello World example](https://bumblebee-status.readthedocs.io/en/main/development/module.html) to `~/.config/bumblebee-status/modules/helloworld.py`, and tried to run it with `bumblebee-status -m helloworld`.
