### ISSUE TITLE
PulseCTL select_default_device_popup not working

### ISSUE THREAD

**Issue by cloudUser98** [tobi-wan-kenobi/bumblebee-status#965]
Affected module: pulsectl

Description:
the parameter pulse(out/in).left-click=select_default_device_popup is not working.
Below is my conf file. If i set the parameter clicking the icon would do nothing.

[core]
modules = memory, battery, date, time, pulseout, pulsein
theme = iceberg-contrast

[module-parameters]
pulsein.showbars=true
pulseout.showbars=true
pulseout.left-click=select_default_device_popup

**Comment by tobi-wan-kenobi** [comment]
Do you have the Python Tk package installed?

Also, can you please try to run bumblebee in debug mode and see if there are any error messages?

**Comment by cloudUser98** [comment]
@tobi-wan-kenobi Im running fedora 37, i have already installed python3-tkinter package, i ran the debug mode and this is what i get in the logs:

[2023-04-16 12:54:09,599] bumblebee-status INFO     

input event: {"name":"pulseout","instance":"e6a52ec3-0762-4b28-9774-f8ad4feb30c4","button":1,"modifiers":[],"x":1785,"y":16,"relative_x":17,"relative_y":16,"output_x":1785,"output_y":16,"width":72,"height":25}
[2023-04-16 12:54:09,599] cli              

DEBUG    select_default_device_popup

**Comment by tobi-wan-kenobi** [comment]
I am terribly sorry, when migrating the pulseaudio code, I overlooked that functionality. Clear bug.

Until I can fix that, can you please give pasink and pasource a go, instead? They are drop-in replacements and the popup should work.

**Comment by tobi-wan-kenobi** [comment]
@cloudUser98 Sorry that this took so long, but the popup should work now (latest git)

**Comment by cloudUser98** [comment]
@tobi-wan-kenobi it works!!, thank you
