### ISSUE TITLE
Stock started showing up as 'n/a'

### ISSUE THREAD

**Issue by lag-google** [tobi-wan-kenobi/bumblebee-status#971]
#### Description
Affected module: `stock`
Version used: `latest git`

Stock value showing up as `n/a`.

#### How to reproduce
```
status_command ~/projects/bumblebee-status/bumblebee-status \
        -m battery stock weather nic disk:root cpu memory date time pasink pasource \
        -p root.path=/ time.format="%H:%M:%S CW %V" date.format="%a, %b %d %Y" \
           nic.exclude=lo,virbr,docker,vboxnet,veth,br,.*:avah,cvd nic.states=up \
           weather.showminmax=true stock.symbols=googl stock.change=false \
        -t solarized-powerline
```
![image](https://github.com/tobi-wan-kenobi/bumblebee-status/assets/114138157/81694601-930e-4ad1-9d76-6326ae9856d9)

**Comment by tobi-wan-kenobi** [comment]
Looks like Yahoo switched their finance API to something that requires an authorization.

Will need to look into how to retrieve and provide that.

Please note that this is a user-contributed module, so it might take a while until this is fixed.

**Comment by lag-google** [comment]
Any luck with this please?  Has the module author been informed of the breakage?

**Comment by tobi-wan-kenobi** [comment]
Unfortunately not yet, and I don't have a way toccontact the original author. I will do my best to find and implement a different stock provider.

**Comment by tobi-wan-kenobi** [comment]
@lag-google The module should work again, *but* with a slight change of parameters, plus you need an API key from here: https://www.alphavantage.co/support/#api-key

Now, the invocation looks something like this:

`bumblebee-status -m stock -p stock.apikey=<your key> stock.symbols=IBM,A`

and unfortunately doesn't show the currency anymore.

**Comment by lag-google** [comment]
Wonderful.  Thanks for your help.
