### ISSUE TITLE
bar became buggy

### ISSUE THREAD

**Issue by l4n1skyy** [tobi-wan-kenobi/bumblebee-status#975]
![image(1)](https://github.com/tobi-wan-kenobi/bumblebee-status/assets/71810630/e2637c49-3c34-43a4-9bf7-0ae688798a4b)
#### Description
Version used: AUR

**Comment by tobi-wan-kenobi** [comment]
This looks like a font issue to me. Can you please post the font config parts of your i3 config? You need Nerd fonts or Awesome as fallback for icons to work.
