### ISSUE TITLE
System module only shutdown and reboot work

### ISSUE THREAD

**Issue by Farsuperslime** [tobi-wan-kenobi/bumblebee-status#982]
#### Description
Affected module: System
Version used: latest

When system module is added to bar and used only "shutdown" and "reboot" work. This seems to be due to the i3 exit comman being changed at some point from "i3exit" to "i3 exit". Changing commands manually from "i3exit" to "i3 exit" makes all of them work.

#### How to reproduce
1. Add System module to bar.
2. Use any option besides shutdown or reboot.

**Comment by tobi-wan-kenobi** [comment]
Hello,

thanks for the report! The system module has parameters that allow you to override the commands used to execute for each action. Does that work for you as solution?

**Comment by Farsuperslime** [comment]
> Hello,
> 
> thanks for the report! The system module has parameters that allow you to override the commands used to execute for each action. Does that work for you as solution?

Yes, this is what I did to fix it. Just wasn't sure if this was an intended feature or an issue with these commands not working by default

**Comment by tobi-wan-kenobi** [comment]
Yeah, that is a good point. Eventually, I guess we'll want to update the commands, but I don't want to break existing setups, either.

Implementing a fallback mechanism in case the command isn't found might make sense. Will look into that.

**Comment by tobi-wan-kenobi** [comment]
Oh, it's even worse than I thought. "i3exit" is a custom script shipped with Manjaro, I think. I don't even know how to model some of that stuff (switch user, suspend, hibernate) generically.

So for now, I'd kindly ask you to use the parameters to customize the module for your specific usecase. Thanks a lot for your patience!
