### ISSUE TITLE
Documentation for modules 

### ISSUE THREAD

**Issue by PrabhuUdurg** [tobi-wan-kenobi/bumblebee-status#998]
### Feature Request

Hello! Currently, I'm using the Pomodoro module with your status bar and was thinking of implementing audio notification. Besides this, I was thinking of writing a little documentation about how to change work and rest time for people who don't want to deep into the configs. This small documentation also can be added to the main documentation website, under the module https://bumblebee-status.readthedocs.io/en/latest/

Let me know if it's a good idea to work on!!!

**Comment by tobi-wan-kenobi** [comment]
sounds great and would be much appreciated!

You just need to update the docstring in the module, the module docs are autogenerated from there.

Cheers!

**Comment by PrabhuUdurg** [comment]
Okay! I'll start working. Happy Hacktober!
